<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property \Illuminate\Support\Carbon $day
 * @property int $orders
 * @property int $revenue_cents
 */
class DailyRevenue extends Model
{
    protected $table = 'analytics.daily_revenue';

    protected $primaryKey = 'day';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = false;

    protected $fillable = [
        'day',
        'orders',
        'revenue_cents',
    ];

    protected $casts = [
        'day' => 'date',
        'orders' => 'integer',
        'revenue_cents' => 'integer',
    ];
}
