<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property string $id
 * @property int $sender_id
 * @property int|null $recipient_id
 * @property string $body
 * @property \Illuminate\Support\Carbon $sent_at
 * @property-read Customer|null $recipient
 * @property-read Customer $sender
 */
class Message extends Model
{
    protected $table = 'public.messages';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = false;

    protected $fillable = [
        'id',
        'sender_id',
        'recipient_id',
        'body',
        'sent_at',
    ];

    protected $casts = [
        'sender_id' => 'integer',
        'recipient_id' => 'integer',
        'sent_at' => 'datetime',
    ];

    public function recipient(): BelongsTo
    {
        return $this->belongsTo(Customer::class, 'recipient_id', 'id');
    }

    public function sender(): BelongsTo
    {
        return $this->belongsTo(Customer::class, 'sender_id', 'id');
    }
}
