<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Reads the view order_summary; it cannot be written through.
 *
 * @property int|null $id
 * @property string|null $email
 * @property OrderStatus|null $status
 * @property int|null $total_cents
 */
class OrderSummary extends Model
{
    protected $table = 'public.order_summary';

    protected $primaryKey = null;

    public $incrementing = false;

    public $timestamps = false;

    protected $casts = [
        'id' => 'integer',
        'status' => OrderStatus::class,
        'total_cents' => 'integer',
    ];
}
