<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property string $sku
 * @property string $name
 * @property string|null $description
 * @property int|null $category_id
 * @property int $price_cents
 * @property int $stock
 * @property array $attributes
 * @property float|null $weight_kg
 * @property bool $discontinued
 * @property \Illuminate\Support\Carbon|null $released_on
 * @property \Illuminate\Support\Carbon $updated_at
 * @property-read Category|null $category
 * @property-read \Illuminate\Database\Eloquent\Collection<int, OrderItem> $orderItems
 */
class Product extends Model
{
    protected $table = 'public.products';

    public $timestamps = false;

    protected $fillable = [
        'sku',
        'name',
        'description',
        'category_id',
        'price_cents',
        'stock',
        'attributes',
        'weight_kg',
        'discontinued',
        'released_on',
        'updated_at',
    ];

    protected $casts = [
        'id' => 'integer',
        'category_id' => 'integer',
        'price_cents' => 'integer',
        'stock' => 'integer',
        'attributes' => 'array',
        'weight_kg' => 'float',
        'discontinued' => 'boolean',
        'released_on' => 'date',
        'updated_at' => 'datetime',
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function orderItems(): HasMany
    {
        return $this->hasMany(OrderItem::class, 'product_id', 'id');
    }
}
