<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * @property int $id
 * @property int $order_id
 * @property int $line_no
 * @property string|null $category_slug
 * @property string $tracking_code
 * @property-read Category|null $category
 */
class Shipment extends Model
{
    protected $table = 'public.shipments';

    public $timestamps = false;

    protected $fillable = [
        'order_id',
        'line_no',
        'category_slug',
        'tracking_code',
    ];

    protected $casts = [
        'id' => 'integer',
        'order_id' => 'integer',
        'line_no' => 'integer',
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_slug', 'slug');
    }
}
