<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int $id
 * @property int $small
 * @property float|null $ratio
 * @property string|null $price
 * @property string|null $amount
 * @property string $code
 * @property string|null $fixed
 * @property string|null $starts
 * @property string|null $starts_tz
 * @property string|null $span
 * @property string|null $addr
 * @property string|null $doc
 * @property string|null $flags
 * @property string|null $search
 * @property string|null $scores
 * @property \Illuminate\Support\Carbon $day
 * @property array|null $meta
 * @property string $label
 * @property string|null $total
 * @property \Illuminate\Support\Carbon $stamp
 */
class TypeSample extends Model
{
    protected $table = 'public.type_samples';

    public $timestamps = false;

    protected $fillable = [
        'small',
        'ratio',
        'price',
        'amount',
        'code',
        'fixed',
        'starts',
        'starts_tz',
        'span',
        'addr',
        'doc',
        'flags',
        'search',
        'scores',
        'day',
        'meta',
        'label',
        'stamp',
    ];

    protected $casts = [
        'id' => 'integer',
        'small' => 'integer',
        'ratio' => 'float',
        'day' => 'date',
        'meta' => 'array',
        'total' => 'decimal:2',
        'stamp' => 'datetime',
    ];
}
