// Generated by Just Dashboard. Prisma 7 reads the connection from this file
// instead of the schema. Set DATABASE_URL in your environment.

import { defineConfig, env } from "prisma/config"

export default defineConfig({
  schema: "schema.prisma",
  datasource: {
    url: env("DATABASE_URL"),
  },
})
