// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Exact
// numerics are strings, so nothing is rounded on the way through.

package models

import (
	"time"

	"gorm.io/datatypes"
)

// PostsStatus is the posts_status enum.
type PostsStatus string

const (
	PostsStatusDraft     PostsStatus = "draft"
	PostsStatusPublished PostsStatus = "published"
	PostsStatusArchived  PostsStatus = "archived"
)

// EventsKind is the events_kind enum.
type EventsKind string

const (
	EventsKindView  EventsKind = "view"
	EventsKindShare EventsKind = "share"
)

// Author maps the authors table.
type Author struct {
	ID          uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement" json:"id"`
	Handle      string    `gorm:"column:handle;type:varchar(40);not null;uniqueIndex:handle" json:"handle"`
	DisplayName string    `gorm:"column:display_name;type:varchar(120);not null" json:"display_name"`
	Bio         *string   `gorm:"column:bio;type:text" json:"bio"`
	IsStaff     bool      `gorm:"column:is_staff;type:tinyint(1);not null;default:false" json:"is_staff"`
	JoinedAt    time.Time `gorm:"column:joined_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"joined_at"`

	Posts []Post `gorm:"foreignKey:AuthorID;references:ID" json:"posts,omitempty"`
}

// TableName is the table GORM reads and writes for Author.
func (Author) TableName() string { return "blog.authors" }

// Event maps the events table.
type Event struct {
	ID     int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	Title  string `gorm:"column:title;type:varchar(200);not null" json:"title"`
	HeldIn *int16 `gorm:"column:held_in;type:year" json:"held_in"`
}

// TableName is the table GORM reads and writes for Event.
func (Event) TableName() string { return "blog.events" }

// PostTag maps the post_tags table.
type PostTag struct {
	PostID int64  `gorm:"column:post_id;type:bigint;primaryKey" json:"post_id"`
	Tag    string `gorm:"column:tag;type:varchar(40);primaryKey" json:"tag"`

	Post *Post `gorm:"foreignKey:PostID;references:ID;constraint:OnDelete:CASCADE" json:"post,omitempty"`
}

// TableName is the table GORM reads and writes for PostTag.
func (PostTag) TableName() string { return "blog.post_tags" }

// Post maps posts: Everything that has been written
type Post struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	AuthorID    uint32         `gorm:"column:author_id;type:int unsigned;not null" json:"author_id"`
	Slug        string         `gorm:"column:slug;type:varchar(160);not null;uniqueIndex:slug" json:"slug"`
	Title       string         `gorm:"column:title;type:varchar(200);not null" json:"title"`
	Body        *string        `gorm:"column:body;type:mediumtext" json:"body"`
	Status      PostsStatus    `gorm:"column:status;type:enum('draft','published','archived');not null;default:draft;index:idx_posts_status,priority:1" json:"status"`
	Flags       *string        `gorm:"column:flags;type:set('pinned','featured')" json:"flags"`
	Views       uint32         `gorm:"column:views;type:int unsigned;not null;default:0" json:"views"`
	Rating      *string        `gorm:"column:rating;type:decimal(4,2)" json:"rating"`
	Meta        datatypes.JSON `gorm:"column:meta;type:json" json:"meta"`
	Cover       []byte         `gorm:"column:cover;type:mediumblob" json:"cover"`
	Digest      []byte         `gorm:"column:digest;type:binary(16)" json:"digest"`
	PublishedAt *time.Time     `gorm:"column:published_at;type:datetime(6);index:idx_posts_status,priority:2" json:"published_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`

	Author   *Author      `gorm:"foreignKey:AuthorID;references:ID;constraint:OnDelete:RESTRICT" json:"author,omitempty"`
	PostTags []PostTag    `gorm:"foreignKey:PostID;references:ID" json:"post_tags,omitempty"`
	Events   []StatsEvent `gorm:"foreignKey:PostID;references:ID" json:"events,omitempty"`
}

// TableName is the table GORM reads and writes for Post.
func (Post) TableName() string { return "blog.posts" }

// StatsEvent maps the events table.
type StatsEvent struct {
	ID     int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	PostID *int64     `gorm:"column:post_id;type:bigint;index:idx_events_post" json:"post_id"`
	Kind   EventsKind `gorm:"column:kind;type:enum('view','share');not null" json:"kind"`
	SeenAt time.Time  `gorm:"column:seen_at;type:timestamp(3);not null;default:CURRENT_TIMESTAMP(3)" json:"seen_at"`

	Post *Post `gorm:"foreignKey:PostID;references:ID;constraint:OnDelete:SET NULL" json:"post,omitempty"`
}

// TableName is the table GORM reads and writes for StatsEvent.
func (StatsEvent) TableName() string { return "stats.events" }
