// Generated by Just Dashboard from live database introspection.
// One schema per table, plus an `Insert` variant with the columns the
// database fills in made optional — which is the difference between a
// schema you can validate a row with and one you can validate a form with.

import { z } from "zod"

export const PageViewsDeviceSchema = z.enum(["desktop", "mobile"])
export type PageViewsDevice = z.infer<typeof PageViewsDeviceSchema>

export const PageViewSchema = z.object({
  ts: z.coerce.date(),
  user_id: z.string(),
  path: z.string(),
  country: z.string(),
  duration_ms: z.number().int(),
  is_bot: z.number().int(),
  referrer: z.string().nullable(),
  tags: z.array(z.string()),
  device: PageViewsDeviceSchema,
  revenue: z.string(),
  session: z.string(),
  seen: z.coerce.date(),
  props: z.unknown(),
  big: z.string(),
})
export type PageView = z.infer<typeof PageViewSchema>
export const PageViewInsertSchema = PageViewSchema.partial({ "session": true, "seen": true })
