// Generated by Just Dashboard from live database introspection.
// The Database interface Kysely is typed by. Generated<T> marks a column
// the database fills in: optional on insert, always present on select.

import type { ColumnType, Generated, Insertable, Selectable, Updateable } from "kysely"

export type Int8 = ColumnType<string, string | number | bigint, string | number | bigint>
export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface AccountTable {
  id: Generated<number>
  guid: Generated<string>
  name: string
  notes: string | null
  code: string | null
  active: Generated<boolean>
  level: Generated<number>
  balance: number | null
  credit: Generated<number>
  photo: Buffer | null
  opened_on: Timestamp | null
  created_at: Generated<Timestamp>
  seen_at: Timestamp | null
  version: Buffer
}

export interface TransferTable {
  id: Generated<Int8>
  from_account: number
  to_account: number | null
  amount: number
  memo: Generated<string>
}

export interface SalesAccountTable {
  id: number
  region: string
  payload: string | null
}

export interface Database {
  "dbo.accounts": AccountTable
  "dbo.transfers": TransferTable
  "sales.accounts": SalesAccountTable
}

export type Account = Selectable<AccountTable>
export type NewAccount = Insertable<AccountTable>
export type AccountUpdate = Updateable<AccountTable>
export type Transfer = Selectable<TransferTable>
export type NewTransfer = Insertable<TransferTable>
export type TransferUpdate = Updateable<TransferTable>
export type SalesAccount = Selectable<SalesAccountTable>
export type NewSalesAccount = Insertable<SalesAccountTable>
export type SalesAccountUpdate = Updateable<SalesAccountTable>
