// Generated by Just Dashboard from live database introspection.
// One schema per table, shaped as a row the database returns.

import { z } from "zod"

export const EventKindSchema = z.enum(["page_view", "click", "add-to-cart"])
export type EventKind = z.infer<typeof EventKindSchema>

export const CustomerTierSchema = z.enum(["free", "plus", "pro"])
export type CustomerTier = z.infer<typeof CustomerTierSchema>

export const OrderStatusSchema = z.enum(["pending", "paid", "shipped", "delivered", "cancelled", "refunded"])
export type OrderStatus = z.infer<typeof OrderStatusSchema>

export const DailyRevenueSchema = z.object({
  day: z.coerce.date(),
  orders: z.number().int(),
  revenue_cents: z.string(),
})
export type DailyRevenue = z.infer<typeof DailyRevenueSchema>

export const AnalyticsEventSchema = z.object({
  id: z.string(),
  customer_id: z.string().nullable(),
  kind: EventKindSchema,
  path: z.string().nullable(),
  duration_ms: z.number().int().nullable(),
  props: z.unknown().nullable(),
  occurred_at: z.coerce.date(),
})
export type AnalyticsEvent = z.infer<typeof AnalyticsEventSchema>

export const MixedCaseTableSchema = z.object({
  Id: z.number().int(),
  select: z.string().nullable(),
  "weird column": z.string().nullable(),
  "2fa": z.boolean(),
})
export type MixedCaseTable = z.infer<typeof MixedCaseTableSchema>

export const AuditLogSchema = z.object({
  at: z.coerce.date(),
  actor: z.string().nullable(),
  action: z.string(),
  payload: z.unknown().nullable(),
})
export type AuditLog = z.infer<typeof AuditLogSchema>

export const CategorySchema = z.object({
  id: z.number().int(),
  slug: z.string(),
  name: z.string(),
  parent_id: z.number().int().nullable(),
})
export type Category = z.infer<typeof CategorySchema>

export const CustomerProfileSchema = z.object({
  customer_id: z.string(),
  bio: z.string().nullable(),
  website: z.string().nullable(),
})
export type CustomerProfile = z.infer<typeof CustomerProfileSchema>

export const CustomerSchema = z.object({
  id: z.string(),
  email: z.string(),
  full_name: z.string(),
  tier: CustomerTierSchema,
  country: z.string().nullable(),
  marketing_opt_in: z.boolean(),
  tags: z.array(z.string()),
  profile: z.unknown(),
  avatar: z.string().nullable(),
  external_id: z.string(),
  lifetime_value: z.string(),
  created_at: z.coerce.date(),
  last_seen_at: z.coerce.date().nullable(),
})
export type Customer = z.infer<typeof CustomerSchema>

export const EventSchema = z.object({
  id: z.string(),
  name: z.string(),
  starts_at: z.coerce.date(),
})
export type Event = z.infer<typeof EventSchema>

export const MeasurementSchema = z.object({
  sensor_id: z.number().int(),
  taken_at: z.coerce.date(),
  reading: z.number().nullable(),
})
export type Measurement = z.infer<typeof MeasurementSchema>

export const MessageSchema = z.object({
  id: z.string(),
  sender_id: z.string(),
  recipient_id: z.string().nullable(),
  body: z.string(),
  sent_at: z.coerce.date(),
})
export type Message = z.infer<typeof MessageSchema>

export const OrderItemSchema = z.object({
  order_id: z.string(),
  line_no: z.number().int(),
  product_id: z.string(),
  quantity: z.number().int(),
  unit_price_cents: z.number().int(),
})
export type OrderItem = z.infer<typeof OrderItemSchema>

export const OrderSchema = z.object({
  id: z.string(),
  customer_id: z.string(),
  status: OrderStatusSchema,
  total_cents: z.string(),
  currency: z.string(),
  shipping_address: z.unknown().nullable(),
  note: z.string().nullable(),
  placed_at: z.coerce.date(),
  shipped_at: z.coerce.date().nullable(),
})
export type Order = z.infer<typeof OrderSchema>

export const ProductSchema = z.object({
  id: z.string(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  category_id: z.number().int().nullable(),
  price_cents: z.number().int(),
  stock: z.number().int(),
  attributes: z.unknown(),
  weight_kg: z.number().nullable(),
  discontinued: z.boolean(),
  released_on: z.coerce.date().nullable(),
  updated_at: z.coerce.date(),
})
export type Product = z.infer<typeof ProductSchema>

export const ShipmentSchema = z.object({
  id: z.number().int(),
  order_id: z.string(),
  line_no: z.number().int(),
  category_slug: z.string().nullable(),
  tracking_code: z.string(),
})
export type Shipment = z.infer<typeof ShipmentSchema>

export const TypeSampleSchema = z.object({
  id: z.number().int(),
  small: z.number().int(),
  ratio: z.number().nullable(),
  price: z.string().nullable(),
  amount: z.string().nullable(),
  code: z.string(),
  fixed: z.string().nullable(),
  starts: z.string().nullable(),
  starts_tz: z.string().nullable(),
  span: z.string().nullable(),
  addr: z.string().nullable(),
  doc: z.string().nullable(),
  flags: z.string().nullable(),
  search: z.string().nullable(),
  scores: z.array(z.number().int()).nullable(),
  day: z.coerce.date(),
  meta: z.unknown().nullable(),
  label: z.string(),
  total: z.string().nullable(),
  stamp: z.coerce.date(),
})
export type TypeSample = z.infer<typeof TypeSampleSchema>
