# Generated by Just Dashboard from live database introspection.
# A reviewed starting point: verify types, defaults and relationships.

import datetime
import decimal
from typing import Optional

from sqlalchemy import CHAR, CLOB, ForeignKey, UniqueConstraint, text
from sqlalchemy.dialects.oracle import (
    BINARY_DOUBLE,
    DATE,
    INTERVAL,
    NUMBER,
    NVARCHAR2,
    RAW,
    TIMESTAMP,
    VARCHAR2,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Customer(Base):
    __tablename__ = "CUSTOMERS"
    __table_args__ = (
        UniqueConstraint("EMAIL", name="CUSTOMERS_EMAIL_UK"),
    )

    ID: Mapped[int] = mapped_column(NUMBER(10, 0), primary_key=True)
    EMAIL: Mapped[str] = mapped_column(VARCHAR2(255))
    FULL_NAME: Mapped[Optional[str]] = mapped_column(NVARCHAR2(200))
    BALANCE: Mapped[decimal.Decimal] = mapped_column(NUMBER(18, 2), server_default=text("0"))
    POINTS: Mapped[Optional[decimal.Decimal]] = mapped_column(NUMBER)
    BIG_ID: Mapped[Optional[int]] = mapped_column(NUMBER(18, 0))
    RATIO: Mapped[Optional[float]] = mapped_column(BINARY_DOUBLE)
    NOTES: Mapped[Optional[str]] = mapped_column(CLOB)
    TOKEN: Mapped[Optional[bytes]] = mapped_column(RAW(16))
    STATE: Mapped[str] = mapped_column(CHAR(1), server_default=text("'A'"))
    CREATED: Mapped[datetime.datetime] = mapped_column(DATE, server_default=text("SYSDATE"))
    UPDATED: Mapped[Optional[datetime.datetime]] = mapped_column(TIMESTAMP(timezone=True))
    KEPT_FOR: Mapped[Optional[datetime.timedelta]] = mapped_column(INTERVAL)

    ORDERS: Mapped[list["Order"]] = relationship(back_populates="CUSTOMER", foreign_keys="Order.CUSTOMER_ID")


class Order(Base):
    __tablename__ = "ORDERS"

    ID: Mapped[int] = mapped_column(NUMBER(10, 0), primary_key=True, autoincrement=False)
    CUSTOMER_ID: Mapped[int] = mapped_column(NUMBER(10, 0), ForeignKey("CUSTOMERS.ID", ondelete="CASCADE", name="ORDERS_CUSTOMER_FK"))
    TOTAL: Mapped[decimal.Decimal] = mapped_column(NUMBER(12, 2))
    PLACED: Mapped[datetime.datetime] = mapped_column(TIMESTAMP, server_default=text("SYSTIMESTAMP"))

    CUSTOMER: Mapped["Customer"] = relationship(back_populates="ORDERS", foreign_keys=[CUSTOMER_ID])
