// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { type Opt, type Rel } from "@mikro-orm/core"
import { Entity, Enum, Index, ManyToOne, PrimaryKey, Property } from "@mikro-orm/decorators/legacy"
import { Customer } from "./Customer"
import { EventKind } from "./enums"

@Entity({ tableName: "events", schema: "analytics" })
@Index({ name: "events_occurred_idx", properties: ["occurredAt"] })
export class AnalyticsEvent {
  @PrimaryKey({ type: "bigint", columnType: "bigint" })
  id!: bigint & Opt

  @ManyToOne({ entity: () => Customer, fieldName: "customer_id", nullable: true, deleteRule: "set null" })
  customer!: Rel<Customer> | null

  @Enum({ items: () => EventKind, nativeEnumName: "event_kind" })
  kind!: EventKind

  @Property({ type: "text", columnType: "text", nullable: true })
  path!: string | null

  @Property({ type: "integer", columnType: "integer", fieldName: "duration_ms", nullable: true })
  durationMs!: number | null

  @Property({ type: "json", columnType: "jsonb", nullable: true })
  props!: unknown

  @Property({ type: "datetime", columnType: "timestamp with time zone", fieldName: "occurred_at" })
  occurredAt!: Date
}
