// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { Collection, type Opt, type Rel } from "@mikro-orm/core"
import {
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryKey,
  Property,
  Unique,
} from "@mikro-orm/decorators/legacy"
import { Product } from "./Product"
import { Shipment } from "./Shipment"

@Entity({ tableName: "categories", schema: "public" })
@Unique({ name: "categories_slug_key", properties: ["slug"] })
export class Category {
  @PrimaryKey({ type: "integer", columnType: "integer" })
  id!: number & Opt

  @Property({ type: "text", columnType: "text" })
  slug!: string

  @Property({ type: "text", columnType: "text" })
  name!: string

  @ManyToOne({ entity: () => Category, fieldName: "parent_id", nullable: true })
  parent!: Rel<Category> | null

  @OneToMany({ entity: () => Category, mappedBy: "parent" })
  categories = new Collection<Category>(this)

  @OneToMany({ entity: () => Product, mappedBy: "category" })
  products = new Collection<Product>(this)

  @OneToMany({ entity: () => Shipment, mappedBy: "category" })
  shipments = new Collection<Shipment>(this)
}
