// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { Collection, type Opt, type Rel } from "@mikro-orm/core"
import {
  Entity,
  Enum,
  OneToMany,
  OneToOne,
  PrimaryKey,
  Property,
  Unique,
} from "@mikro-orm/decorators/legacy"
import { AnalyticsEvent } from "./AnalyticsEvent"
import { CustomerProfile } from "./CustomerProfile"
import { Message } from "./Message"
import { Order } from "./Order"
import { CustomerTier } from "./enums"

/** People who have an account in the shop */
@Entity({ tableName: "customers", schema: "public" })
@Unique({ name: "customers_email_key", properties: ["email"] })
export class Customer {
  @PrimaryKey({ type: "bigint", columnType: "bigint" })
  id!: bigint & Opt

  @Property({ type: "text", columnType: "text" })
  email!: string

  @Property({ type: "text", columnType: "text", fieldName: "full_name" })
  fullName!: string

  @Enum({ items: () => CustomerTier, nativeEnumName: "customer_tier", default: "free" })
  tier!: CustomerTier & Opt

  @Property({ type: "character", columnType: "character(2)", nullable: true })
  country!: string | null

  @Property({ type: "boolean", columnType: "boolean", fieldName: "marketing_opt_in", default: false })
  marketingOptIn!: boolean & Opt

  @Property({ type: "array", columnType: "text[]", defaultRaw: "'{}'::text[]" })
  tags!: string[] & Opt

  /** Free-form preferences captured at sign-up */
  @Property({ type: "json", columnType: "jsonb", defaultRaw: "'{}'::jsonb" })
  profile!: unknown & Opt

  @Property({ type: "blob", columnType: "bytea", nullable: true })
  avatar!: Buffer | null

  @Property({ type: "uuid", columnType: "uuid", fieldName: "external_id", defaultRaw: "gen_random_uuid()" })
  externalId!: string & Opt

  @Property({ type: "decimal", columnType: "numeric(12,2)", fieldName: "lifetime_value", defaultRaw: "0" })
  lifetimeValue!: string & Opt

  @Property({ type: "datetime", columnType: "timestamp with time zone", fieldName: "created_at", defaultRaw: "now()" })
  createdAt!: Date & Opt

  @Property({ type: "datetime", columnType: "timestamp with time zone", fieldName: "last_seen_at", nullable: true })
  lastSeenAt!: Date | null

  @OneToMany({ entity: () => AnalyticsEvent, mappedBy: "customer" })
  events = new Collection<AnalyticsEvent>(this)

  @OneToOne({ entity: () => CustomerProfile, mappedBy: "customer" })
  customerProfile?: Rel<CustomerProfile> | null

  @OneToMany({ entity: () => Message, mappedBy: "recipient" })
  messagesRecipientId = new Collection<Message>(this)

  @OneToMany({ entity: () => Message, mappedBy: "sender" })
  messagesSenderId = new Collection<Message>(this)

  @OneToMany({ entity: () => Order, mappedBy: "customer" })
  orders = new Collection<Order>(this)
}
