// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { PrimaryKeyProp, type Rel } from "@mikro-orm/core"
import { Entity, OneToOne, Property } from "@mikro-orm/decorators/legacy"
import { Customer } from "./Customer"

@Entity({ tableName: "customer_profiles", schema: "public" })
export class CustomerProfile {
  [PrimaryKeyProp]?: "customer"

  @OneToOne({ entity: () => Customer, fieldName: "customer_id", primary: true, deleteRule: "cascade" })
  customer!: Rel<Customer>

  @Property({ type: "text", columnType: "text", nullable: true })
  bio!: string | null

  @Property({ type: "string", columnType: "character varying(255)", nullable: true })
  website!: string | null
}
