// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { PrimaryKeyProp } from "@mikro-orm/core"
import { Entity, PrimaryKey, Property } from "@mikro-orm/decorators/legacy"

@Entity({ tableName: "daily_revenue", schema: "analytics" })
export class DailyRevenue {
  [PrimaryKeyProp]?: "day"

  @PrimaryKey({ type: "date", columnType: "date" })
  day!: string

  @Property({ type: "integer", columnType: "integer" })
  orders!: number

  @Property({ type: "bigint", columnType: "bigint", fieldName: "revenue_cents" })
  revenueCents!: bigint
}
