// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { Collection, type Opt, type Rel } from "@mikro-orm/core"
import {
  Entity,
  Enum,
  Index,
  ManyToOne,
  OneToMany,
  PrimaryKey,
  Property,
} from "@mikro-orm/decorators/legacy"
import { Customer } from "./Customer"
import { OrderItem } from "./OrderItem"
import { OrderStatus } from "./enums"

@Entity({ tableName: "orders", schema: "public" })
@Index({ name: "orders_status_placed_idx", properties: ["status", "placedAt"] })
export class Order {
  @PrimaryKey({ type: "bigint", columnType: "bigint" })
  id!: bigint & Opt

  @ManyToOne({ entity: () => Customer, fieldName: "customer_id", deleteRule: "cascade" })
  customer!: Rel<Customer>

  @Enum({ items: () => OrderStatus, nativeEnumName: "order_status", default: "pending" })
  status!: OrderStatus & Opt

  @Property({ type: "bigint", columnType: "bigint", fieldName: "total_cents", defaultRaw: "0" })
  totalCents!: bigint & Opt

  @Property({ type: "character", columnType: "character(3)", default: "EUR" })
  currency!: string & Opt

  @Property({ type: "json", columnType: "jsonb", fieldName: "shipping_address", nullable: true })
  shippingAddress!: unknown

  @Property({ type: "text", columnType: "text", nullable: true })
  note!: string | null

  @Property({ type: "datetime", columnType: "timestamp with time zone", fieldName: "placed_at", defaultRaw: "now()" })
  placedAt!: Date & Opt

  @Property({ type: "datetime", columnType: "timestamp with time zone", fieldName: "shipped_at", nullable: true })
  shippedAt!: Date | null

  @OneToMany({ entity: () => OrderItem, mappedBy: "order" })
  orderItems = new Collection<OrderItem>(this)
}
