// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { Collection, type Opt, type Rel } from "@mikro-orm/core"
import {
  Entity,
  Index,
  ManyToOne,
  OneToMany,
  PrimaryKey,
  Property,
  Unique,
} from "@mikro-orm/decorators/legacy"
import { Category } from "./Category"
import { OrderItem } from "./OrderItem"

@Entity({ tableName: "products", schema: "public" })
@Unique({ name: "products_sku_key", properties: ["sku"] })
@Index({ name: "products_category_idx", properties: ["category"] })
export class Product {
  @PrimaryKey({ type: "bigint", columnType: "bigint" })
  id!: bigint & Opt

  @Property({ type: "string", columnType: "character varying(32)" })
  sku!: string

  @Property({ type: "string", columnType: "character varying(200)" })
  name!: string

  @Property({ type: "text", columnType: "text", nullable: true })
  description!: string | null

  @ManyToOne({ entity: () => Category, fieldName: "category_id", nullable: true })
  category!: Rel<Category> | null

  @Property({ type: "integer", columnType: "integer", fieldName: "price_cents" })
  priceCents!: number

  @Property({ type: "integer", columnType: "integer", default: 0 })
  stock!: number & Opt

  @Property({ type: "json", columnType: "jsonb", defaultRaw: "'{}'::jsonb" })
  attributes!: unknown & Opt

  @Property({ type: "double", columnType: "double precision", fieldName: "weight_kg", nullable: true })
  weightKg!: number | null

  @Property({ type: "boolean", columnType: "boolean", default: false })
  discontinued!: boolean & Opt

  @Property({ type: "date", columnType: "date", fieldName: "released_on", nullable: true })
  releasedOn!: string | null

  @Property({ type: "datetime", columnType: "timestamp without time zone", fieldName: "updated_at", defaultRaw: "now()" })
  updatedAt!: Date & Opt

  @OneToMany({ entity: () => OrderItem, mappedBy: "product" })
  orderItems = new Collection<OrderItem>(this)
}
