// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { type Opt, type Rel } from "@mikro-orm/core"
import { Entity, ManyToOne, PrimaryKey, Property, Unique } from "@mikro-orm/decorators/legacy"
import { Category } from "./Category"
import { OrderItem } from "./OrderItem"

@Entity({ tableName: "shipments", schema: "public" })
@Unique({ name: "shipments_tracking_code_key", properties: ["trackingCode"] })
export class Shipment {
  @PrimaryKey({ type: "integer", columnType: "integer" })
  id!: number & Opt

  @ManyToOne({ entity: () => OrderItem, fieldNames: ["order_id", "line_no"], deleteRule: "cascade" })
  orderItem!: Rel<OrderItem>

  @ManyToOne({ entity: () => Category, fieldName: "category_slug", referencedColumnNames: ["slug"], nullable: true })
  category!: Rel<Category> | null

  @Property({ type: "string", columnType: "character varying(40)", fieldName: "tracking_code" })
  trackingCode!: string
}
