// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { type Opt } from "@mikro-orm/core"
import { Entity, PrimaryKey, Property } from "@mikro-orm/decorators/legacy"

@Entity({ tableName: "type_samples", schema: "public" })
export class TypeSample {
  @PrimaryKey({ type: "integer", columnType: "integer" })
  id!: number & Opt

  @Property({ type: "smallint", columnType: "smallint", default: 0 })
  small!: number & Opt

  @Property({ type: "float", columnType: "real", nullable: true })
  ratio!: number | null

  @Property({ type: "decimal", columnType: "money", nullable: true })
  price!: string | null

  @Property({ type: "decimal", columnType: "numeric", nullable: true })
  amount!: string | null

  @Property({ type: "string", columnType: "character varying(16)", default: "N/A" })
  code!: string & Opt

  @Property({ type: "character", columnType: "character(4)", nullable: true })
  fixed!: string | null

  @Property({ type: "time", columnType: "time without time zone", nullable: true })
  starts!: string | null

  @Property({ type: "time", columnType: "time with time zone", fieldName: "starts_tz", nullable: true })
  startsTz!: string | null

  @Property({ type: "interval", columnType: "interval", nullable: true })
  span!: string | null

  @Property({ type: "string", columnType: "inet", nullable: true })
  addr!: string | null

  @Property({ type: "string", columnType: "xml", nullable: true })
  doc!: string | null

  @Property({ type: "string", columnType: "bit(8)", nullable: true })
  flags!: string | null

  @Property({ type: "string", columnType: "tsvector", nullable: true })
  search!: string | null

  @Property({ type: "array", columnType: "integer[]", nullable: true })
  scores!: number[] | null

  @Property({ type: "date", columnType: "date", defaultRaw: "CURRENT_DATE" })
  day!: string & Opt

  @Property({ type: "json", columnType: "json", nullable: true })
  meta!: unknown

  @Property({ type: "text", columnType: "text", default: "it's" })
  label!: string & Opt

  @Property({ type: "decimal", columnType: "numeric(10,2)", nullable: true, generated: "((small)::numeric * 1.5) stored" })
  total!: (string | null) & Opt

  @Property({ type: "datetime", columnType: "timestamp(3) without time zone", defaultRaw: "timezone('utc'::text, now())" })
  stamp!: Date & Opt
}
