// Generated by Just Dashboard from live database introspection.
// Row types as the database returns them. A nullable column is `| null`
// rather than optional: the key is always present, its value may not be.

export interface Note {
  id: number
  user_id: number
  title: string
  body: string | null
  pinned: boolean
  score: number | null
  price: string | null
  payload: unknown | null
  attachment: string | null
  created_at: string
}

export interface UserTag {
  user_id: number
  tag: string
}

export interface User {
  id: number
  email: string
  name: string | null
}
