// Generated by Just Dashboard from live database introspection.
// The shape `diesel print-schema` writes. A reviewed starting point: check it
// against your migrations before relying on it.

pub mod blog {
    pub mod sql_types {
        #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
        #[diesel(mysql_type(name = "Short"))]
        pub struct Year;

        #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
        #[diesel(mysql_type(name = "Enum"))]
        pub struct PostsStatus;

        #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
        #[diesel(mysql_type(name = "Set"))]
        pub struct Set;
    }

    diesel::table! {
        use diesel::sql_types::*;

        blog.authors (id) {
            id -> Unsigned<Integer>,
            #[max_length = 40]
            handle -> Varchar,
            #[max_length = 120]
            display_name -> Varchar,
            bio -> Nullable<Text>,
            is_staff -> Bool,
            joined_at -> Datetime,
        }
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::Year;

        blog.events (id) {
            id -> Bigint,
            #[max_length = 200]
            title -> Varchar,
            held_in -> Nullable<Year>,
        }
    }

    diesel::table! {
        use diesel::sql_types::*;

        blog.post_tags (post_id, tag) {
            post_id -> Bigint,
            #[max_length = 40]
            tag -> Varchar,
        }
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::PostsStatus;
        use super::sql_types::Set;

        blog.posts (id) {
            id -> Bigint,
            author_id -> Unsigned<Integer>,
            #[max_length = 160]
            slug -> Varchar,
            #[max_length = 200]
            title -> Varchar,
            body -> Nullable<Mediumtext>,
            status -> PostsStatus,
            flags -> Nullable<Set>,
            views -> Unsigned<Integer>,
            rating -> Nullable<Decimal>,
            meta -> Nullable<Json>,
            cover -> Nullable<Mediumblob>,
            #[max_length = 16]
            digest -> Nullable<Binary>,
            published_at -> Nullable<Datetime>,
            updated_at -> Timestamp,
        }
    }

    diesel::joinable!(post_tags -> posts (post_id));
    diesel::joinable!(posts -> authors (author_id));

    diesel::allow_tables_to_appear_in_same_query!(
        authors,
        events,
        post_tags,
        posts,
    );
}

pub mod stats {
    pub mod sql_types {
        #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
        #[diesel(mysql_type(name = "Enum"))]
        pub struct EventsKind;
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::EventsKind;

        stats.events (id) {
            id -> Bigint,
            post_id -> Nullable<Bigint>,
            kind -> EventsKind,
            seen_at -> Timestamp,
        }
    }
}
