// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  type Relation,
} from "typeorm"
import { Customer } from "./Customer"
import { EventKind } from "./enums"

@Index("events_occurred_idx", ["occurredAt"])
@Entity("events", { schema: "analytics" })
export class AnalyticsEvent {
  @PrimaryGeneratedColumn("identity", { type: "bigint", generatedIdentity: "ALWAYS" })
  id!: string

  @Column({ type: "bigint", name: "customer_id", nullable: true })
  customerId!: string | null

  @Column({ type: "enum", enum: EventKind, enumName: "event_kind" })
  kind!: EventKind

  @Column({ type: "text", nullable: true })
  path!: string | null

  @Column({ type: "integer", name: "duration_ms", nullable: true })
  durationMs!: number | null

  @Column({ type: "jsonb", nullable: true })
  props!: unknown

  @Column({ type: "timestamp with time zone", name: "occurred_at" })
  occurredAt!: Date

  @ManyToOne(() => Customer, (other) => other.events, { onDelete: "SET NULL" })
  @JoinColumn({ name: "customer_id", referencedColumnName: "id", foreignKeyConstraintName: "events_customer_id_fkey" })
  customer!: Relation<Customer> | null
}
