// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import { Column, Entity, PrimaryColumn } from "typeorm"

@Entity("Mixed Case Table", { schema: "public" })
export class MixedCaseTable {
  @PrimaryColumn({ type: "integer", name: "Id" })
  id!: number

  @Column({ type: "text", nullable: true })
  select!: string | null

  @Column({ type: "text", name: "weird column", nullable: true })
  weirdColumn!: string | null

  @Column({ type: "boolean", name: "2fa", default: false })
  _2fa!: boolean
}
