// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  type Relation,
} from "typeorm"
import { Category } from "./Category"
import { OrderItem } from "./OrderItem"

@Index("products_sku_key", ["sku"], { unique: true })
@Index("products_category_idx", ["categoryId"])
@Entity("products", { schema: "public" })
export class Product {
  @PrimaryGeneratedColumn({ type: "bigint" })
  id!: string

  @Column({ type: "varchar", length: 32 })
  sku!: string

  @Column({ type: "varchar", length: 200 })
  name!: string

  @Column({ type: "text", nullable: true })
  description!: string | null

  @Column({ type: "integer", name: "category_id", nullable: true })
  categoryId!: number | null

  @Column({ type: "integer", name: "price_cents" })
  priceCents!: number

  @Column({ type: "integer", default: 0 })
  stock!: number

  @Column({ type: "jsonb", default: () => "'{}'::jsonb" })
  attributes!: unknown

  @Column({ type: "double precision", name: "weight_kg", nullable: true })
  weightKg!: number | null

  @Column({ type: "boolean", default: false })
  discontinued!: boolean

  @Column({ type: "date", name: "released_on", nullable: true })
  releasedOn!: string | null

  @Column({ type: "timestamp", name: "updated_at", default: () => "now()" })
  updatedAt!: Date

  @ManyToOne(() => Category, (other) => other.products)
  @JoinColumn({ name: "category_id", referencedColumnName: "id", foreignKeyConstraintName: "products_category_id_fkey" })
  category!: Relation<Category> | null

  @OneToMany(() => OrderItem, (other) => other.product)
  orderItems!: Relation<OrderItem>[]
}
