// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  type Relation,
} from "typeorm"
import { Category } from "./Category"
import { OrderItem } from "./OrderItem"

@Index("shipments_tracking_code_key", ["trackingCode"], { unique: true })
@Entity("shipments", { schema: "public" })
export class Shipment {
  @PrimaryGeneratedColumn({ type: "integer" })
  id!: number

  @Column({ type: "bigint", name: "order_id" })
  orderId!: string

  @Column({ type: "smallint", name: "line_no" })
  lineNo!: number

  @Column({ type: "text", name: "category_slug", nullable: true })
  categorySlug!: string | null

  @Column({ type: "varchar", name: "tracking_code", length: 40 })
  trackingCode!: string

  @ManyToOne(() => Category, (other) => other.shipments)
  @JoinColumn({ name: "category_slug", referencedColumnName: "slug", foreignKeyConstraintName: "shipments_category_slug_fkey" })
  category!: Relation<Category> | null

  @ManyToOne(() => OrderItem, (other) => other.shipments, { onDelete: "CASCADE" })
  @JoinColumn([{ name: "order_id", referencedColumnName: "orderId", foreignKeyConstraintName: "shipments_item_fkey" }, { name: "line_no", referencedColumnName: "lineNo" }])
  orderItem!: Relation<OrderItem>
}
