// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import { ViewColumn, ViewEntity } from "typeorm"

@ViewEntity({ name: "top_products", schema: "analytics", materialized: true, synchronize: false })
export class TopProduct {
  @ViewColumn({ name: "product_id" })
  productId!: string | null

  @ViewColumn()
  units!: string | null
}
