// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import { Column, Entity, PrimaryGeneratedColumn } from "typeorm"

@Entity("type_samples", { schema: "public" })
export class TypeSample {
  @PrimaryGeneratedColumn("identity", { type: "integer", generatedIdentity: "BY DEFAULT" })
  id!: number

  @Column({ type: "smallint", default: 0 })
  small!: number

  @Column({ type: "real", nullable: true })
  ratio!: number | null

  @Column({ type: "money", nullable: true })
  price!: string | null

  @Column({ type: "numeric", nullable: true })
  amount!: string | null

  @Column({ type: "varchar", length: 16, default: "N/A" })
  code!: string

  @Column({ type: "char", length: 4, nullable: true })
  fixed!: string | null

  @Column({ type: "time", nullable: true })
  starts!: string | null

  @Column({ type: "time with time zone", name: "starts_tz", nullable: true })
  startsTz!: string | null

  @Column({ type: "interval", nullable: true })
  span!: unknown

  @Column({ type: "inet", nullable: true })
  addr!: string | null

  @Column({ type: "xml", nullable: true })
  doc!: string | null

  @Column({ type: "bit", length: 8, nullable: true })
  flags!: string | null

  @Column({ type: "tsvector", nullable: true })
  search!: string | null

  @Column({ type: "integer", array: true, nullable: true })
  scores!: number[] | null

  @Column({ type: "date", default: () => "CURRENT_DATE" })
  day!: string

  @Column({ type: "json", nullable: true })
  meta!: unknown

  @Column({ type: "text", default: "it's" })
  label!: string

  @Column({ type: "numeric", precision: 10, scale: 2, nullable: true, generatedType: "STORED", asExpression: "((small)::numeric * 1.5)" })
  total!: string | null

  @Column({ type: "timestamp", precision: 3, default: () => "timezone('utc'::text, now())" })
  stamp!: Date
}
