// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations before
// registering these entities.

import { Collection, type Opt, type Rel } from "@mikro-orm/core"
import {
  Entity,
  Index,
  ManyToOne,
  OneToMany,
  PrimaryKey,
  Property,
  Unique,
} from "@mikro-orm/decorators/legacy"

@Entity({ tableName: "accounts", schema: "dbo" })
@Unique({ name: "UQ_accounts_guid", properties: ["guid"] })
export class Account {
  @PrimaryKey({ type: "integer", columnType: "int" })
  id!: number & Opt

  @Property({ type: "uuid", columnType: "uniqueidentifier", defaultRaw: "newid()" })
  guid!: string & Opt

  @Property({ type: "string", columnType: "nvarchar(200)" })
  name!: string

  @Property({ type: "string", columnType: "nvarchar(max)", nullable: true })
  notes!: string | null

  @Property({ type: "character", columnType: "char(8)", nullable: true })
  code!: string | null

  @Property({ type: "boolean", columnType: "bit", default: true })
  active!: boolean & Opt

  @Property({ type: "tinyint", columnType: "tinyint", unsigned: true, default: 0 })
  level!: number & Opt

  @Property({ type: "decimal", columnType: "money", nullable: true })
  balance!: string | null

  @Property({ type: "decimal", columnType: "decimal(18,2)", defaultRaw: "((0))" })
  credit!: string & Opt

  @Property({ type: "blob", columnType: "varbinary(max)", nullable: true })
  photo!: Buffer | null

  @Property({ type: "date", columnType: "date", nullable: true })
  opened_on!: string | null

  @Property({ type: "datetime", columnType: "datetime2", defaultRaw: "(sysdatetime())" })
  created_at!: Date & Opt

  @Property({ type: "datetime", columnType: "datetimeoffset", nullable: true })
  seen_at!: Date | null

  @Property({ type: "blob", columnType: "timestamp" })
  version!: Buffer

  @OneToMany({ entity: () => Transfer, mappedBy: "from_account_ref" })
  transfers_from_account = new Collection<Transfer>(this)

  @OneToMany({ entity: () => Transfer, mappedBy: "to_account_ref" })
  transfers_to_account = new Collection<Transfer>(this)
}

@Entity({ tableName: "transfers", schema: "dbo" })
@Index({ name: "IX_transfers_from", properties: ["from_account_ref"] })
export class Transfer {
  @PrimaryKey({ type: "bigint", columnType: "bigint" })
  id!: bigint & Opt

  @ManyToOne({ entity: () => Account, fieldName: "from_account", deleteRule: "cascade" })
  from_account_ref!: Rel<Account>

  @ManyToOne({ entity: () => Account, fieldName: "to_account", nullable: true })
  to_account_ref!: Rel<Account> | null

  @Property({ type: "decimal", columnType: "decimal(18,2)" })
  amount!: string

  @Property({ type: "string", columnType: "varchar(255)", default: "" })
  memo!: string & Opt
}

@Entity({ tableName: "accounts", schema: "sales" })
export class SalesAccount {
  @PrimaryKey({ type: "integer", columnType: "int", autoincrement: false })
  id!: number

  @Property({ type: "character", columnType: "nchar(2)" })
  region!: string

  @Property({ type: "string", columnType: "xml", nullable: true })
  payload!: string | null
}
