// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations.

import { relations } from "drizzle-orm"
import {
  bigint,
  bigserial,
  boolean,
  char,
  customType,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core"

const bytea = customType<{ data: Buffer }>({
  dataType() {
    return "bytea"
  },
})

export const customer_tier = pgEnum("customer_tier", ["free", "plus", "pro"])
export const order_status = pgEnum("order_status", ["pending", "paid", "shipped", "delivered", "cancelled", "refunded"])

/** People who have an account in the shop */
export const customers = pgTable("customers", {
  id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
  email: text("email").notNull().unique(),
  full_name: text("full_name").notNull(),
  tier: customer_tier("tier").notNull().default("free"),
  country: char("country", { length: 2 }),
  marketing_opt_in: boolean("marketing_opt_in").notNull().default(false),
  tags: text("tags").array().notNull().default([]),
  profile: jsonb("profile").notNull().default({}),
  avatar: bytea("avatar"),
  external_id: uuid("external_id").notNull().defaultRandom(),
  lifetime_value: numeric("lifetime_value", { precision: 12, scale: 2 }).notNull().default("0"),
  created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  last_seen_at: timestamp("last_seen_at", { withTimezone: true }),
})

export const order_items = pgTable(
  "order_items",
  {
    order_id: bigint("order_id", { mode: "number" }).notNull().references(() => orders.id, { onDelete: "cascade" }),
    line_no: smallint("line_no").notNull(),
    product_id: bigint("product_id", { mode: "number" }).notNull(),
    quantity: integer("quantity").notNull().default(1),
    unit_price_cents: integer("unit_price_cents").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.order_id, table.line_no] }),
    unique("order_items_order_product_key").on(table.order_id, table.product_id),
  ],
)

export const orders = pgTable(
  "orders",
  {
    id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
    customer_id: bigint("customer_id", { mode: "number" }).notNull().references(() => customers.id, { onDelete: "cascade" }),
    status: order_status("status").notNull().default("pending"),
    total_cents: bigint("total_cents", { mode: "number" }).notNull().default(0),
    currency: char("currency", { length: 3 }).notNull().default("EUR"),
    shipping_address: jsonb("shipping_address"),
    note: text("note"),
    placed_at: timestamp("placed_at", { withTimezone: true }).notNull().defaultNow(),
    shipped_at: timestamp("shipped_at", { withTimezone: true }),
  },
  (table) => [
    index("orders_status_placed_idx").on(table.status, table.placed_at.desc()),
  ],
)

export const customersRelations = relations(customers, ({ many }) => ({
  orders: many(orders, { relationName: "orders_customer_id" }),
}))

export const order_itemsRelations = relations(order_items, ({ one }) => ({
  order: one(orders, {
    fields: [order_items.order_id],
    references: [orders.id],
    relationName: "order_items_order_id",
  }),
}))

export const ordersRelations = relations(orders, ({ one, many }) => ({
  customer: one(customers, {
    fields: [orders.customer_id],
    references: [customers.id],
    relationName: "orders_customer_id",
  }),
  order_items: many(order_items, { relationName: "order_items_order_id" }),
}))
