// Generated by Just Dashboard from live database introspection.
// The Database interface Kysely is typed by. Generated<T> marks a column
// the database fills in: optional on insert, always present on select.

import type { Generated, Insertable, Selectable, Updateable } from "kysely"

export interface CustomerTable {
  ID: Generated<string>
  EMAIL: string
  FULL_NAME: string | null
  BALANCE: Generated<string>
  POINTS: string | null
  BIG_ID: string | null
  RATIO: number | null
  NOTES: string | null
  TOKEN: string | null
  STATE: Generated<string>
  CREATED: Generated<string>
  UPDATED: string | null
  KEPT_FOR: string | null
}

export interface OrderTable {
  ID: string
  CUSTOMER_ID: string
  TOTAL: string
  PLACED: Generated<string>
}

export interface Database {
  CUSTOMERS: CustomerTable
  ORDERS: OrderTable
}

export type Customer = Selectable<CustomerTable>
export type NewCustomer = Insertable<CustomerTable>
export type CustomerUpdate = Updateable<CustomerTable>
export type Order = Selectable<OrderTable>
export type NewOrder = Insertable<OrderTable>
export type OrderUpdate = Updateable<OrderTable>
