// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: structs to scan rows into, in the shape sqlc
// writes. Exact numerics and UUIDs are strings, so they need no extra module.

package models

import (
	"database/sql"
	"time"
)

// Customer maps the CUSTOMERS table.
type Customer struct {
	ID       int64           `db:"ID" json:"ID"`
	Email    string          `db:"EMAIL" json:"EMAIL"`
	FullName sql.NullString  `db:"FULL_NAME" json:"FULL_NAME"`
	Balance  string          `db:"BALANCE" json:"BALANCE"`
	Points   sql.NullString  `db:"POINTS" json:"POINTS"`
	BigID    sql.NullInt64   `db:"BIG_ID" json:"BIG_ID"`
	Ratio    sql.NullFloat64 `db:"RATIO" json:"RATIO"`
	Notes    sql.NullString  `db:"NOTES" json:"NOTES"`
	Token    []byte          `db:"TOKEN" json:"TOKEN"`
	State    string          `db:"STATE" json:"STATE"`
	Created  time.Time       `db:"CREATED" json:"CREATED"`
	Updated  sql.NullTime    `db:"UPDATED" json:"UPDATED"`
	KeptFor  sql.NullString  `db:"KEPT_FOR" json:"KEPT_FOR"`
}

// Order maps the ORDERS table.
type Order struct {
	ID         int64     `db:"ID" json:"ID"`
	CustomerID int64     `db:"CUSTOMER_ID" json:"CUSTOMER_ID"`
	Total      string    `db:"TOTAL" json:"TOTAL"`
	Placed     time.Time `db:"PLACED" json:"PLACED"`
}
