// Generated by Just Dashboard from live database introspection.
// Row types as the database returns them. A nullable column is `| null`
// rather than optional: the key is always present, its value may not be.

export type EventKind = "page_view" | "click" | "add-to-cart"

export type CustomerTier = "free" | "plus" | "pro"

export type OrderStatus = "pending" | "paid" | "shipped" | "delivered" | "cancelled" | "refunded"

export interface DailyRevenue {
  day: string
  orders: number
  revenue_cents: string
}

export interface AnalyticsEvent {
  id: string
  customer_id: string | null
  kind: EventKind
  path: string | null
  duration_ms: number | null
  props: unknown | null
  occurred_at: string
}

export interface TopProduct {
  product_id: string | null
  units: string | null
}

export interface MixedCaseTable {
  Id: number
  select: string | null
  "weird column": string | null
  "2fa": boolean
}

export interface AuditLog {
  at: string
  actor: string | null
  action: string
  payload: unknown | null
}

export interface Category {
  id: number
  slug: string
  name: string
  parent_id: number | null
}

export interface CustomerProfile {
  customer_id: string
  bio: string | null
  website: string | null
}

/** People who have an account in the shop */
export interface Customer {
  id: string
  email: string
  full_name: string
  tier: CustomerTier
  country: string | null
  marketing_opt_in: boolean
  tags: string[]
  profile: unknown
  avatar: string | null
  external_id: string
  lifetime_value: string
  created_at: string
  last_seen_at: string | null
}

export interface Event {
  id: string
  name: string
  starts_at: string
}

export interface Measurement {
  sensor_id: number
  taken_at: string
  reading: number | null
}

export interface Message {
  id: string
  sender_id: string
  recipient_id: string | null
  body: string
  sent_at: string
}

export interface OrderItem {
  order_id: string
  line_no: number
  product_id: string
  quantity: number
  unit_price_cents: number
}

export interface OrderSummary {
  id: string | null
  email: string | null
  status: OrderStatus | null
  total_cents: string | null
}

export interface Order {
  id: string
  customer_id: string
  status: OrderStatus
  total_cents: string
  currency: string
  shipping_address: unknown | null
  note: string | null
  placed_at: string
  shipped_at: string | null
}

export interface Product {
  id: string
  sku: string
  name: string
  description: string | null
  category_id: number | null
  price_cents: number
  stock: number
  attributes: unknown
  weight_kg: number | null
  discontinued: boolean
  released_on: string | null
  updated_at: string
}

export interface Shipment {
  id: number
  order_id: string
  line_no: number
  category_slug: string | null
  tracking_code: string
}

export interface TypeSample {
  id: number
  small: number
  ratio: number | null
  price: string | null
  amount: string | null
  code: string
  fixed: string | null
  starts: string | null
  starts_tz: string | null
  span: string | null
  addr: string | null
  doc: string | null
  flags: string | null
  search: string | null
  scores: number[] | null
  day: string
  meta: unknown | null
  label: string
  total: string | null
  stamp: string
}
