// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: structs to scan rows into, in the shape sqlc
// writes. Exact numerics and UUIDs are strings, so they need no extra module.

package models

import (
	"database/sql"
	"time"
)

// Account maps the accounts table.
type Account struct {
	ID        int32          `db:"id" json:"id"`
	GUID      string         `db:"guid" json:"guid"`
	Name      string         `db:"name" json:"name"`
	Notes     sql.NullString `db:"notes" json:"notes"`
	Code      sql.NullString `db:"code" json:"code"`
	Active    bool           `db:"active" json:"active"`
	Level     uint8          `db:"level" json:"level"`
	Balance   sql.NullString `db:"balance" json:"balance"`
	Credit    string         `db:"credit" json:"credit"`
	Photo     []byte         `db:"photo" json:"photo"`
	OpenedOn  sql.NullTime   `db:"opened_on" json:"opened_on"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	SeenAt    sql.NullTime   `db:"seen_at" json:"seen_at"`
	Version   []byte         `db:"version" json:"version"`
}

// Transfer maps the transfers table.
type Transfer struct {
	ID          int64         `db:"id" json:"id"`
	FromAccount int32         `db:"from_account" json:"from_account"`
	ToAccount   sql.NullInt32 `db:"to_account" json:"to_account"`
	Amount      string        `db:"amount" json:"amount"`
	Memo        string        `db:"memo" json:"memo"`
}

// SalesAccount maps the accounts table.
type SalesAccount struct {
	ID      int32          `db:"id" json:"id"`
	Region  string         `db:"region" json:"region"`
	Payload sql.NullString `db:"payload" json:"payload"`
}
