-- Generated by Just Dashboard from live database introspection.
-- The schema as CREATE statements in PostgreSQL's own dialect. A reviewed starting
-- point: structure only — no rows, grants, functions or triggers.

CREATE SCHEMA "analytics";

CREATE TYPE "analytics"."event_kind" AS ENUM ('page_view', 'click', 'add-to-cart');

CREATE TYPE "public"."customer_tier" AS ENUM ('free', 'plus', 'pro');

CREATE TYPE "public"."order_status" AS ENUM ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded');

CREATE TABLE "analytics"."daily_revenue" (
  "day" date NOT NULL,
  "orders" integer NOT NULL,
  "revenue_cents" bigint NOT NULL,
  CONSTRAINT "daily_revenue_pkey" PRIMARY KEY ("day")
);

CREATE TABLE "analytics"."events" (
  "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  "customer_id" bigint,
  "kind" analytics.event_kind NOT NULL,
  "path" text,
  "duration_ms" integer,
  "props" jsonb,
  "occurred_at" timestamp with time zone NOT NULL,
  CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "events_occurred_idx" ON "analytics"."events" ("occurred_at");

CREATE TABLE "public"."Mixed Case Table" (
  "Id" integer NOT NULL,
  "select" text,
  "weird column" text,
  "2fa" boolean DEFAULT false NOT NULL,
  CONSTRAINT "Mixed Case Table_pkey" PRIMARY KEY ("Id")
);

CREATE TABLE "public"."audit_log" (
  "at" timestamp with time zone DEFAULT now() NOT NULL,
  "actor" text,
  "action" text NOT NULL,
  "payload" jsonb
);

CREATE TABLE "public"."categories" (
  "id" serial NOT NULL,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "parent_id" integer,
  CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "categories_slug_key" ON "public"."categories" ("slug");

CREATE TABLE "public"."customer_profiles" (
  "customer_id" bigint NOT NULL,
  "bio" text,
  "website" character varying(255),
  CONSTRAINT "customer_profiles_pkey" PRIMARY KEY ("customer_id")
);

CREATE TABLE "public"."customers" (
  "id" bigserial NOT NULL,
  "email" text NOT NULL,
  "full_name" text NOT NULL,
  "tier" customer_tier DEFAULT 'free'::customer_tier NOT NULL,
  "country" character(2),
  "marketing_opt_in" boolean DEFAULT false NOT NULL,
  "tags" text[] DEFAULT '{}'::text[] NOT NULL,
  "profile" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "avatar" bytea,
  "external_id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "lifetime_value" numeric(12,2) DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "last_seen_at" timestamp with time zone,
  CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."customers" IS 'People who have an account in the shop';

COMMENT ON COLUMN "public"."customers"."profile" IS 'Free-form preferences captured at sign-up';

CREATE UNIQUE INDEX "customers_email_key" ON "public"."customers" ("email");

CREATE UNIQUE INDEX customers_lower_email_idx ON public.customers USING btree (lower(email));

CREATE INDEX customers_active_idx ON public.customers USING btree (last_seen_at) WHERE (last_seen_at IS NOT NULL);

CREATE TABLE "public"."events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying(120) NOT NULL,
  "starts_at" timestamp without time zone NOT NULL,
  CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "public"."measurements" (
  "sensor_id" integer NOT NULL,
  "taken_at" timestamp with time zone NOT NULL,
  "reading" double precision,
  CONSTRAINT "measurements_pkey" PRIMARY KEY ("sensor_id", "taken_at")
) PARTITION BY RANGE (taken_at);

CREATE TABLE "public"."messages" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "sender_id" bigint NOT NULL,
  "recipient_id" bigint,
  "body" text NOT NULL,
  "sent_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "public"."order_items" (
  "order_id" bigint NOT NULL,
  "line_no" smallint NOT NULL,
  "product_id" bigint NOT NULL,
  "quantity" integer DEFAULT 1 NOT NULL,
  "unit_price_cents" integer NOT NULL,
  CONSTRAINT "order_items_pkey" PRIMARY KEY ("order_id", "line_no"),
  CONSTRAINT "order_items_quantity_check" CHECK ((quantity > 0))
);

CREATE UNIQUE INDEX "order_items_order_product_key" ON "public"."order_items" ("order_id", "product_id");

CREATE TABLE "public"."orders" (
  "id" bigserial NOT NULL,
  "customer_id" bigint NOT NULL,
  "status" order_status DEFAULT 'pending'::order_status NOT NULL,
  "total_cents" bigint DEFAULT 0 NOT NULL,
  "currency" character(3) DEFAULT 'EUR'::bpchar NOT NULL,
  "shipping_address" jsonb,
  "note" text,
  "placed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "shipped_at" timestamp with time zone,
  CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

CREATE INDEX orders_status_placed_idx ON public.orders USING btree (status, placed_at DESC);

CREATE TABLE "public"."products" (
  "id" bigserial NOT NULL,
  "sku" character varying(32) NOT NULL,
  "name" character varying(200) NOT NULL,
  "description" text,
  "category_id" integer,
  "price_cents" integer NOT NULL,
  "stock" integer DEFAULT 0 NOT NULL,
  "attributes" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "weight_kg" double precision,
  "discontinued" boolean DEFAULT false NOT NULL,
  "released_on" date,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "products_sku_key" ON "public"."products" ("sku");

CREATE INDEX products_category_idx ON public.products USING btree (category_id);

CREATE INDEX products_attributes_gin ON public.products USING gin (attributes);

CREATE TABLE "public"."shipments" (
  "id" serial NOT NULL,
  "order_id" bigint NOT NULL,
  "line_no" smallint NOT NULL,
  "category_slug" text,
  "tracking_code" character varying(40) NOT NULL,
  CONSTRAINT "shipments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "shipments_tracking_code_key" ON "public"."shipments" ("tracking_code");

CREATE TABLE "public"."type_samples" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "small" smallint DEFAULT 0 NOT NULL,
  "ratio" real,
  "price" money,
  "amount" numeric,
  "code" character varying(16) DEFAULT 'N/A'::character varying NOT NULL,
  "fixed" character(4),
  "starts" time without time zone,
  "starts_tz" time with time zone,
  "span" interval,
  "addr" inet,
  "doc" xml,
  "flags" bit(8),
  "search" tsvector,
  "scores" integer[],
  "day" date DEFAULT CURRENT_DATE NOT NULL,
  "meta" json,
  "label" text DEFAULT 'it''s'::text NOT NULL,
  "total" numeric(10,2) GENERATED ALWAYS AS (((small)::numeric * 1.5)) STORED,
  "stamp" timestamp(3) without time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT "type_samples_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "analytics"."events" ADD CONSTRAINT "events_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE SET NULL;

ALTER TABLE "public"."categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."categories" ("id");

ALTER TABLE "public"."customer_profiles" ADD CONSTRAINT "customer_profiles_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."messages" ADD CONSTRAINT "messages_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "public"."customers" ("id") ON DELETE SET NULL;

ALTER TABLE "public"."messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id");

ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories" ("id");

ALTER TABLE "public"."shipments" ADD CONSTRAINT "shipments_category_slug_fkey" FOREIGN KEY ("category_slug") REFERENCES "public"."categories" ("slug");

ALTER TABLE "public"."shipments" ADD CONSTRAINT "shipments_item_fkey" FOREIGN KEY ("order_id", "line_no") REFERENCES "public"."order_items" ("order_id", "line_no") ON DELETE CASCADE;
