// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type NonAttribute,
  type Sequelize,
} from "sequelize"
import { Customer } from "./Customer"
import { EventKind } from "./enums"

export class AnalyticsEvent extends Model<InferAttributes<AnalyticsEvent>, InferCreationAttributes<AnalyticsEvent>> {
  declare id: CreationOptional<string>
  declare customerId: CreationOptional<string | null>
  declare kind: EventKind
  declare path: CreationOptional<string | null>
  declare durationMs: CreationOptional<number | null>
  declare props: CreationOptional<unknown>
  declare occurredAt: Date

  declare customer?: NonAttribute<Customer>
}

export function initAnalyticsEvent(sequelize: Sequelize): typeof AnalyticsEvent {
  AnalyticsEvent.init(
    {
      id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true, allowNull: false },
      customerId: { type: DataTypes.BIGINT, field: "customer_id", allowNull: true },
      kind: { type: DataTypes.ENUM("page_view", "click", "add-to-cart"), allowNull: false },
      path: { type: DataTypes.TEXT, allowNull: true },
      durationMs: { type: DataTypes.INTEGER, field: "duration_ms", allowNull: true },
      props: { type: DataTypes.JSONB, allowNull: true },
      occurredAt: { type: DataTypes.DATE, field: "occurred_at", allowNull: false },
    },
    {
      sequelize,
      tableName: "events",
      schema: "analytics",
      timestamps: false,
      indexes: [
        { name: "events_occurred_idx", fields: ["occurred_at"] },
      ],
    },
  )
  return AnalyticsEvent
}
