// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type Sequelize,
} from "sequelize"

export class AuditLog extends Model<InferAttributes<AuditLog>, InferCreationAttributes<AuditLog>> {
  declare at: CreationOptional<Date>
  declare actor: CreationOptional<string | null>
  declare action: string
  declare payload: CreationOptional<unknown>
}

export function initAuditLog(sequelize: Sequelize): typeof AuditLog {
  AuditLog.init(
    {
      at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
      actor: { type: DataTypes.TEXT, allowNull: true },
      action: { type: DataTypes.TEXT, allowNull: false },
      payload: { type: DataTypes.JSONB, allowNull: true },
    },
    {
      sequelize,
      tableName: "audit_log",
      schema: "public",
      timestamps: false,
    },
  )
  AuditLog.removeAttribute("id")
  return AuditLog
}
