// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type Sequelize,
} from "sequelize"

export class DailyRevenue extends Model<InferAttributes<DailyRevenue>, InferCreationAttributes<DailyRevenue>> {
  declare day: string
  declare orders: number
  declare revenueCents: string
}

export function initDailyRevenue(sequelize: Sequelize): typeof DailyRevenue {
  DailyRevenue.init(
    {
      day: { type: DataTypes.DATEONLY, primaryKey: true, allowNull: false },
      orders: { type: DataTypes.INTEGER, allowNull: false },
      revenueCents: { type: DataTypes.BIGINT, field: "revenue_cents", allowNull: false },
    },
    {
      sequelize,
      tableName: "daily_revenue",
      schema: "analytics",
      timestamps: false,
    },
  )
  return DailyRevenue
}
