// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

export type EventKind = "page_view" | "click" | "add-to-cart"

export type CustomerTier = "free" | "plus" | "pro"

export type OrderStatus = "pending" | "paid" | "shipped" | "delivered" | "cancelled" | "refunded"
