// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type NonAttribute,
  type Sequelize,
  literal,
} from "sequelize"
import { Customer } from "./Customer"

export class Message extends Model<InferAttributes<Message>, InferCreationAttributes<Message>> {
  declare id: CreationOptional<string>
  declare senderId: string
  declare recipientId: CreationOptional<string | null>
  declare body: string
  declare sentAt: CreationOptional<Date>

  declare recipient?: NonAttribute<Customer>
  declare sender?: NonAttribute<Customer>
}

export function initMessage(sequelize: Sequelize): typeof Message {
  Message.init(
    {
      id: { type: DataTypes.UUID, primaryKey: true, allowNull: false, defaultValue: literal("gen_random_uuid()") },
      senderId: { type: DataTypes.BIGINT, field: "sender_id", allowNull: false },
      recipientId: { type: DataTypes.BIGINT, field: "recipient_id", allowNull: true },
      body: { type: DataTypes.TEXT, allowNull: false },
      sentAt: { type: DataTypes.DATE(3), field: "sent_at", allowNull: false, defaultValue: DataTypes.NOW },
    },
    {
      sequelize,
      tableName: "messages",
      schema: "public",
      timestamps: false,
    },
  )
  return Message
}
