// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type NonAttribute,
  type Sequelize,
} from "sequelize"
import { Customer } from "./Customer"
import { OrderItem } from "./OrderItem"
import { OrderStatus } from "./enums"

export class Order extends Model<InferAttributes<Order>, InferCreationAttributes<Order>> {
  declare id: CreationOptional<string>
  declare customerId: string
  declare status: CreationOptional<OrderStatus>
  declare totalCents: CreationOptional<string>
  declare currency: CreationOptional<string>
  declare shippingAddress: CreationOptional<unknown>
  declare note: CreationOptional<string | null>
  declare placedAt: CreationOptional<Date>
  declare shippedAt: CreationOptional<Date | null>

  declare customer?: NonAttribute<Customer>
  declare orderItems?: NonAttribute<OrderItem[]>
}

export function initOrder(sequelize: Sequelize): typeof Order {
  Order.init(
    {
      id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true, allowNull: false },
      customerId: { type: DataTypes.BIGINT, field: "customer_id", allowNull: false },
      status: { type: DataTypes.ENUM("pending", "paid", "shipped", "delivered", "cancelled", "refunded"), allowNull: false, defaultValue: "pending" },
      totalCents: { type: DataTypes.BIGINT, field: "total_cents", allowNull: false, defaultValue: "0" },
      currency: { type: DataTypes.CHAR(3), allowNull: false, defaultValue: "EUR" },
      shippingAddress: { type: DataTypes.JSONB, field: "shipping_address", allowNull: true },
      note: { type: DataTypes.TEXT, allowNull: true },
      placedAt: { type: DataTypes.DATE, field: "placed_at", allowNull: false, defaultValue: DataTypes.NOW },
      shippedAt: { type: DataTypes.DATE, field: "shipped_at", allowNull: true },
    },
    {
      sequelize,
      tableName: "orders",
      schema: "public",
      timestamps: false,
      indexes: [
        { name: "orders_status_placed_idx", fields: ["status", "placed_at"] },
      ],
    },
  )
  return Order
}
