// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type NonAttribute,
  type Sequelize,
} from "sequelize"
import { Category } from "./Category"

export class Shipment extends Model<InferAttributes<Shipment>, InferCreationAttributes<Shipment>> {
  declare id: CreationOptional<number>
  declare orderId: string
  declare lineNo: number
  declare categorySlug: CreationOptional<string | null>
  declare trackingCode: string

  declare category?: NonAttribute<Category>
}

export function initShipment(sequelize: Sequelize): typeof Shipment {
  Shipment.init(
    {
      id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true, allowNull: false },
      orderId: { type: DataTypes.BIGINT, field: "order_id", allowNull: false },
      lineNo: { type: DataTypes.SMALLINT, field: "line_no", allowNull: false },
      categorySlug: { type: DataTypes.TEXT, field: "category_slug", allowNull: true },
      trackingCode: { type: DataTypes.STRING(40), field: "tracking_code", allowNull: false },
    },
    {
      sequelize,
      tableName: "shipments",
      schema: "public",
      timestamps: false,
      indexes: [
        { name: "shipments_tracking_code_key", unique: true, fields: ["tracking_code"] },
      ],
    },
  )
  return Shipment
}
