// Generated by Just Dashboard from live database introspection.
// The Database interface Kysely is typed by. Generated<T> marks a column
// the database fills in: optional on insert, always present on select.

import type { Generated, Insertable, Selectable, Updateable } from "kysely"

export interface NoteTable {
  id: Generated<number>
  user_id: number
  title: string
  body: string | null
  pinned: Generated<number>
  score: number | null
  price: number | null
  payload: string | null
  attachment: Buffer | null
  created_at: Generated<string>
}

export interface UserTagTable {
  user_id: number
  tag: string
}

export interface UserTable {
  id: Generated<number>
  email: string
  name: string | null
}

export interface Database {
  notes: NoteTable
  user_tags: UserTagTable
  users: UserTable
}

export type Note = Selectable<NoteTable>
export type NewNote = Insertable<NoteTable>
export type NoteUpdate = Updateable<NoteTable>
export type UserTag = Selectable<UserTagTable>
export type NewUserTag = Insertable<UserTagTable>
export type UserTagUpdate = Updateable<UserTagTable>
export type User = Selectable<UserTable>
export type NewUser = Insertable<UserTable>
export type UserUpdate = Updateable<UserTable>
