// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations.

import { relations, sql } from "drizzle-orm"
import {
  type AnyPgColumn,
  bigint,
  bigserial,
  boolean,
  char,
  customType,
  date,
  doublePrecision,
  foreignKey,
  index,
  inet,
  integer,
  interval,
  json,
  jsonb,
  numeric,
  pgEnum,
  pgSchema,
  pgTable,
  primaryKey,
  real,
  serial,
  smallint,
  text,
  time,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core"

const bytea = customType<{ data: Buffer }>({
  dataType() {
    return "bytea"
  },
})

const money = customType<{ data: string }>({
  dataType() {
    return "money"
  },
})

const xml = customType<{ data: string }>({
  dataType() {
    return "xml"
  },
})

const bit8 = customType<{ data: string }>({
  dataType() {
    return "bit(8)"
  },
})

const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector"
  },
})

export const analytics = pgSchema("analytics")

export const eventKind = analytics.enum("event_kind", ["page_view", "click", "add-to-cart"])
export const customerTier = pgEnum("customer_tier", ["free", "plus", "pro"])
export const orderStatus = pgEnum("order_status", ["pending", "paid", "shipped", "delivered", "cancelled", "refunded"])

export const dailyRevenue = analytics.table("daily_revenue", {
  day: date("day").primaryKey().notNull(),
  orders: integer("orders").notNull(),
  revenueCents: bigint("revenue_cents", { mode: "number" }).notNull(),
})

export const analyticsEvents = analytics.table(
  "events",
  {
    id: bigint("id", { mode: "number" }).primaryKey().notNull().generatedAlwaysAsIdentity(),
    customerId: bigint("customer_id", { mode: "number" }).references(() => customers.id, { onDelete: "set null" }),
    kind: eventKind("kind").notNull(),
    path: text("path"),
    durationMs: integer("duration_ms"),
    props: jsonb("props"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    index("events_occurred_idx").on(table.occurredAt),
  ],
)

export const mixedCaseTable = pgTable("Mixed Case Table", {
  id: integer("Id").primaryKey().notNull(),
  select: text("select"),
  weirdColumn: text("weird column"),
  _2fa: boolean("2fa").notNull().default(false),
})

export const auditLog = pgTable("audit_log", {
  at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  actor: text("actor"),
  action: text("action").notNull(),
  payload: jsonb("payload"),
})

export const categories = pgTable("categories", {
  id: serial("id").primaryKey().notNull(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  parentId: integer("parent_id").references((): AnyPgColumn => categories.id),
})

export const customerProfiles = pgTable("customer_profiles", {
  customerId: bigint("customer_id", { mode: "number" }).primaryKey().notNull().references(() => customers.id, { onDelete: "cascade" }),
  bio: text("bio"),
  website: varchar("website", { length: 255 }),
})

/** People who have an account in the shop */
export const customers = pgTable("customers", {
  id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
  email: text("email").notNull().unique(),
  fullName: text("full_name").notNull(),
  tier: customerTier("tier").notNull().default("free"),
  country: char("country", { length: 2 }),
  marketingOptIn: boolean("marketing_opt_in").notNull().default(false),
  tags: text("tags").array().notNull().default([]),
  profile: jsonb("profile").notNull().default({}),
  avatar: bytea("avatar"),
  externalId: uuid("external_id").notNull().defaultRandom(),
  lifetimeValue: numeric("lifetime_value", { precision: 12, scale: 2 }).notNull().default("0"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
})

export const events = pgTable("events", {
  id: bigint("id", { mode: "number" }).primaryKey().notNull().generatedByDefaultAsIdentity(),
  name: varchar("name", { length: 120 }).notNull(),
  startsAt: timestamp("starts_at").notNull(),
})

export const measurements = pgTable(
  "measurements",
  {
    sensorId: integer("sensor_id").notNull(),
    takenAt: timestamp("taken_at", { withTimezone: true }).notNull(),
    reading: doublePrecision("reading"),
  },
  (table) => [
    primaryKey({ columns: [table.sensorId, table.takenAt] }),
  ],
)

export const messages = pgTable("messages", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  senderId: bigint("sender_id", { mode: "number" }).notNull().references(() => customers.id, { onDelete: "cascade" }),
  recipientId: bigint("recipient_id", { mode: "number" }).references(() => customers.id, { onDelete: "set null" }),
  body: text("body").notNull(),
  sentAt: timestamp("sent_at", { precision: 3, withTimezone: true }).notNull().defaultNow(),
})

export const orderItems = pgTable(
  "order_items",
  {
    orderId: bigint("order_id", { mode: "number" }).notNull().references(() => orders.id, { onDelete: "cascade" }),
    lineNo: smallint("line_no").notNull(),
    productId: bigint("product_id", { mode: "number" }).notNull().references(() => products.id),
    quantity: integer("quantity").notNull().default(1),
    unitPriceCents: integer("unit_price_cents").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.orderId, table.lineNo] }),
    unique("order_items_order_product_key").on(table.orderId, table.productId),
  ],
)

export const orders = pgTable(
  "orders",
  {
    id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
    customerId: bigint("customer_id", { mode: "number" }).notNull().references(() => customers.id, { onDelete: "cascade" }),
    status: orderStatus("status").notNull().default("pending"),
    totalCents: bigint("total_cents", { mode: "number" }).notNull().default(0),
    currency: char("currency", { length: 3 }).notNull().default("EUR"),
    shippingAddress: jsonb("shipping_address"),
    note: text("note"),
    placedAt: timestamp("placed_at", { withTimezone: true }).notNull().defaultNow(),
    shippedAt: timestamp("shipped_at", { withTimezone: true }),
  },
  (table) => [
    index("orders_status_placed_idx").on(table.status, table.placedAt.desc()),
  ],
)

export const products = pgTable(
  "products",
  {
    id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
    sku: varchar("sku", { length: 32 }).notNull().unique(),
    name: varchar("name", { length: 200 }).notNull(),
    description: text("description"),
    categoryId: integer("category_id").references(() => categories.id),
    priceCents: integer("price_cents").notNull(),
    stock: integer("stock").notNull().default(0),
    attributes: jsonb("attributes").notNull().default({}),
    weightKg: doublePrecision("weight_kg"),
    discontinued: boolean("discontinued").notNull().default(false),
    releasedOn: date("released_on"),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [
    index("products_category_idx").on(table.categoryId),
    index("products_attributes_gin").using("gin", table.attributes),
  ],
)

export const shipments = pgTable(
  "shipments",
  {
    id: serial("id").primaryKey().notNull(),
    orderId: bigint("order_id", { mode: "number" }).notNull(),
    lineNo: smallint("line_no").notNull(),
    categorySlug: text("category_slug").references(() => categories.slug),
    trackingCode: varchar("tracking_code", { length: 40 }).notNull().unique(),
  },
  (table) => [
    foreignKey({ columns: [table.orderId, table.lineNo], foreignColumns: [orderItems.orderId, orderItems.lineNo], name: "shipments_item_fkey" }).onDelete("cascade"),
  ],
)

export const typeSamples = pgTable("type_samples", {
  id: integer("id").primaryKey().notNull().generatedByDefaultAsIdentity(),
  small: smallint("small").notNull().default(0),
  ratio: real("ratio"),
  price: money("price"),
  amount: numeric("amount"),
  code: varchar("code", { length: 16 }).notNull().default("N/A"),
  fixed: char("fixed", { length: 4 }),
  starts: time("starts"),
  startsTz: time("starts_tz", { withTimezone: true }),
  span: interval("span"),
  addr: inet("addr"),
  doc: xml("doc"),
  flags: bit8("flags"),
  search: tsvector("search"),
  scores: integer("scores").array(),
  day: date("day").notNull().default(sql`CURRENT_DATE`),
  meta: json("meta"),
  label: text("label").notNull().default("it's"),
  total: numeric("total", { precision: 10, scale: 2 }).generatedAlwaysAs(sql`((small)::numeric * 1.5)`),
  stamp: timestamp("stamp", { precision: 3 }).notNull().default(sql`timezone('utc'::text, now())`),
})

export const analyticsEventsRelations = relations(analyticsEvents, ({ one }) => ({
  customer: one(customers, {
    fields: [analyticsEvents.customerId],
    references: [customers.id],
    relationName: "events_customer_id",
  }),
}))

export const categoriesRelations = relations(categories, ({ one, many }) => ({
  parent: one(categories, {
    fields: [categories.parentId],
    references: [categories.id],
    relationName: "categories_parent_id",
  }),
  categories: many(categories, { relationName: "categories_parent_id" }),
  products: many(products, { relationName: "products_category_id" }),
  shipments: many(shipments, { relationName: "shipments_category_slug" }),
}))

export const customerProfilesRelations = relations(customerProfiles, ({ one }) => ({
  customer: one(customers, {
    fields: [customerProfiles.customerId],
    references: [customers.id],
    relationName: "customer_profiles_customer_id",
  }),
}))

export const customersRelations = relations(customers, ({ one, many }) => ({
  events: many(analyticsEvents, { relationName: "events_customer_id" }),
  customerProfile: one(customerProfiles, {
    fields: [customers.id],
    references: [customerProfiles.customerId],
    relationName: "customer_profiles_customer_id",
  }),
  messagesRecipientId: many(messages, { relationName: "messages_recipient_id" }),
  messagesSenderId: many(messages, { relationName: "messages_sender_id" }),
  orders: many(orders, { relationName: "orders_customer_id" }),
}))

export const messagesRelations = relations(messages, ({ one }) => ({
  recipient: one(customers, {
    fields: [messages.recipientId],
    references: [customers.id],
    relationName: "messages_recipient_id",
  }),
  sender: one(customers, {
    fields: [messages.senderId],
    references: [customers.id],
    relationName: "messages_sender_id",
  }),
}))

export const orderItemsRelations = relations(orderItems, ({ one, many }) => ({
  order: one(orders, {
    fields: [orderItems.orderId],
    references: [orders.id],
    relationName: "order_items_order_id",
  }),
  product: one(products, {
    fields: [orderItems.productId],
    references: [products.id],
    relationName: "order_items_product_id",
  }),
  shipments: many(shipments, { relationName: "shipments_order_id_line_no" }),
}))

export const ordersRelations = relations(orders, ({ one, many }) => ({
  customer: one(customers, {
    fields: [orders.customerId],
    references: [customers.id],
    relationName: "orders_customer_id",
  }),
  orderItems: many(orderItems, { relationName: "order_items_order_id" }),
}))

export const productsRelations = relations(products, ({ one, many }) => ({
  category: one(categories, {
    fields: [products.categoryId],
    references: [categories.id],
    relationName: "products_category_id",
  }),
  orderItems: many(orderItems, { relationName: "order_items_product_id" }),
}))

export const shipmentsRelations = relations(shipments, ({ one }) => ({
  category: one(categories, {
    fields: [shipments.categorySlug],
    references: [categories.slug],
    relationName: "shipments_category_slug",
  }),
  orderItem: one(orderItems, {
    fields: [shipments.orderId, shipments.lineNo],
    references: [orderItems.orderId, orderItems.lineNo],
    relationName: "shipments_order_id_line_no",
  }),
}))
