package dbx

import (
	"context"
	"errors"
	"os"
	"reflect"
	"strings"
	"testing"
)

// Oracle answers from views no other engine has, counts its binds by the
// order their names first appear, hands back a LONG where others have text
// and has no empty string. A query written from its documentation is a guess
// until a server has run it.
func TestLiveOracleCatalogAndStructureChanges(t *testing.T) {
	db := catalogLive(t, DriverOracle, "JD_TEST_ORACLE_DSN")
	ctx := context.Background()
	const d = DriverOracle
	info, err := ParseDSN(d, os.Getenv("JD_TEST_ORACLE_DSN"))
	if err != nil || info.User == "" {
		t.Fatalf("the DSN names no user: %v", err)
	}
	// A schema is a user, and an unquoted user name is stored in upper case.
	schema := strings.ToUpper(info.User)
	drop := []string{
		`DROP MATERIALIZED VIEW "JD_CAT_COUNTS"`, `DROP VIEW "JD_CAT_ACTIVE"`, `DROP VIEW "JD_CAT_TITLES"`,
		`DROP SYNONYM "JD_CAT_PEOPLE"`, `DROP PROCEDURE "JD_CAT_NOOP"`, `DROP FUNCTION "JD_CAT_ADD"`,
		`DROP PACKAGE "JD_CAT_PKG"`,
		`DROP TABLE "JD_CAT_POSTS" CASCADE CONSTRAINTS PURGE`, `DROP TABLE "JD_CAT_ARTICLES" CASCADE CONSTRAINTS PURGE`,
		`DROP TABLE "JD_CAT_USERS" CASCADE CONSTRAINTS PURGE`, `DROP TABLE "JD_CAT_MADE" CASCADE CONSTRAINTS PURGE`,
		`DROP TABLE "JD_CAT_MADE2" CASCADE CONSTRAINTS PURGE`,
		`DROP SEQUENCE "JD_CAT_SEQ"`, `DROP TYPE "JD_CAT_PAIR"`,
		// A table dropped through a plan goes to the recycle bin; this takes
		// the test's own out of it and leaves anyone else's.
		`PURGE TABLE "JD_CAT_MADE2"`,
	}
	// Oracle has no DROP … IF EXISTS before 23ai, so a drop of what is not
	// there is expected to fail and is not a reason to stop.
	clean := func() {
		for _, s := range drop {
			_, _ = db.ExecContext(context.Background(), s)
		}
	}
	clean()
	t.Cleanup(clean)
	catalogExec(t, db,
		`CREATE TYPE "JD_CAT_PAIR" AS OBJECT (a NUMBER, b VARCHAR2(10))`,
		`CREATE SEQUENCE "JD_CAT_SEQ" START WITH 100 INCREMENT BY 5`,
		`CREATE TABLE "JD_CAT_USERS" (
		  "ID" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		  "EMAIL" VARCHAR2(255 CHAR) NOT NULL,
		  "NAME" VARCHAR2(100),
		  "NICK" VARCHAR2(50),
		  "SHOUT" VARCHAR2(100) GENERATED ALWAYS AS (UPPER("NAME")) VIRTUAL,
		  "SCORE" NUMBER(5) DEFAULT 5,
		  "CREATED" TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
		  CONSTRAINT "JD_CAT_USERS_EMAIL" UNIQUE ("EMAIL"),
		  CONSTRAINT "JD_CAT_SCORE_POSITIVE" CHECK ("SCORE" > 0))`,
		`COMMENT ON TABLE "JD_CAT_USERS" IS 'People'`,
		`COMMENT ON COLUMN "JD_CAT_USERS"."EMAIL" IS 'Login address'`,
		`CREATE TABLE "JD_CAT_POSTS" (
		  "ID" NUMBER(10) PRIMARY KEY,
		  "AUTHOR_ID" NUMBER(10) NOT NULL,
		  "TITLE" VARCHAR2(255) NOT NULL, "BODY" CLOB,
		  CONSTRAINT "JD_CAT_POSTS_AUTHOR" FOREIGN KEY ("AUTHOR_ID") REFERENCES "JD_CAT_USERS"("ID") ON DELETE CASCADE)`,
		`CREATE INDEX "JD_CAT_POSTS_TITLE" ON "JD_CAT_POSTS" ("TITLE")`,
		`CREATE INDEX "JD_CAT_POSTS_LOWER" ON "JD_CAT_POSTS" (LOWER("TITLE"))`,
		`CREATE VIEW "JD_CAT_ACTIVE" AS SELECT "ID", "EMAIL" FROM "JD_CAT_USERS" WHERE "NAME" IS NOT NULL`,
		`CREATE MATERIALIZED VIEW "JD_CAT_COUNTS" AS SELECT "AUTHOR_ID", COUNT(*) AS n FROM "JD_CAT_POSTS" GROUP BY "AUTHOR_ID"`,
		`CREATE FUNCTION "JD_CAT_ADD"(a NUMBER, b NUMBER) RETURN NUMBER IS BEGIN RETURN a + b; END;`,
		`CREATE PROCEDURE "JD_CAT_NOOP" IS BEGIN NULL; END;`,
		`CREATE PACKAGE "JD_CAT_PKG" AS FUNCTION one RETURN NUMBER; END;`,
		`CREATE PACKAGE BODY "JD_CAT_PKG" AS FUNCTION one RETURN NUMBER IS BEGIN RETURN 1; END; END;`,
		`CREATE TRIGGER "JD_CAT_TOUCH" BEFORE INSERT OR UPDATE ON "JD_CAT_USERS" FOR EACH ROW BEGIN :NEW."NAME" := :NEW."NAME"; END;`,
		`CREATE SYNONYM "JD_CAT_PEOPLE" FOR "JD_CAT_USERS"`,
		`INSERT INTO "JD_CAT_USERS" ("EMAIL", "NAME", "SCORE") VALUES ('a@x.io', 'Ann', 3)`,
		`INSERT INTO "JD_CAT_USERS" ("EMAIL", "NAME", "SCORE") VALUES ('b@x.io', NULL, NULL)`,
		`INSERT INTO "JD_CAT_POSTS" ("ID", "AUTHOR_ID", "TITLE") VALUES (1, 1, 'Hello')`,
	)
	run := runPlan(t, db)
	describe := func(table string) *TableDetail {
		t.Helper()
		detail, err := DescribeTable(ctx, db, d, schema, table)
		if err != nil {
			t.Fatal(err)
		}
		return detail
	}

	t.Run("tree", func(t *testing.T) {
		// No schema named: the user the session is.
		catalog, err := ReadCatalog(ctx, db, d, CatalogOptions{})
		if err != nil {
			t.Fatal(err)
		}
		if catalog.Errors != nil {
			t.Errorf("groups failed: %v", catalog.Errors)
		}
		if catalog.Schema != schema || catalog.DefaultSchema != schema {
			t.Errorf("schema = %q, default = %q, want %q", catalog.Schema, catalog.DefaultSchema, schema)
		}
		groups := []string{}
		for group := range catalog.Objects {
			groups = append(groups, group)
		}
		if advertised := CatalogGroups(d, ""); len(advertised) != len(groups) {
			t.Errorf("Oracle advertises %v and read %v", advertised, groups)
		}
		var own, system *CatalogSchema
		for i := range catalog.Schemas {
			switch catalog.Schemas[i].Name {
			case schema:
				own = &catalog.Schemas[i]
			case "SYS":
				system = &catalog.Schemas[i]
			}
		}
		if own == nil || own.System || !own.Default || own.Tables != -1 || system == nil || !system.System {
			t.Errorf("schemas: own = %+v, SYS = %+v", own, system)
		}
		// The size is the login's own segments: the table's and its two indexes'.
		if users := catObject(catalog.Objects[GroupTables], "JD_CAT_USERS"); users == nil || users.Comment != "People" ||
			users.Rows == nil || users.Schema != schema || users.Size <= 0 {
			t.Errorf("users = %+v", users)
		}
		// A materialized view's container is a table to Oracle and not to
		// anyone reading the tree.
		if catObject(catalog.Objects[GroupTables], "JD_CAT_COUNTS") != nil || catObject(catalog.Objects[GroupTables], "JD_CAT_ACTIVE") != nil {
			t.Errorf("tables = %+v", catalog.Objects[GroupTables])
		}
		if catObject(catalog.Objects[GroupViews], "JD_CAT_ACTIVE") == nil {
			t.Errorf("views = %+v", catalog.Objects[GroupViews])
		}
		if mv := catObject(catalog.Objects[GroupMaterializedViews], "JD_CAT_COUNTS"); mv == nil || !strings.HasPrefix(mv.Detail, "refresh ") {
			t.Errorf("materialized view = %+v", mv)
		}
		if fn := catObject(catalog.Objects[GroupFunctions], "JD_CAT_ADD"); fn == nil || fn.Language != "PL/SQL" || fn.Detail != "" {
			t.Errorf("function = %+v", fn)
		}
		if catObject(catalog.Objects[GroupProcedures], "JD_CAT_NOOP") == nil || catObject(catalog.Objects[GroupPackages], "JD_CAT_PKG") == nil {
			t.Errorf("procedures = %+v, packages = %+v", catalog.Objects[GroupProcedures], catalog.Objects[GroupPackages])
		}
		if tr := catObject(catalog.Objects[GroupTriggers], "JD_CAT_TOUCH"); tr == nil || tr.Table != "JD_CAT_USERS" ||
			tr.Detail != "BEFORE INSERT OR UPDATE, each row" {
			t.Errorf("trigger = %+v", tr)
		}
		if seq := catObject(catalog.Objects[GroupSequences], "JD_CAT_SEQ"); seq == nil || seq.Detail != "step 5" {
			t.Errorf("sequence = %+v", seq)
		}
		if typ := catObject(catalog.Objects[GroupTypes], "JD_CAT_PAIR"); typ == nil || typ.Kind != KindType {
			t.Errorf("type = %+v", typ)
		}
		if syn := catObject(catalog.Objects[GroupSynonyms], "JD_CAT_PEOPLE"); syn == nil || syn.Detail != schema+".JD_CAT_USERS" {
			t.Errorf("synonym = %+v", syn)
		}
		// Named, the same schema reads the same, and is cut where it is told to be.
		named, err := ReadCatalog(ctx, db, d, CatalogOptions{Schema: schema, Limit: 1})
		if err != nil || named.Errors != nil || len(named.Objects[GroupTables]) != 1 || !contains(named.Truncated, GroupTables) {
			t.Errorf("bounded catalogue: %d tables, cut %v, errors %v, %v", len(named.Objects[GroupTables]), named.Truncated, named.Errors, err)
		}
		// Every schema at once: the unnamed case binds no schema at all, and
		// leaves Oracle's own schemas out.
		all, err := ReadCatalog(ctx, db, d, CatalogOptions{All: true})
		if err != nil || all.Errors != nil || all.Schema != "" || catObject(all.Objects[GroupTables], "JD_CAT_USERS") == nil ||
			catObject(all.Objects[GroupTriggers], "JD_CAT_TOUCH") == nil {
			t.Errorf("every schema: schema %q, %d tables, errors %v, %v", all.Schema, len(all.Objects[GroupTables]), all.Errors, err)
		}
		for _, o := range all.Objects[GroupTables] {
			if o.Schema == "SYS" || o.Schema == "SYSTEM" {
				t.Errorf("every schema lists one of Oracle's own: %+v", o)
				break
			}
		}
	})

	t.Run("table", func(t *testing.T) {
		users := describe("JD_CAT_USERS")
		if users.Type != TableTypeTable || users.Comment != "People" || users.Schema != schema || users.Owner != schema ||
			!reflect.DeepEqual(users.PrimaryKey, []string{"ID"}) {
			t.Errorf("users = %+v", users)
		}
		if users.DataSize <= 0 || users.IndexSize <= 0 || users.Size != users.DataSize+users.IndexSize {
			t.Errorf("users takes %d bytes: %d of rows, %d of indexes", users.Size, users.DataSize, users.IndexSize)
		}
		if c := catColumn(t, users, "ID"); c.Identity != "by default" || c.Key != "PRI" || c.Type != "NUMBER(10,0)" || c.Default != "" {
			t.Errorf("ID = %+v", c)
		}
		// The length is in characters, as it was declared: in bytes a 255
		// character column of a UTF-8 database reads as 1020.
		if c := catColumn(t, users, "EMAIL"); c.Comment != "Login address" || c.Type != "VARCHAR2(255)" || c.Nullable {
			t.Errorf("EMAIL = %+v", c)
		}
		if c := catColumn(t, users, "SHOUT"); c.GeneratedKind != "virtual" || !strings.Contains(c.Generated, `UPPER("NAME")`) || c.Default != "" {
			t.Errorf("SHOUT = %+v", c)
		}
		if c := catColumn(t, users, "SCORE"); c.Default != "5" || !c.Nullable {
			t.Errorf("SCORE = %+v", c)
		}
		if c := catColumn(t, users, "CREATED"); c.Type != "TIMESTAMP(3)" || !strings.EqualFold(c.Default, "SYSTIMESTAMP") {
			t.Errorf("CREATED = %+v", c)
		}
		// NOT NULL is a check constraint to Oracle and nullability to a reader.
		if len(users.Constraints) != 2 {
			t.Errorf("constraints = %+v", users.Constraints)
		}
		if c := catConstraint(users, "JD_CAT_SCORE_POSITIVE"); c == nil || c.Type != ConstraintCheck || c.Definition != `CHECK ("SCORE" > 0)` {
			t.Errorf("check = %+v", c)
		}
		if c := catConstraint(users, "JD_CAT_USERS_EMAIL"); c == nil || c.Type != ConstraintUnique || c.Definition != `UNIQUE ("EMAIL")` {
			t.Errorf("unique = %+v", c)
		}
		if len(users.ReferencedBy) != 1 || users.ReferencedBy[0].Table != "JD_CAT_POSTS" || users.ReferencedBy[0].OnDelete != "CASCADE" ||
			!reflect.DeepEqual(users.ReferencedBy[0].RefColumns, []string{"ID"}) {
			t.Errorf("referencedBy = %+v", users.ReferencedBy)
		}
		if !strings.Contains(users.CreateSQL, `CREATE TABLE "`+schema+`"."JD_CAT_USERS"`) {
			t.Errorf("definition (%s):\n%s", users.CreateSQLSource, users.CreateSQL)
		}

		posts := describe("JD_CAT_POSTS")
		if ix := catIndex(posts, "JD_CAT_POSTS_TITLE"); ix == nil || ix.Method != "NORMAL" || ix.Unique ||
			ix.Definition != `CREATE INDEX "JD_CAT_POSTS_TITLE" ON "`+schema+`"."JD_CAT_POSTS" ("TITLE")` {
			t.Errorf("index = %+v", ix)
		}
		// A function-based index is its expression, not the hidden column
		// Oracle stores it in.
		if ix := catIndex(posts, "JD_CAT_POSTS_LOWER"); ix == nil || !ix.Expression || len(ix.Columns) != 1 ||
			!strings.Contains(ix.Columns[0], `LOWER("TITLE")`) {
			t.Errorf("function-based index = %+v", ix)
		}
		if len(posts.ForeignKeys) != 1 || posts.ForeignKeys[0].Name != "JD_CAT_POSTS_AUTHOR" || posts.ForeignKeys[0].OnDelete != "CASCADE" ||
			posts.ForeignKeys[0].RefTable != "JD_CAT_USERS" {
			t.Errorf("foreign keys = %+v", posts.ForeignKeys)
		}
		if view := describe("JD_CAT_ACTIVE"); view.Type != TableTypeView || len(view.Columns) != 2 || !strings.Contains(view.CreateSQL, "JD_CAT_ACTIVE") {
			t.Errorf("view = %+v", view)
		}
		// With no schema named, the session's own is read.
		unqualified, err := DescribeTable(ctx, db, d, "", "JD_CAT_POSTS")
		if err != nil || unqualified.Schema != schema || !reflect.DeepEqual(unqualified.PrimaryKey, []string{"ID"}) || len(unqualified.ForeignKeys) != 1 {
			t.Errorf("without a schema = %+v, %v", unqualified, err)
		}
	})

	t.Run("definitions", func(t *testing.T) {
		for kind, want := range map[string]struct{ name, text string }{
			KindView:             {"JD_CAT_ACTIVE", `VIEW "` + schema + `"."JD_CAT_ACTIVE"`},
			KindMaterializedView: {"JD_CAT_COUNTS", "MATERIALIZED VIEW"},
			KindFunction:         {"JD_CAT_ADD", "RETURN a + b"},
			KindProcedure:        {"JD_CAT_NOOP", "BEGIN NULL; END"},
			KindPackage:          {"JD_CAT_PKG", "FUNCTION one RETURN NUMBER"},
			KindTrigger:          {"JD_CAT_TOUCH", "BEFORE INSERT OR UPDATE"},
			KindSequence:         {"JD_CAT_SEQ", "INCREMENT BY 5"},
			KindType:             {"JD_CAT_PAIR", "AS OBJECT"},
			KindSynonym:          {"JD_CAT_PEOPLE", "JD_CAT_USERS"},
			KindTable:            {"JD_CAT_POSTS", `"JD_CAT_POSTS"`},
		} {
			def, err := ReadObjectDefinition(ctx, db, d, ObjectRef{Kind: kind, Schema: schema, Name: want.name})
			if err != nil || !strings.Contains(def.Definition, want.text) || def.Schema != schema {
				t.Errorf("%s = %+v, %v", kind, def, err)
			}
		}
		// The assembled form is what a login without DBMS_METADATA is given,
		// and is read from the source views either way.
		for kind, want := range map[string]struct{ name, text string }{
			KindView:     {"JD_CAT_ACTIVE", `CREATE OR REPLACE VIEW "` + schema + `"."JD_CAT_ACTIVE" AS`},
			KindFunction: {"JD_CAT_ADD", `CREATE OR REPLACE FUNCTION "JD_CAT_ADD"`},
			KindPackage:  {"JD_CAT_PKG", `CREATE OR REPLACE PACKAGE BODY "JD_CAT_PKG"`},
			KindTrigger:  {"JD_CAT_TOUCH", `CREATE OR REPLACE TRIGGER "JD_CAT_TOUCH"`},
			KindSequence: {"JD_CAT_SEQ", "INCREMENT BY 5"},
			KindSynonym:  {"JD_CAT_PEOPLE", `FOR ` + schema + `.JD_CAT_USERS`},
		} {
			if text, _ := (oracleDialect{}).assembledDefinition(ctx, db, kind, schema, want.name); !strings.Contains(text, want.text) {
				t.Errorf("assembled %s is missing %q:\n%s", kind, want.text, text)
			}
		}
		tr, err := ReadObjectDefinition(ctx, db, d, ObjectRef{Kind: KindTrigger, Name: "JD_CAT_TOUCH"})
		if err != nil || tr.Table != "JD_CAT_USERS" || catFact(tr.Details, "Status") != "valid" {
			t.Errorf("trigger = %+v, %v", tr, err)
		}
		if _, err := ReadObjectDefinition(ctx, db, d, ObjectRef{Kind: KindView, Schema: schema, Name: "JD_CAT_USERS"}); !errors.Is(err, ErrObjectNotFound) {
			t.Errorf("a table asked for as a view: %v", err)
		}
		if _, err := ReadObjectDefinition(ctx, db, d, ObjectRef{Kind: KindEnum, Schema: schema, Name: "X"}); !errors.Is(err, ErrNoDefinition) {
			t.Errorf("an enum type on Oracle: %v", err)
		}
	})

	// MODIFY changes the properties it names and leaves the rest.
	t.Run("alter_column", func(t *testing.T) {
		stmt := run(PlanAlterColumn(ctx, db, d, ColumnChange{
			Schema: schema, Table: "JD_CAT_USERS", Column: "NICK", Type: "VARCHAR2(200 CHAR)",
		}))
		if stmt != `ALTER TABLE "`+schema+`"."JD_CAT_USERS" MODIFY ("NICK" VARCHAR2(200 CHAR))` {
			t.Errorf("statement = %s", stmt)
		}
		if c := catColumn(t, describe("JD_CAT_USERS"), "NICK"); c.Type != "VARCHAR2(200)" || !c.Nullable {
			t.Errorf("NICK after widening = %+v", c)
		}
		run(PlanAlterColumn(ctx, db, d, ColumnChange{Schema: schema, Table: "JD_CAT_USERS", Column: "SCORE", Default: ddlString("9")}))
		if c := catColumn(t, describe("JD_CAT_USERS"), "SCORE"); c.Default != "9" || c.Type != "NUMBER(5,0)" {
			t.Errorf("SCORE after a new default = %+v", c)
		}
		// Oracle has no DROP DEFAULT; a default of NULL is none.
		run(PlanAlterColumn(ctx, db, d, ColumnChange{Schema: schema, Table: "JD_CAT_USERS", Column: "SCORE", DropDefault: true}))
		if c := catColumn(t, describe("JD_CAT_USERS"), "SCORE"); c.Default != "" {
			t.Errorf("SCORE after dropping its default = %+v", c)
		}
		// One statement: a NOT NULL the rows cannot satisfy leaves the type
		// change undone as well.
		plan, err := PlanAlterColumn(ctx, db, d, ColumnChange{
			Schema: schema, Table: "JD_CAT_USERS", Column: "SCORE", Type: "NUMBER(9)", Nullable: ddlBool(false),
		})
		if err != nil {
			t.Fatal(err)
		}
		if err := plan.Exec(ctx, db); err == nil {
			t.Fatal("NOT NULL was set over a NULL")
		}
		if c := catColumn(t, describe("JD_CAT_USERS"), "SCORE"); c.Type != "NUMBER(5,0)" {
			t.Errorf("a failed change left the type altered: %+v", c)
		}
		run(PlanAlterColumn(ctx, db, d, ColumnChange{Schema: schema, Table: "JD_CAT_POSTS", Column: "TITLE", Nullable: ddlBool(true)}))
		if c := catColumn(t, describe("JD_CAT_POSTS"), "TITLE"); !c.Nullable {
			t.Errorf("TITLE after relaxing it = %+v", c)
		}
		run(PlanAlterColumn(ctx, db, d, ColumnChange{Schema: schema, Table: "JD_CAT_POSTS", Column: "TITLE", Nullable: ddlBool(false)}))
	})

	t.Run("comments", func(t *testing.T) {
		run(PlanComment(ctx, db, d, CommentSpec{Schema: schema, Table: "JD_CAT_POSTS", Comment: `What's \ written`}))
		run(PlanComment(ctx, db, d, CommentSpec{Schema: schema, Table: "JD_CAT_POSTS", Column: "TITLE", Comment: "Headline"}))
		posts := describe("JD_CAT_POSTS")
		if posts.Comment != `What's \ written` || catColumn(t, posts, "TITLE").Comment != "Headline" {
			t.Errorf("comments = %q / %q", posts.Comment, catColumn(t, posts, "TITLE").Comment)
		}
		// An empty string is NULL here, which is how a comment is removed.
		run(PlanComment(ctx, db, d, CommentSpec{Schema: schema, Table: "JD_CAT_POSTS", Column: "TITLE"}))
		if c := catColumn(t, describe("JD_CAT_POSTS"), "TITLE"); c.Comment != "" {
			t.Errorf("an empty comment did not remove it: %q", c.Comment)
		}
	})

	t.Run("foreign_keys_and_constraints", func(t *testing.T) {
		run(PlanDropForeignKey(d, schema, "JD_CAT_POSTS", "JD_CAT_POSTS_AUTHOR"))
		if posts := describe("JD_CAT_POSTS"); len(posts.ForeignKeys) != 0 {
			t.Errorf("the dropped key is still there: %+v", posts.ForeignKeys)
		}
		run(PlanAddForeignKey(d, ForeignKeySpec{
			Schema: schema, Table: "JD_CAT_POSTS", Name: "JD_CAT_POSTS_AUTHOR", Columns: []string{"AUTHOR_ID"},
			RefTable: "JD_CAT_USERS", RefColumns: []string{"ID"}, OnDelete: "set null", OnUpdate: "no action",
		}))
		if posts := describe("JD_CAT_POSTS"); len(posts.ForeignKeys) != 1 || posts.ForeignKeys[0].OnDelete != "SET NULL" {
			t.Errorf("the added key = %+v", posts.ForeignKeys)
		}
		run(PlanAddConstraint(d, ConstraintSpec{Schema: schema, Table: "JD_CAT_POSTS", Type: "unique", Name: "JD_CAT_POSTS_UQ", Columns: []string{"AUTHOR_ID", "TITLE"}}))
		run(PlanAddConstraint(d, ConstraintSpec{Schema: schema, Table: "JD_CAT_POSTS", Type: "check", Name: "JD_CAT_TITLE_LEN", Expression: `LENGTH("TITLE") > 0`}))
		posts := describe("JD_CAT_POSTS")
		if catConstraint(posts, "JD_CAT_POSTS_UQ") == nil || catConstraint(posts, "JD_CAT_TITLE_LEN") == nil {
			t.Errorf("constraints = %+v", posts.Constraints)
		}
		if ix := catIndex(posts, "JD_CAT_POSTS_UQ"); ix == nil || ix.Constraint != "JD_CAT_POSTS_UQ" {
			t.Errorf("the constraint's index = %+v", ix)
		}
		run(PlanDropConstraint(ctx, db, d, schema, "JD_CAT_POSTS", "JD_CAT_POSTS_UQ", ""))
		run(PlanDropConstraint(ctx, db, d, schema, "JD_CAT_POSTS", "JD_CAT_TITLE_LEN", "check"))
		if posts := describe("JD_CAT_POSTS"); len(posts.Constraints) != 0 {
			t.Errorf("dropped constraints are still there: %+v", posts.Constraints)
		}
	})

	t.Run("indexes_and_views", func(t *testing.T) {
		// The index is named in the table's schema, not the session's.
		stmt := run(PlanCreateIndex(ctx, db, d, IndexSpec{
			Schema: schema, Table: "JD_CAT_POSTS", Name: "JD_CAT_POSTS_AUTHOR_IX", Columns: []string{"AUTHOR_ID"}, Concurrently: true,
		}))
		if stmt != `CREATE INDEX "`+schema+`"."JD_CAT_POSTS_AUTHOR_IX" ON "`+schema+`"."JD_CAT_POSTS" ("AUTHOR_ID") ONLINE` {
			t.Errorf("statement = %s", stmt)
		}
		if catIndex(describe("JD_CAT_POSTS"), "JD_CAT_POSTS_AUTHOR_IX") == nil {
			t.Error("the created index is not listed")
		}
		run(PlanDropIndex(d, schema, "JD_CAT_POSTS", "JD_CAT_POSTS_AUTHOR_IX"))
		if catIndex(describe("JD_CAT_POSTS"), "JD_CAT_POSTS_AUTHOR_IX") != nil {
			t.Error("the dropped index is still there")
		}

		run(PlanCreateView(d, ViewSpec{Schema: schema, Name: "JD_CAT_TITLES", Query: `SELECT "TITLE" FROM "JD_CAT_POSTS"`}))
		run(PlanCreateView(d, ViewSpec{Schema: schema, Name: "JD_CAT_TITLES", Query: `SELECT "ID", "TITLE" FROM "JD_CAT_POSTS"`, Replace: true}))
		if view := describe("JD_CAT_TITLES"); view.Type != TableTypeView || len(view.Columns) != 2 {
			t.Errorf("replaced view = %+v", view)
		}
		run(PlanDropView(d, schema, "JD_CAT_TITLES", false))
	})

	t.Run("tables_and_columns", func(t *testing.T) {
		run(PlanCreateTable(d, schema, "JD_CAT_MADE", []NewColumn{
			{Name: "ID", Type: "NUMBER(10)", PrimaryKey: true, NotNull: true},
			{Name: "LABEL", Type: "VARCHAR2(40 CHAR)"},
			{Name: "PRICE", Type: "NUMBER(18,2)", NotNull: true, Default: "0"},
			{Name: "RATIO", Type: "FLOAT(53)"},
		}))
		run(PlanAddColumn(d, schema, "JD_CAT_MADE", NewColumn{Name: "SEEN", Type: "TIMESTAMP(6) WITH TIME ZONE", NotNull: true, Default: "SYSTIMESTAMP"}))
		made := describe("JD_CAT_MADE")
		if c := catColumn(t, made, "PRICE"); c.Type != "NUMBER(18,2)" || c.Nullable || c.Default != "0" {
			t.Errorf("PRICE = %+v", c)
		}
		if c := catColumn(t, made, "SEEN"); !strings.HasPrefix(c.Type, "TIMESTAMP(6) WITH TIME ZONE") || c.Nullable {
			t.Errorf("SEEN = %+v", c)
		}
		// A FLOAT's precision is binary digits, and one that was declared is
		// part of the type.
		if c := catColumn(t, made, "RATIO"); c.Type != "FLOAT(53)" {
			t.Errorf("RATIO = %+v", c)
		}
		run(PlanRenameColumn(d, schema, "JD_CAT_MADE", "LABEL", "CAPTION"))
		run(PlanDropColumn(ctx, db, d, schema, "JD_CAT_MADE", "SEEN"))
		run(PlanRenameTable(d, schema, "JD_CAT_MADE", "JD_CAT_MADE2"))
		if made := describe("JD_CAT_MADE2"); made.Schema != schema || len(made.Columns) != 4 || catColumn(t, made, "CAPTION").Type != "VARCHAR2(40)" {
			t.Errorf("renamed table = %+v", made)
		}
		catalogExec(t, db, `INSERT INTO "JD_CAT_MADE2" ("ID") VALUES (1)`)
		run(PlanTruncate(d, schema, "JD_CAT_MADE2"))
		var n int
		if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM "JD_CAT_MADE2"`).Scan(&n); err != nil || n != 0 {
			t.Errorf("rows after truncate = %d, %v", n, err)
		}
		run(PlanDropTable(d, schema, "JD_CAT_MADE2"))
		if gone := describe("JD_CAT_MADE2"); len(gone.Columns) != 0 || gone.Type != "" {
			t.Errorf("the dropped table is still there: %+v", gone)
		}
	})

	// A login that may read DBA_SEGMENTS is answered from it, for a schema
	// that is not its own.
	t.Run("sizes_for_another_schema", func(t *testing.T) {
		if os.Getenv("JD_TEST_ORACLE_ADMIN_DSN") == "" {
			t.Skip("set JD_TEST_ORACLE_ADMIN_DSN to run this")
		}
		admin := liveSQL(t, d, "JD_TEST_ORACLE_ADMIN_DSN", "")
		catalog, err := ReadCatalog(ctx, admin, d, CatalogOptions{Schema: schema})
		if err != nil {
			t.Fatal(err)
		}
		if posts := catObject(catalog.Objects[GroupTables], "JD_CAT_POSTS"); posts == nil || posts.Size <= 0 {
			t.Errorf("posts as another login sees it = %+v (errors %v)", posts, catalog.Errors)
		}
		detail, err := DescribeTable(ctx, admin, d, schema, "JD_CAT_POSTS")
		if err != nil || detail.DataSize <= 0 || detail.IndexSize <= 0 {
			t.Errorf("posts as another login describes it: %d of rows, %d of indexes, %v", detail.DataSize, detail.IndexSize, err)
		}
	})

	t.Run("graph", func(t *testing.T) {
		graph, err := BuildSchemaGraph(ctx, db, d, schema)
		if err != nil {
			t.Fatal(err)
		}
		found := false
		for _, e := range graph.Edges {
			if e.From == TableKey(schema, "JD_CAT_POSTS") && e.To == TableKey(schema, "JD_CAT_USERS") {
				found = true
			}
		}
		if !found {
			t.Errorf("edges = %+v", graph.Edges)
		}
		relations, err := Relations(ctx, db, d, schema)
		if err != nil || len(relations[TableKey(schema, "JD_CAT_POSTS")]) != 1 {
			t.Errorf("relations = %+v, %v", relations, err)
		}
		outline, err := OutlineWithLimit(ctx, db, d, schema, 0)
		if err != nil || !reflect.DeepEqual(outline.Tables[TableKey(schema, "JD_CAT_POSTS")], []string{"ID", "AUTHOR_ID", "TITLE", "BODY"}) {
			t.Errorf("outline = %+v, %v", outline, err)
		}
	})
}
