package dbx

import (
	"fmt"
	"strings"
)

// Sequelize.
//
// Typed models in Sequelize 6's own TypeScript style — a class per table that
// declares its attributes, an init function that defines them, and one
// initModels that calls every init and then wires the associations, because
// an association can only be made once both models exist. Constraints keep
// their database names through the `indexes` option, and a table with no
// primary key has the `id` attribute Sequelize would invent removed.

type sequelizeGen struct {
	*ormGen
	names *ormNaming
}

func generateSequelize(g *ormGen) []ORMFile {
	s := &sequelizeGen{ormGen: g}
	rules := tsClassRules(g, strings.Fields(`DataTypes Model Sequelize literal initModels
		CreationOptional InferAttributes InferCreationAttributes NonAttribute`)...)
	rules.modelSuffix = "Model"
	// Sequelize refuses an association whose alias is also an attribute, and
	// these are names every model instance already has.
	rules.member = strings.Fields(`sequelize isNewRecord dataValues save update destroy reload get set
		changed previous validate toJSON equals increment decrement restore where`)
	s.names = g.names(rules)

	var units []*tsUnit
	if len(g.enums) > 0 {
		u := newTSUnit("enums")
		var b strings.Builder
		for i, e := range g.enums {
			if i > 0 {
				b.WriteString("\n")
			}
			u.symbols = append(u.symbols, s.names.enum[e])
			fmt.Fprintf(&b, "export type %s = %s\n", s.names.enum[e], tsUnion(e.Values))
		}
		u.body = b.String()
		units = append(units, u)
	}
	for _, m := range g.models {
		units = append(units, s.model(m))
	}
	units = append(units, s.initModels())

	header := "// Generated by Just Dashboard from live database introspection.\n" +
		"// A reviewed starting point: verify types, defaults and associations. Call\n" +
		"// initModels(sequelize) once, before the first query.\n"
	return tsLayout(header, units, g.opts.Split, "models.ts")
}

// dataType maps a column onto a Sequelize DataType expression and the
// TypeScript type its values have.
func (s *sequelizeGen) dataType(m *ormTable, c *ormCol) (expr, ts string) {
	t := c.t
	// A type Sequelize has no DataType for is passed as its SQL name, which
	// Sequelize accepts and writes into the DDL verbatim.
	raw := func(ts string) (string, string) {
		name := strings.ToUpper(strings.TrimSuffix(strings.TrimSpace(c.Type), "[]"))
		if s.driver == DriverClickHouse || name == "" {
			name = strings.ToUpper(t.Name)
		}
		return jsString(name), ts
	}
	unsigned := func(expr string) string {
		if t.Unsigned && s.driver == DriverMySQL {
			return expr + ".UNSIGNED"
		}
		return expr
	}
	// A 64-bit integer comes back as a string from the PostgreSQL and SQL
	// Server drivers, and as a number from the others.
	big := "string"
	if s.driver == DriverMySQL || s.driver == DriverSQLite || s.driver == DriverOracle {
		big = "number"
	}
	blob := func(name string) string {
		switch name {
		case "tinyblob":
			return `DataTypes.BLOB("tiny")`
		case "mediumblob":
			return `DataTypes.BLOB("medium")`
		case "longblob":
			return `DataTypes.BLOB("long")`
		}
		return "DataTypes.BLOB"
	}

	switch t.Kind {
	case ormBool:
		if t.Name == "bit" && s.driver == DriverMySQL {
			expr, ts = raw("Buffer")
		} else {
			expr, ts = "DataTypes.BOOLEAN", "boolean"
		}
	case ormInt8:
		expr, ts = unsigned("DataTypes.TINYINT"), "number"
	case ormInt16:
		expr, ts = unsigned("DataTypes.SMALLINT"), "number"
	case ormInt32:
		expr, ts = unsigned("DataTypes.INTEGER"), "number"
		if t.Name == "mediumint" {
			expr = unsigned("DataTypes.MEDIUMINT")
		}
	case ormInt64:
		expr, ts = unsigned("DataTypes.BIGINT"), big
	case ormFloat32:
		expr, ts = "DataTypes.REAL", "number"
		if s.driver == DriverMySQL {
			expr = "DataTypes.FLOAT"
		}
	case ormFloat64:
		expr, ts = "DataTypes.DOUBLE", "number"
	case ormDecimal:
		expr, ts = "DataTypes.DECIMAL", "string"
		if t.HasPrecision {
			expr = fmt.Sprintf("DataTypes.DECIMAL(%d, %d)", t.Precision, t.Scale)
		}
	case ormChar:
		expr, ts = "DataTypes.CHAR", "string"
		if t.Length > 0 {
			expr = fmt.Sprintf("DataTypes.CHAR(%d)", t.Length)
		}
	case ormVarchar:
		expr, ts = "DataTypes.STRING", "string"
		switch {
		case t.Length > 0:
			expr = fmt.Sprintf("DataTypes.STRING(%d)", t.Length)
		case t.Length < 0:
			expr = "DataTypes.TEXT"
		}
	case ormText:
		expr, ts = "DataTypes.TEXT", "string"
		switch t.Name {
		case "tinytext":
			expr = `DataTypes.TEXT("tiny")`
		case "mediumtext":
			expr = `DataTypes.TEXT("medium")`
		case "longtext":
			expr = `DataTypes.TEXT("long")`
		case "citext":
			expr = "DataTypes.CITEXT"
		case "name", "rowid", "urowid", "long":
			expr, ts = raw("string")
		}
	case ormUUID:
		expr, ts = "DataTypes.UUID", "string"
	case ormJSON:
		expr, ts = "DataTypes.JSON", "unknown"
		if t.Name == "jsonb" {
			expr = "DataTypes.JSONB"
		}
	case ormBytes:
		expr, ts = blob(t.Name), "Buffer"
		if t.Name == "binary" || t.Name == "varbinary" || t.Name == "raw" || t.Name == "rowversion" {
			expr, ts = raw("Buffer")
		}
	case ormDate:
		expr, ts = "DataTypes.DATEONLY", "string"
	case ormTime:
		expr, ts = "DataTypes.TIME", "string"
		if t.TZ {
			expr, ts = raw("string")
		}
	case ormDateTime, ormDateTimeTZ:
		expr, ts = "DataTypes.DATE", "Date"
		if t.HasPrecision && t.Precision > 0 {
			expr = fmt.Sprintf("DataTypes.DATE(%d)", t.Precision)
		}
	case ormEnumKind:
		if t.Enum != nil {
			expr, ts = "DataTypes.ENUM("+strings.Join(jsStrings(t.Enum.Values), ", ")+")", s.names.enum[t.Enum]
		} else {
			expr, ts = "DataTypes.STRING", "string"
		}
	case ormNet:
		switch t.Name {
		case "inet":
			expr, ts = "DataTypes.INET", "string"
		case "cidr":
			expr, ts = "DataTypes.CIDR", "string"
		case "macaddr":
			expr, ts = "DataTypes.MACADDR", "string"
		default:
			expr, ts = raw("string")
		}
	case ormUnknown:
		s.warn("%s.%s has type %s, which Sequelize has no DataType for; it is passed through by its SQL name.", s.label(m), c.Name, c.Type)
		expr, ts = raw("string")
	default:
		// money, xml, interval, bit, year, set, geometry: real types with no
		// DataType of their own.
		expr, ts = raw("string")
		if t.Kind == ormYear {
			ts = "number"
		}
		if t.Kind == ormGeo {
			ts = "unknown"
		}
	}
	if t.Array {
		expr, ts = "DataTypes.ARRAY("+expr+")", ts+"[]"
	}
	return expr, ts
}

func (s *sequelizeGen) initName(m *ormTable) string { return "init" + s.names.model[m] }

func (s *sequelizeGen) model(m *ormTable) *tsUnit {
	class := s.names.model[m]
	u := newTSUnit(class, class, s.initName(m))
	u.use("sequelize", "DataTypes", "Model", "type InferAttributes", "type InferCreationAttributes", "type Sequelize")

	var decl, attrs strings.Builder
	for _, c := range m.cols {
		name := s.names.field[c]
		expr, ts := s.dataType(m, c)
		if e := c.t.Enum; e != nil {
			u.ref(s.names.enum[e])
		}
		declared := ts
		if c.Nullable && ts != "unknown" {
			declared += " | null"
		}
		parts := []string{"type: " + expr}
		if name != c.Name {
			parts = append(parts, "field: "+jsString(c.Name))
		}
		if m.pk[c.Name] {
			parts = append(parts, "primaryKey: true")
		}
		if c.def.Kind == ormDefAuto && c.t.isInteger() && s.opts.Defaults {
			parts = append(parts, "autoIncrement: true")
		}
		parts = append(parts, fmt.Sprintf("allowNull: %t", c.Nullable))
		optional := c.Nullable
		if s.opts.Defaults {
			if def := s.defaultValue(u, c, ts); def != "" {
				parts = append(parts, "defaultValue: "+def)
			}
			optional = optional || c.dbFills()
		}
		if c.Comment != "" {
			parts = append(parts, "comment: "+jsString(ormOneLine(c.Comment)))
		}
		if optional {
			u.use("sequelize", "type CreationOptional")
			declared = "CreationOptional<" + declared + ">"
		}
		fmt.Fprintf(&decl, "  declare %s: %s\n", name, declared)
		fmt.Fprintf(&attrs, "      %s: %s,\n", jsKey(name), jsObject(parts))
	}

	single := func(r *ormRel) bool { return len(r.fk.Columns) == 1 }
	var assoc strings.Builder
	for _, r := range m.rels {
		if !single(r) {
			continue
		}
		u.use("sequelize", "type NonAttribute")
		u.ref(s.names.model[r.to])
		fmt.Fprintf(&assoc, "  declare %s?: NonAttribute<%s>\n", s.names.fwd[r], s.names.model[r.to])
	}
	for _, r := range m.back {
		if !single(r) {
			continue
		}
		u.use("sequelize", "type NonAttribute")
		u.ref(s.names.model[r.from])
		arity := "[]"
		if r.unique {
			arity = ""
		}
		fmt.Fprintf(&assoc, "  declare %s?: NonAttribute<%s%s>\n", s.names.back[r], s.names.model[r.from], arity)
	}

	options := []string{"sequelize", "tableName: " + jsString(m.Name)}
	if s.qualified(m) {
		options = append(options, "schema: "+jsString(m.Schema))
	}
	// The columns are declared as they are; Sequelize must not add its own.
	options = append(options, "timestamps: false")
	if m.Comment != "" {
		options = append(options, "comment: "+jsString(ormOneLine(m.Comment)))
	}
	var indexes []string
	for _, ix := range m.uniques {
		indexes = append(indexes, fmt.Sprintf("{ name: %s, unique: true, fields: [%s] }",
			jsString(ix.Name), strings.Join(jsStrings(ix.Columns), ", ")))
	}
	for _, ix := range s.plainIndexes(m) {
		indexes = append(indexes, fmt.Sprintf("{ name: %s, fields: [%s] }",
			jsString(ix.Name), strings.Join(jsStrings(ix.Columns), ", ")))
	}

	var b strings.Builder
	b.WriteString(tsDocComment("", m.Comment))
	fmt.Fprintf(&b, "export class %s extends Model<InferAttributes<%s>, InferCreationAttributes<%s>> {\n", class, class, class)
	b.WriteString(decl.String())
	if assoc.Len() > 0 {
		b.WriteString("\n" + assoc.String())
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "export function %s(sequelize: Sequelize): typeof %s {\n", s.initName(m), class)
	fmt.Fprintf(&b, "  %s.init(\n    {\n%s    },\n    {\n", class, attrs.String())
	for _, o := range options {
		b.WriteString("      " + o + ",\n")
	}
	if len(indexes) > 0 {
		b.WriteString("      indexes: [\n")
		for _, ix := range indexes {
			b.WriteString("        " + ix + ",\n")
		}
		b.WriteString("      ],\n")
	}
	b.WriteString("    },\n  )\n")
	if len(m.PrimaryKey) == 0 {
		// Sequelize adds an auto-increment `id` to a model with no primary
		// key. The table has no such column.
		fmt.Fprintf(&b, "  %s.removeAttribute(\"id\")\n", class)
		s.warn("%s has no primary key; the model has Sequelize's invented id removed, and rows cannot be updated or deleted through it one at a time.", s.label(m))
	}
	fmt.Fprintf(&b, "  return %s\n}\n", class)
	u.body = b.String()
	return u
}

// defaultValue renders a column default for init(): a literal where it is one,
// DataTypes.NOW for the current time, and literal("…") for anything else the
// database computes.
func (s *sequelizeGen) defaultValue(u *tsUnit, c *ormCol, ts string) string {
	if c.Generated {
		return ""
	}
	raw := func(expr string) string {
		u.use("sequelize", "literal")
		return "literal(" + jsString(expr) + ")"
	}
	d := c.def
	switch d.Kind {
	case ormDefNow:
		if (c.t.Kind == ormDateTime || c.t.Kind == ormDateTimeTZ) && !c.t.Array {
			return "DataTypes.NOW"
		}
		return raw(d.sql(s.driver))
	case ormDefUUID:
		return raw(d.Text)
	case ormDefExpr, ormDefJSON, ormDefEmptyArray:
		return raw(d.sql(s.driver))
	case ormDefString:
		if c.t.Array {
			return raw(d.sql(s.driver))
		}
		return jsString(d.Text)
	case ormDefNumber:
		if ts == "number" {
			return d.Text
		}
		return jsString(d.Text)
	case ormDefBool:
		if ts == "boolean" {
			return fmt.Sprintf("%t", d.Bool)
		}
		return raw(d.sql(s.driver))
	}
	return ""
}

// initModels is the one function a caller runs: every model defined, then
// every association made.
func (s *sequelizeGen) initModels() *tsUnit {
	u := newTSUnit("init-models", "initModels")
	u.use("sequelize", "type Sequelize")
	var b strings.Builder
	b.WriteString("export function initModels(sequelize: Sequelize) {\n")
	var classes []string
	for _, m := range s.models {
		u.ref(s.initName(m))
		u.ref(s.names.model[m])
		classes = append(classes, s.names.model[m])
		fmt.Fprintf(&b, "  %s(sequelize)\n", s.initName(m))
	}
	wrote := false
	for _, m := range s.models {
		for _, r := range m.rels {
			if len(r.fk.Columns) != 1 {
				s.warn("%s.%s is a composite foreign key, which Sequelize associations cannot express; the association was left out.",
					s.label(m), strings.Join(r.fk.Columns, ", "))
				continue
			}
			if !wrote {
				b.WriteString("\n")
				wrote = true
			}
			from, to := s.names.model[r.from], s.names.model[r.to]
			key := jsString(s.names.field[m.byCol[r.fk.Columns[0]]])
			target := jsString(s.names.field[r.to.byCol[r.fk.RefColumns[0]]])
			var rules []string
			if a := ormAction(r.fk.OnDelete); a != "" {
				rules = append(rules, "onDelete: "+jsString(a))
			}
			if a := ormAction(r.fk.OnUpdate); a != "" {
				rules = append(rules, "onUpdate: "+jsString(a))
			}
			belongs := append([]string{"as: " + jsString(s.names.fwd[r]), "foreignKey: " + key, "targetKey: " + target}, rules...)
			fmt.Fprintf(&b, "  %s.belongsTo(%s, %s)\n", from, to, jsObject(belongs))
			has := "hasMany"
			if r.unique {
				has = "hasOne"
			}
			fmt.Fprintf(&b, "  %s.%s(%s, { as: %s, foreignKey: %s, sourceKey: %s })\n",
				to, has, from, jsString(s.names.back[r]), key, target)
		}
	}
	fmt.Fprintf(&b, "\n  return { %s }\n}\n", strings.Join(classes, ", "))
	u.body = b.String()
	return u
}
