package dbx

import (
	"fmt"
	"sort"
	"strings"
)

// SQLAlchemy.
//
// SQLAlchemy 2 declarative models with Mapped[] annotations, close to what
// sqlacodegen writes. The nullability of a column is its annotation —
// Mapped[Optional[str]] — and a default is passed as the database's own
// expression in server_default, so the model says what the table does rather
// than re-implementing it in Python. A table the ORM cannot map as a class,
// because it has no primary key, is declared as a Table on the same metadata,
// which keeps it queryable and keeps foreign keys into it resolvable.

// pyType is a rendered SQLAlchemy type with what it needs imported and the
// Python type its values have.
type pyType struct {
	expr string
	py   string
	// imports are module -> names.
	imports map[string][]string
}

func saType(module, name, args, py string) pyType {
	expr := name
	if args != "" {
		expr += "(" + args + ")"
	}
	return pyType{expr: expr, py: py, imports: map[string][]string{module: {name}}}
}

const (
	saCore   = "sqlalchemy"
	saPG     = "sqlalchemy.dialects.postgresql"
	saMySQL  = "sqlalchemy.dialects.mysql"
	saMSSQL  = "sqlalchemy.dialects.mssql"
	saOracle = "sqlalchemy.dialects.oracle"
)

// sqlalchemyNames are the names a generated module imports or declares, which
// a model class must not be called: a table named "dates" would otherwise
// define a Date class over the column type of the same name.
var sqlalchemyNames = strings.Fields(`Base Any Optional Table Column ForeignKey ForeignKeyConstraint Index
	UniqueConstraint Identity Enum DeclarativeBase Mapped mapped_column relationship text
	BigInteger Boolean CHAR Date DateTime Double Float Integer Interval JSON LargeBinary Numeric REAL
	SmallInteger String Text Time Uuid Unicode UnicodeText NCHAR BINARY VARBINARY TIMESTAMP DATETIME
	CLOB BLOB ARRAY
	BIT CIDR CITEXT INET JSONB MACADDR MACADDR8 MONEY OID TSVECTOR
	BIGINT INTEGER LONGBLOB LONGTEXT MEDIUMBLOB MEDIUMINT MEDIUMTEXT SET SMALLINT TIME TINYBLOB
	TINYINT TINYTEXT YEAR
	DATETIME2 DATETIMEOFFSET IMAGE ROWVERSION SMALLDATETIME SMALLMONEY UNIQUEIDENTIFIER XML NTEXT
	BINARY_DOUBLE BINARY_FLOAT DATE LONG NCLOB NUMBER NVARCHAR2 RAW ROWID VARCHAR2 FLOAT INTERVAL`)

type sqlalchemyGen struct {
	*ormGen
	names   *ormNaming
	imports map[string]map[string]bool
	stdlib  map[string]bool
	typing  map[string]bool
	// classes are the tables mapped as declarative classes; the rest are
	// Table objects.
	classes map[*ormTable]bool
}

func generateSQLAlchemy(g *ormGen) []ORMFile {
	s := &sqlalchemyGen{
		ormGen: g, imports: map[string]map[string]bool{}, stdlib: map[string]bool{},
		typing: map[string]bool{}, classes: map[*ormTable]bool{},
	}
	s.names = g.names(ormNameRules{
		model:        func(t string) string { return pascal(singular(t)) },
		field:        sanitizeIdent,
		top:          sqlalchemyNames,
		modelSuffix:  "Model",
		escapeTop:    pyIdent,
		escapeMember: pyIdent,
		// Names the declarative base keeps for itself on every mapped class.
		member: []string{"metadata", "registry"},
	})
	for _, m := range g.models {
		if !m.view && len(m.PrimaryKey) > 0 {
			s.classes[m] = true
		}
	}

	var body strings.Builder
	for _, m := range g.models {
		body.WriteString("\n\n")
		if s.classes[m] {
			body.WriteString(s.class(m))
		} else {
			body.WriteString(s.table(m))
		}
	}

	s.use("sqlalchemy.orm", "DeclarativeBase")
	var b strings.Builder
	b.WriteString("# Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("# A reviewed starting point: verify types, defaults and relationships.\n")
	if len(s.stdlib) > 0 {
		b.WriteString("\n")
		for _, mod := range ormSortedKeys(s.stdlib) {
			b.WriteString("import " + mod + "\n")
		}
		if len(s.typing) > 0 {
			b.WriteString("from typing import " + strings.Join(ormSortedKeys(s.typing), ", ") + "\n")
		}
	} else if len(s.typing) > 0 {
		b.WriteString("\nfrom typing import " + strings.Join(ormSortedKeys(s.typing), ", ") + "\n")
	}
	b.WriteString("\n")
	modules := make([]string, 0, len(s.imports))
	for mod := range s.imports {
		modules = append(modules, mod)
	}
	sort.Strings(modules)
	for _, mod := range modules {
		b.WriteString(pyImport(mod, ormSortedKeys(s.imports[mod])))
	}
	b.WriteString("\n\nclass Base(DeclarativeBase):\n    pass\n")
	b.WriteString(body.String())
	return []ORMFile{{Filename: "models.py", Content: b.String()}}
}

func ormSortedKeys(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// pyImport renders `from module import a, b`, wrapped in parentheses once it
// passes the line length black keeps to.
func pyImport(module string, names []string) string {
	line := fmt.Sprintf("from %s import %s\n", module, strings.Join(names, ", "))
	if len(line) <= 89 {
		return line
	}
	return fmt.Sprintf("from %s import (\n    %s,\n)\n", module, strings.Join(names, ",\n    "))
}

func (s *sqlalchemyGen) use(module string, names ...string) {
	if s.imports[module] == nil {
		s.imports[module] = map[string]bool{}
	}
	for _, n := range names {
		s.imports[module][n] = true
	}
}

func (s *sqlalchemyGen) useType(t pyType) pyType {
	for module, names := range t.imports {
		s.use(module, names...)
	}
	switch {
	case strings.HasPrefix(t.py, "datetime."):
		s.stdlib["datetime"] = true
	case strings.HasPrefix(t.py, "decimal."):
		s.stdlib["decimal"] = true
	case strings.HasPrefix(t.py, "uuid."):
		s.stdlib["uuid"] = true
	case t.py == "Any":
		s.typing["Any"] = true
	}
	return t
}

// columnType maps a column onto a SQLAlchemy type for its engine: the generic
// type where it names the same column the dialect would create, the dialect's
// own type where the generic one would not.
func (s *sqlalchemyGen) columnType(m *ormTable, c *ormCol) pyType {
	t := c.t
	if t.Enum != nil {
		args := strings.Join(jsStrings(t.Enum.Values), ", ")
		if !t.Enum.inline {
			args += ", name=" + jsString(t.Enum.Name)
			if t.Enum.Schema != "" && s.schemaArg(t.Enum.Schema) {
				args += ", schema=" + jsString(t.Enum.Schema)
			}
		}
		el := saType(saCore, "Enum", args, "str")
		return s.array(el, t)
	}
	numeric := func() pyType {
		if t.HasPrecision {
			return saType(saCore, "Numeric", fmt.Sprintf("%d, %d", t.Precision, t.Scale), "decimal.Decimal")
		}
		return saType(saCore, "Numeric", "", "decimal.Decimal")
	}
	sized := func(module, name, py string) pyType {
		if t.Length > 0 {
			return saType(module, name, fmt.Sprintf("%d", t.Length), py)
		}
		return saType(module, name, "", py)
	}
	// SQLAlchemy's own stand-in for "no type", NullType, cannot be mapped: the
	// ORM then looks for a type in the annotation and finds none. Text reads
	// and writes whatever the driver hands over as a string.
	unknown := func() pyType {
		s.warn("%s.%s has type %s, which SQLAlchemy has no type for here; it is declared as Text.", s.label(m), c.Name, c.Type)
		return saType(saCore, "Text", "", "str")
	}

	var out pyType
	switch s.driver {
	case DriverPostgres:
		switch t.Kind {
		case ormBool:
			out = saType(saCore, "Boolean", "", "bool")
		case ormInt16:
			out = saType(saCore, "SmallInteger", "", "int")
		case ormInt32:
			out = saType(saCore, "Integer", "", "int")
		case ormInt64:
			out = saType(saCore, "BigInteger", "", "int")
			if t.Name == "oid" {
				out = saType(saPG, "OID", "", "int")
			}
		case ormFloat32:
			out = saType(saCore, "REAL", "", "float")
		case ormFloat64:
			out = saType(saCore, "Double", "", "float")
		case ormDecimal:
			out = numeric()
		case ormMoney:
			out = saType(saPG, "MONEY", "", "str")
		case ormChar:
			out = sized(saCore, "CHAR", "str")
		case ormVarchar:
			out = sized(saCore, "String", "str")
		case ormText:
			out = saType(saCore, "Text", "", "str")
			if t.Name == "citext" {
				out = saType(saPG, "CITEXT", "", "str")
			}
		case ormUUID:
			out = saType(saCore, "Uuid", "", "uuid.UUID")
		case ormJSON:
			out = saType(saCore, "JSON", "", "Any")
			if t.Name == "jsonb" {
				out = saType(saPG, "JSONB", "", "Any")
			}
		case ormBytes:
			out = saType(saCore, "LargeBinary", "", "bytes")
		case ormDate:
			out = saType(saCore, "Date", "", "datetime.date")
		case ormTime:
			out = saType(saCore, "Time", "", "datetime.time")
			if t.TZ {
				out = saType(saCore, "Time", "timezone=True", "datetime.time")
			}
		case ormDateTime, ormDateTimeTZ:
			var args []string
			if t.Kind == ormDateTimeTZ {
				args = append(args, "timezone=True")
			}
			if t.HasPrecision {
				args = append(args, fmt.Sprintf("precision=%d", t.Precision))
				out = saType(saPG, "TIMESTAMP", strings.Join(args, ", "), "datetime.datetime")
			} else {
				out = saType(saCore, "DateTime", strings.Join(args, ", "), "datetime.datetime")
			}
		case ormInterval:
			out = saType(saCore, "Interval", "", "datetime.timedelta")
		case ormNet:
			out = saType(saPG, strings.ToUpper(t.Name), "", "str")
		case ormBit:
			args := ""
			if t.Length > 0 {
				args = fmt.Sprintf("%d", t.Length)
			}
			if t.Name == "varbit" {
				args = strings.TrimPrefix(args+", varying=True", ", ")
			}
			out = saType(saPG, "BIT", args, "str")
		case ormXML:
			// PostgreSQL's xml has no SQLAlchemy type; it reads and writes as text.
			out = saType(saCore, "Text", "", "str")
		default:
			if strings.EqualFold(strings.TrimSuffix(strings.TrimSpace(c.Type), "[]"), "tsvector") {
				out = saType(saPG, "TSVECTOR", "", "str")
			} else {
				out = unknown()
			}
		}

	case DriverMySQL:
		unsigned := func(name, generic string) pyType {
			if t.Unsigned {
				return saType(saMySQL, name, "unsigned=True", "int")
			}
			if generic == "" {
				return saType(saMySQL, name, "", "int")
			}
			return saType(saCore, generic, "", "int")
		}
		fsp := func(name string) pyType {
			return saType(saMySQL, name, fmt.Sprintf("fsp=%d", t.Precision), "datetime.datetime")
		}
		switch t.Kind {
		case ormBool:
			out = saType(saCore, "Boolean", "", "bool")
			if t.Name == "bit" {
				out = saType(saMySQL, "BIT", "1", "int")
			}
		case ormInt8:
			out = unsigned("TINYINT", "")
		case ormInt16:
			out = unsigned("SMALLINT", "SmallInteger")
		case ormInt32:
			if t.Name == "mediumint" {
				out = unsigned("MEDIUMINT", "")
			} else {
				out = unsigned("INTEGER", "Integer")
			}
		case ormInt64:
			out = unsigned("BIGINT", "BigInteger")
		case ormFloat32:
			out = saType(saCore, "Float", "", "float")
		case ormFloat64:
			out = saType(saCore, "Double", "", "float")
		case ormDecimal:
			out = numeric()
		case ormChar:
			out = sized(saCore, "CHAR", "str")
		case ormVarchar:
			out = sized(saCore, "String", "str")
		case ormText:
			out = saType(saCore, "Text", "", "str")
			if t.Name != "text" {
				out = saType(saMySQL, strings.ToUpper(t.Name), "", "str")
			}
		case ormJSON:
			out = saType(saCore, "JSON", "", "Any")
		case ormBytes:
			switch t.Name {
			case "binary":
				out = sized(saCore, "BINARY", "bytes")
			case "varbinary":
				out = sized(saCore, "VARBINARY", "bytes")
			case "blob":
				out = saType(saCore, "BLOB", "", "bytes")
			default:
				out = saType(saMySQL, strings.ToUpper(t.Name), "", "bytes")
			}
		case ormBit:
			out = saType(saMySQL, "BIT", fmt.Sprintf("%d", max(t.Length, 1)), "int")
		case ormDate:
			out = saType(saCore, "Date", "", "datetime.date")
		case ormTime:
			out = saType(saCore, "Time", "", "datetime.time")
			if t.HasPrecision && t.Precision > 0 {
				out = saType(saMySQL, "TIME", fmt.Sprintf("fsp=%d", t.Precision), "datetime.time")
			}
		case ormDateTime:
			out = saType(saCore, "DateTime", "", "datetime.datetime")
			if t.HasPrecision && t.Precision > 0 {
				out = fsp("DATETIME")
			}
		case ormDateTimeTZ:
			out = saType(saCore, "TIMESTAMP", "", "datetime.datetime")
			if t.HasPrecision && t.Precision > 0 {
				out = fsp("TIMESTAMP")
			}
		case ormYear:
			out = saType(saMySQL, "YEAR", "", "int")
		case ormSet:
			out = saType(saMySQL, "SET", strings.Join(jsStrings(t.Values), ", "), "set[str]")
		case ormUUID:
			out = saType(saCore, "Uuid", "", "uuid.UUID")
		default:
			out = unknown()
		}

	case DriverSQLite:
		switch t.Kind {
		case ormBool:
			out = saType(saCore, "Boolean", "", "bool")
		case ormInt8, ormInt16, ormInt32, ormYear:
			out = saType(saCore, "Integer", "", "int")
		case ormInt64:
			out = saType(saCore, "BigInteger", "", "int")
		case ormFloat32, ormFloat64:
			out = saType(saCore, "Float", "", "float")
		case ormDecimal, ormMoney:
			out = numeric()
		case ormChar, ormVarchar:
			out = sized(saCore, "String", "str")
		case ormJSON:
			out = saType(saCore, "JSON", "", "Any")
		case ormBytes:
			out = saType(saCore, "LargeBinary", "", "bytes")
		case ormDate:
			out = saType(saCore, "Date", "", "datetime.date")
		case ormTime:
			out = saType(saCore, "Time", "", "datetime.time")
		case ormDateTime, ormDateTimeTZ:
			out = saType(saCore, "DateTime", "", "datetime.datetime")
		default:
			out = saType(saCore, "Text", "", "str")
		}

	case DriverMSSQL:
		switch t.Kind {
		case ormBool:
			out = saType(saCore, "Boolean", "", "bool")
		case ormInt8:
			out = saType(saMSSQL, "TINYINT", "", "int")
		case ormInt16:
			out = saType(saCore, "SmallInteger", "", "int")
		case ormInt32:
			out = saType(saCore, "Integer", "", "int")
		case ormInt64:
			out = saType(saCore, "BigInteger", "", "int")
		case ormFloat32:
			out = saType(saCore, "REAL", "", "float")
		case ormFloat64:
			out = saType(saCore, "Float", "53", "float")
		case ormDecimal:
			out = numeric()
		case ormMoney:
			out = saType(saMSSQL, strings.ToUpper(t.Name), "", "decimal.Decimal")
		case ormChar:
			out = sized(saCore, "CHAR", "str")
			if t.Name == "nchar" {
				out = sized(saCore, "NCHAR", "str")
			}
		case ormVarchar:
			out = sized(saCore, "String", "str")
			if t.Name == "nvarchar" {
				out = sized(saCore, "Unicode", "str")
			}
		case ormText:
			out = saType(saCore, "Text", "", "str")
			if t.Name == "ntext" {
				out = saType(saMSSQL, "NTEXT", "", "str")
			}
		case ormUUID:
			out = saType(saCore, "Uuid", "", "uuid.UUID")
		case ormXML:
			out = saType(saMSSQL, "XML", "", "str")
		case ormBytes:
			switch t.Name {
			case "binary":
				out = sized(saCore, "BINARY", "bytes")
			case "varbinary":
				out = sized(saCore, "VARBINARY", "bytes")
			case "image":
				out = saType(saMSSQL, "IMAGE", "", "bytes")
			default:
				out = saType(saMSSQL, "ROWVERSION", "", "bytes")
			}
		case ormDate:
			out = saType(saCore, "Date", "", "datetime.date")
		case ormTime:
			out = saType(saCore, "Time", "", "datetime.time")
		case ormDateTime:
			switch t.Name {
			case "datetime2":
				out = saType(saMSSQL, "DATETIME2", "", "datetime.datetime")
			case "smalldatetime":
				out = saType(saMSSQL, "SMALLDATETIME", "", "datetime.datetime")
			default:
				out = saType(saCore, "DateTime", "", "datetime.datetime")
			}
		case ormDateTimeTZ:
			out = saType(saMSSQL, "DATETIMEOFFSET", "", "datetime.datetime")
		default:
			out = unknown()
		}

	case DriverOracle:
		switch t.Kind {
		case ormBool:
			out = saType(saCore, "Boolean", "", "bool")
		case ormInt32, ormInt64:
			out = saType(saOracle, "NUMBER", fmt.Sprintf("%d, %d", t.Precision, t.Scale), "int")
		case ormDecimal:
			out = saType(saOracle, "NUMBER", "", "decimal.Decimal")
			if t.HasPrecision {
				out = saType(saOracle, "NUMBER", fmt.Sprintf("%d, %d", t.Precision, t.Scale), "decimal.Decimal")
			}
		case ormFloat32:
			out = saType(saOracle, "BINARY_FLOAT", "", "float")
			if t.Name == "float" {
				out = saType(saOracle, "FLOAT", "", "float")
			}
		case ormFloat64:
			out = saType(saOracle, "BINARY_DOUBLE", "", "float")
			if t.Name == "float" {
				out = saType(saOracle, "FLOAT", "", "float")
			}
		case ormChar:
			out = sized(saCore, "CHAR", "str")
			if t.Name == "nchar" {
				out = sized(saCore, "NCHAR", "str")
			}
		case ormVarchar:
			out = sized(saOracle, strings.ToUpper(t.Name), "str")
		case ormText:
			switch t.Name {
			case "clob":
				out = saType(saCore, "CLOB", "", "str")
			case "nclob":
				out = saType(saOracle, "NCLOB", "", "str")
			case "long":
				out = saType(saOracle, "LONG", "", "str")
			default:
				out = saType(saOracle, "ROWID", "", "str")
			}
		case ormBytes:
			out = saType(saCore, "BLOB", "", "bytes")
			if t.Name == "raw" {
				out = sized(saOracle, "RAW", "bytes")
			}
		case ormDateTime:
			out = saType(saOracle, "DATE", "", "datetime.datetime")
			if t.Name != "date" {
				out = saType(saOracle, "TIMESTAMP", "", "datetime.datetime")
			}
		case ormDateTimeTZ:
			out = saType(saOracle, "TIMESTAMP", "timezone=True", "datetime.datetime")
		case ormInterval:
			out = saType(saOracle, "INTERVAL", "", "datetime.timedelta")
		case ormJSON:
			out = saType(saCore, "JSON", "", "Any")
		default:
			out = unknown()
		}
	}
	return s.array(out, t)
}

// array wraps an element type as a PostgreSQL array.
func (s *sqlalchemyGen) array(el pyType, t ormType) pyType {
	if !t.Array {
		return s.useType(el)
	}
	s.useType(el)
	out := pyType{expr: "ARRAY(" + el.expr + ")", py: "list[" + el.py + "]", imports: map[string][]string{saPG: {"ARRAY"}}}
	return s.useType(out)
}

// schemaArg reports whether a schema has to be written for a table or type to
// be found: SQLAlchemy takes none for the connection's default.
func (s *sqlalchemyGen) schemaArg(schema string) bool {
	if schema == "" || s.driver == DriverSQLite {
		return false
	}
	if s.multiSchema {
		return true
	}
	switch s.driver {
	case DriverPostgres, DriverMSSQL:
		return s.defaultSchema != "" && schema != s.defaultSchema
	}
	return false
}

// columnArgs renders the arguments shared by mapped_column() and Column():
// the type, a single-column foreign key, the key and default flags.
func (s *sqlalchemyGen) columnArgs(m *ormTable, c *ormCol, t pyType) []string {
	args := []string{t.expr}
	if c.Identity == "always" || c.Identity == "by default" {
		s.use(saCore, "Identity")
		if c.Identity == "always" {
			args = append(args, "Identity(always=True)")
		} else {
			args = append(args, "Identity()")
		}
	}
	// Foreign keys are part of the table whether or not relations were asked
	// for: they are constraints, and the relationships only read them.
	for _, fk := range m.ForeignKeys {
		if len(fk.Columns) != 1 || fk.Columns[0] != c.Name || len(fk.RefColumns) != 1 || fk.RefTable == "" {
			continue
		}
		target := fk.RefTable + "." + fk.RefColumns[0]
		refSchema := fk.RefSchema
		if refSchema == "" {
			refSchema = m.Schema
		}
		if s.schemaArg(refSchema) {
			target = refSchema + "." + target
		}
		if !s.inOutput(refSchema, fk.RefTable) || fk.RefColumns[0] == "" {
			continue
		}
		s.use(saCore, "ForeignKey")
		parts := []string{jsString(target)}
		if a := ormAction(fk.OnDelete); a != "" && a != "NO ACTION" {
			parts = append(parts, "ondelete="+jsString(a))
		}
		if a := ormAction(fk.OnUpdate); a != "" && a != "NO ACTION" {
			parts = append(parts, "onupdate="+jsString(a))
		}
		// SQLite names no foreign keys; the name it is given here is a counter.
		if fk.Name != "" && s.driver != DriverSQLite {
			parts = append(parts, "name="+jsString(fk.Name))
		}
		args = append(args, "ForeignKey("+strings.Join(parts, ", ")+")")
	}
	if m.pk[c.Name] {
		args = append(args, "primary_key=True")
		if len(m.PrimaryKey) == 1 && c.t.isInteger() && c.def.Kind != ormDefAuto {
			// SQLAlchemy takes a lone integer key for auto-numbered unless told.
			args = append(args, "autoincrement=False")
		}
	}
	if c.Generated {
		if c.GeneratedExpr != "" {
			s.use(saCore, "Computed")
			args = append(args, "Computed("+jsString(c.GeneratedExpr)+", persisted=True)")
		}
	} else if s.opts.Defaults && c.def.Kind != ormDefNone && c.def.Kind != ormDefAuto && c.def.Kind != ormDefAssumedAuto {
		if expr := c.def.sql(s.driver); expr != "" {
			s.use(saCore, "text")
			args = append(args, "server_default=text("+jsString(expr)+")")
		}
	}
	if c.Comment != "" {
		args = append(args, "comment="+jsString(ormOneLine(c.Comment)))
	}
	return args
}

// inOutput reports whether a table is among the models being written, so a
// ForeignKey never names a table the metadata will not have.
func (s *sqlalchemyGen) inOutput(schema, name string) bool {
	for _, m := range s.models {
		if m.Name == name && (m.Schema == schema || schema == "") {
			return true
		}
	}
	return false
}

// tableArgs renders the constraints and indexes that are not part of one
// column, and the keyword arguments that place the table.
func (s *sqlalchemyGen) tableArgs(m *ormTable) (positional []string, keywords [][2]string) {
	for _, fk := range m.ForeignKeys {
		if len(fk.Columns) < 2 || len(fk.Columns) != len(fk.RefColumns) {
			continue
		}
		refSchema := fk.RefSchema
		if refSchema == "" {
			refSchema = m.Schema
		}
		if !s.inOutput(refSchema, fk.RefTable) {
			continue
		}
		prefix := fk.RefTable + "."
		if s.schemaArg(refSchema) {
			prefix = refSchema + "." + prefix
		}
		targets := make([]string, len(fk.RefColumns))
		for i, c := range fk.RefColumns {
			targets[i] = jsString(prefix + c)
		}
		s.use(saCore, "ForeignKeyConstraint")
		parts := []string{
			"[" + strings.Join(jsStrings(fk.Columns), ", ") + "]",
			"[" + strings.Join(targets, ", ") + "]",
		}
		if a := ormAction(fk.OnDelete); a != "" && a != "NO ACTION" {
			parts = append(parts, "ondelete="+jsString(a))
		}
		if a := ormAction(fk.OnUpdate); a != "" && a != "NO ACTION" {
			parts = append(parts, "onupdate="+jsString(a))
		}
		if fk.Name != "" && s.driver != DriverSQLite {
			parts = append(parts, "name="+jsString(fk.Name))
		}
		positional = append(positional, "ForeignKeyConstraint("+strings.Join(parts, ", ")+")")
	}
	if !m.view {
		for _, ix := range m.uniques {
			s.use(saCore, "UniqueConstraint")
			positional = append(positional, fmt.Sprintf("UniqueConstraint(%s, name=%s)",
				strings.Join(jsStrings(ix.Columns), ", "), jsString(ix.Name)))
		}
		for _, ix := range m.indexes {
			s.use(saCore, "Index")
			parts := append([]string{jsString(ix.Name)}, jsStrings(ix.Columns)...)
			if method := strings.ToLower(ix.Method); method != "" && method != "btree" && s.driver == DriverPostgres {
				parts = append(parts, "postgresql_using="+jsString(method))
			}
			positional = append(positional, "Index("+strings.Join(parts, ", ")+")")
		}
	}
	if s.schemaArg(m.Schema) {
		keywords = append(keywords, [2]string{"schema", jsString(m.Schema)})
	}
	if m.Comment != "" {
		keywords = append(keywords, [2]string{"comment", jsString(ormOneLine(m.Comment))})
	}
	return positional, keywords
}

func (s *sqlalchemyGen) class(m *ormTable) string {
	s.use("sqlalchemy.orm", "Mapped", "mapped_column")
	var b strings.Builder
	fmt.Fprintf(&b, "class %s(Base):\n", s.names.model[m])
	fmt.Fprintf(&b, "    __tablename__ = %s\n", jsString(m.Name))

	positional, keywords := s.tableArgs(m)
	var dict []string
	for _, kw := range keywords {
		dict = append(dict, jsString(kw[0])+": "+kw[1])
	}
	switch {
	case len(positional) > 0:
		b.WriteString("    __table_args__ = (\n")
		for _, p := range positional {
			b.WriteString("        " + p + ",\n")
		}
		if len(dict) > 0 {
			b.WriteString("        {" + strings.Join(dict, ", ") + "},\n")
		}
		b.WriteString("    )\n")
	case len(dict) > 0:
		b.WriteString("    __table_args__ = {" + strings.Join(dict, ", ") + "}\n")
	}
	b.WriteString("\n")

	for _, c := range m.cols {
		t := s.columnType(m, c)
		name := s.names.field[c]
		annotation := t.py
		if c.Nullable {
			s.typing["Optional"] = true
			annotation = "Optional[" + annotation + "]"
		}
		args := s.columnArgs(m, c, t)
		if name != c.Name {
			args = append([]string{jsString(c.Name)}, args...)
		}
		fmt.Fprintf(&b, "    %s: Mapped[%s] = mapped_column(%s)\n", name, annotation, strings.Join(args, ", "))
	}

	attrs := func(t *ormTable, cols []string) []string {
		out := make([]string, len(cols))
		for i, c := range cols {
			out[i] = s.names.field[t.byCol[c]]
		}
		return out
	}
	var rels []string
	for _, r := range m.rels {
		if !s.classes[r.to] {
			continue
		}
		other := s.names.model[r.to]
		annotation := jsString(other)
		if r.optional {
			s.typing["Optional"] = true
			annotation = "Optional[" + annotation + "]"
		}
		parts := []string{
			"back_populates=" + jsString(s.names.back[r]),
			"foreign_keys=[" + strings.Join(attrs(m, r.fk.Columns), ", ") + "]",
		}
		if r.self {
			// Both ends are this class; remote_side says which end is the parent.
			parts = append(parts, "remote_side=["+strings.Join(attrs(m, r.fk.RefColumns), ", ")+"]")
		}
		rels = append(rels, fmt.Sprintf("    %s: Mapped[%s] = relationship(%s)\n", s.names.fwd[r], annotation, strings.Join(parts, ", ")))
	}
	for _, r := range m.back {
		if !s.classes[r.from] {
			continue
		}
		other := s.names.model[r.from]
		cols := attrs(r.from, r.fk.Columns)
		for i := range cols {
			cols[i] = other + "." + cols[i]
		}
		keys := cols[0]
		if len(cols) > 1 {
			keys = "[" + strings.Join(cols, ", ") + "]"
		}
		parts := []string{"back_populates=" + jsString(s.names.fwd[r]), "foreign_keys=" + jsString(keys)}
		annotation := "list[" + jsString(other) + "]"
		if r.unique {
			s.typing["Optional"] = true
			annotation = "Optional[" + jsString(other) + "]"
			parts = append(parts, "uselist=False")
		}
		rels = append(rels, fmt.Sprintf("    %s: Mapped[%s] = relationship(%s)\n", s.names.back[r], annotation, strings.Join(parts, ", ")))
	}
	if len(rels) > 0 {
		s.use("sqlalchemy.orm", "relationship")
		b.WriteString("\n" + strings.Join(rels, ""))
	}
	return b.String()
}

// table declares a relation the ORM cannot map as a class — it has no primary
// key, or it is a view — as a Table on the same metadata.
func (s *sqlalchemyGen) table(m *ormTable) string {
	s.use(saCore, "Table", "Column")
	var b strings.Builder
	switch {
	case m.view:
		fmt.Fprintf(&b, "# %s is a %s: declared as a Table to select from, never to create.\n", ormOneLine(m.Name), m.Kind)
	default:
		s.warn("%s has no primary key, so it is declared as a Table rather than a mapped class: SQLAlchemy's ORM needs a key to tell rows apart.", s.label(m))
		fmt.Fprintf(&b, "# %s has no primary key, which the ORM needs to map a class; it is a Table instead.\n", ormOneLine(m.Name))
	}
	fmt.Fprintf(&b, "%s = Table(\n    %s,\n    Base.metadata,\n", s.names.top.take("t_"+ormSnake(m.Name)), jsString(m.Name))
	for _, c := range m.cols {
		t := s.columnType(m, c)
		args := append([]string{jsString(c.Name)}, s.columnArgs(m, c, t)...)
		if !c.Nullable {
			args = append(args, "nullable=False")
		}
		b.WriteString("    Column(" + strings.Join(args, ", ") + "),\n")
	}
	positional, keywords := s.tableArgs(m)
	for _, p := range positional {
		b.WriteString("    " + p + ",\n")
	}
	for _, kw := range keywords {
		b.WriteString("    " + kw[0] + "=" + kw[1] + ",\n")
	}
	b.WriteString(")\n")
	return b.String()
}
