package dbx

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// Go: GORM models, and plain structs in the shape sqlc writes.
//
// Both are one file of structs, differing in what the struct is for. A GORM
// model carries the whole column in its tag — name, database type, key,
// default, indexes — plus relation fields and a TableName method, because
// GORM would otherwise guess all of those from the Go names. A plain struct is
// only somewhere to scan a row into: a db tag, and for a nullable column
// either database/sql's Null type or a pointer, as asked.
//
// Neither reaches for a third-party type where the standard library has one
// that scans correctly: an exact numeric is a string, a UUID is a string. The
// exceptions are GORM's own datatypes.JSON and lib/pq's array types, which are
// what GORM users already have on hand.

// goInitialisms are the words Go's own style keeps in capitals.
var goInitialisms = ormWordSet(`ACL API ASCII CPU CSS DNS EOF GUID HTML HTTP HTTPS ID IP JSON LHS QPS RAM
	RHS RPC SLA SMTP SQL SSH TCP TLS TTL UDP UI UID UUID URI URL UTF8 VM XML XMPP XSRF XSS`)

// goName renders a database name as an exported Go identifier: customer_id ->
// CustomerID, "weird column" -> WeirdColumn, CUSTOMERS -> Customers.
func goName(name string) string {
	var b strings.Builder
	for _, w := range ormIdentWords(name) {
		upper := strings.ToUpper(w)
		switch {
		case goInitialisms[upper]:
			b.WriteString(upper)
		case w == upper:
			// A shouted name (Oracle's default) is one word, not an acronym.
			b.WriteString(upper[:1] + strings.ToLower(w[1:]))
		default:
			b.WriteString(strings.ToUpper(w[:1]) + w[1:])
		}
	}
	s := b.String()
	if s == "" {
		return "Field"
	}
	if s[0] >= '0' && s[0] <= '9' {
		return "X" + s
	}
	return s
}

type goGen struct {
	*ormGen
	names   *ormNaming
	gorm    bool
	imports map[string]bool
	// nullEnums names the Null wrapper of each enum a nullable column uses.
	nullEnums map[*ormEnum]string
}

func generateGorm(g *ormGen) []ORMFile      { return generateGo(g, true) }
func generateGoStructs(g *ormGen) []ORMFile { return generateGo(g, false) }

func generateGo(g *ormGen, gorm bool) []ORMFile {
	o := &goGen{ormGen: g, gorm: gorm, imports: map[string]bool{}, nullEnums: map[*ormEnum]string{}}
	o.names = g.names(ormNameRules{
		model:  func(t string) string { return goName(singular(t)) },
		field:  goName,
		enum:   goName,
		member: []string{"TableName"},
	})

	var structs strings.Builder
	for _, m := range g.models {
		structs.WriteString("\n" + o.structFor(m))
	}
	var enums strings.Builder
	for _, e := range g.enums {
		enums.WriteString("\n" + o.enum(e))
	}

	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	if gorm {
		b.WriteString("// A reviewed starting point: verify types, defaults and relations. Exact\n")
		b.WriteString("// numerics are strings, so nothing is rounded on the way through.\n")
	} else {
		b.WriteString("// A reviewed starting point: structs to scan rows into, in the shape sqlc\n")
		b.WriteString("// writes. Exact numerics and UUIDs are strings, so they need no extra module.\n")
	}
	fmt.Fprintf(&b, "\npackage %s\n", g.opts.Package)
	if len(o.imports) > 0 {
		// The standard library first, then the rest, as goimports groups them.
		var std, third []string
		for _, p := range ormSortedKeys(o.imports) {
			if strings.Contains(p, ".") {
				third = append(third, p)
			} else {
				std = append(std, p)
			}
		}
		b.WriteString("\nimport (\n")
		for _, p := range std {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
		if len(std) > 0 && len(third) > 0 {
			b.WriteString("\n")
		}
		for _, p := range third {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
		b.WriteString(")\n")
	}
	b.WriteString(enums.String())
	b.WriteString(structs.String())

	src := b.String()
	if formatted, err := format.Source([]byte(src)); err == nil {
		src = string(formatted)
	} else {
		g.warn("The generated Go could not be formatted (%v); it is returned as written.", err)
	}
	return []ORMFile{{Filename: "models.go", Content: src}}
}

// goEnumConsts gives each enum label a constant name under its type's.
func goEnumConsts(typeName string, values []string, top *ormNamer) [][2]string {
	out := make([][2]string, 0, len(values))
	for _, v := range values {
		suffix := goName(v)
		if len(ormIdentWords(v)) == 0 {
			suffix = "Empty"
		}
		out = append(out, [2]string{top.take(typeName + suffix), v})
	}
	return out
}

func (o *goGen) enum(e *ormEnum) string {
	name := o.names.enum[e]
	var b strings.Builder
	fmt.Fprintf(&b, "// %s is the %s enum.\n", name, ormOneLine(e.Name))
	fmt.Fprintf(&b, "type %s string\n\nconst (\n", name)
	for _, c := range goEnumConsts(name, e.Values, o.names.top) {
		fmt.Fprintf(&b, "\t%s %s = %s\n", c[0], name, strconv.Quote(c[1]))
	}
	b.WriteString(")\n")
	if o.gorm {
		return b.String()
	}

	// What sqlc writes beside an enum: a Scan so a driver's string or bytes
	// land in the type, and a Null wrapper for the columns that allow NULL.
	o.imports["fmt"] = true
	fmt.Fprintf(&b, `
func (e *%[1]s) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = %[1]s(s)
	case string:
		*e = %[1]s(s)
	default:
		return fmt.Errorf("unsupported scan type for %[1]s: %%T", src)
	}
	return nil
}
`, name)
	null := o.nullEnums[e]
	if null == "" {
		return b.String()
	}
	o.imports["database/sql/driver"] = true
	fmt.Fprintf(&b, `
// %[2]s is a %[1]s that may be NULL.
type %[2]s struct {
	%[1]s %[1]s %[3]s
	Valid bool %[4]s
}

func (ns *%[2]s) Scan(value any) error {
	if value == nil {
		ns.%[1]s, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.%[1]s.Scan(value)
}

func (ns %[2]s) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.%[1]s), nil
}
`, name, null, o.jsonTag(ormSnake(name)), o.jsonTag("valid"))
	return b.String()
}

func (o *goGen) jsonTag(name string) string {
	if !o.opts.JSONTags {
		return ""
	}
	return goTag([][2]string{{"json", name}})
}

// goTag renders a struct tag. A raw string cannot hold a backtick, so a tag
// that has one — a MySQL default can — is written as an interpreted string.
func goTag(pairs [][2]string) string {
	var parts []string
	for _, p := range pairs {
		parts = append(parts, p[0]+":"+strconv.Quote(p[1]))
	}
	tag := strings.Join(parts, " ")
	if tag == "" {
		return ""
	}
	if strings.Contains(tag, "`") {
		return strconv.Quote(tag)
	}
	return "`" + tag + "`"
}

// goType maps a column onto a Go type. scalar is the non-null type; the
// nullable form is derived from it by the caller.
func (o *goGen) goType(m *ormTable, c *ormCol) (scalar string, nilable bool) {
	t := c.t
	if t.Array {
		return o.arrayType(m, c), true
	}
	unsigned := func(bits string) string {
		if t.Unsigned {
			return "uint" + bits
		}
		return "int" + bits
	}
	switch t.Kind {
	case ormBool:
		if t.Name == "bit" && o.driver == DriverMySQL {
			return "[]byte", true
		}
		return "bool", false
	case ormInt8:
		return unsigned("8"), false
	case ormInt16, ormYear:
		return unsigned("16"), false
	case ormInt32:
		return unsigned("32"), false
	case ormInt64:
		return unsigned("64"), false
	case ormFloat32:
		return "float32", false
	case ormFloat64:
		return "float64", false
	case ormJSON:
		if o.gorm {
			o.imports["gorm.io/datatypes"] = true
			return "datatypes.JSON", true
		}
		o.imports["encoding/json"] = true
		return "json.RawMessage", true
	case ormBytes, ormBit:
		return "[]byte", true
	case ormDate, ormDateTime, ormDateTimeTZ:
		return "time.Time", false
	case ormEnumKind:
		if t.Enum != nil {
			return o.names.enum[t.Enum], false
		}
	case ormUnknown:
		o.warn("%s.%s has type %s, which has no mapping here; it is typed as a string.", o.label(m), c.Name, c.Type)
	}
	// Text of every kind, and the values only text carries without loss: exact
	// numerics, UUIDs, a time of day, an interval.
	return "string", false
}

// arrayType maps a PostgreSQL or ClickHouse array. GORM gets lib/pq's array
// types, which are what read and write a PostgreSQL array through
// database/sql; the plain structs get slices, which is what sqlc declares.
func (o *goGen) arrayType(m *ormTable, c *ormCol) string {
	el := "string"
	pq := "pq.StringArray"
	switch c.t.Kind {
	case ormBool:
		el, pq = "bool", "pq.BoolArray"
	case ormInt8, ormInt16, ormInt32:
		el, pq = "int32", "pq.Int32Array"
	case ormInt64:
		el, pq = "int64", "pq.Int64Array"
	case ormFloat32:
		el, pq = "float32", "pq.Float32Array"
	case ormFloat64:
		el, pq = "float64", "pq.Float64Array"
	case ormEnumKind:
		if c.t.Enum != nil && !o.gorm {
			el = o.names.enum[c.t.Enum]
		}
	}
	if o.gorm && o.driver == DriverPostgres {
		o.imports["github.com/lib/pq"] = true
		return pq
	}
	return "[]" + el
}

// nullable renders the type of a column that allows NULL.
func (o *goGen) nullable(c *ormCol, scalar string, nilable bool) string {
	if nilable {
		return scalar
	}
	if o.gorm || o.opts.Nulls == "pointer" {
		return "*" + scalar
	}
	if e := c.t.Enum; e != nil && c.t.Kind == ormEnumKind {
		// The wrapper is declared with the enum, once something needs it.
		if o.nullEnums[e] == "" {
			o.nullEnums[e] = o.names.top.take("Null" + scalar)
		}
		return o.nullEnums[e]
	}
	o.imports["database/sql"] = true
	switch scalar {
	case "string":
		return "sql.NullString"
	case "bool":
		return "sql.NullBool"
	case "int16":
		return "sql.NullInt16"
	case "int32":
		return "sql.NullInt32"
	case "int64":
		return "sql.NullInt64"
	case "float64":
		return "sql.NullFloat64"
	case "time.Time":
		return "sql.NullTime"
	}
	// The sizes database/sql has no named type for.
	return "sql.Null[" + scalar + "]"
}

func (o *goGen) structFor(m *ormTable) string {
	name := o.names.model[m]
	var b strings.Builder
	switch {
	case m.Comment != "":
		fmt.Fprintf(&b, "// %s maps %s: %s\n", name, ormOneLine(m.Name), ormOneLine(m.Comment))
	case m.view:
		fmt.Fprintf(&b, "// %s maps the %s %s, which is read-only.\n", name, m.Kind, ormOneLine(m.Name))
	default:
		fmt.Fprintf(&b, "// %s maps the %s table.\n", name, ormOneLine(m.Name))
	}
	fmt.Fprintf(&b, "type %s struct {\n", name)

	// Which named indexes each column takes part in, with its position.
	type membership struct {
		kind, name string
		priority   int
	}
	members := map[string][]membership{}
	if o.gorm && !m.view {
		for _, ix := range m.uniques {
			for i, col := range ix.Columns {
				p := 0
				if len(ix.Columns) > 1 {
					p = i + 1
				}
				members[col] = append(members[col], membership{"uniqueIndex", ix.Name, p})
			}
		}
		for _, ix := range o.plainIndexes(m) {
			for i, col := range ix.Columns {
				p := 0
				if len(ix.Columns) > 1 {
					p = i + 1
				}
				members[col] = append(members[col], membership{"index", ix.Name, p})
			}
		}
	}

	for _, c := range m.cols {
		scalar, nilable := o.goType(m, c)
		typ := scalar
		if c.Nullable {
			typ = o.nullable(c, scalar, nilable)
		}
		if strings.Contains(typ, "time.Time") {
			// Imported for the type as written: a nullable column is a
			// sql.NullTime, which needs database/sql and not time.
			o.imports["time"] = true
		}
		var tag [][2]string
		if o.gorm {
			parts := []string{"column:" + goTagValue(c.Name), "type:" + goTagValue(ormTypeFold(strings.TrimSpace(c.Type), strings.ToLower))}
			if m.pk[c.Name] && !m.view {
				parts = append(parts, "primaryKey")
				if len(m.PrimaryKey) == 1 && c.t.isInteger() {
					// GORM numbers a lone integer key itself unless told not to.
					if c.def.Kind == ormDefAuto {
						parts = append(parts, "autoIncrement")
					} else {
						parts = append(parts, "autoIncrement:false")
					}
				}
			}
			if !c.Nullable && !m.pk[c.Name] {
				parts = append(parts, "not null")
			}
			if o.opts.Defaults && !c.Generated {
				switch c.def.Kind {
				case ormDefString:
					parts = append(parts, "default:"+goTagValue(gormStringDefault(o.driver, c.def.Text)))
				case ormDefNumber:
					parts = append(parts, "default:"+goTagValue(c.def.Text))
				case ormDefBool:
					parts = append(parts, fmt.Sprintf("default:%t", c.def.Bool))
				case ormDefNow, ormDefUUID, ormDefExpr, ormDefJSON, ormDefEmptyArray:
					parts = append(parts, "default:"+goTagValue(c.def.sql(o.driver)))
				}
			}
			if c.Generated {
				// Read it, never write it.
				parts = append(parts, "->")
			}
			for _, mem := range members[c.Name] {
				entry := mem.kind + ":" + goTagValue(mem.name)
				if mem.priority > 0 {
					entry += fmt.Sprintf(",priority:%d", mem.priority)
				}
				parts = append(parts, entry)
			}
			tag = append(tag, [2]string{"gorm", strings.Join(parts, ";")})
		} else {
			tag = append(tag, [2]string{"db", c.Name})
		}
		if o.opts.JSONTags {
			tag = append(tag, [2]string{"json", c.Name})
		}
		if c.Comment != "" {
			fmt.Fprintf(&b, "\t// %s\n", ormOneLine(c.Comment))
		}
		fmt.Fprintf(&b, "\t%s %s %s\n", o.names.field[c], typ, goTag(tag))
	}

	if o.gorm {
		fields := func(t *ormTable, cols []string) string {
			out := make([]string, len(cols))
			for i, col := range cols {
				out[i] = o.names.field[t.byCol[col]]
			}
			return strings.Join(out, ",")
		}
		relTag := func(r *ormRel, constraint bool) string {
			parts := []string{"foreignKey:" + fields(r.from, r.fk.Columns), "references:" + fields(r.to, r.fk.RefColumns)}
			if constraint {
				var rules []string
				if a := ormAction(r.fk.OnUpdate); a != "" && a != "NO ACTION" {
					rules = append(rules, "OnUpdate:"+a)
				}
				if a := ormAction(r.fk.OnDelete); a != "" && a != "NO ACTION" {
					rules = append(rules, "OnDelete:"+a)
				}
				if len(rules) > 0 {
					parts = append(parts, "constraint:"+strings.Join(rules, ","))
				}
			}
			return strings.Join(parts, ";")
		}
		if len(m.rels)+len(m.back) > 0 {
			b.WriteString("\n")
		}
		for _, r := range m.rels {
			tag := [][2]string{{"gorm", relTag(r, true)}}
			if o.opts.JSONTags {
				tag = append(tag, [2]string{"json", ormSnake(o.names.fwd[r]) + ",omitempty"})
			}
			fmt.Fprintf(&b, "\t%s *%s %s\n", o.names.fwd[r], o.names.model[r.to], goTag(tag))
		}
		for _, r := range m.back {
			tag := [][2]string{{"gorm", relTag(r, false)}}
			if o.opts.JSONTags {
				tag = append(tag, [2]string{"json", ormSnake(o.names.back[r]) + ",omitempty"})
			}
			typ := "[]" + o.names.model[r.from]
			if r.unique {
				typ = "*" + o.names.model[r.from]
			}
			fmt.Fprintf(&b, "\t%s %s %s\n", o.names.back[r], typ, goTag(tag))
		}
	}
	b.WriteString("}\n")

	if o.gorm {
		table := m.Name
		if o.qualified(m) {
			table = m.Schema + "." + m.Name
		}
		fmt.Fprintf(&b, "\n// TableName is the table GORM reads and writes for %s.\n", name)
		fmt.Fprintf(&b, "func (%s) TableName() string { return %s }\n", name, strconv.Quote(table))
	}
	return b.String()
}

// gormStringDefault is a string default as GORM's tag has to be given it. GORM
// takes a default with parentheses in it for a database expression, and "null"
// or nothing for no default at all; quoted as SQL, each is the string it is.
func gormStringDefault(driver Driver, text string) string {
	if text != "" && !strings.EqualFold(text, "null") && !(strings.Contains(text, "(") && strings.Contains(text, ")")) {
		return text
	}
	if driver == DriverMySQL {
		return ormMySQLString(text)
	}
	return ormSQLString(text)
}

// goTagValue escapes a value for a gorm tag, whose settings are separated by
// semicolons.
func goTagValue(s string) string {
	return strings.ReplaceAll(s, ";", `\;`)
}
