package dbx

import (
	"fmt"
	"strings"
)

// TypeScript types, Zod schemas and Kysely's Database interface.
//
// Prisma and Drizzle are what you generate when the ORM owns the schema. A web
// developer reading rows out of an existing database and shaping them into an
// API response wants neither: they want the row's type, and something that
// validates a payload before it becomes one. Those are the first two files
// below. The third is the same types arranged the way Kysely asks for them,
// where the difference is that Kysely's are the driver's types, not JSON's: a
// timestamp there is a Date, because that is what the driver hands back.

// tsRules names things the way the type targets always have: a table becomes a
// singular PascalCase type, a column keeps its own name.
func tsRules(g *ormGen) ormNameRules {
	rules := ormNameRules{
		model:     func(s string) string { return pascal(singular(s)) },
		field:     func(s string) string { return s },
		enum:      pascal,
		escapeTop: tsTypeName,
	}
	if g.opts.Naming == ORMNamingCamel {
		rules.field = ormCamel
	}
	return rules
}

// tsType maps a column onto a TypeScript type.
//
// bigint becomes string, not number: a 64-bit integer does not survive
// JSON.parse intact, and silently rounding an id is the kind of bug that
// surfaces months later as two records mysteriously becoming one.
func tsType(g *ormGen, n *ormNaming, m *ormTable, c *ormCol, dates string) string {
	t := c.t
	var typ string
	switch t.Kind {
	case ormBool:
		typ = "boolean"
	case ormInt8, ormInt16, ormInt32, ormFloat32, ormFloat64, ormYear:
		typ = "number"
	case ormInt64, ormBigNum, ormDecimal, ormMoney:
		typ = "string"
	case ormDate, ormDateTime, ormDateTimeTZ:
		typ = dates
	case ormJSON:
		typ = "unknown"
	case ormEnumKind:
		typ = "string"
		if t.Enum != nil {
			typ = n.enum[t.Enum]
		}
	case ormUnknown:
		g.warn("%s.%s has type %s, which has no mapping here; it is typed as a string.", g.label(m), c.Name, c.Type)
		typ = "string"
	default:
		typ = "string"
	}
	if t.Array {
		typ += "[]"
	}
	return typ
}

func tsUnion(values []string) string {
	if len(values) == 0 {
		return "never"
	}
	return strings.Join(jsStrings(values), " | ")
}

func generateTypeScript(g *ormGen) []ORMFile {
	n := g.names(tsRules(g))
	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// Row types as the database returns them. A nullable column is `| null`\n")
	b.WriteString("// rather than optional: the key is always present, its value may not be.\n")
	for _, e := range g.enums {
		fmt.Fprintf(&b, "\nexport type %s = %s\n", n.enum[e], tsUnion(e.Values))
	}
	for _, m := range g.models {
		b.WriteString("\n")
		if m.Comment != "" {
			fmt.Fprintf(&b, "/** %s */\n", ormBlockComment(m.Comment))
		}
		fmt.Fprintf(&b, "export interface %s {\n", n.model[m])
		for _, c := range m.cols {
			typ := tsType(g, n, m, c, g.opts.Dates)
			if c.Nullable {
				typ += " | null"
			}
			fmt.Fprintf(&b, "  %s: %s\n", tsPropertyName(n.field[c]), typ)
		}
		b.WriteString("}\n")
	}
	return []ORMFile{{Filename: "types.ts", Content: b.String()}}
}

func zodType(g *ormGen, n *ormNaming, m *ormTable, c *ormCol) string {
	t := c.t
	var expr string
	switch t.Kind {
	case ormBool:
		expr = "z.boolean()"
	case ormInt8, ormInt16, ormInt32, ormYear:
		expr = "z.number().int()"
	case ormFloat32, ormFloat64:
		expr = "z.number()"
	case ormDate, ormDateTime, ormDateTimeTZ:
		// Coerced rather than z.string(): a date arrives as a string over JSON
		// and as a Date from a driver, and a schema that only accepts one of
		// those fails on whichever half of the app it did not anticipate.
		expr = "z.coerce.date()"
	case ormJSON:
		expr = "z.unknown()"
	case ormEnumKind:
		expr = "z.string()"
		if t.Enum != nil {
			expr = n.enum[t.Enum] + "Schema"
		}
	case ormUnknown:
		g.warn("%s.%s has type %s, which has no mapping here; it is validated as a string.", g.label(m), c.Name, c.Type)
		expr = "z.string()"
	default:
		expr = "z.string()"
	}
	if t.Array {
		expr = "z.array(" + expr + ")"
	}
	return expr
}

func generateZod(g *ormGen) []ORMFile {
	n := g.names(tsRules(g))
	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	if g.opts.InsertSchemas {
		b.WriteString("// One schema per table, plus an `Insert` variant with the columns the\n")
		b.WriteString("// database fills in made optional — which is the difference between a\n")
		b.WriteString("// schema you can validate a row with and one you can validate a form with.\n\n")
	} else {
		b.WriteString("// One schema per table, shaped as a row the database returns.\n\n")
	}
	b.WriteString(`import { z } from "zod"` + "\n")

	for _, e := range g.enums {
		name := n.enum[e]
		fmt.Fprintf(&b, "\nexport const %sSchema = z.enum([%s])\n", name, strings.Join(jsStrings(e.Values), ", "))
		fmt.Fprintf(&b, "export type %s = z.infer<typeof %sSchema>\n", name, name)
	}
	for _, m := range g.models {
		name := n.model[m]
		fmt.Fprintf(&b, "\nexport const %sSchema = z.object({\n", name)
		for _, c := range m.cols {
			expr := zodType(g, n, m, c)
			if c.Nullable {
				expr += ".nullable()"
			}
			fmt.Fprintf(&b, "  %s: %s,\n", tsPropertyName(n.field[c]), expr)
		}
		b.WriteString("})\n")
		fmt.Fprintf(&b, "export type %s = z.infer<typeof %sSchema>\n", name, name)
		if !g.opts.InsertSchemas || m.view {
			continue
		}
		// The insert variant: anything the database fills in is optional on
		// the way in.
		optional := []string{}
		for _, c := range m.cols {
			if c.dbFills() {
				optional = append(optional, jsString(n.field[c]))
			}
		}
		if len(optional) > 0 {
			fmt.Fprintf(&b, "export const %sInsertSchema = %sSchema.partial({ %s })\n",
				name, name, strings.Join(optional, ": true, ")+": true")
		} else {
			fmt.Fprintf(&b, "export const %sInsertSchema = %sSchema\n", name, name)
		}
	}
	return []ORMFile{{Filename: "schemas.ts", Content: b.String()}}
}

// --- Kysely ---------------------------------------------------------------

// kyselyAliases are the helper types a Kysely schema names its columns with.
// Each says three things — what a select returns, what an insert accepts and
// what an update accepts — which is why they are not plain types.
var kyselyAliases = map[string]string{
	"Int8":      "ColumnType<string, string | number | bigint, string | number | bigint>",
	"Numeric":   "ColumnType<string, string | number, string | number>",
	"Timestamp": "ColumnType<Date, Date | string, Date | string>",
	"Json":      "ColumnType<JsonValue, string, string>",
}

const kyselyJSONTypes = `export type JsonPrimitive = string | number | boolean | null
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue | undefined }
`

type kyselyGen struct {
	*ormGen
	names   *ormNaming
	aliases map[string]bool
}

// column types a column as the engine's usual driver returns it: node-postgres,
// mysql2, better-sqlite3, tedious. The engines Kysely reaches through a
// community dialect get the JSON-safe types the plain TypeScript target uses.
func (k *kyselyGen) column(m *ormTable, c *ormCol) string {
	t := c.t
	alias := func(name string) string {
		k.aliases[name] = true
		return name
	}
	var typ string
	if t.Kind == ormEnumKind && t.Enum != nil {
		typ = k.names.enum[t.Enum]
	} else {
		switch k.driver {
		case DriverPostgres:
			switch t.Kind {
			case ormBool:
				typ = "boolean"
			case ormInt8, ormInt16, ormInt32, ormFloat32, ormFloat64:
				typ = "number"
			case ormInt64:
				typ = alias("Int8")
				if t.Name == "oid" {
					typ = "number"
				}
			case ormDecimal:
				typ = alias("Numeric")
			case ormDate, ormDateTime, ormDateTimeTZ:
				typ = alias("Timestamp")
			case ormJSON:
				typ = alias("Json")
			case ormBytes:
				typ = "Buffer"
			case ormInterval, ormGeo, ormUnknown:
				// The driver returns its own object for these, or text it was
				// not told how to parse.
				typ = "unknown"
			default:
				typ = "string"
			}
		case DriverMySQL:
			switch t.Kind {
			case ormBool, ormInt8, ormInt16, ormInt32, ormInt64, ormFloat32, ormFloat64, ormYear:
				// mysql2 returns TINYINT(1) as the 0 or 1 it is, and a BIGINT
				// as a number unless it is told otherwise.
				typ = "number"
				if t.Kind == ormBool && t.Name == "bit" {
					typ = "Buffer"
				}
			case ormDecimal:
				typ = alias("Numeric")
			case ormDate, ormDateTime, ormDateTimeTZ:
				typ = alias("Timestamp")
			case ormJSON:
				typ = alias("Json")
			case ormBytes, ormBit:
				typ = "Buffer"
			case ormGeo, ormUnknown:
				typ = "unknown"
			default:
				typ = "string"
			}
		case DriverSQLite:
			switch t.Kind {
			case ormBool, ormInt8, ormInt16, ormInt32, ormInt64, ormFloat32, ormFloat64, ormYear, ormDecimal, ormMoney:
				// SQLite has no boolean and no decimal: both are numbers.
				typ = "number"
			case ormBytes:
				typ = "Buffer"
			default:
				typ = "string"
			}
		case DriverMSSQL:
			switch t.Kind {
			case ormBool:
				typ = "boolean"
			case ormInt8, ormInt16, ormInt32, ormFloat32, ormFloat64, ormDecimal, ormMoney:
				typ = "number"
			case ormInt64:
				typ = alias("Int8")
			case ormDate, ormTime, ormDateTime, ormDateTimeTZ:
				typ = alias("Timestamp")
			case ormBytes:
				typ = "Buffer"
			case ormGeo, ormUnknown:
				typ = "unknown"
			default:
				typ = "string"
			}
		default:
			typ = tsType(k.ormGen, k.names, m, c, "string")
			typ = strings.TrimSuffix(typ, "[]")
		}
	}
	if t.Array {
		typ += "[]"
	}
	if c.Nullable {
		typ += " | null"
	}
	switch {
	case m.view:
	case c.Generated || c.Identity == "always":
		typ = "GeneratedAlways<" + typ + ">"
		k.aliases["GeneratedAlways"] = true
	case c.dbFills():
		typ = "Generated<" + typ + ">"
		k.aliases["Generated"] = true
	}
	return typ
}

func generateKysely(g *ormGen) []ORMFile {
	k := &kyselyGen{ormGen: g, aliases: map[string]bool{}}
	rules := tsRules(g)
	rules.top = []string{
		"Database", "ColumnType", "Generated", "GeneratedAlways", "Insertable", "Selectable", "Updateable",
		"Int8", "Numeric", "Timestamp", "Json", "JsonValue", "JsonPrimitive",
	}
	k.names = g.names(rules)

	var tables, rows strings.Builder
	type entry struct{ key, iface string }
	var entries []entry
	for _, m := range g.models {
		name := k.names.model[m]
		iface := k.names.top.take(name + "Table")
		if m.Comment != "" {
			fmt.Fprintf(&tables, "\n/** %s */", ormBlockComment(m.Comment))
		}
		fmt.Fprintf(&tables, "\nexport interface %s {\n", iface)
		for _, c := range m.cols {
			fmt.Fprintf(&tables, "  %s: %s\n", tsPropertyName(k.names.field[c]), k.column(m, c))
		}
		tables.WriteString("}\n")

		key := m.Name
		if g.opts.Naming == ORMNamingCamel {
			key = ormCamel(m.Name)
		}
		if g.qualified(m) && !(g.driver == DriverPostgres && m.Schema == g.defaultSchema) {
			key = m.Schema + "." + key
		}
		entries = append(entries, entry{key: key, iface: iface})

		fmt.Fprintf(&rows, "export type %s = Selectable<%s>\n", name, iface)
		if !m.view {
			fmt.Fprintf(&rows, "export type %s = Insertable<%s>\n", k.names.top.take("New"+name), iface)
			fmt.Fprintf(&rows, "export type %s = Updateable<%s>\n", k.names.top.take(name+"Update"), iface)
		}
	}

	imports := []string{"Insertable", "Selectable", "Updateable"}
	for _, name := range []string{"Generated", "GeneratedAlways"} {
		if k.aliases[name] {
			imports = append(imports, name)
		}
	}
	for _, name := range []string{"Int8", "Numeric", "Timestamp", "Json"} {
		if k.aliases[name] {
			imports = append(imports, "ColumnType")
			break
		}
	}
	set := map[string]bool{}
	for _, name := range imports {
		set[name] = true
	}

	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// The Database interface Kysely is typed by. Generated<T> marks a column\n")
	b.WriteString("// the database fills in: optional on insert, always present on select.\n\n")
	b.WriteString(strings.Replace(tsImport(tsSortedImports(set), "kysely"), "import {", "import type {", 1))
	if k.aliases["Json"] {
		b.WriteString("\n" + kyselyJSONTypes)
	}
	first := true
	for _, name := range []string{"Int8", "Numeric", "Timestamp", "Json"} {
		if !k.aliases[name] {
			continue
		}
		if first && !k.aliases["Json"] {
			b.WriteString("\n")
		}
		first = false
		fmt.Fprintf(&b, "export type %s = %s\n", name, kyselyAliases[name])
	}
	for _, e := range g.enums {
		fmt.Fprintf(&b, "\nexport type %s = %s\n", k.names.enum[e], tsUnion(e.Values))
	}
	b.WriteString(tables.String())
	b.WriteString("\nexport interface Database {\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  %s: %s\n", tsPropertyName(e.key), e.iface)
	}
	b.WriteString("}\n\n")
	b.WriteString(rows.String())
	return []ORMFile{{Filename: "database.ts", Content: b.String()}}
}
