package dbx

import (
	"fmt"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

// Django.
//
// A models.py in the shape `manage.py inspectdb` writes, with the parts
// inspectdb leaves for the reader filled in: foreign keys keep the database's
// own ON DELETE rule instead of DO_NOTHING everywhere, every reverse relation
// has a related_name so two keys to one model do not clash, an enum column
// gets a TextChoices class, and a literal default becomes db_default so
// create() works without restating it. managed = False stays the default: the
// tables exist, and Django's migrations should not think they own them.
//
// Django names a column's field, not the column, so a foreign-key column is
// declared as the relation ("customer", column customer_id) and never beside
// it. A composite foreign key has no field at all in Django; its columns stay
// plain fields and the result says so.

type djangoGen struct {
	*ormGen
	names   *ormNaming
	imports map[string]map[string]bool
	// claimed says which relation a column is declared as, per table.
	claimed map[*ormTable]map[string]*ormRel
	owned   map[*ormRel]bool
}

// djangoFieldName makes a name Django accepts for a field, the way inspectdb
// does: lower case, no double or trailing underscore, not a keyword.
func djangoFieldName(name string) string {
	s := strings.ToLower(sanitizeIdent(name))
	for strings.Contains(s, "__") {
		s = strings.ReplaceAll(s, "__", "_")
	}
	if strings.HasPrefix(s, "_") {
		s = "field" + s
	}
	if strings.HasSuffix(s, "_") {
		s += "field"
	}
	if pyReserved[s] {
		s += "_field"
	}
	return s
}

func generateDjango(g *ormGen) []ORMFile {
	d := &djangoGen{
		ormGen: g, imports: map[string]map[string]bool{},
		claimed: map[*ormTable]map[string]*ormRel{}, owned: map[*ormRel]bool{},
	}
	d.names = g.names(ormNameRules{
		model:       func(t string) string { return pascal(singular(t)) },
		field:       djangoFieldName,
		top:         []string{"models", "ArrayField", "Now", "RandomUUID", "Meta"},
		modelSuffix: "Model",
		escapeTop:   pyIdent,
		// Names every model already has; a field may not shadow them.
		member: strings.Fields(`pk objects save delete clean check full_clean refresh_from_db
			validate_unique validate_constraints serializable_value`),
	})

	for _, m := range g.models {
		d.claimed[m] = map[string]*ormRel{}
		for _, r := range m.rels {
			switch {
			case len(r.fk.Columns) != 1:
				d.warn("%s.%s is a composite foreign key, which Django has no field for; its columns are plain fields.",
					d.label(m), strings.Join(r.fk.Columns, ", "))
			case len(r.to.PrimaryKey) > 1:
				d.warn("%s.%s references %s, whose primary key is composite; Django cannot point a ForeignKey at it, so the column is a plain field.",
					d.label(m), r.fk.Columns[0], d.label(r.to))
			case d.claimed[m][r.fk.Columns[0]] != nil:
				d.warn("%s.%s is in two foreign keys; only the first is a relation.", d.label(m), r.fk.Columns[0])
			default:
				d.claimed[m][r.fk.Columns[0]] = r
				d.owned[r] = true
			}
		}
	}

	if g.driver == DriverMSSQL {
		g.warn("Django ships no SQL Server backend of its own: these models need the mssql-django package to connect.")
	}

	var body strings.Builder
	for _, e := range g.enums {
		body.WriteString("\n\n" + d.choices(e))
	}
	for _, m := range g.models {
		body.WriteString("\n\n" + d.model(m))
	}

	var b strings.Builder
	b.WriteString("# Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("# A reviewed starting point, in the shape inspectdb writes: verify field\n")
	b.WriteString("# types and on_delete rules.")
	if !g.opts.Managed {
		b.WriteString(" managed = False keeps Django's migrations\n# away from tables that already exist.\n")
	} else {
		b.WriteString(" These models are managed: run makemigrations\n# --dry-run first and read what Django thinks it has to change.\n")
	}
	b.WriteString("\n")
	d.use("django.db", "models")
	modules := make([]string, 0, len(d.imports))
	for mod := range d.imports {
		modules = append(modules, mod)
	}
	sort.Strings(modules)
	for _, mod := range modules {
		b.WriteString(pyImport(mod, ormSortedKeys(d.imports[mod])))
	}
	b.WriteString(body.String())
	return []ORMFile{{Filename: "models.py", Content: b.String()}}
}

func (d *djangoGen) use(module string, names ...string) {
	if d.imports[module] == nil {
		d.imports[module] = map[string]bool{}
	}
	for _, n := range names {
		d.imports[module][n] = true
	}
}

// djangoChoiceNames gives each enum label a member name for a TextChoices class.
func djangoChoiceNames(values []string) [][2]string {
	used := newORMNamer(false)
	out := make([][2]string, 0, len(values))
	for _, v := range values {
		name := "EMPTY"
		if words := ormIdentWords(v); len(words) > 0 {
			name = strings.ToUpper(strings.Join(words, "_"))
		}
		if name[0] >= '0' && name[0] <= '9' {
			name = "V_" + name
		}
		if pyReserved[name] {
			name += "_"
		}
		out = append(out, [2]string{used.take(name), v})
	}
	return out
}

func (d *djangoGen) choices(e *ormEnum) string {
	var b strings.Builder
	fmt.Fprintf(&b, "class %s(models.TextChoices):\n", d.names.enum[e])
	if len(e.Values) == 0 {
		b.WriteString("    pass\n")
	}
	for _, m := range djangoChoiceNames(e.Values) {
		label := strings.TrimSpace(strings.NewReplacer("_", " ", "-", " ").Replace(m[1]))
		// By rune: the first byte of "în lucru" is half a letter.
		if first, size := utf8.DecodeRuneInString(label); first != utf8.RuneError {
			label = string(unicode.ToUpper(first)) + label[size:]
		}
		fmt.Fprintf(&b, "    %s = %s, %s\n", m[0], jsString(m[1]), jsString(label))
	}
	return b.String()
}

// field maps a column onto a Django field class and its arguments. guess is
// true where Django has no field for the type and a text field stands in,
// which inspectdb marks the same way.
func (d *djangoGen) field(m *ormTable, c *ormCol) (class string, args []string, guess bool) {
	t := c.t
	if t.Enum != nil && !t.Array {
		longest := 1
		for _, v := range t.Enum.Values {
			longest = max(longest, len([]rune(v)))
		}
		return "models.CharField", []string{
			fmt.Sprintf("max_length=%d", longest), "choices=" + d.names.enum[t.Enum] + ".choices",
		}, false
	}
	decimal := func() (string, []string, bool) {
		if t.HasPrecision && t.Precision > 0 {
			return "models.DecimalField", []string{
				fmt.Sprintf("max_digits=%d", t.Precision), fmt.Sprintf("decimal_places=%d", t.Scale),
			}, false
		}
		if d.driver == DriverOracle {
			// A bare NUMBER is a float as far as Django's Oracle backend goes.
			return "models.FloatField", nil, false
		}
		// An unconstrained numeric: these are inspectdb's own stand-ins.
		return "models.DecimalField", []string{"max_digits=65535", "decimal_places=65535"}, false
	}
	integer := func(signed, unsigned string) (string, []string, bool) {
		if t.Unsigned {
			return "models." + unsigned, nil, false
		}
		return "models." + signed, nil, false
	}
	switch t.Kind {
	case ormBool:
		if t.Name == "bit" && d.driver == DriverMySQL {
			return "models.TextField", nil, true
		}
		class = "models.BooleanField"
	case ormInt8, ormInt16:
		return integer("SmallIntegerField", "PositiveSmallIntegerField")
	case ormInt32, ormYear:
		return integer("IntegerField", "PositiveIntegerField")
	case ormInt64:
		return integer("BigIntegerField", "PositiveBigIntegerField")
	case ormFloat32, ormFloat64:
		class = "models.FloatField"
	case ormDecimal:
		return decimal()
	case ormMoney:
		if d.driver == DriverMSSQL {
			digits := map[string]int{"money": 19, "smallmoney": 10}[t.Name]
			return "models.DecimalField", []string{fmt.Sprintf("max_digits=%d", digits), "decimal_places=4"}, false
		}
		return "models.TextField", nil, true
	case ormChar, ormVarchar:
		if t.Length > 0 {
			return "models.CharField", []string{fmt.Sprintf("max_length=%d", t.Length)}, false
		}
		class = "models.TextField"
	case ormText, ormXML:
		class = "models.TextField"
	case ormUUID:
		class = "models.UUIDField"
		if d.driver == DriverSQLite {
			// SQLite keeps whatever text was written; Django's UUIDField there
			// expects 32 hex digits with no hyphens.
			class = "models.TextField"
		}
	case ormJSON:
		class = "models.JSONField"
	case ormBytes:
		class = "models.BinaryField"
	case ormDate:
		class = "models.DateField"
	case ormTime:
		class = "models.TimeField"
	case ormDateTime, ormDateTimeTZ:
		class = "models.DateTimeField"
	case ormInterval:
		class = "models.DurationField"
	case ormNet:
		if t.Name == "inet" {
			class = "models.GenericIPAddressField"
		} else {
			return "models.TextField", nil, true
		}
	default:
		return "models.TextField", nil, true
	}
	return class, args, false
}

// column renders a column's field, array-wrapped where it is one.
func (d *djangoGen) column(m *ormTable, c *ormCol) (expr string, guess bool) {
	class, args, guess := d.field(m, c)
	if guess {
		d.warn("%s.%s has type %s, which Django has no field for; it is declared as a TextField.", d.label(m), c.Name, c.Type)
	}
	name := d.names.field[c]

	pk := len(m.PrimaryKey) == 1 && m.pk[c.Name]
	if pk && c.def.Kind == ormDefAuto && c.t.isInteger() && !c.t.Array {
		class = map[ormKind]string{
			ormInt8: "models.SmallAutoField", ormInt16: "models.SmallAutoField",
			ormInt32: "models.AutoField", ormInt64: "models.BigAutoField",
		}[c.t.Kind]
		args = nil
	}
	if c.t.Array && d.driver == DriverPostgres {
		d.use("django.contrib.postgres.fields", "ArrayField")
		args = []string{class + "(" + strings.Join(args, ", ") + ")"}
		class = "ArrayField"
	}
	if pk {
		args = append(args, "primary_key=True")
	}
	if _, ok := m.uniqueOn(c.Name); ok && !pk {
		args = append(args, "unique=True")
	}
	if name != c.Name {
		args = append(args, "db_column="+jsString(c.Name))
	}
	if c.Nullable {
		args = append(args, "blank=True", "null=True")
	}
	if d.opts.Defaults {
		args = append(args, d.dbDefault(c, class)...)
	}
	if c.Generated {
		// Django would write this column on every insert. It has no way to be
		// told otherwise without restating the expression as a GeneratedField.
		args = append(args, "editable=False")
		d.warn("%s.%s is a generated column. Django will try to write it on insert; turn it into a GeneratedField with the database's expression before saving through this model.", d.label(m), c.Name)
	}
	if c.Comment != "" {
		args = append(args, "db_comment="+jsString(ormOneLine(c.Comment)))
	}
	return class + "(" + strings.Join(args, ", ") + ")", guess
}

// dbDefault renders db_default for the defaults Django can state: a literal,
// the current time, a random UUID on PostgreSQL. An expression it cannot state
// is left to the database, which applies it whenever Django leaves the column
// out — and Django leaves out a field that has db_default and no value.
func (d *djangoGen) dbDefault(c *ormCol, class string) []string {
	if c.Generated || c.t.Array {
		return nil
	}
	def := c.def
	switch def.Kind {
	case ormDefString:
		return []string{"db_default=" + jsString(def.Text)}
	case ormDefNumber:
		switch class {
		case "models.DecimalField":
			d.use("decimal", "Decimal")
			return []string{"db_default=Decimal(" + jsString(def.Text) + ")"}
		case "models.TextField", "models.CharField":
			return []string{"db_default=" + jsString(def.Text)}
		}
		return []string{"db_default=" + def.Text}
	case ormDefBool:
		if class == "models.BooleanField" {
			if def.Bool {
				return []string{"db_default=True"}
			}
			return []string{"db_default=False"}
		}
	case ormDefNow:
		if class == "models.DateTimeField" {
			d.use("django.db.models.functions", "Now")
			return []string{"db_default=Now()"}
		}
	case ormDefUUID:
		if d.driver == DriverPostgres && class == "models.UUIDField" && strings.EqualFold(def.Text, "gen_random_uuid()") {
			d.use("django.contrib.postgres.functions", "RandomUUID")
			return []string{"db_default=RandomUUID()"}
		}
	}
	return nil
}

func djangoOnDelete(rule string) string {
	switch ormAction(rule) {
	case "CASCADE":
		return "models.CASCADE"
	case "SET NULL":
		return "models.SET_NULL"
	case "RESTRICT":
		return "models.RESTRICT"
	case "SET DEFAULT":
		return "models.SET_DEFAULT"
	}
	return "models.DO_NOTHING"
}

// dbTable is the table's name as Django has to be given it. Django has no
// schema setting on a model; the long-standing way to reach another schema is
// to close the quote Django opens, write the dot, and open the next one.
func (d *djangoGen) dbTable(m *ormTable) string {
	if !d.qualified(m) {
		return m.Name
	}
	switch d.driver {
	case DriverMySQL:
		return m.Schema + "`.`" + m.Name
	case DriverMSSQL:
		return m.Schema + "].[" + m.Name
	case DriverOracle:
		return `"` + m.Schema + `"."` + m.Name + `"`
	}
	return m.Schema + `"."` + m.Name
}

func (d *djangoGen) model(m *ormTable) string {
	claimed := d.claimed[m]
	var b strings.Builder
	fmt.Fprintf(&b, "class %s(models.Model):\n", d.names.model[m])

	// The name an index or a constraint knows a column by: its field's.
	fieldOf := func(col string) string {
		if r := claimed[col]; r != nil {
			return d.names.fwd[r]
		}
		return d.names.field[m.byCol[col]]
	}
	if len(m.PrimaryKey) > 1 {
		keys := make([]string, len(m.PrimaryKey))
		for i, col := range m.PrimaryKey {
			keys[i] = jsString(fieldOf(col))
			if r := claimed[col]; r != nil {
				keys[i] = jsString(d.names.fwd[r] + "_id")
			}
		}
		fmt.Fprintf(&b, "    pk = models.CompositePrimaryKey(%s)\n", strings.Join(keys, ", "))
	}
	if len(m.PrimaryKey) == 0 {
		d.warn("%s has no primary key. Django will assume an id column that is not there; queries that select or filter on pk will fail.", d.label(m))
		b.WriteString("    # No primary key in the database: Django will assume an \"id\" column that does not exist.\n")
	}

	for _, c := range m.cols {
		if r := claimed[c.Name]; r != nil {
			b.WriteString("    " + d.relation(m, r) + "\n")
			continue
		}
		expr, guess := d.column(m, c)
		line := fmt.Sprintf("    %s = %s", d.names.field[c], expr)
		if guess {
			line += "  # This field type is a guess."
		}
		b.WriteString(line + "\n")
	}

	b.WriteString("\n    class Meta:\n")
	fmt.Fprintf(&b, "        managed = %s\n", map[bool]string{true: "True", false: "False"}[d.opts.Managed])
	fmt.Fprintf(&b, "        db_table = %s\n", jsString(d.dbTable(m)))
	if m.Comment != "" {
		fmt.Fprintf(&b, "        db_table_comment = %s\n", jsString(ormOneLine(m.Comment)))
	}
	fields := func(cols []string, desc []bool) string {
		out := make([]string, len(cols))
		for i, col := range cols {
			out[i] = fieldOf(col)
			if i < len(desc) && desc[i] {
				out[i] = "-" + out[i]
			}
			out[i] = jsString(out[i])
		}
		return "[" + strings.Join(out, ", ") + "]"
	}
	if uniques := m.compositeUniques(); len(uniques) > 0 {
		b.WriteString("        constraints = [\n")
		for _, ix := range uniques {
			fmt.Fprintf(&b, "            models.UniqueConstraint(fields=%s, name=%s),\n", fields(ix.Columns, nil), jsString(ix.Name))
		}
		b.WriteString("        ]\n")
	}
	var indexes []string
	for _, ix := range m.indexes {
		class := "models.Index"
		if method := strings.ToLower(ix.Method); method != "" && method != "btree" {
			name := map[string]string{
				"gin": "GinIndex", "gist": "GistIndex", "brin": "BrinIndex", "hash": "HashIndex", "spgist": "SpGistIndex",
			}[method]
			if name == "" || d.driver != DriverPostgres {
				d.warn("Index %s on %s uses the %s access method, which this target does not describe; it was left out.", ix.Name, d.label(m), method)
				continue
			}
			d.use("django.contrib.postgres.indexes", name)
			class = name
		}
		args := "fields=" + fields(ix.Columns, ix.Desc)
		// Django refuses an index name longer than thirty characters; past
		// that it is left to name the index itself.
		if len(ix.Name) <= 30 && ix.Name != "" {
			args += ", name=" + jsString(ix.Name)
		}
		indexes = append(indexes, class+"("+args+")")
	}
	if len(indexes) > 0 {
		b.WriteString("        indexes = [\n")
		for _, ix := range indexes {
			b.WriteString("            " + ix + ",\n")
		}
		b.WriteString("        ]\n")
	}
	return b.String()
}

// relation renders a foreign-key column as the field Django wants in its place.
func (d *djangoGen) relation(m *ormTable, r *ormRel) string {
	col := m.byCol[r.fk.Columns[0]]
	name := d.names.fwd[r]
	target := jsString(d.names.model[r.to])
	if r.self {
		target = `"self"`
	}
	class := "models.ForeignKey"
	if r.unique {
		class = "models.OneToOneField"
	}
	args := []string{target, djangoOnDelete(r.fk.OnDelete)}
	if name+"_id" != col.Name {
		args = append(args, "db_column="+jsString(col.Name))
	}
	if ref := r.fk.RefColumns[0]; !r.to.pk[ref] {
		args = append(args, "to_field="+jsString(d.names.field[r.to.byCol[ref]]))
	}
	args = append(args, "related_name="+jsString(d.names.back[r]))
	if len(m.PrimaryKey) == 1 && m.pk[col.Name] {
		args = append(args, "primary_key=True")
	} else if _, ok := m.uniqueOn(col.Name); ok && !r.unique {
		args = append(args, "unique=True")
	}
	if col.Nullable {
		args = append(args, "blank=True", "null=True")
	}
	if col.Comment != "" {
		args = append(args, "db_comment="+jsString(ormOneLine(col.Comment)))
	}
	return fmt.Sprintf("%s = %s(%s)", name, class, strings.Join(args, ", "))
}
