package dbx

import (
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// The generators against real catalogues.
//
// The fixture tests prove what a generator writes for a given structure. These
// prove the structure is read correctly in the first place: that an enum
// column comes back as that enum, an identity column as one, a partial index
// as partial — the facts information_schema does not carry and the generators
// cannot work without.
//
// Each engine is skipped unless its DSN is set. There is deliberately no
// default address: these tests create and drop schemas, and must only ever do
// that where they were pointed.

func ormLiveDB(t *testing.T, driver Driver, env string) *sql.DB {
	t.Helper()
	dsn := os.Getenv(env)
	if dsn == "" {
		t.Skipf("set %s to run this against a real %s", env, driver)
	}
	d, err := DialectFor(driver)
	if err != nil {
		t.Fatal(err)
	}
	db, err := sql.Open(d.SQLDriverName(), d.NormaliseDSN(dsn))
	if err != nil {
		t.Skipf("%s unavailable (%s): %v", driver, env, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		t.Skipf("%s unreachable — set %s to run this (%v)", driver, env, err)
	}
	t.Cleanup(func() { db.Close() })
	return db
}

func ormExec(t *testing.T, db *sql.DB, stmts ...string) {
	t.Helper()
	for _, s := range stmts {
		if _, err := db.ExecContext(context.Background(), s); err != nil {
			t.Fatalf("seed failed: %v\n%s", err, s)
		}
	}
}

func ormGenerate(t *testing.T, s *ORMSchema, req ORMRequest) *ORMResult {
	t.Helper()
	opts, err := req.Options()
	if err != nil {
		t.Fatalf("%s options: %v", req.Target, err)
	}
	res, err := GenerateORMFiles(s, opts)
	if err != nil {
		t.Fatalf("%s: %v", req.Target, err)
	}
	return res
}

func ormMustContain(t *testing.T, what, out string, want ...string) {
	t.Helper()
	for _, w := range want {
		if !strings.Contains(out, w) {
			t.Errorf("%s is missing %q\n---\n%s", what, w, out)
		}
	}
}

func ormMustNotContain(t *testing.T, what, out string, unwanted ...string) {
	t.Helper()
	for _, w := range unwanted {
		if strings.Contains(out, w) {
			t.Errorf("%s contains %q\n---\n%s", what, w, out)
		}
	}
}

func ormTableNamed(s *ORMSchema, schema, name string) *ORMTable {
	for i := range s.Tables {
		if s.Tables[i].Schema == schema && s.Tables[i].Name == name {
			return &s.Tables[i]
		}
	}
	return nil
}

func ormColumnNamed(t *ORMTable, name string) *ORMColumn {
	if t == nil {
		return nil
	}
	for i := range t.Columns {
		if t.Columns[i].Name == name {
			return &t.Columns[i]
		}
	}
	return nil
}

func ormIndexNamed(t *ORMTable, name string) *ORMIndex {
	if t == nil {
		return nil
	}
	for i := range t.Indexes {
		if t.Indexes[i].Name == name {
			return &t.Indexes[i]
		}
	}
	return nil
}

// ormLiveShop is a shop in two schemas, in the shapes real schemas have: a
// serial key, an identity key, a composite key, a table with no key, enums in
// both schemas, a domain, arrays, a generated column, a partitioned table with
// a partition, the same table name twice, and indexes of every awkward kind.
var ormLiveShop = []string{
	`CREATE SCHEMA jd_orm_shop`,
	`CREATE SCHEMA jd_orm_stats`,
	`CREATE TYPE jd_orm_shop.order_status AS ENUM ('pending','paid','shipped','in-transit')`,
	`CREATE TYPE jd_orm_stats.event_kind AS ENUM ('page_view','click')`,
	`CREATE DOMAIN jd_orm_shop.email_address AS varchar(320)`,
	`CREATE TABLE jd_orm_shop.customers (
		id bigserial PRIMARY KEY,
		email jd_orm_shop.email_address NOT NULL UNIQUE,
		full_name text NOT NULL,
		country char(2),
		marketing_opt_in boolean NOT NULL DEFAULT false,
		tags text[] NOT NULL DEFAULT '{}',
		profile jsonb NOT NULL DEFAULT '{}',
		avatar bytea,
		external_id uuid NOT NULL DEFAULT gen_random_uuid(),
		lifetime_value numeric(12,2) NOT NULL DEFAULT 0,
		created_at timestamptz NOT NULL DEFAULT now(),
		last_seen_at timestamptz
	)`,
	`COMMENT ON TABLE jd_orm_shop.customers IS 'People who have an account in the shop'`,
	`COMMENT ON COLUMN jd_orm_shop.customers.profile IS 'Free-form preferences'`,
	`CREATE UNIQUE INDEX customers_lower_email_idx ON jd_orm_shop.customers (lower(email::text))`,
	`CREATE INDEX customers_active_idx ON jd_orm_shop.customers (last_seen_at) WHERE last_seen_at IS NOT NULL`,
	`CREATE TABLE jd_orm_shop.categories (
		id serial PRIMARY KEY,
		slug text NOT NULL UNIQUE,
		parent_id int REFERENCES jd_orm_shop.categories(id)
	)`,
	`CREATE TABLE jd_orm_shop.products (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		sku varchar(32) NOT NULL UNIQUE,
		category_id int REFERENCES jd_orm_shop.categories(id),
		price_cents integer NOT NULL CHECK (price_cents >= 0),
		attributes jsonb NOT NULL DEFAULT '{}',
		released_on date,
		updated_at timestamp(3) NOT NULL DEFAULT now()
	)`,
	`CREATE INDEX products_category_idx ON jd_orm_shop.products (category_id) INCLUDE (sku)`,
	`CREATE INDEX products_attributes_gin ON jd_orm_shop.products USING gin (attributes)`,
	`CREATE TABLE jd_orm_shop.orders (
		id bigserial PRIMARY KEY,
		customer_id bigint NOT NULL REFERENCES jd_orm_shop.customers(id) ON DELETE CASCADE,
		status jd_orm_shop.order_status NOT NULL DEFAULT 'pending',
		currency char(3) NOT NULL DEFAULT 'EUR',
		placed_at timestamptz NOT NULL DEFAULT now()
	)`,
	`CREATE INDEX orders_status_placed_idx ON jd_orm_shop.orders (status, placed_at DESC)`,
	`CREATE TABLE jd_orm_shop.order_items (
		order_id bigint NOT NULL REFERENCES jd_orm_shop.orders(id) ON DELETE CASCADE,
		line_no smallint NOT NULL,
		product_id bigint NOT NULL REFERENCES jd_orm_shop.products(id),
		quantity integer NOT NULL DEFAULT 1,
		unit_price_cents integer NOT NULL,
		total_cents integer GENERATED ALWAYS AS (quantity * unit_price_cents) STORED,
		PRIMARY KEY (order_id, line_no)
	)`,
	`CREATE TABLE jd_orm_shop.shipments (
		id serial PRIMARY KEY,
		order_id bigint NOT NULL,
		line_no smallint NOT NULL,
		category_slug text REFERENCES jd_orm_shop.categories(slug),
		tracking_code varchar(40) NOT NULL UNIQUE,
		CONSTRAINT shipments_item_fkey FOREIGN KEY (order_id, line_no)
			REFERENCES jd_orm_shop.order_items(order_id, line_no) ON DELETE CASCADE
	)`,
	`CREATE TABLE jd_orm_shop.audit_log (at timestamptz NOT NULL DEFAULT now(), action text NOT NULL, payload jsonb)`,
	`CREATE TABLE jd_orm_shop.events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name text NOT NULL)`,
	`CREATE TABLE jd_orm_shop.measurements (
		sensor_id int NOT NULL,
		taken_at timestamptz NOT NULL,
		reading double precision,
		PRIMARY KEY (sensor_id, taken_at)
	) PARTITION BY RANGE (taken_at)`,
	`CREATE TABLE jd_orm_shop.measurements_2024 PARTITION OF jd_orm_shop.measurements
		FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')`,
	`CREATE VIEW jd_orm_shop.order_summary AS
		SELECT o.id, c.email, o.status FROM jd_orm_shop.orders o JOIN jd_orm_shop.customers c ON c.id = o.customer_id`,
	`CREATE TABLE jd_orm_stats.events (
		id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		customer_id bigint REFERENCES jd_orm_shop.customers(id) ON DELETE SET NULL,
		kind jd_orm_stats.event_kind NOT NULL,
		kinds jd_orm_stats.event_kind[],
		occurred_at timestamptz NOT NULL
	)`,
	`CREATE MATERIALIZED VIEW jd_orm_stats.top_products AS
		SELECT product_id, sum(quantity) AS units FROM jd_orm_shop.order_items GROUP BY 1`,
}

var ormLiveShopDrop = []string{
	`DROP SCHEMA IF EXISTS jd_orm_stats CASCADE`,
	`DROP SCHEMA IF EXISTS jd_orm_shop CASCADE`,
}

func TestLiveORMPostgres(t *testing.T) {
	db := ormLiveDB(t, DriverPostgres, "JD_TEST_POSTGRES_DSN")
	ctx := context.Background()
	ormExec(t, db, ormLiveShopDrop...)
	t.Cleanup(func() {
		for _, s := range ormLiveShopDrop {
			_, _ = db.ExecContext(context.Background(), s)
		}
	})
	ormExec(t, db, ormLiveShop...)
	scope := ORMScope{Schemas: []string{"jd_orm_shop", "jd_orm_stats"}}

	schema, err := LoadORMSchema(ctx, db, DriverPostgres, scope)
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}
	for _, w := range schema.Warnings {
		t.Errorf("loading reported: %s", w)
	}
	if !schema.Detailed || schema.Flavor != "" {
		t.Errorf("Detailed = %v, Flavor = %q", schema.Detailed, schema.Flavor)
	}

	t.Run("the_catalogue_is_read_for_what_it_is", func(t *testing.T) {
		customers := ormTableNamed(schema, "jd_orm_shop", "customers")
		if customers == nil {
			t.Fatal("customers was not loaded")
		}
		if customers.Comment != "People who have an account in the shop" {
			t.Errorf("table comment = %q", customers.Comment)
		}
		for name, want := range map[string]string{
			// A domain reads as what it is a domain over.
			"email": "character varying(320)", "country": "character(2)", "tags": "text[]",
			"lifetime_value": "numeric(12,2)", "created_at": "timestamp with time zone",
		} {
			if c := ormColumnNamed(customers, name); c == nil || c.Type != want {
				t.Errorf("customers.%s type = %+v, want %q", name, c, want)
			}
		}
		if c := ormColumnNamed(customers, "profile"); c == nil || c.Comment != "Free-form preferences" {
			t.Errorf("customers.profile comment = %+v", c)
		}
		if ix := ormIndexNamed(customers, "customers_lower_email_idx"); ix == nil || !ix.Expression || !ix.Unique {
			t.Errorf("the expression index was not marked as one: %+v", ix)
		}
		if ix := ormIndexNamed(customers, "customers_active_idx"); ix == nil || !ix.Partial {
			t.Errorf("the partial index was not marked as one: %+v", ix)
		}

		orders := ormTableNamed(schema, "jd_orm_shop", "orders")
		if c := ormColumnNamed(orders, "status"); c == nil || c.EnumSchema != "jd_orm_shop" || c.EnumName != "order_status" {
			t.Errorf("orders.status enum = %+v", c)
		}
		if ix := ormIndexNamed(orders, "orders_status_placed_idx"); ix == nil || len(ix.Desc) != 2 || ix.Desc[0] || !ix.Desc[1] {
			t.Errorf("descending column not read: %+v", ix)
		}

		products := ormTableNamed(schema, "jd_orm_shop", "products")
		if c := ormColumnNamed(products, "id"); c == nil || c.Identity != "by default" || !c.AutoIncrement {
			t.Errorf("products.id identity = %+v", c)
		}
		if ix := ormIndexNamed(products, "products_category_idx"); ix == nil || len(ix.Columns) != 1 || ix.Columns[0] != "category_id" {
			t.Errorf("an INCLUDE column was read as a key column: %+v", ix)
		}
		if ix := ormIndexNamed(products, "products_attributes_gin"); ix == nil || ix.Method != "gin" {
			t.Errorf("gin index method = %+v", ix)
		}
		if len(products.Checks) != 1 || !strings.Contains(products.Checks[0].Definition, "price_cents >= 0") {
			t.Errorf("check constraints = %+v", products.Checks)
		}

		items := ormTableNamed(schema, "jd_orm_shop", "order_items")
		if c := ormColumnNamed(items, "total_cents"); c == nil || !c.Generated || !strings.Contains(c.GeneratedExpr, "quantity") || c.Default != "" {
			t.Errorf("generated column = %+v", c)
		}

		if m := ormTableNamed(schema, "jd_orm_shop", "measurements"); m == nil || m.Kind != ORMKindPartitioned || !strings.Contains(m.PartitionKey, "taken_at") {
			t.Errorf("partitioned table = %+v", m)
		}
		if p := ormTableNamed(schema, "jd_orm_shop", "measurements_2024"); p == nil || p.Kind != ORMKindPartition {
			t.Errorf("partition = %+v", p)
		}
		if v := ormTableNamed(schema, "jd_orm_shop", "order_summary"); v == nil || v.Kind != ORMKindView || !strings.Contains(v.CreateSQL, "SELECT") {
			t.Errorf("view = %+v", v)
		}
		if v := ormTableNamed(schema, "jd_orm_stats", "top_products"); v == nil || v.Kind != ORMKindMatView {
			t.Errorf("materialized view = %+v", v)
		}
		events := ormTableNamed(schema, "jd_orm_stats", "events")
		if c := ormColumnNamed(events, "kinds"); c == nil || c.EnumName != "event_kind" || !strings.HasSuffix(c.Type, "[]") {
			t.Errorf("an array of enums = %+v", c)
		}
	})

	t.Run("prisma", func(t *testing.T) {
		res := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma})
		ormMustContain(t, "schema.prisma", res.Schema,
			`provider = "postgresql"`,
			`schemas  = ["jd_orm_shop", "jd_orm_stats"]`,
			"model customers {",
			"id BigInt @id @default(autoincrement())",
			"email String @unique @db.VarChar(320)",
			"country String? @db.Char(2)",
			"tags String[] @default([])",
			`profile Json @default("{}")`,
			`external_id String @default(dbgenerated("gen_random_uuid()")) @db.Uuid`,
			"lifetime_value Decimal @default(0) @db.Decimal(12, 2)",
			"created_at DateTime @default(now()) @db.Timestamptz(6)",
			"status order_status @default(pending)",
			`customer customers @relation("orders_customer_id", fields: [customer_id], references: [id], onDelete: Cascade, onUpdate: NoAction)`,
			`orders orders[] @relation("orders_customer_id")`,
			"@@id([order_id, line_no])",
			// A key of two columns, and a key to a unique column that is not
			// the primary key.
			`order_item order_items @relation("shipments_order_id_line_no", fields: [order_id, line_no], references: [order_id, line_no], onDelete: Cascade, onUpdate: NoAction)`,
			`category categories? @relation("shipments_category_slug", fields: [category_slug], references: [slug], onDelete: NoAction, onUpdate: NoAction)`,
			`@@index([status, placed_at(sort: Desc)], map: "orders_status_placed_idx")`,
			`@@index([attributes], map: "products_attributes_gin", type: Gin)`,
			// The same table name in two schemas: both survive, told apart.
			"model events {", "model jd_orm_stats_events {", `@@map("events")`,
			`@@schema("jd_orm_stats")`,
			"kinds event_kind[]",
			"enum order_status {", `in_transit @map("in-transit")`,
			"@@ignore",
		)
		ormMustNotContain(t, "schema.prisma", res.Schema,
			"USER-DEFINED", "ARRAY", "measurements_2024", "model order_summary", "model top_products",
			// A unique index over an expression, or over some rows, says
			// nothing about a column.
			"last_seen_at DateTime? @unique",
		)
		if res.Counts.Tables != 10 || res.Counts.Enums != 2 || res.Counts.Views != 0 || res.Counts.Relations != 8 {
			t.Errorf("counts = %+v", res.Counts)
		}
		joined := strings.Join(res.Warnings, "\n")
		ormMustContain(t, "warnings", joined,
			"One partition was left out", "customers_lower_email_idx", "customers_active_idx",
			"jd_orm_shop.audit_log has no primary key")
	})

	t.Run("drizzle", func(t *testing.T) {
		res := ormGenerate(t, schema, ORMRequest{Target: ORMDrizzle, Views: ormYes()})
		ormMustContain(t, "schema.ts", res.Schema,
			`from "drizzle-orm/pg-core"`,
			`export const jd_orm_shop = pgSchema("jd_orm_shop")`,
			`export const order_status = jd_orm_shop.enum("order_status", ["pending", "paid", "shipped", "in-transit"])`,
			`id: bigserial("id", { mode: "number" }).primaryKey().notNull(),`,
			`email: varchar("email", { length: 320 }).notNull().unique(),`,
			`tags: text("tags").array().notNull().default([]),`,
			`external_id: uuid("external_id").notNull().defaultRandom(),`,
			`created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),`,
			`status: order_status("status").notNull().default("pending"),`,
			`.references(() => customers.id, { onDelete: "cascade" })`,
			`parent_id: integer("parent_id").references((): AnyPgColumn => categories.id),`,
			`id: bigint("id", { mode: "number" }).primaryKey().notNull().generatedByDefaultAsIdentity(),`,
			"generatedAlwaysAs(sql`(quantity * unit_price_cents)`)",
			"primaryKey({ columns: [table.order_id, table.line_no] })",
			`foreignKey({ columns: [table.order_id, table.line_no], foreignColumns: [order_items.order_id, order_items.line_no], name: "shipments_item_fkey" }).onDelete("cascade")`,
			`category_slug: text("category_slug").references(() => categories.slug),`,
			`index("orders_status_placed_idx").on(table.status, table.placed_at.desc())`,
			`index("products_attributes_gin").using("gin", table.attributes)`,
			`jd_orm_shop.view("order_summary", {`, `jd_orm_stats.materializedView("top_products", {`, ".existing()",
			"export const customersRelations = relations(customers, ({ many }) => ({",
			`orders: many(orders, { relationName: "orders_customer_id" }),`,
			"export const ordersRelations = relations(orders, ({ one, many }) => ({",
		)
		ormMustNotContain(t, "schema.ts", res.Schema, "measurements_2024", "user-defined", "USER-DEFINED")
		if res.Counts.Views != 2 {
			t.Errorf("views counted = %d, want 2", res.Counts.Views)
		}
	})

	t.Run("every_target_generates", func(t *testing.T) {
		for _, target := range ORMTargets() {
			res := ormGenerate(t, schema, ORMRequest{Target: target})
			if strings.TrimSpace(res.Schema) == "" {
				t.Errorf("%s produced nothing", target)
			}
			for _, f := range res.Files {
				ormMustNotContain(t, string(target)+"/"+f.Filename, f.Content, "USER-DEFINED")
			}
		}
	})

	// The SQL target has to be good enough to rebuild the schema: drop both
	// schemas, run the script, and everything read back must generate the same
	// Prisma schema as before. Only the partition is allowed to be missing —
	// the script says it does not create those.
	t.Run("the_sql_target_rebuilds_the_schema", func(t *testing.T) {
		before := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma, Views: ormYes()})
		script := ormGenerate(t, schema, ORMRequest{Target: ORMSQL, Views: ormYes()})
		ormExec(t, db, ormLiveShopDrop...)
		ormRunScript(t, db, script.Schema)
		rebuilt, err := LoadORMSchema(ctx, db, DriverPostgres, scope)
		if err != nil {
			t.Fatalf("LoadORMSchema after rebuild: %v", err)
		}
		after := ormGenerate(t, rebuilt, ORMRequest{Target: ORMPrisma, Views: ormYes()})
		if before.Schema != after.Schema {
			t.Errorf("the rebuilt database generates a different Prisma schema.\n--- before\n%s\n--- after\n%s", before.Schema, after.Schema)
		}
	})

	t.Run("selected_tables", func(t *testing.T) {
		narrowed, err := LoadORMSchema(ctx, db, DriverPostgres, ORMScope{
			Schemas: scope.Schemas, Tables: []string{"customers", "jd_orm_shop.orders"},
		})
		if err != nil {
			t.Fatalf("LoadORMSchema: %v", err)
		}
		res := ormGenerate(t, narrowed, ORMRequest{Target: ORMPrisma, Tables: []string{"customers", "jd_orm_shop.orders"}})
		ormMustContain(t, "schema.prisma", res.Schema, "model customers {", "model orders {", `@relation("orders_customer_id"`)
		ormMustNotContain(t, "schema.prisma", res.Schema, "model order_items", "model products", "order_items[]")
		// Leaving order_items and stats.events out was the caller's choice;
		// the relations that went with them are not worth a sentence each.
		ormMustNotContain(t, "warnings", strings.Join(res.Warnings, "\n"), "references", "relation was left out")
		if _, err := LoadORMSchema(ctx, db, DriverPostgres, ORMScope{Schemas: scope.Schemas, Tables: []string{"nope"}}); err == nil {
			t.Error("a table that is not there was accepted")
		}
	})

	// A generation that will not emit views does not read them, and writes
	// what it would have written had it read them.
	t.Run("views_are_read_only_when_wanted", func(t *testing.T) {
		req := ORMRequest{Target: ORMPrisma, Schemas: scope.Schemas}
		asked, err := req.Scope(DriverPostgres, "")
		if err != nil || !asked.SkipViews {
			t.Fatalf("scope = %+v (%v), want views skipped", asked, err)
		}
		lean, err := LoadORMSchema(ctx, db, DriverPostgres, asked)
		if err != nil {
			t.Fatalf("LoadORMSchema: %v", err)
		}
		for _, name := range []string{"order_summary", "top_products"} {
			var found *ORMTable
			for i := range lean.Tables {
				if lean.Tables[i].Name == name {
					found = &lean.Tables[i]
				}
			}
			if found == nil || len(found.Columns) != 0 || (found.Kind != ORMKindView && found.Kind != ORMKindMatView) {
				t.Errorf("%s = %+v, want a view that was listed and not read", name, found)
			}
		}
		// Read afresh: the rebuild above has changed what is there.
		full, err := LoadORMSchema(ctx, db, DriverPostgres, scope)
		if err != nil {
			t.Fatalf("LoadORMSchema: %v", err)
		}
		want := ormGenerate(t, full, req)
		got := ormGenerate(t, lean, req)
		if got.Schema != want.Schema || strings.Join(got.Warnings, "\n") != strings.Join(want.Warnings, "\n") {
			t.Errorf("the schema read without its views generates differently.\n--- with\n%s\n--- without\n%s", want.Schema, got.Schema)
		}
	})
}

// MySQL and MariaDB print defaults differently and keep auto-increment in a
// column of its own; both have to read the same.
func TestLiveORMMySQL(t *testing.T) {
	for _, env := range []string{"JD_TEST_MYSQL_DSN", "JD_TEST_ORM_MYSQL8_DSN"} {
		t.Run(env, func(t *testing.T) {
			db := ormLiveDB(t, DriverMySQL, env)
			ctx := context.Background()
			drop := []string{
				`DROP VIEW IF EXISTS jd_orm_published`,
				`DROP TABLE IF EXISTS jd_orm_posts`, `DROP TABLE IF EXISTS jd_orm_authors`,
			}
			ormExec(t, db, drop...)
			t.Cleanup(func() {
				for _, s := range drop {
					_, _ = db.ExecContext(context.Background(), s)
				}
			})
			ormExec(t, db,
				`CREATE TABLE jd_orm_authors (
					id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
					handle VARCHAR(40) NOT NULL UNIQUE,
					is_staff TINYINT(1) NOT NULL DEFAULT 0,
					joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
				) ENGINE=InnoDB`,
				`CREATE TABLE jd_orm_posts (
					id BIGINT AUTO_INCREMENT PRIMARY KEY,
					author_id INT UNSIGNED NOT NULL,
					title VARCHAR(200) NOT NULL,
					body MEDIUMTEXT,
					status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
					views INT UNSIGNED NOT NULL DEFAULT 0,
					rating DECIMAL(4,2),
					meta JSON,
					slug_len INT GENERATED ALWAYS AS (CHAR_LENGTH(title)) STORED,
					updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
					CONSTRAINT jd_orm_posts_author FOREIGN KEY (author_id) REFERENCES jd_orm_authors(id) ON DELETE CASCADE,
					INDEX jd_orm_posts_status (status, updated_at),
					UNIQUE INDEX jd_orm_posts_title_prefix (title(20)),
					FULLTEXT INDEX jd_orm_posts_body (body)
				) ENGINE=InnoDB`,
				`CREATE VIEW jd_orm_published AS SELECT id, title FROM jd_orm_posts WHERE status = 'published'`,
			)
			var database string
			if err := db.QueryRowContext(ctx, `SELECT DATABASE()`).Scan(&database); err != nil {
				t.Fatal(err)
			}
			tables := []string{"jd_orm_authors", "jd_orm_posts", "jd_orm_published"}
			schema, err := LoadORMSchema(ctx, db, DriverMySQL, ORMScope{Schemas: []string{database}, Tables: tables})
			if err != nil {
				t.Fatalf("LoadORMSchema: %v", err)
			}
			for _, w := range schema.Warnings {
				t.Errorf("loading reported: %s", w)
			}
			if !schema.Detailed {
				t.Error("the catalogue's column detail was not read")
			}

			posts := ormTableNamed(schema, database, "jd_orm_posts")
			if c := ormColumnNamed(posts, "id"); c == nil || !c.AutoIncrement {
				t.Errorf("posts.id auto-increment = %+v", c)
			}
			if c := ormColumnNamed(posts, "updated_at"); c == nil || !c.OnUpdateNow {
				t.Errorf("posts.updated_at ON UPDATE = %+v", c)
			}
			if c := ormColumnNamed(posts, "slug_len"); c == nil || !c.Generated {
				t.Errorf("posts.slug_len generated = %+v", c)
			}
			if ix := ormIndexNamed(posts, "jd_orm_posts_body"); ix == nil || ix.Method != "fulltext" {
				t.Errorf("full-text index = %+v", ix)
			}
			if ix := ormIndexNamed(posts, "jd_orm_posts_title_prefix"); ix == nil || !ix.Expression {
				t.Errorf("prefix index was not marked: %+v", ix)
			}

			res := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma, Tables: tables})
			ormMustContain(t, "schema.prisma", res.Schema,
				`provider = "mysql"`,
				"id Int @id @default(autoincrement()) @db.UnsignedInt",
				"is_staff Boolean @default(false)",
				"joined_at DateTime @default(now()) @db.DateTime(0)",
				"status jd_orm_posts_status @default(draft)",
				"views Int @default(0) @db.UnsignedInt",
				"rating Decimal? @db.Decimal(4, 2)",
				"updated_at DateTime @default(now()) @db.Timestamp(0)",
				`@relation("jd_orm_posts_author_id", fields: [author_id], references: [id], onDelete: Cascade`,
				"enum jd_orm_posts_status {",
			)
			ormMustNotContain(t, "schema.prisma", res.Schema, "title String @unique", "model jd_orm_published")

			drizzle := ormGenerate(t, schema, ORMRequest{Target: ORMDrizzle, Tables: tables, Views: ormYes()})
			ormMustContain(t, "schema.ts", drizzle.Schema,
				`from "drizzle-orm/mysql-core"`,
				`id: int("id", { unsigned: true }).primaryKey().notNull().autoincrement(),`,
				`is_staff: boolean("is_staff").notNull().default(false),`,
				`status: mysqlEnum("status", ["draft", "published", "archived"]).notNull().default("draft"),`,
				`updated_at: timestamp("updated_at").notNull().defaultNow().onUpdateNow(),`,
				`mysqlView("jd_orm_published", {`,
			)

			for _, target := range ORMTargets() {
				if ORMUnsupported(target, DriverMySQL) != "" {
					continue
				}
				if out := ormGenerate(t, schema, ORMRequest{Target: target, Tables: tables}); strings.TrimSpace(out.Schema) == "" {
					t.Errorf("%s produced nothing", target)
				}
			}
		})
	}
}

// MySQL prints a string default bare, so 'rgb(0,0,0)' and (json_object()) look
// alike in the catalogue and only EXTRA tells them apart; MariaDB quotes the
// first and prints the second bare. Both have to come out as what they are —
// and written back as SQL, both have to be accepted and mean the same again.
func TestLiveORMMySQLDefaults(t *testing.T) {
	for _, env := range []string{"JD_TEST_MYSQL_DSN", "JD_TEST_ORM_MYSQL8_DSN"} {
		t.Run(env, func(t *testing.T) {
			db := ormLiveDB(t, DriverMySQL, env)
			ctx := context.Background()
			drop := []string{`DROP TABLE IF EXISTS jd_orm_looks`, `DROP TABLE IF EXISTS jd_orm_looks_copy`}
			ormExec(t, db, drop...)
			t.Cleanup(func() {
				for _, s := range drop {
					_, _ = db.ExecContext(context.Background(), s)
				}
			})
			ormExec(t, db, `CREATE TABLE jd_orm_looks (
				id INT PRIMARY KEY,
				colour VARCHAR(32) NOT NULL DEFAULT 'rgb(0,0,0)',
				title VARCHAR(32) NOT NULL DEFAULT 'Untitled (1)',
				path VARCHAR(64) NOT NULL DEFAULT 'C:\\it''s\\',
				word VARCHAR(16) NOT NULL DEFAULT 'now',
				flag VARCHAR(16) NOT NULL DEFAULT 'true',
				code VARCHAR(16) NOT NULL DEFAULT '007',
				born DATE NOT NULL DEFAULT '2020-01-02',
				details JSON DEFAULT (JSON_OBJECT()),
				token VARCHAR(36) NOT NULL DEFAULT (UUID()),
				sum INT NOT NULL DEFAULT (1 + 1),
				seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
				audience ENUM('Public','Back\\slash') NOT NULL DEFAULT 'Public'
			) ENGINE=InnoDB`)
			var database string
			if err := db.QueryRowContext(ctx, `SELECT DATABASE()`).Scan(&database); err != nil {
				t.Fatal(err)
			}
			load := func(table string) *ORMSchema {
				t.Helper()
				schema, err := LoadORMSchema(ctx, db, DriverMySQL, ORMScope{Schemas: []string{database}, Tables: []string{table}})
				if err != nil {
					t.Fatalf("LoadORMSchema: %v", err)
				}
				for _, w := range schema.Warnings {
					t.Errorf("loading reported: %s", w)
				}
				return schema
			}
			schema := load("jd_orm_looks")
			req := ORMRequest{Target: ORMPrisma, Tables: []string{"jd_orm_looks"}}

			prisma := ormGenerate(t, schema, req).Schema
			ormMustContain(t, "schema.prisma", prisma,
				`colour String @default("rgb(0,0,0)") @db.VarChar(32)`,
				`title String @default("Untitled (1)") @db.VarChar(32)`,
				`path String @default("C:\\it's\\") @db.VarChar(64)`,
				`word String @default("now") @db.VarChar(16)`,
				`flag String @default("true") @db.VarChar(16)`,
				`code String @default("007") @db.VarChar(16)`,
				`@default(dbgenerated("(json_object())"))`,
				`token String @default(dbgenerated("(uuid())")) @db.VarChar(36)`,
				`sum Int @default(dbgenerated("(1 + 1)"))`,
				"seen DateTime @default(now()) @db.DateTime(0)",
				"audience jd_orm_looks_audience @default(Public)",
				`Back_slash @map("Back\\slash")`,
			)
			ormMustNotContain(t, "schema.prisma", prisma, `dbgenerated("rgb(0,0,0)")`, `dbgenerated("json_object()")`, `dbgenerated("now")`)

			req.Target = ORMGorm
			ormMustContain(t, "models.go", ormGenerate(t, schema, req).Schema,
				`type:enum('Public','Back\\\\slash')`, `default:'rgb(0,0,0)'`, `default:(json_object())`)

			// The same table again, assembled from what was read instead of
			// copied from the engine, defaults written back as SQL.
			copied := *schema
			copied.Tables = append([]ORMTable(nil), schema.Tables...)
			copied.Tables[0].Name, copied.Tables[0].CreateSQL = "jd_orm_looks_copy", ""
			req.Target = ORMSQL
			ormRunScript(t, db, ormGenerate(t, &copied, req).Schema)
			again := ormTableNamed(load("jd_orm_looks_copy"), database, "jd_orm_looks_copy")
			for _, c := range schema.Tables[0].Columns {
				twin := ormColumnNamed(again, c.Name)
				if twin == nil || twin.Default != c.Default || twin.DefaultExpr != c.DefaultExpr || twin.Type != c.Type {
					t.Errorf("%s came back as %+v, was %+v", c.Name, twin, c)
				}
			}
		})
	}
}

func TestLiveORMSQLite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "orm.db")
	db, err := sql.Open("sqlite", sqliteDialect{}.NormaliseDSN(path))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Close() })
	ormExec(t, db,
		`CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT, score REAL DEFAULT 1.5)`,
		`CREATE TABLE notes (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
			title VARCHAR(120) NOT NULL DEFAULT 'untitled',
			pinned BOOLEAN NOT NULL DEFAULT 0,
			payload JSON,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX idx_notes_user ON notes(user_id)`,
		`CREATE INDEX idx_notes_pinned ON notes(title) WHERE pinned = 1`,
		`CREATE INDEX idx_notes_lower ON notes(lower(title))`,
		`CREATE VIEW note_titles AS SELECT id, title FROM notes`,
	)
	ctx := context.Background()
	schema, err := LoadORMSchema(ctx, db, DriverSQLite, ORMScope{})
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}
	for _, w := range schema.Warnings {
		t.Errorf("loading reported: %s", w)
	}
	notes := ormTableNamed(schema, "main", "notes")
	if ix := ormIndexNamed(notes, "idx_notes_pinned"); ix == nil || !ix.Partial {
		t.Errorf("partial index = %+v", ix)
	}
	if ix := ormIndexNamed(notes, "idx_notes_lower"); ix == nil || !ix.Expression {
		t.Errorf("expression index = %+v", ix)
	}

	prisma := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma})
	ormMustContain(t, "schema.prisma", prisma.Schema,
		`provider = "sqlite"`,
		"id Int @id @default(autoincrement())",
		"email String @unique",
		`title String @default("untitled")`,
		"pinned Boolean @default(false)",
		"created_at DateTime @default(now())",
		// REFERENCES users, with no column: the parent's key is filled in.
		`user users @relation("notes_user_id", fields: [user_id], references: [id], onDelete: Cascade`,
		`@@index([user_id], map: "idx_notes_user")`,
	)
	ormMustNotContain(t, "schema.prisma", prisma.Schema, "idx_notes_pinned", "idx_notes_lower", "note_titles")

	drizzle := ormGenerate(t, schema, ORMRequest{Target: ORMDrizzle})
	ormMustContain(t, "schema.ts", drizzle.Schema,
		`id: integer("id").primaryKey({ autoIncrement: true }).notNull(),`,
		`id: integer("id").primaryKey().notNull(),`,
		`pinned: integer("pinned", { mode: "boolean" }).notNull().default(false),`,
		"created_at: text(\"created_at\").notNull().default(sql`CURRENT_TIMESTAMP`),",
		`user_id: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),`,
	)
	for _, target := range ORMTargets() {
		if out := ormGenerate(t, schema, ORMRequest{Target: target}); strings.TrimSpace(out.Schema) == "" {
			t.Errorf("%s produced nothing", target)
		}
	}
}

// ClickHouse has types and no relations. The type targets and the SQL target
// read it; the relational mappers refuse it with a reason.
func TestLiveORMClickHouse(t *testing.T) {
	db := ormLiveDB(t, DriverClickHouse, "JD_TEST_CLICKHOUSE_DSN")
	ctx := context.Background()
	drop := `DROP TABLE IF EXISTS jd_orm_page_views`
	ormExec(t, db, drop)
	t.Cleanup(func() { _, _ = db.ExecContext(context.Background(), drop) })
	ormExec(t, db, `CREATE TABLE jd_orm_page_views (
		ts DateTime, user_id UInt64, path String, country LowCardinality(String),
		referrer Nullable(String), tags Array(String), device Enum8('desktop' = 1, 'mobile' = 2),
		revenue Decimal(18, 4), session UUID DEFAULT generateUUIDv4()
	) ENGINE = MergeTree ORDER BY (ts, user_id)`)
	var database string
	if err := db.QueryRowContext(ctx, `SELECT currentDatabase()`).Scan(&database); err != nil {
		t.Fatal(err)
	}
	scope, err := ORMRequest{Target: ORMSQL, Tables: []string{"jd_orm_page_views"}}.Scope(DriverClickHouse, database)
	if err != nil {
		t.Fatal(err)
	}
	schema, err := LoadORMSchema(ctx, db, DriverClickHouse, scope)
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}

	ts := ormGenerate(t, schema, ORMRequest{Target: ORMTypeScript})
	ormMustContain(t, "types.ts", ts.Schema,
		`export type JdOrmPageViewsDevice = "desktop" | "mobile"`,
		"user_id: string", "referrer: string | null", "tags: string[]", "device: JdOrmPageViewsDevice", "revenue: string")
	sqlOut := ormGenerate(t, schema, ORMRequest{Target: ORMSQL})
	ormMustContain(t, "schema.sql", sqlOut.Schema, "ENGINE = MergeTree", "ORDER BY (ts, user_id)", "LowCardinality(String)")

	opts, _ := ORMRequest{Target: ORMPrisma}.Options()
	if _, err := GenerateORMFiles(schema, opts); err == nil || !strings.Contains(err.Error(), "Prisma has no connector for ClickHouse") {
		t.Errorf("Prisma for ClickHouse was not refused with its reason: %v", err)
	}
}

// ormLiveSQLServerView is kept by the server exactly as it is sent, which is
// what lets the test ask for it back word for word.
const ormLiveSQLServerView = `CREATE VIEW jd_orm.open_accounts AS
SELECT id, name FROM jd_orm.accounts WHERE active = 1 AND name <> 'it''s closed'`

// SQL Server keeps identity, computed columns, filtered indexes and INCLUDE
// columns in sys.* views the shared introspection does not read.
func TestLiveORMSQLServer(t *testing.T) {
	db := ormLiveDB(t, DriverMSSQL, "JD_TEST_ORM_MSSQL_DSN")
	ctx := context.Background()
	drop := []string{
		`IF OBJECT_ID('jd_orm.open_accounts', 'V') IS NOT NULL DROP VIEW jd_orm.open_accounts`,
		`IF OBJECT_ID('jd_orm.transfers', 'U') IS NOT NULL DROP TABLE jd_orm.transfers`,
		`IF OBJECT_ID('jd_orm.accounts', 'U') IS NOT NULL DROP TABLE jd_orm.accounts`,
	}
	ormExec(t, db, `IF SCHEMA_ID('jd_orm') IS NULL EXEC('CREATE SCHEMA jd_orm')`)
	ormExec(t, db, drop...)
	t.Cleanup(func() {
		for _, s := range append(drop, `IF SCHEMA_ID('jd_orm') IS NOT NULL DROP SCHEMA jd_orm`) {
			_, _ = db.ExecContext(context.Background(), s)
		}
	})
	ormExec(t, db,
		`CREATE TABLE jd_orm.accounts (
			id INT IDENTITY(1,1) CONSTRAINT PK_jd_orm_accounts PRIMARY KEY,
			guid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
			name NVARCHAR(200) NOT NULL,
			notes NVARCHAR(MAX) NULL,
			active BIT NOT NULL DEFAULT 1,
			level TINYINT NOT NULL DEFAULT 0,
			balance MONEY NULL,
			credit DECIMAL(18,2) NOT NULL DEFAULT 0,
			photo VARBINARY(MAX) NULL,
			created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
			seen_at DATETIMEOFFSET NULL,
			doubled AS (credit * 2),
			version ROWVERSION
		)`,
		`CREATE UNIQUE INDEX UQ_jd_orm_accounts_guid ON jd_orm.accounts(guid)`,
		`CREATE INDEX IX_jd_orm_accounts_name ON jd_orm.accounts(name) INCLUDE (active)`,
		`CREATE INDEX IX_jd_orm_accounts_level ON jd_orm.accounts(level) WHERE active = 1`,
		`CREATE TABLE jd_orm.transfers (
			id BIGINT IDENTITY(1,1) CONSTRAINT PK_jd_orm_transfers PRIMARY KEY,
			from_account INT NOT NULL CONSTRAINT FK_jd_orm_from REFERENCES jd_orm.accounts(id) ON DELETE CASCADE,
			to_account INT NULL CONSTRAINT FK_jd_orm_to REFERENCES jd_orm.accounts(id),
			amount DECIMAL(18,2) NOT NULL,
			memo VARCHAR(255) NOT NULL DEFAULT ''
		)`,
		ormLiveSQLServerView,
	)
	scope := ORMScope{Schemas: []string{"jd_orm"}}
	schema, err := LoadORMSchema(ctx, db, DriverMSSQL, scope)
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}
	for _, w := range schema.Warnings {
		t.Errorf("loading reported: %s", w)
	}
	if !schema.Detailed {
		t.Error("identity and computed columns were not read")
	}
	accounts := ormTableNamed(schema, "jd_orm", "accounts")
	if c := ormColumnNamed(accounts, "id"); c == nil || !c.AutoIncrement {
		t.Errorf("accounts.id identity = %+v", c)
	}
	if c := ormColumnNamed(accounts, "doubled"); c == nil || !c.Generated || !strings.Contains(c.GeneratedExpr, "credit") {
		t.Errorf("computed column = %+v", c)
	}
	if ix := ormIndexNamed(accounts, "IX_jd_orm_accounts_name"); ix == nil || len(ix.Columns) != 1 || ix.Columns[0] != "name" {
		t.Errorf("an INCLUDE column was read as a key column: %+v", ix)
	}
	if ix := ormIndexNamed(accounts, "IX_jd_orm_accounts_level"); ix == nil || !ix.Partial {
		t.Errorf("filtered index = %+v", ix)
	}

	prismaOf := func(s *ORMSchema) string { return ormGenerate(t, s, ORMRequest{Target: ORMPrisma}).Schema }
	before := prismaOf(schema)
	ormMustContain(t, "schema.prisma", before,
		`provider = "sqlserver"`,
		"id Int @id @default(autoincrement())",
		`guid String @unique(map: "UQ_jd_orm_accounts_guid") @default(dbgenerated("newid()")) @db.UniqueIdentifier`,
		"name String @db.NVarChar(200)",
		"notes String? @db.NVarChar(Max)",
		"active Boolean @default(true)",
		"level Int @default(0) @db.TinyInt",
		"balance Float? @db.Money",
		"credit Decimal @default(0) @db.Decimal(18, 2)",
		"photo Bytes? @db.VarBinary(Max)",
		"created_at DateTime @default(now())",
		"seen_at DateTime? @db.DateTimeOffset",
		// Two keys to the same parent, neither with an _id to drop: the
		// relation is named after its column.
		`from_account_ref accounts @relation("transfers_from_account", fields: [from_account], references: [id], onDelete: Cascade, onUpdate: NoAction)`,
		`to_account_ref accounts? @relation("transfers_to_account", fields: [to_account], references: [id], onDelete: NoAction, onUpdate: NoAction)`,
		`version Unsupported("timestamp")`,
		`memo String @default("") @db.VarChar(255)`,
		`@@index([name], map: "IX_jd_orm_accounts_name")`,
	)
	ormMustNotContain(t, "schema.prisma", before, "IX_jd_orm_accounts_level")

	// A view is in the script as the statement SQL Server kept for it, not as
	// a table with the view's columns. The guarded script is run from nothing
	// as one batch — which CREATE VIEW only survives inside EXEC — and then
	// again over what the first run made, statement by statement.
	t.Run("views_come_back_as_views", func(t *testing.T) {
		req := ORMRequest{Target: ORMSQL, Schema: "jd_orm", Views: ormYes(), IfNotExists: ormYes()}
		asked, err := req.Scope(DriverMSSQL, "")
		if err != nil {
			t.Fatal(err)
		}
		read := func() *ORMSchema {
			t.Helper()
			s, err := LoadORMSchema(ctx, db, DriverMSSQL, asked)
			if err != nil {
				t.Fatalf("LoadORMSchema: %v", err)
			}
			for _, w := range s.Warnings {
				t.Errorf("loading reported: %s", w)
			}
			return s
		}
		withViews := read()
		view := ormTableNamed(withViews, "jd_orm", "open_accounts")
		if view == nil || view.Kind != ORMKindView || strings.TrimSpace(view.CreateSQL) != ormLiveSQLServerView {
			t.Fatalf("view = %+v, want the statement that made it", view)
		}
		prismaOf := func(s *ORMSchema) string {
			return ormGenerate(t, s, ORMRequest{Target: ORMPrisma, Views: ormYes()}).Schema
		}
		before := prismaOf(withViews)
		ormMustContain(t, "schema.prisma", before, "view open_accounts {")

		script := ormGenerate(t, withViews, req)
		ormMustContain(t, "schema.sql", script.Schema,
			"IF OBJECT_ID(N'[jd_orm].[open_accounts]', N'V') IS NULL\nEXEC(N'"+strings.ReplaceAll(ormLiveSQLServerView, "'", "''")+"');")
		ormMustNotContain(t, "schema.sql", script.Schema, "CREATE TABLE [jd_orm].[open_accounts]")
		if script.Counts.Views != 1 || script.Counts.Tables != 2 {
			t.Errorf("counts = %+v", script.Counts)
		}
		for _, w := range script.Warnings {
			if strings.Contains(w, "open_accounts") {
				t.Errorf("the view was not written: %s", w)
			}
		}

		ormExec(t, db, drop...)
		if _, err := db.ExecContext(ctx, script.Schema); err != nil {
			t.Fatalf("the script does not run as one batch: %v\n%s", err, script.Schema)
		}
		ormRunScript(t, db, script.Schema)
		if _, err := db.ExecContext(ctx, `INSERT INTO jd_orm.accounts (name, active) VALUES (N'kept', 1), (N'it''s closed', 1), (N'gone', 0)`); err != nil {
			t.Fatal(err)
		}
		var open int
		if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM jd_orm.open_accounts`).Scan(&open); err != nil || open != 1 {
			t.Errorf("the rebuilt view answers %d rows (%v), want 1", open, err)
		}
		if after := prismaOf(read()); after != before {
			t.Errorf("the rebuilt database generates a different Prisma schema.\n--- before\n%s\n--- after\n%s", before, after)
		}
	})

	// Drop the tables, run the generated script, and the same Prisma schema
	// has to come back out.
	script := ormGenerate(t, schema, ORMRequest{Target: ORMSQL})
	ormExec(t, db, drop...)
	ormRunScript(t, db, script.Schema)
	rebuilt, err := LoadORMSchema(ctx, db, DriverMSSQL, scope)
	if err != nil {
		t.Fatalf("LoadORMSchema after rebuild: %v", err)
	}
	if after := prismaOf(rebuilt); after != before {
		t.Errorf("the rebuilt database generates a different Prisma schema.\n--- before\n%s\n--- after\n%s", before, after)
	}

	for _, target := range ORMTargets() {
		if ORMUnsupported(target, DriverMSSQL) != "" {
			continue
		}
		if out := ormGenerate(t, schema, ORMRequest{Target: target}); strings.TrimSpace(out.Schema) == "" {
			t.Errorf("%s produced nothing", target)
		}
	}
}

// Oracle has one numeric type, shouts its names, and keeps an identity
// column's sequence in its default.
func TestLiveORMOracle(t *testing.T) {
	db := ormLiveDB(t, DriverOracle, "JD_TEST_ORM_ORACLE_DSN")
	ctx := context.Background()
	drop := func() {
		for _, s := range []string{
			`DROP VIEW JD_ORM_ACTIVE_CUSTOMERS`, `DROP TABLE JD_ORM_ORDERS PURGE`, `DROP TABLE JD_ORM_CUSTOMERS PURGE`,
		} {
			_, _ = db.ExecContext(context.Background(), s)
		}
	}
	drop()
	t.Cleanup(drop)
	ormExec(t, db,
		`CREATE TABLE JD_ORM_CUSTOMERS (
			ID NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			EMAIL VARCHAR2(255) NOT NULL CONSTRAINT JD_ORM_CUSTOMERS_EMAIL_UK UNIQUE,
			FULL_NAME NVARCHAR2(200),
			BALANCE NUMBER(18,2) DEFAULT 0 NOT NULL,
			POINTS NUMBER,
			NOTES CLOB,
			TOKEN RAW(16),
			STATE CHAR(1) DEFAULT 'A' NOT NULL,
			CREATED DATE DEFAULT SYSDATE NOT NULL,
			UPDATED TIMESTAMP(6) WITH TIME ZONE,
			KEPT_FOR INTERVAL DAY(2) TO SECOND(6)
		)`,
		`CREATE TABLE JD_ORM_ORDERS (
			ID NUMBER(10,0) PRIMARY KEY,
			CUSTOMER_ID NUMBER(10,0) NOT NULL
				CONSTRAINT JD_ORM_ORDERS_CUSTOMER_FK REFERENCES JD_ORM_CUSTOMERS(ID) ON DELETE CASCADE,
			TOTAL NUMBER(12,2) NOT NULL,
			PLACED TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
		)`,
		`CREATE VIEW JD_ORM_ACTIVE_CUSTOMERS AS SELECT ID, EMAIL FROM JD_ORM_CUSTOMERS WHERE STATE = 'A'`,
	)
	var owner string
	if err := db.QueryRowContext(ctx, `SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM dual`).Scan(&owner); err != nil {
		t.Fatal(err)
	}
	tables := []string{"JD_ORM_CUSTOMERS", "JD_ORM_ORDERS"}
	schema, err := LoadORMSchema(ctx, db, DriverOracle, ORMScope{Schemas: []string{owner}, Tables: tables, Statements: true})
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}
	customers := ormTableNamed(schema, owner, "JD_ORM_CUSTOMERS")
	if customers == nil {
		t.Fatalf("customers was not loaded: %+v", schema.Tables)
	}
	for name, want := range map[string]string{
		"ID": "NUMBER(10,0)", "EMAIL": "VARCHAR2(255)", "POINTS": "NUMBER", "NOTES": "CLOB", "TOKEN": "RAW(16)",
		"CREATED": "DATE", "UPDATED": "TIMESTAMP(6) WITH TIME ZONE", "KEPT_FOR": "INTERVAL DAY(2) TO SECOND(6)",
	} {
		if c := ormColumnNamed(customers, name); c == nil || c.Type != want {
			t.Errorf("%s type = %+v, want %q", name, c, want)
		}
	}

	ts := ormGenerate(t, schema, ORMRequest{Target: ORMTypeScript, Tables: tables})
	ormMustContain(t, "types.ts", ts.Schema,
		"export interface JdOrmCustomer {", "ID: string", "EMAIL: string", "FULL_NAME: string | null",
		"BALANCE: string", "POINTS: string | null", "CREATED: string")

	typeorm := ormGenerate(t, schema, ORMRequest{Target: ORMTypeORM, Tables: tables})
	ormMustContain(t, "entities.ts", typeorm.Schema,
		`@Entity("JD_ORM_CUSTOMERS")`,
		// The identity column's default is its sequence, which is how it is
		// recognised as the generated key.
		`@PrimaryGeneratedColumn({ type: "number" })`,
		`@Column({ type: "varchar2", length: 255 })`,
		// 200 characters, not the 400 bytes they occupy.
		`@Column({ type: "nvarchar2", length: 200, nullable: true })`,
		`@Column({ type: "number", precision: 18, scale: 2, default: 0 })`,
		`@Column({ type: "date", default: () => "SYSDATE" })`,
		`@ManyToOne(() => JdOrmCustomer, (other) => other.JD_ORM_ORDERS, { onDelete: "CASCADE" })`,
		"CUSTOMER!: Relation<JdOrmCustomer>",
		"JD_ORM_ORDERS!: Relation<JdOrmOrder>[]",
	)
	// The primary key's own index is not a second unique constraint.
	ormMustNotContain(t, "entities.ts", typeorm.Schema, `["ID"], { unique: true }`)

	sqlOut := ormGenerate(t, schema, ORMRequest{Target: ORMSQL, Tables: tables})
	ormMustContain(t, "schema.sql", sqlOut.Schema, "JD_ORM_CUSTOMERS", "JD_ORM_ORDERS", "VARCHAR2(255)")

	// A view's statement is asked of DBMS_METADATA as a view. Asked as a table
	// it is not found, and what used to stand in was a CREATE TABLE with the
	// view's columns.
	t.Run("views_come_back_as_views", func(t *testing.T) {
		req := ORMRequest{Target: ORMSQL, Schema: owner, Tables: []string{"JD_ORM_ACTIVE_CUSTOMERS"}, Views: ormYes()}
		asked, err := req.Scope(DriverOracle, "")
		if err != nil {
			t.Fatal(err)
		}
		views, err := LoadORMSchema(ctx, db, DriverOracle, asked)
		if err != nil {
			t.Fatalf("LoadORMSchema: %v", err)
		}
		view := ormTableNamed(views, owner, "JD_ORM_ACTIVE_CUSTOMERS")
		if view == nil || view.Kind != ORMKindView || !strings.Contains(view.CreateSQL, "VIEW") {
			t.Fatalf("view = %+v, want its own statement", view)
		}
		script := ormGenerate(t, views, req)
		ormMustContain(t, "schema.sql", script.Schema,
			`VIEW "`+owner+`"."JD_ORM_ACTIVE_CUSTOMERS"`, "SELECT ID, EMAIL FROM JD_ORM_CUSTOMERS WHERE STATE = 'A'")
		ormMustNotContain(t, "schema.sql", script.Schema, "CREATE TABLE")
		if script.Counts.Views != 1 || script.Counts.Tables != 0 || len(script.Warnings) != 0 {
			t.Errorf("counts = %+v, warnings = %q", script.Counts, script.Warnings)
		}
		ormExec(t, db, `DROP VIEW JD_ORM_ACTIVE_CUSTOMERS`, `INSERT INTO JD_ORM_CUSTOMERS (EMAIL) VALUES ('a@example.test')`)
		// Oracle takes one statement at a time and no terminator with it.
		for _, stmt := range splitSQLStatements(DriverOracle, script.Schema) {
			ormExec(t, db, stmt)
		}
		var active int
		if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM JD_ORM_ACTIVE_CUSTOMERS`).Scan(&active); err != nil || active != 1 {
			t.Errorf("the rebuilt view answers %d rows (%v), want 1", active, err)
		}
	})

	opts, _ := ORMRequest{Target: ORMPrisma}.Options()
	if _, err := GenerateORMFiles(schema, opts); err == nil || !strings.Contains(err.Error(), "Prisma has no connector for Oracle") {
		t.Errorf("Prisma for Oracle was not refused with its reason: %v", err)
	}
	for _, target := range ORMTargets() {
		if ORMUnsupported(target, DriverOracle) != "" {
			continue
		}
		if out := ormGenerate(t, schema, ORMRequest{Target: target, Tables: tables}); strings.TrimSpace(out.Schema) == "" {
			t.Errorf("%s produced nothing", target)
		}
	}

	// The script made of DBMS_METADATA's own statements rebuilds the tables:
	// identity column, constraints and the foreign key included.
	t.Run("the_sql_target_rebuilds_the_tables", func(t *testing.T) {
		entitiesOf := func(s *ORMSchema) string {
			return ormGenerate(t, s, ORMRequest{Target: ORMTypeORM, Tables: tables}).Schema
		}
		before := entitiesOf(schema)
		drop()
		for _, stmt := range splitSQLStatements(DriverOracle, sqlOut.Schema) {
			ormExec(t, db, stmt)
		}
		rebuilt, err := LoadORMSchema(ctx, db, DriverOracle, ORMScope{Schemas: []string{owner}, Tables: tables, Statements: true})
		if err != nil {
			t.Fatalf("LoadORMSchema after rebuild: %v", err)
		}
		if after := entitiesOf(rebuilt); after != before {
			t.Errorf("the rebuilt tables generate different entities.\n--- before\n%s\n--- after\n%s", before, after)
		}
	})

	// Where DBMS_METADATA hands no statement over, one is assembled from the
	// catalogue, and Oracle has to take that one too: it is particular about
	// the order of DEFAULT and NOT NULL. Last, because it replaces the tables.
	t.Run("the_assembled_script_runs", func(t *testing.T) {
		read := func() *ORMSchema {
			t.Helper()
			s, err := LoadORMSchema(ctx, db, DriverOracle, ORMScope{Schemas: []string{owner}, Tables: tables})
			if err != nil {
				t.Fatalf("LoadORMSchema: %v", err)
			}
			return s
		}
		typesOf := func(s *ORMSchema) string {
			return ormGenerate(t, s, ORMRequest{Target: ORMTypeScript, Tables: tables}).Schema
		}
		bare := read()
		before := typesOf(bare)
		script := ormGenerate(t, bare, ORMRequest{Target: ORMSQL, Tables: tables})
		ormMustContain(t, "warnings", strings.Join(script.Warnings, "\n"), "the engine returned no CREATE statement")
		ormMustContain(t, "schema.sql", script.Schema, `"BALANCE" NUMBER(18,2) DEFAULT 0 NOT NULL`, `"CREATED" DATE DEFAULT SYSDATE NOT NULL`)
		drop()
		for _, stmt := range splitSQLStatements(DriverOracle, script.Schema) {
			ormExec(t, db, stmt)
		}
		if after := typesOf(read()); after != before {
			t.Errorf("the rebuilt tables read differently.\n--- before\n%s\n--- after\n%s", before, after)
		}
	})
}

// CockroachDB answers on PostgreSQL's driver and is not PostgreSQL: it has its
// own Prisma provider, its own serial, and a catalogue that lacks some of the
// functions the PostgreSQL facts are read with.
func TestLiveORMCockroachDB(t *testing.T) {
	db := ormLiveDB(t, DriverPostgres, "JD_TEST_ORM_COCKROACH_DSN")
	ctx := context.Background()
	drop := []string{
		`DROP TABLE IF EXISTS jd_orm_entries`, `DROP TABLE IF EXISTS jd_orm_accounts`, `DROP TYPE IF EXISTS jd_orm_status`,
	}
	ormExec(t, db, drop...)
	t.Cleanup(func() {
		for _, s := range drop {
			_, _ = db.ExecContext(context.Background(), s)
		}
	})
	ormExec(t, db,
		`CREATE TYPE jd_orm_status AS ENUM ('open', 'closed')`,
		`CREATE TABLE jd_orm_accounts (
			id INT8 PRIMARY KEY DEFAULT unique_rowid(),
			email STRING NOT NULL UNIQUE,
			status jd_orm_status NOT NULL DEFAULT 'open',
			balance DECIMAL(12,2) NOT NULL DEFAULT 0,
			small INT2,
			tags STRING[],
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE TABLE jd_orm_entries (
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			account_id INT8 NOT NULL REFERENCES jd_orm_accounts(id) ON DELETE CASCADE,
			amount DECIMAL(12,2) NOT NULL,
			INDEX jd_orm_entries_account_idx (account_id)
		)`,
	)
	tables := []string{"jd_orm_accounts", "jd_orm_entries"}
	schema, err := LoadORMSchema(ctx, db, DriverPostgres, ORMScope{Schemas: []string{"public"}, Tables: tables})
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}
	if schema.Flavor != "cockroachdb" {
		t.Errorf("flavor = %q", schema.Flavor)
	}
	for _, w := range schema.Warnings {
		t.Errorf("loading reported: %s", w)
	}
	res := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma, Tables: tables})
	ormMustContain(t, "schema.prisma", res.Schema,
		`provider = "cockroachdb"`,
		"id BigInt @id @default(autoincrement())",
		"email String @unique",
		"status jd_orm_status @default(open)",
		"balance Decimal @default(0) @db.Decimal(12, 2)",
		"small Int? @db.Int2",
		"tags String[]",
		"created_at DateTime @default(now()) @db.Timestamptz(6)",
		`id String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid`,
		`account jd_orm_accounts @relation("jd_orm_entries_account_id", fields: [account_id], references: [id], onDelete: Cascade`,
		`@@index([account_id], map: "jd_orm_entries_account_idx")`,
		"enum jd_orm_status {",
	)
	for _, target := range ORMTargets() {
		if out := ormGenerate(t, schema, ORMRequest{Target: target, Tables: tables}); strings.TrimSpace(out.Schema) == "" {
			t.Errorf("%s produced nothing", target)
		}
	}
}

// ormRunScript runs a generated SQL script the way an operator's client would:
// one statement at a time, in order. The SQL target puts a blank line between
// statements and none inside one.
func ormRunScript(t *testing.T, db *sql.DB, script string) {
	t.Helper()
	for _, stmt := range strings.Split(script, "\n\n") {
		var lines []string
		for _, line := range strings.Split(stmt, "\n") {
			if !strings.HasPrefix(line, "--") {
				lines = append(lines, line)
			}
		}
		if s := strings.TrimSpace(strings.Join(lines, "\n")); s != "" {
			if _, err := db.ExecContext(context.Background(), s); err != nil {
				t.Fatalf("the generated script failed: %v\n%s", err, s)
			}
		}
	}
}

// A name can hold PostgreSQL's dollar quote. The guarded script wraps CREATE
// TYPE and ADD CONSTRAINT in a DO block, and a block quoted with $$ ends at
// the first $$ inside it — here an enum label and a constraint name, each
// followed by a DROP TABLE that would then run as a statement of its own.
func TestLiveORMPostgresDollarQuotes(t *testing.T) {
	db := ormLiveDB(t, DriverPostgres, "JD_TEST_POSTGRES_DSN")
	ctx := context.Background()
	// A second schema, a table, a column, an index and a check constraint
	// whose names hold every other character SQL gives a meaning to.
	const odd = `jd_orm $$ "q" 'x' \ ; -- */`
	oddQ := `"` + strings.ReplaceAll(odd, `"`, `""`) + `"`
	drop := []string{
		`DROP SCHEMA IF EXISTS jd_orm_dollar CASCADE`, `DROP SCHEMA IF EXISTS ` + oddQ + ` CASCADE`,
		`DROP SCHEMA IF EXISTS jd_orm_canary CASCADE`,
	}
	ormExec(t, db, drop...)
	t.Cleanup(func() {
		for _, s := range drop {
			_, _ = db.ExecContext(context.Background(), s)
		}
	})
	labels := []string{"a", "x$$; DROP TABLE jd_orm_canary.important; --", "price$", "$jd$", "it's"}
	ormExec(t, db,
		`CREATE SCHEMA jd_orm_canary`,
		`CREATE TABLE jd_orm_canary.important (id int PRIMARY KEY)`,
		`CREATE SCHEMA jd_orm_dollar`,
		`CREATE TYPE jd_orm_dollar.kind AS ENUM ('a', 'x$$; DROP TABLE jd_orm_canary.important; --', 'price$', '$jd$', 'it''s')`,
		`CREATE TABLE jd_orm_dollar.owners (id int PRIMARY KEY)`,
		`CREATE TABLE jd_orm_dollar.things (
			id int PRIMARY KEY,
			kind jd_orm_dollar.kind NOT NULL DEFAULT 'a',
			owner_id int,
			CONSTRAINT "fk$$; DROP TABLE jd_orm_canary.important; --" FOREIGN KEY (owner_id) REFERENCES jd_orm_dollar.owners(id)
		)`,
		`CREATE SCHEMA `+oddQ,
		`CREATE TABLE `+oddQ+`.`+oddQ+` (
			id int PRIMARY KEY,
			`+oddQ+` text NOT NULL DEFAULT 'd$$ ''x'' "q" \ ; -- */',
			thing_id int,
			CONSTRAINT `+oddQ+` CHECK (length(`+oddQ+`) >= 0),
			CONSTRAINT "odd fk $$ ; --" FOREIGN KEY (thing_id) REFERENCES jd_orm_dollar.things(id) ON DELETE SET NULL
		)`,
		`CREATE INDEX "odd ix $$ ""q"" ; --" ON `+oddQ+`.`+oddQ+` (`+oddQ+`)`,
		`COMMENT ON TABLE `+oddQ+`.`+oddQ+` IS 'about $$ ''x'' "q" \ ; -- */'`,
		`COMMENT ON COLUMN `+oddQ+`.`+oddQ+`.`+oddQ+` IS 'column $$ ''x'' \'`,
	)
	scope := ORMScope{Schemas: []string{"jd_orm_dollar", odd}, Statements: true}
	schema, err := LoadORMSchema(ctx, db, DriverPostgres, scope)
	if err != nil {
		t.Fatalf("LoadORMSchema: %v", err)
	}
	before := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma})
	script := ormGenerate(t, schema, ORMRequest{Target: ORMSQL, IfNotExists: ormYes()})
	ormMustContain(t, "schema.sql", script.Schema,
		"DO $jd1$ BEGIN\n  CREATE TYPE \"jd_orm_dollar\".\"kind\" AS ENUM",
		"DO $jd$ BEGIN\n  ALTER TABLE \"jd_orm_dollar\".\"things\" ADD CONSTRAINT \"fk$$; DROP TABLE jd_orm_canary.important; --\"")

	if n := strings.Count(script.Schema, "\nDO $"); n != 3 {
		t.Errorf("%d DO blocks, want the enum and two foreign keys\n%s", n, script.Schema)
	}
	for _, w := range script.Warnings {
		t.Errorf("the script reported: %s", w)
	}

	// Rebuild from the script, then run it again over what it built: the
	// second run is what IF NOT EXISTS and the DO blocks are for.
	ormExec(t, db, `DROP SCHEMA jd_orm_dollar CASCADE`, `DROP SCHEMA `+oddQ+` CASCADE`)
	ormRunScript(t, db, script.Schema)
	ormRunScript(t, db, script.Schema)

	var rows int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM jd_orm_canary.important`).Scan(&rows); err != nil {
		t.Fatalf("the table a label tried to drop is gone: %v", err)
	}
	rebuilt, err := LoadORMSchema(ctx, db, DriverPostgres, scope)
	if err != nil {
		t.Fatalf("LoadORMSchema after rebuild: %v", err)
	}
	if len(rebuilt.Enums) == 0 {
		t.Fatal("no enum after the rebuild")
	}
	for _, e := range rebuilt.Enums {
		if e.Schema == "jd_orm_dollar" && strings.Join(e.Values, "\x00") != strings.Join(labels, "\x00") {
			t.Errorf("labels after the rebuild = %q, want %q", e.Values, labels)
		}
	}
	things := ormTableNamed(rebuilt, "jd_orm_dollar", "things")
	if things == nil || len(things.ForeignKeys) != 1 || things.ForeignKeys[0].Name != "fk$$; DROP TABLE jd_orm_canary.important; --" {
		t.Errorf("the foreign key did not come back as it was: %+v", things)
	}
	oddTable := ormTableNamed(rebuilt, odd, odd)
	was := ormTableNamed(schema, odd, odd)
	if oddTable == nil || was == nil {
		t.Fatalf("the oddly named table did not come back: %+v", oddTable)
	}
	if c, w := ormColumnNamed(oddTable, odd), ormColumnNamed(was, odd); c == nil || w == nil || c.Default != w.Default || c.Comment != w.Comment {
		t.Errorf("the oddly named column came back as %+v, was %+v", c, w)
	}
	if oddTable.Comment != was.Comment || len(oddTable.Checks) != 1 || oddTable.Checks[0].Name != odd ||
		ormIndexNamed(oddTable, `odd ix $$ "q" ; --`) == nil || len(oddTable.ForeignKeys) != 1 || oddTable.ForeignKeys[0].Name != "odd fk $$ ; --" {
		t.Errorf("the oddly named table came back as %+v, was %+v", oddTable, was)
	}
	after := ormGenerate(t, rebuilt, ORMRequest{Target: ORMPrisma})
	if before.Schema != after.Schema {
		t.Errorf("the rebuilt database generates a different Prisma schema.\n--- before\n%s\n--- after\n%s", before.Schema, after.Schema)
	}
}

// PostgreSQL releases older than the catalogue queries were written on. A
// column the server does not have fails the query that names it, and with it
// every enum, array, domain and identity column of the schema — so each
// release is read here for real. JD_TEST_ORM_POSTGRES_OLD_DSNS takes the DSNs,
// separated by spaces.
func TestLiveORMOlderPostgres(t *testing.T) {
	dsns := strings.Fields(os.Getenv("JD_TEST_ORM_POSTGRES_OLD_DSNS"))
	if len(dsns) == 0 {
		t.Skip("set JD_TEST_ORM_POSTGRES_OLD_DSNS to run this against PostgreSQL 9.6, 10 and 11")
	}
	d, err := DialectFor(DriverPostgres)
	if err != nil {
		t.Fatal(err)
	}
	for _, dsn := range dsns {
		db, err := sql.Open(d.SQLDriverName(), d.NormaliseDSN(dsn))
		if err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { db.Close() })
		ctx := context.Background()
		var num string
		if err := db.QueryRowContext(ctx, `SHOW server_version_num`).Scan(&num); err != nil {
			t.Fatalf("no PostgreSQL at one of the DSNs: %v", err)
		}
		version := ormAtoi(num, 0)
		t.Run("server_"+num, func(t *testing.T) {
			drop := `DROP SCHEMA IF EXISTS jd_orm_old CASCADE`
			ormExec(t, db, drop)
			t.Cleanup(func() { _, _ = db.ExecContext(context.Background(), drop) })
			ormExec(t, db,
				`CREATE SCHEMA jd_orm_old`,
				`CREATE TYPE jd_orm_old.status AS ENUM ('open', 'closed')`,
				`CREATE DOMAIN jd_orm_old.email AS varchar(320)`,
				`CREATE TABLE jd_orm_old.accounts (
					id bigserial PRIMARY KEY,
					email jd_orm_old.email NOT NULL,
					status jd_orm_old.status NOT NULL DEFAULT 'open',
					tags text[] NOT NULL DEFAULT '{}',
					balance numeric(12,2) NOT NULL DEFAULT 0,
					closed_at timestamptz
				)`,
				`COMMENT ON COLUMN jd_orm_old.accounts.email IS 'Where statements go'`,
				`CREATE UNIQUE INDEX accounts_open_email_idx ON jd_orm_old.accounts (email) WHERE closed_at IS NULL`,
				`CREATE INDEX accounts_lower_email_idx ON jd_orm_old.accounts (lower(email::text))`,
				`CREATE TABLE jd_orm_old.entries (
					id serial PRIMARY KEY,
					account_id bigint NOT NULL REFERENCES jd_orm_old.accounts(id) ON DELETE CASCADE,
					amount numeric(12,2) NOT NULL CHECK (amount <> 0)
				)`,
				`CREATE INDEX entries_amount_idx ON jd_orm_old.entries (amount DESC)`,
			)
			if version >= 100000 {
				ormExec(t, db,
					`CREATE TABLE jd_orm_old.notes (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, body text)`,
					`CREATE TABLE jd_orm_old.readings (sensor int NOT NULL, taken_at timestamptz NOT NULL) PARTITION BY RANGE (taken_at)`,
					`CREATE TABLE jd_orm_old.readings_2024 PARTITION OF jd_orm_old.readings FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')`,
				)
			}
			if version >= 110000 {
				ormExec(t, db, `CREATE INDEX entries_account_idx ON jd_orm_old.entries (account_id) INCLUDE (amount)`)
			}

			schema, err := LoadORMSchema(ctx, db, DriverPostgres, ORMScope{Schemas: []string{"jd_orm_old"}})
			if err != nil {
				t.Fatalf("LoadORMSchema: %v", err)
			}
			for _, w := range schema.Warnings {
				t.Errorf("loading reported: %s", w)
			}
			accounts := ormTableNamed(schema, "jd_orm_old", "accounts")
			if c := ormColumnNamed(accounts, "status"); c == nil || c.EnumName != "status" || c.EnumSchema != "jd_orm_old" {
				t.Errorf("accounts.status = %+v, want the enum", c)
			}
			if c := ormColumnNamed(accounts, "email"); c == nil || c.Type != "character varying(320)" || c.Comment != "Where statements go" {
				t.Errorf("accounts.email = %+v, want the domain's base type and its comment", c)
			}
			if c := ormColumnNamed(accounts, "tags"); c == nil || c.Type != "text[]" {
				t.Errorf("accounts.tags = %+v, want text[]", c)
			}
			if ix := ormIndexNamed(accounts, "accounts_open_email_idx"); ix == nil || !ix.Partial || !ix.Unique {
				t.Errorf("accounts_open_email_idx = %+v, want a partial unique index", ix)
			}
			if ix := ormIndexNamed(accounts, "accounts_lower_email_idx"); ix == nil || !ix.Expression {
				t.Errorf("accounts_lower_email_idx = %+v, want an expression index", ix)
			}
			entries := ormTableNamed(schema, "jd_orm_old", "entries")
			if ix := ormIndexNamed(entries, "entries_amount_idx"); ix == nil || len(ix.Desc) != 1 || !ix.Desc[0] {
				t.Errorf("entries_amount_idx = %+v, want descending", ix)
			}
			if entries == nil || len(entries.Checks) != 1 {
				t.Errorf("entries checks = %+v, want one", entries)
			}

			res := ormGenerate(t, schema, ORMRequest{Target: ORMPrisma})
			ormMustContain(t, "schema.prisma", res.Schema,
				"id BigInt @id @default(autoincrement())",
				"email String @db.VarChar(320)",
				"status status @default(open)",
				"tags String[] @default([])",
				"balance Decimal @default(0) @db.Decimal(12, 2)",
				`@relation("entries_account_id", fields: [account_id], references: [id], onDelete: Cascade`,
				"@@index([amount(sort: Desc)])",
				"enum status {",
			)
			ormMustNotContain(t, "schema.prisma", res.Schema, "Unsupported(", "USER-DEFINED", "ARRAY", "email String @unique")
			ormMustContain(t, "warnings", strings.Join(res.Warnings, "\n"), "Index accounts_open_email_idx on accounts covers only some rows")

			if version >= 100000 {
				if c := ormColumnNamed(ormTableNamed(schema, "jd_orm_old", "notes"), "id"); c == nil || c.Identity != "always" {
					t.Errorf("notes.id = %+v, want an identity column", c)
				}
				if p := ormTableNamed(schema, "jd_orm_old", "readings_2024"); p == nil || p.Kind != ORMKindPartition {
					t.Errorf("readings_2024 = %+v, want a partition", p)
				}
				if p := ormTableNamed(schema, "jd_orm_old", "readings"); p == nil || p.Kind != ORMKindPartitioned {
					t.Errorf("readings = %+v, want a partitioned table", p)
				}
				ormMustNotContain(t, "schema.prisma", res.Schema, "readings_2024")
			}
			if version >= 110000 {
				if ix := ormIndexNamed(entries, "entries_account_idx"); ix == nil || strings.Join(ix.Columns, ",") != "account_id" {
					t.Errorf("entries_account_idx = %+v, want its one key column", ix)
				}
			}
			for _, target := range ORMTargets() {
				if out := ormGenerate(t, schema, ORMRequest{Target: target}); strings.TrimSpace(out.Schema) == "" {
					t.Errorf("%s produced nothing", target)
				}
			}
		})
	}
}
