package dbx

import (
	"fmt"
	"strings"
)

// MikroORM.
//
// Entities for MikroORM's decorator API, in the shape its own entity generator
// writes. Two things differ from the other class-based targets and are both
// MikroORM's rules rather than choices made here: a foreign-key column is not
// declared beside its relation — the relation property is the column — and a
// primary key that is not called id has to be named in [PrimaryKeyProp] for
// the types to know it.
//
// Every scalar carries both `type` (how MikroORM converts the value) and
// `columnType` (what the column is in the database), so nothing is left for
// the schema generator to infer.

type mikroGen struct {
	*ormGen
	names *ormNaming
	// claimed says which relation stands in for a column, per table; owned is
	// the set of foreign keys that are a relation on their own table.
	claimed map[*ormTable]map[string]*ormRel
	owned   map[*ormRel]bool
}

func generateMikroORM(g *ormGen) []ORMFile {
	k := &mikroGen{ormGen: g, claimed: map[*ormTable]map[string]*ormRel{}, owned: map[*ormRel]bool{}}
	rules := tsClassRules(g, strings.Fields(`Entity Enum Index ManyToOne OneToMany OneToOne PrimaryKey
		Property Unique Collection PrimaryKeyProp Opt Rel`)...)
	rules.modelSuffix = "Entity"
	k.names = g.names(rules)

	for _, m := range g.models {
		k.claimed[m] = map[string]*ormRel{}
		for _, r := range m.rels {
			free := true
			for _, col := range r.fk.Columns {
				if k.claimed[m][col] != nil {
					free = false
				}
			}
			if !free {
				k.warn("%s.%s is part of two foreign keys; only the first is a relation, because MikroORM maps a column to one property.",
					k.label(m), strings.Join(r.fk.Columns, ", "))
				continue
			}
			for _, col := range r.fk.Columns {
				k.claimed[m][col] = r
			}
			k.owned[r] = true
		}
	}

	var units []*tsUnit
	if u := tsEnumUnit(g, k.names); u != nil {
		units = append(units, u)
	}
	for _, m := range g.models {
		units = append(units, k.entity(m))
	}
	header := "// Generated by Just Dashboard from live database introspection.\n" +
		"// A reviewed starting point: verify types, defaults and relations before\n" +
		"// registering these entities.\n"
	return tsLayout(header, units, g.opts.Split, "entities.ts")
}

// scalar maps a column onto MikroORM's mapped type and the TypeScript type its
// values have at runtime.
func (k *mikroGen) scalar(c *ormCol) (mapped, ts string) {
	t := c.t
	switch t.Kind {
	case ormBool:
		mapped, ts = "boolean", "boolean"
	case ormInt8:
		mapped, ts = "tinyint", "number"
	case ormInt16:
		mapped, ts = "smallint", "number"
	case ormInt32, ormYear:
		mapped, ts = "integer", "number"
		if t.Name == "mediumint" {
			mapped = "mediumint"
		}
	case ormInt64:
		// MikroORM maps a 64-bit column to a JavaScript bigint.
		mapped, ts = "bigint", "bigint"
	case ormFloat32:
		mapped, ts = "float", "number"
	case ormFloat64:
		mapped, ts = "double", "number"
	case ormDecimal, ormMoney, ormBigNum:
		mapped, ts = "decimal", "string"
	case ormChar:
		mapped, ts = "character", "string"
	case ormVarchar:
		mapped, ts = "string", "string"
	case ormText:
		mapped, ts = "text", "string"
	case ormUUID:
		mapped, ts = "uuid", "string"
	case ormJSON:
		mapped, ts = "json", "unknown"
	case ormBytes:
		mapped, ts = "blob", "Buffer"
	case ormDate:
		mapped, ts = "date", "string"
	case ormTime:
		mapped, ts = "time", "string"
	case ormDateTime, ormDateTimeTZ:
		mapped, ts = "datetime", "Date"
	case ormInterval:
		mapped, ts = "interval", "string"
	default:
		mapped, ts = "string", "string"
	}
	if t.Array {
		return "array", ts + "[]"
	}
	return mapped, ts
}

// columnType is the column's type in the database's own spelling.
func mikroColumnType(c *ormCol) string {
	return strings.Join(strings.Fields(strings.ToLower(c.Type)), " ")
}

func mikroRule(rule string) string {
	if a := ormAction(rule); a != "" && a != "NO ACTION" {
		return strings.ToLower(a)
	}
	return ""
}

func (k *mikroGen) entity(m *ormTable) *tsUnit {
	class := k.names.model[m]
	u := newTSUnit(class, class)
	const decorators = "@mikro-orm/decorators/legacy"

	claimed := k.claimed[m]
	propOf := func(col string) string {
		if r := claimed[col]; r != nil {
			return k.names.fwd[r]
		}
		return k.names.field[m.byCol[col]]
	}
	props := func(cols []string) string {
		seen := map[string]bool{}
		var out []string
		for _, col := range cols {
			if p := propOf(col); !seen[p] {
				seen[p] = true
				out = append(out, jsString(p))
			}
		}
		return "[" + strings.Join(out, ", ") + "]"
	}

	var b strings.Builder
	b.WriteString(tsDocComment("", m.Comment))
	if len(m.PrimaryKey) == 0 {
		k.warn("%s has no primary key. MikroORM needs one to track an entity: mark the columns that identify a row with @PrimaryKey.", k.label(m))
		b.WriteString("// No primary key in the database. MikroORM needs one: mark the identifying columns with @PrimaryKey.\n")
	}
	u.use(decorators, "Entity")
	entity := []string{"tableName: " + jsString(m.Name)}
	if k.qualified(m) {
		entity = append(entity, "schema: "+jsString(m.Schema))
	}
	fmt.Fprintf(&b, "@Entity(%s)\n", jsObject(entity))
	for _, ix := range m.uniques {
		u.use(decorators, "Unique")
		fmt.Fprintf(&b, "@Unique({ name: %s, properties: %s })\n", jsString(ix.Name), props(ix.Columns))
	}
	for _, ix := range k.plainIndexes(m) {
		u.use(decorators, "Index")
		fmt.Fprintf(&b, "@Index({ name: %s, properties: %s })\n", jsString(ix.Name), props(ix.Columns))
	}
	fmt.Fprintf(&b, "export class %s {\n", class)

	// The key's property names, for the types: MikroORM only assumes "id".
	var keyProps []string
	seenKey := map[string]bool{}
	for _, col := range m.PrimaryKey {
		if p := propOf(col); !seenKey[p] {
			seenKey[p] = true
			keyProps = append(keyProps, jsString(p))
		}
	}
	first := true
	member := func(lines ...string) {
		if !first {
			b.WriteString("\n")
		}
		first = false
		for _, l := range lines {
			b.WriteString("  " + l + "\n")
		}
	}
	switch {
	case len(keyProps) > 1:
		u.use("@mikro-orm/core", "PrimaryKeyProp")
		member("[PrimaryKeyProp]?: [" + strings.Join(keyProps, ", ") + "]")
	case len(keyProps) == 1 && keyProps[0] != `"id"`:
		u.use("@mikro-orm/core", "PrimaryKeyProp")
		member("[PrimaryKeyProp]?: " + keyProps[0])
	}

	emitted := map[*ormRel]bool{}
	for _, c := range m.cols {
		if r := claimed[c.Name]; r != nil {
			if !emitted[r] {
				emitted[r] = true
				member(k.relation(u, m, r)...)
			}
			continue
		}
		member(k.property(u, m, c)...)
	}
	for _, r := range m.back {
		// The other side has to be a relation there for this side to point at.
		if !k.owned[r] {
			continue
		}
		other := k.names.model[r.from]
		u.ref(other)
		if r.unique {
			u.use(decorators, "OneToOne")
			u.use("@mikro-orm/core", "type Rel")
			member(fmt.Sprintf("@OneToOne({ entity: () => %s, mappedBy: %s })", other, jsString(k.names.fwd[r])),
				fmt.Sprintf("%s?: Rel<%s> | null", k.names.back[r], other))
			continue
		}
		u.use(decorators, "OneToMany")
		u.use("@mikro-orm/core", "Collection")
		member(fmt.Sprintf("@OneToMany({ entity: () => %s, mappedBy: %s })", other, jsString(k.names.fwd[r])),
			fmt.Sprintf("%s = new Collection<%s>(this)", k.names.back[r], other))
	}
	b.WriteString("}\n")
	u.body = b.String()
	return u
}

func (k *mikroGen) property(u *tsUnit, m *ormTable, c *ormCol) []string {
	const decorators = "@mikro-orm/decorators/legacy"
	name := k.names.field[c]
	var lines []string
	if c.Comment != "" {
		lines = append(lines, strings.TrimSuffix(tsDocComment("", c.Comment), "\n"))
	}
	pk := m.pk[c.Name]

	var parts []string
	var ts string
	decorator := "Property"
	if e := c.t.Enum; e != nil && !c.t.Array {
		decorator = "Enum"
		ts = k.names.enum[e]
		u.ref(ts)
		parts = append(parts, "items: () => "+ts)
		if !e.inline {
			parts = append(parts, "nativeEnumName: "+jsString(e.Name))
		}
	} else {
		var mapped string
		mapped, ts = k.scalar(c)
		if c.t.Kind == ormUnknown {
			k.warn("%s.%s has type %s, which MikroORM has no mapped type for; it is handled as a string.", k.label(m), c.Name, c.Type)
		}
		parts = append(parts, "type: "+jsString(mapped), "columnType: "+jsString(mikroColumnType(c)))
	}
	if name != c.Name {
		parts = append(parts, "fieldName: "+jsString(c.Name))
	}
	if c.t.Unsigned {
		parts = append(parts, "unsigned: true")
	}
	if c.Nullable {
		parts = append(parts, "nullable: true")
	}
	optional := false
	if k.opts.Defaults {
		extra, opt := k.defaults(c, ts)
		parts = append(parts, extra...)
		optional = opt
	}
	if pk {
		decorator = "PrimaryKey"
		// A lone integer key is assumed to be auto-numbered unless told.
		if len(m.PrimaryKey) == 1 && c.t.isInteger() && c.def.Kind != ormDefAuto {
			parts = append(parts, "autoincrement: false")
		}
	}
	u.use(decorators, decorator)

	declared := ts
	if c.Nullable && ts != "unknown" {
		declared += " | null"
	}
	if optional {
		u.use("@mikro-orm/core", "type Opt")
		if strings.Contains(declared, " | ") {
			declared = "(" + declared + ")"
		}
		declared += " & Opt"
	}
	return append(lines, fmt.Sprintf("@%s(%s)", decorator, jsObject(parts)), fmt.Sprintf("%s!: %s", name, declared))
}

// defaults renders a column's default as decorator options, and reports
// whether the property is thereby optional when an entity is created.
func (k *mikroGen) defaults(c *ormCol, ts string) (parts []string, optional bool) {
	if c.Generated {
		if c.GeneratedExpr != "" {
			return []string{"generated: " + jsString(c.GeneratedExpr+" stored")}, true
		}
		return []string{"persist: false"}, true
	}
	raw := func(expr string) []string { return []string{"defaultRaw: " + jsString(expr)} }
	d := c.def
	switch d.Kind {
	case ormDefAuto:
		return nil, true
	case ormDefNow, ormDefExpr, ormDefJSON, ormDefEmptyArray:
		return raw(d.sql(k.driver)), true
	case ormDefUUID:
		return raw(d.Text), true
	case ormDefString:
		if c.t.Array {
			return raw(d.sql(k.driver)), true
		}
		return []string{"default: " + jsString(d.Text)}, true
	case ormDefNumber:
		if ts == "number" {
			return []string{"default: " + d.Text}, true
		}
		return raw(d.sql(k.driver)), true
	case ormDefBool:
		if ts == "boolean" {
			return []string{fmt.Sprintf("default: %t", d.Bool)}, true
		}
		return raw(d.sql(k.driver)), true
	}
	return nil, false
}

func (k *mikroGen) relation(u *tsUnit, m *ormTable, r *ormRel) []string {
	const decorators = "@mikro-orm/decorators/legacy"
	other := k.names.model[r.to]
	u.ref(other)
	u.use("@mikro-orm/core", "type Rel")
	decorator := "ManyToOne"
	if r.unique {
		decorator = "OneToOne"
	}
	u.use(decorators, decorator)

	parts := []string{"entity: () => " + other}
	if len(r.fk.Columns) == 1 {
		parts = append(parts, "fieldName: "+jsString(r.fk.Columns[0]))
	} else {
		parts = append(parts, "fieldNames: ["+strings.Join(jsStrings(r.fk.Columns), ", ")+"]")
	}
	if !ormSameColumns(r.fk.RefColumns, r.to.PrimaryKey) {
		parts = append(parts, "referencedColumnNames: ["+strings.Join(jsStrings(r.fk.RefColumns), ", ")+"]")
	}
	primary := true
	for _, col := range r.fk.Columns {
		if !m.pk[col] {
			primary = false
		}
	}
	if primary {
		parts = append(parts, "primary: true")
	}
	if r.optional {
		parts = append(parts, "nullable: true")
	}
	if a := mikroRule(r.fk.OnDelete); a != "" {
		parts = append(parts, "deleteRule: "+jsString(a))
	}
	if a := mikroRule(r.fk.OnUpdate); a != "" {
		parts = append(parts, "updateRule: "+jsString(a))
	}
	declared := "Rel<" + other + ">"
	if r.optional {
		declared += " | null"
	}
	return []string{
		fmt.Sprintf("@%s(%s)", decorator, jsObject(parts)),
		fmt.Sprintf("%s!: %s", k.names.fwd[r], declared),
	}
}
