package dbx

import (
	"fmt"
	"regexp"
	"strings"
)

// SQL.
//
// The schema as CREATE statements in the source engine's own dialect. Where
// the engine keeps the statement that made a table (MySQL, SQLite, ClickHouse,
// Oracle through DBMS_METADATA), that text is used as it is: nothing written
// here could be more exact. Where it keeps none (PostgreSQL, SQL Server) the
// statements are assembled from the catalogue — types as the catalogue prints
// them, the index definitions PostgreSQL itself reports, foreign keys added
// last so the order of the tables does not matter.
//
// It is a description of structure, not a dump: no rows, no ownership or
// grants, no functions or triggers.

type sqlGen struct {
	*ormGen
	b strings.Builder
}

func generateSQL(g *ormGen) []ORMFile {
	s := &sqlGen{ormGen: g}
	fmt.Fprintf(&s.b, "-- Generated by Just Dashboard from live database introspection.\n")
	fmt.Fprintf(&s.b, "-- The schema as CREATE statements in %s's own dialect. A reviewed starting\n", ormEngineName(g.driver, g.flavor))
	s.b.WriteString("-- point: structure only — no rows, grants, functions or triggers.\n")

	switch g.driver {
	case DriverPostgres:
		s.postgres()
	case DriverMSSQL:
		s.mssql()
	default:
		s.verbatim()
	}
	return []ORMFile{{Filename: "schema.sql", Content: s.b.String()}}
}

func (s *sqlGen) quote(name string) string {
	q, err := s.dialect.QuoteIdent(name)
	if err != nil {
		// An identifier the dialect refuses to quote cannot be written safely.
		return ""
	}
	return q
}

func (s *sqlGen) quoteAll(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = s.quote(n)
	}
	return strings.Join(out, ", ")
}

// rel is a table reference, schema-qualified when the schema has to be said.
func (s *sqlGen) rel(schema, name string) string {
	q := s.quote(name)
	if schema == "" || s.driver == DriverSQLite {
		return q
	}
	if s.multiSchema || (s.defaultSchema != "" && schema != s.defaultSchema) {
		return s.quote(schema) + "." + q
	}
	return q
}

// writable reports whether every name in a table can be quoted, warning once
// when one cannot.
func (s *sqlGen) writable(m *ormTable) bool {
	if s.quote(m.Name) == "" || (m.Schema != "" && s.quote(m.Schema) == "") {
		s.warn("%s has a name that cannot be quoted safely and was left out.", ormOneLine(s.label(m)))
		return false
	}
	for _, c := range m.cols {
		if s.quote(c.Name) == "" {
			s.warn("%s has a column whose name cannot be quoted safely and was left out.", ormOneLine(s.label(m)))
			return false
		}
	}
	return true
}

func (s *sqlGen) statement(text string) {
	s.b.WriteString("\n" + strings.TrimRight(text, " \t\n;") + ";\n")
}

// actions renders ON DELETE / ON UPDATE for a foreign key, leaving out the
// engine's default.
func sqlActions(fk ForeignKey) string {
	out := ""
	if a := ormAction(fk.OnDelete); a != "" && a != "NO ACTION" {
		out += " ON DELETE " + a
	}
	if a := ormAction(fk.OnUpdate); a != "" && a != "NO ACTION" {
		out += " ON UPDATE " + a
	}
	return out
}

// foreignKeys writes each foreign key as an ALTER TABLE, after every table
// exists. A key into a table that is not in the output is left out and said.
func (s *sqlGen) foreignKeys(wrap func(m *ormTable, name, stmt string) string) {
	if !s.opts.Relations {
		return
	}
	present := map[string]bool{}
	for _, m := range s.models {
		// A table that could not be written is not there to be referenced.
		if !m.view && s.writable(m) {
			present[ormTableKey(m.Schema, m.Name)] = true
		}
	}
	for _, m := range s.models {
		if m.view || !s.writable(m) {
			continue
		}
		for _, fk := range m.ForeignKeys {
			if fk.RefTable == "" || len(fk.Columns) == 0 || len(fk.Columns) != len(fk.RefColumns) {
				continue
			}
			refSchema := fk.RefSchema
			if refSchema == "" {
				refSchema = m.Schema
			}
			if !present[ormTableKey(refSchema, fk.RefTable)] {
				if !s.opts.Selected {
					s.warn("%s.%s references %s.%s, which is not in this script; the foreign key was left out.",
						s.label(m), strings.Join(fk.Columns, ", "), refSchema, fk.RefTable)
				}
				continue
			}
			stmt := fmt.Sprintf("ALTER TABLE %s ADD", s.rel(m.Schema, m.Name))
			if fk.Name != "" && s.quote(fk.Name) != "" {
				stmt += " CONSTRAINT " + s.quote(fk.Name)
			}
			stmt += fmt.Sprintf(" FOREIGN KEY (%s) REFERENCES %s (%s)%s",
				s.quoteAll(fk.Columns), s.rel(refSchema, fk.RefTable), s.quoteAll(fk.RefColumns), sqlActions(fk))
			s.statement(wrap(m, fk.Name, stmt))
		}
	}
}

// primaryKey renders a table's PRIMARY KEY clause, named where the catalogue
// gave the constraint a name.
func (s *sqlGen) primaryKey(m *ormTable) string {
	if len(m.PrimaryKey) == 0 {
		return ""
	}
	clause := "PRIMARY KEY (" + s.quoteAll(m.PrimaryKey) + ")"
	for _, ix := range m.Indexes {
		if ix.Primary && ix.Name != "" && s.quote(ix.Name) != "" && ix.Name != "PRIMARY" &&
			!strings.HasPrefix(ix.Name, "sqlite_autoindex_") {
			return "CONSTRAINT " + s.quote(ix.Name) + " " + clause
		}
	}
	return clause
}

// --- PostgreSQL -----------------------------------------------------------

var postgresCreateIndexRe = regexp.MustCompile(`^CREATE (UNIQUE )?INDEX `)

func (s *sqlGen) postgres() {
	guard := s.opts.IfNotExists
	exists := ""
	if guard {
		exists = "IF NOT EXISTS "
	}
	// CREATE TYPE and ADD CONSTRAINT have no IF NOT EXISTS; a block that
	// swallows "already there" is PostgreSQL's own idiom for it.
	tolerate := func(stmt string) string {
		if !guard {
			return stmt
		}
		return "DO $$ BEGIN\n  " + stmt + ";\nEXCEPTION WHEN duplicate_object THEN NULL;\nEND $$"
	}

	for _, schema := range s.schemaNames() {
		if schema != s.defaultSchema && s.quote(schema) != "" {
			s.statement("CREATE SCHEMA " + exists + s.quote(schema))
		}
	}
	for _, e := range s.enums {
		if s.quote(e.Name) == "" || (e.Schema != "" && s.quote(e.Schema) == "") {
			s.warn("Enum type %s has a name that cannot be quoted safely and was left out.", ormOneLine(e.Name))
			continue
		}
		values := make([]string, len(e.Values))
		for i, v := range e.Values {
			values[i] = ormSQLString(v)
		}
		s.statement(tolerate(fmt.Sprintf("CREATE TYPE %s AS ENUM (%s)", s.rel(e.Schema, e.Name), strings.Join(values, ", "))))
	}

	for _, m := range s.models {
		if m.view || !s.writable(m) {
			continue
		}
		var lines []string
		for _, c := range m.cols {
			line := "  " + s.quote(c.Name) + " " + s.postgresColumnType(m, c)
			switch {
			case c.Generated && c.GeneratedExpr != "":
				line += " GENERATED ALWAYS AS (" + c.GeneratedExpr + ") STORED"
			case c.Identity == "always":
				line += " GENERATED ALWAYS AS IDENTITY"
			case c.Identity == "by default":
				line += " GENERATED BY DEFAULT AS IDENTITY"
			case c.def.Kind != ormDefAuto && strings.TrimSpace(c.Default) != "" && !c.Generated:
				line += " DEFAULT " + strings.TrimSpace(c.Default)
			}
			if !c.Nullable {
				line += " NOT NULL"
			}
			lines = append(lines, line)
		}
		if pk := s.primaryKey(m); pk != "" {
			lines = append(lines, "  "+pk)
		}
		for _, ck := range m.Checks {
			if ck.Name != "" && s.quote(ck.Name) != "" {
				lines = append(lines, "  CONSTRAINT "+s.quote(ck.Name)+" "+ck.Definition)
			} else {
				lines = append(lines, "  "+ck.Definition)
			}
		}
		stmt := fmt.Sprintf("CREATE TABLE %s%s (\n%s\n)", exists, s.rel(m.Schema, m.Name), strings.Join(lines, ",\n"))
		if m.Kind == ORMKindPartitioned {
			if m.PartitionKey != "" {
				stmt += " PARTITION BY " + m.PartitionKey
			}
			s.warn("%s is partitioned: its partitions are not in this script and have to be created with PARTITION OF before it can hold a row.", s.label(m))
		}
		s.statement(stmt)

		if m.Comment != "" {
			s.statement(fmt.Sprintf("COMMENT ON TABLE %s IS %s", s.rel(m.Schema, m.Name), ormSQLString(m.Comment)))
		}
		for _, c := range m.cols {
			if c.Comment != "" {
				s.statement(fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s", s.rel(m.Schema, m.Name), s.quote(c.Name), ormSQLString(c.Comment)))
			}
		}
		for _, ix := range m.Indexes {
			if ix.Primary {
				continue
			}
			if ix.Definition != "" {
				// PostgreSQL's own text for the index: access method, operator
				// classes, expressions and predicate all included.
				def := ix.Definition
				if guard {
					def = postgresCreateIndexRe.ReplaceAllString(def, "${0}IF NOT EXISTS ")
				}
				s.statement(def)
				continue
			}
			if ix.Partial || ix.Expression || len(ix.Columns) == 0 || s.quote(ix.Name) == "" {
				s.warn("Index %s on %s could not be reproduced: its definition was not read.", ix.Name, s.label(m))
				continue
			}
			unique := ""
			if ix.Unique {
				unique = "UNIQUE "
			}
			using := ""
			if method := strings.ToLower(ix.Method); method != "" && method != "btree" {
				using = " USING " + method
			}
			s.statement(fmt.Sprintf("CREATE %sINDEX %s%s ON %s%s (%s)",
				unique, exists, s.quote(ix.Name), s.rel(m.Schema, m.Name), using, s.quoteAll(ix.Columns)))
		}
	}
	s.foreignKeys(func(_ *ormTable, _, stmt string) string { return tolerate(stmt) })

	for _, m := range s.models {
		if !m.view || !s.writable(m) {
			continue
		}
		if strings.TrimSpace(m.CreateSQL) == "" {
			s.warn("The definition of %s %s could not be read; it was left out.", m.Kind, s.label(m))
			continue
		}
		body := strings.TrimRight(strings.TrimSpace(m.CreateSQL), ";")
		switch {
		case m.Kind == ORMKindMatView:
			s.statement(fmt.Sprintf("CREATE MATERIALIZED VIEW %s%s AS\n %s", exists, s.rel(m.Schema, m.Name), body))
		case guard:
			s.statement(fmt.Sprintf("CREATE OR REPLACE VIEW %s AS\n %s", s.rel(m.Schema, m.Name), body))
		default:
			s.statement(fmt.Sprintf("CREATE VIEW %s AS\n %s", s.rel(m.Schema, m.Name), body))
		}
	}
}

// postgresColumnType is the column's type as it can be written back. A column
// numbered by a sequence is written as the serial it was declared as, since
// the sequence it names is not created by this script.
func (s *sqlGen) postgresColumnType(m *ormTable, c *ormCol) string {
	typ := strings.TrimSpace(c.Type)
	if c.def.Kind == ormDefAuto && c.Identity == "" && !c.t.Array {
		switch c.t.Kind {
		case ormInt16:
			return "smallserial"
		case ormInt32:
			return "serial"
		case ormInt64:
			return "bigserial"
		}
	}
	switch strings.ToUpper(typ) {
	case "USER-DEFINED", "ARRAY":
		s.warn("%s.%s has a type the catalogue reported only as %s; the statement will not run until it is filled in.", s.label(m), c.Name, typ)
	}
	return typ
}

// --- SQL Server -----------------------------------------------------------

func (s *sqlGen) mssql() {
	for _, schema := range s.schemaNames() {
		if schema != s.defaultSchema && s.quote(schema) != "" {
			// CREATE SCHEMA has to be the only statement in its batch, hence EXEC.
			s.statement(fmt.Sprintf("IF SCHEMA_ID(N%s) IS NULL EXEC(N%s)",
				ormSQLString(schema), ormSQLString("CREATE SCHEMA "+s.quote(schema))))
		}
	}
	for _, m := range s.models {
		if m.view {
			s.warn("The definition of %s %s is not read for SQL Server; it was left out.", m.Kind, s.label(m))
			continue
		}
		if !s.writable(m) {
			continue
		}
		var lines []string
		for _, c := range m.cols {
			line := "  " + s.quote(c.Name) + " "
			switch {
			case c.Generated && c.GeneratedExpr != "":
				line += "AS " + c.GeneratedExpr
				lines = append(lines, line)
				continue
			case c.t.Name == "rowversion":
				line += "rowversion"
			default:
				line += strings.TrimSpace(c.Type)
			}
			if c.def.Kind == ormDefAuto {
				line += " IDENTITY(1,1)"
			} else if strings.TrimSpace(c.Default) != "" {
				line += " DEFAULT " + strings.TrimSpace(c.Default)
			}
			if c.Nullable {
				line += " NULL"
			} else {
				line += " NOT NULL"
			}
			lines = append(lines, line)
		}
		if pk := s.primaryKey(m); pk != "" {
			lines = append(lines, "  "+pk)
		}
		rel := s.rel(m.Schema, m.Name)
		stmt := fmt.Sprintf("CREATE TABLE %s (\n%s\n)", rel, strings.Join(lines, ",\n"))
		if s.opts.IfNotExists {
			stmt = fmt.Sprintf("IF OBJECT_ID(N%s, N'U') IS NULL\n", ormSQLString(rel)) + stmt
		}
		s.statement(stmt)
		for _, ix := range m.Indexes {
			if ix.Primary {
				continue
			}
			if ix.Partial || ix.Expression || len(ix.Columns) == 0 || s.quote(ix.Name) == "" {
				s.warn("Index %s on %s is filtered or computed and could not be reproduced.", ix.Name, s.label(m))
				continue
			}
			unique := ""
			if ix.Unique {
				unique = "UNIQUE "
			}
			stmt := fmt.Sprintf("CREATE %sINDEX %s ON %s (%s)", unique, s.quote(ix.Name), rel, s.quoteAll(ix.Columns))
			if s.opts.IfNotExists {
				stmt = fmt.Sprintf("IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N%s AND object_id = OBJECT_ID(N%s))\n",
					ormSQLString(ix.Name), ormSQLString(rel)) + stmt
			}
			s.statement(stmt)
		}
	}
	s.foreignKeys(func(_ *ormTable, name, stmt string) string {
		if !s.opts.IfNotExists || name == "" {
			return stmt
		}
		return fmt.Sprintf("IF OBJECT_ID(N%s, N'F') IS NULL\n", ormSQLString(s.quote(name))) + stmt
	})
}

// --- engines that keep the statement ---------------------------------------

var sqlCreateTableRe = regexp.MustCompile(`(?i)^(\s*CREATE\s+(?:TEMPORARY\s+)?TABLE\s+)(IF\s+NOT\s+EXISTS\s+)?`)

// verbatim writes the engine's own CREATE statement for each table, and
// assembles one from the catalogue only where the engine handed none back.
func (s *sqlGen) verbatim() {
	mysql := s.driver == DriverMySQL
	if mysql {
		// The engine's text carries each table's foreign keys inline, so a
		// table can name one that comes later in the script.
		s.statement("SET FOREIGN_KEY_CHECKS = 0")
		if !s.opts.Relations {
			s.warn("MySQL's own CREATE TABLE text includes each table's foreign keys; they are kept as the engine wrote them.")
		}
	}
	current := ""
	for _, m := range s.models {
		if !s.writable(m) {
			continue
		}
		if mysql && s.multiSchema && m.Schema != current {
			current = m.Schema
			s.statement("CREATE DATABASE IF NOT EXISTS " + s.quote(m.Schema))
			s.statement("USE " + s.quote(m.Schema))
		}
		ddl := strings.TrimSpace(m.CreateSQL)
		if m.view {
			if ddl == "" {
				s.warn("The definition of %s %s could not be read; it was left out.", m.Kind, s.label(m))
				continue
			}
			s.statement(ddl)
			continue
		}
		if ddl == "" {
			s.warn("%s: the engine returned no CREATE statement, so one was assembled from the catalogue; storage options and the like are missing from it.", s.label(m))
			s.statement(s.assembled(m))
		} else {
			if s.opts.IfNotExists && s.driver != DriverOracle {
				ddl = sqlCreateTableRe.ReplaceAllString(ddl, "${1}IF NOT EXISTS ")
			}
			s.statement(ddl)
		}
		if s.driver != DriverSQLite {
			continue
		}
		// SQLite keeps an index's statement apart from its table's, and the
		// table's is all that was read: indexes are rebuilt from their columns.
		for _, ix := range m.Indexes {
			if ix.Primary || strings.HasPrefix(ix.Name, "sqlite_autoindex_") {
				continue
			}
			if ix.Partial || ix.Expression || len(ix.Columns) == 0 {
				s.warn("Index %s on %s is partial or over an expression and could not be reproduced.", ix.Name, s.label(m))
				continue
			}
			unique, exists := "", ""
			if ix.Unique {
				unique = "UNIQUE "
			}
			if s.opts.IfNotExists {
				exists = "IF NOT EXISTS "
			}
			s.statement(fmt.Sprintf("CREATE %sINDEX %s%s ON %s (%s)", unique, exists, s.quote(ix.Name), s.quote(m.Name), s.quoteAll(ix.Columns)))
		}
	}
	if s.opts.IfNotExists && s.driver == DriverOracle {
		s.warn("Oracle has no IF NOT EXISTS for CREATE TABLE before 23c; the statements are plain CREATEs.")
	}
	if mysql {
		s.statement("SET FOREIGN_KEY_CHECKS = 1")
	}
}

// assembled is a plain CREATE TABLE from the catalogue: columns, defaults, the
// primary key. It is the fallback for an engine that should have had its own
// text and did not.
func (s *sqlGen) assembled(m *ormTable) string {
	var lines []string
	for _, c := range m.cols {
		line := "  " + s.quote(c.Name) + " " + strings.TrimSpace(c.Type)
		if !c.Nullable && s.driver != DriverClickHouse {
			line += " NOT NULL"
		}
		if strings.TrimSpace(c.Default) != "" && c.def.Kind != ormDefAuto {
			line += " DEFAULT " + c.def.sql(s.driver)
		}
		if c.def.Kind == ormDefAuto && s.driver == DriverMySQL {
			line += " AUTO_INCREMENT"
		}
		lines = append(lines, line)
	}
	if pk := s.primaryKey(m); pk != "" && s.driver != DriverClickHouse {
		lines = append(lines, "  "+pk)
	}
	exists := ""
	if s.opts.IfNotExists && s.driver != DriverOracle {
		exists = "IF NOT EXISTS "
	}
	return fmt.Sprintf("CREATE TABLE %s%s (\n%s\n)", exists, s.rel(m.Schema, m.Name), strings.Join(lines, ",\n"))
}
