package dbx

import (
	"fmt"
	"strings"
)

// Prisma.
//
// The shape follows what `prisma db pull` writes, because that is the file a
// Prisma user will compare this one against: models named after their tables,
// a named relation with both ends present, native types as @db.* where they
// differ from the scalar's default, and Unsupported("…") for a column Prisma
// has no scalar for — which keeps the column in the schema and honest, where
// String would let the client write text into a tsvector.

// prismaProvider maps our driver identity onto Prisma's datasource provider.
// The engines Prisma has no connector for never reach here: the target table
// refuses them before a line is written.
func prismaProvider(driver Driver, flavor string) string {
	switch driver {
	case DriverMySQL:
		return "mysql"
	case DriverSQLite:
		return "sqlite"
	case DriverMSSQL:
		return "sqlserver"
	}
	if flavor == "cockroachdb" {
		return "cockroachdb"
	}
	return "postgresql"
}

// prismaReserved are the names Prisma Client refuses for a model because the
// generated JavaScript could not declare them.
var prismaReserved = ormWordSet(`async await break case catch class const continue debugger default delete
	do else enum export extends false finally for function if implements import in instanceof
	interface let new null package private protected public return super switch this throw true try
	using typeof var void while with yield PrismaClient`)

// prismaIdent makes a name Prisma's grammar accepts: letters, digits and
// underscores, opening with a letter. The original survives through @map.
func prismaIdent(name string) string {
	s := strings.TrimLeft(sanitizeIdent(name), "_0123456789")
	if s == "" {
		return "field"
	}
	return s
}

func prismaModelName(name string) string {
	if prismaReserved[name] {
		return "Renamed" + name
	}
	return name
}

type prismaGen struct {
	*ormGen
	names    *ormNaming
	provider string
	// ignored are the models Prisma Client cannot address, for want of anything
	// that identifies a row.
	ignored map[*ormTable]bool
}

func generatePrisma(g *ormGen) []ORMFile {
	p := &prismaGen{ormGen: g, provider: prismaProvider(g.driver, g.flavor), ignored: map[*ormTable]bool{}}
	rules := ormNameRules{
		model:     func(s string) string { return prismaIdent(s) },
		field:     prismaIdent,
		rel:       prismaIdent,
		enum:      prismaIdent,
		escapeTop: prismaModelName,
		manyBase:  pluralFieldName,
	}
	if g.opts.Naming == ORMNamingCamel {
		rules.model = func(s string) string { return prismaIdent(pascal(singular(s))) }
		rules.field = func(s string) string { return prismaIdent(ormCamel(s)) }
		rules.rel = rules.field
		rules.enum = func(s string) string { return prismaIdent(pascal(s)) }
		rules.manyBase = nil
	}
	p.names = g.names(rules)

	for _, m := range g.models {
		if !m.view && !p.identifiable(m) {
			p.ignored[m] = true
			g.warn("%s has no primary key or required unique column, so Prisma Client cannot address its rows; the model is marked @@ignore.", g.label(m))
		}
	}

	schemas := g.schemaNames()
	multi := g.multiSchema
	if multi && p.provider == "mysql" {
		// Prisma's multi-schema support covers PostgreSQL, CockroachDB and SQL
		// Server. Its MySQL connector reads the one database in the URL, and
		// two models mapped to one table name are a validation error.
		g.refuse("Prisma's MySQL connector reads one database per connection, and these tables are in %d (%s). Generate one database at a time.",
			len(schemas), strings.Join(schemas, ", "))
		return nil
	}
	if !multi && len(schemas) == 1 && len(g.models) > 0 && g.qualified(g.models[0]) {
		g.warn("The tables are in schema %q rather than the default: add ?schema=%s to DATABASE_URL.", schemas[0], schemas[0])
	}
	views := false
	for _, m := range g.models {
		views = views || m.view
	}

	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// A reviewed starting point: verify types, defaults and relation\n")
	b.WriteString("// names before committing. Set DATABASE_URL in your environment.\n\n")
	b.WriteString("datasource db {\n")
	fmt.Fprintf(&b, "  provider = %q\n", p.provider)
	modern := g.opts.PrismaVersion == "7"
	if !modern {
		b.WriteString("  url      = env(\"DATABASE_URL\")\n")
	}
	if multi {
		fmt.Fprintf(&b, "  schemas  = [%s]\n", strings.Join(jsStrings(schemas), ", "))
	}
	b.WriteString("}\n\n")
	b.WriteString("generator client {\n  provider = \"prisma-client-js\"\n")
	var preview []string
	if multi && !modern {
		// Prisma 6.13 made this general; the releases before it need the flag
		// and the ones after only remark on it.
		preview = append(preview, "multiSchema")
	}
	if views {
		preview = append(preview, "views")
	}
	if len(preview) > 0 {
		fmt.Fprintf(&b, "  previewFeatures = [%s]\n", strings.Join(jsStrings(preview), ", "))
	}
	b.WriteString("}\n")

	for _, m := range g.models {
		p.model(&b, m, multi)
	}
	for _, e := range g.enums {
		p.enum(&b, e, multi)
	}

	files := []ORMFile{{Filename: "schema.prisma", Content: b.String()}}
	if modern {
		files = append(files, ORMFile{Filename: "prisma.config.ts", Content: prismaConfigFile})
	}
	return files
}

// prismaConfigFile is where Prisma 7 reads the connection from, now that the
// schema may not carry it.
const prismaConfigFile = `// Generated by Just Dashboard. Prisma 7 reads the connection from this file
// instead of the schema. Set DATABASE_URL in your environment.

import { defineConfig, env } from "prisma/config"

export default defineConfig({
  schema: "schema.prisma",
  datasource: {
    url: env("DATABASE_URL"),
  },
})
`

// identifiable reports whether Prisma has a way to pick one row of a model: a
// primary key, or a unique index none of whose columns can be null.
func (p *prismaGen) identifiable(m *ormTable) bool {
	usable := func(cols []string) bool {
		if len(cols) == 0 {
			return false
		}
		for _, name := range cols {
			c := m.byCol[name]
			if c == nil {
				return false
			}
			if _, _, ok := p.scalar(c); !ok {
				return false
			}
		}
		return true
	}
	if usable(m.PrimaryKey) {
		return true
	}
	for _, ix := range m.uniques {
		required := true
		for _, name := range ix.Columns {
			if c := m.byCol[name]; c == nil || c.Nullable {
				required = false
			}
		}
		if required && usable(ix.Columns) {
			return true
		}
	}
	return false
}

func (p *prismaGen) model(b *strings.Builder, m *ormTable, multi bool) {
	name := p.names.model[m]
	b.WriteString("\n")
	if m.Comment != "" {
		fmt.Fprintf(b, "/// %s\n", ormOneLine(m.Comment))
	}
	if p.ignored[m] {
		b.WriteString("/// The table has nothing that identifies a row, so Prisma Client cannot use it.\n")
	}
	keyword := "model"
	if m.view {
		keyword = "view"
	}
	fmt.Fprintf(b, "%s %s {\n", keyword, name)

	field := func(cols []string) []string {
		out := make([]string, len(cols))
		for i, c := range cols {
			out[i] = p.names.field[m.byCol[c]]
		}
		return out
	}

	for _, c := range m.cols {
		if c.Comment != "" {
			fmt.Fprintf(b, "  /// %s\n", ormOneLine(c.Comment))
		}
		scalar, native, supported := p.scalar(c)
		fname := p.names.field[c]
		typ := scalar
		switch {
		case c.t.Array && supported:
			// A scalar list is never optional in Prisma: an absent list is an
			// empty one.
			typ += "[]"
		case c.Nullable:
			typ += "?"
		}
		line := fmt.Sprintf("  %s %s", fname, typ)
		if len(m.PrimaryKey) == 1 && m.pk[c.Name] && !m.view {
			line += " @id"
		}
		if ix, ok := m.uniqueOn(c.Name); ok {
			line += " @unique"
			if ix.Name != "" && ix.Name != m.Name+"_"+c.Name+"_key" {
				line += fmt.Sprintf("(map: %s)", jsString(ix.Name))
			}
		}
		if p.opts.Defaults {
			if def := p.defaultAttr(c, scalar, supported); def != "" {
				line += " " + def
			}
		}
		if fname != c.Name {
			line += fmt.Sprintf(" @map(%s)", jsString(c.Name))
		}
		if native != "" {
			line += " @db." + native
		}
		if !supported {
			p.warn("%s.%s has type %s, which Prisma has no scalar for; it is emitted as Unsupported and Prisma Client will not read or write it.",
				p.label(m), c.Name, c.Type)
		}
		if c.Generated {
			p.warn("%s.%s is a generated column: the database computes it, so do not write to it.", p.label(m), c.Name)
		}
		b.WriteString(line + "\n")
	}

	// Forward relations, one per foreign key.
	for _, r := range m.rels {
		if !r.to.isKey(r.fk.RefColumns) {
			p.warn("%s.%s references columns of %s that are not a key there; Prisma cannot model the relation and it was left out.",
				p.label(m), strings.Join(r.fk.Columns, ", "), p.label(r.to))
			continue
		}
		optional := ""
		if r.optional {
			optional = "?"
		}
		line := fmt.Sprintf("  %s %s%s @relation(%s, fields: [%s], references: [%s]",
			p.names.fwd[r], p.names.model[r.to], optional, jsString(r.name),
			strings.Join(field(r.fk.Columns), ", "),
			strings.Join(mapFields(r.fk.RefColumns, func(c string) string {
				return p.names.field[r.to.byCol[c]]
			}), ", "))
		if a := p.action(r.fk.OnDelete); a != "" {
			line += ", onDelete: " + a
		}
		if a := p.action(r.fk.OnUpdate); a != "" {
			line += ", onUpdate: " + a
		}
		b.WriteString(line + ")\n")
	}
	// Back-relations: Prisma requires both ends of a relation.
	for _, r := range m.back {
		if !m.isKey(r.fk.RefColumns) {
			continue
		}
		arity := "[]"
		if r.unique {
			arity = "?"
		}
		line := fmt.Sprintf("  %s %s%s @relation(%s)", p.names.back[r], p.names.model[r.from], arity, jsString(r.name))
		if p.ignored[r.from] && !p.ignored[m] {
			line += " @ignore"
		}
		b.WriteString(line + "\n")
	}

	var attrs []string
	if len(m.PrimaryKey) > 1 && !m.view {
		attrs = append(attrs, fmt.Sprintf("@@id([%s])", strings.Join(field(m.PrimaryKey), ", ")))
	}
	for _, ix := range m.compositeUniques() {
		attr := fmt.Sprintf("@@unique([%s]", strings.Join(field(ix.Columns), ", "))
		if ix.Name != "" && ix.Name != m.Name+"_"+strings.Join(ix.Columns, "_")+"_key" {
			attr += ", map: " + jsString(ix.Name)
		}
		attrs = append(attrs, attr+")")
	}
	for _, ix := range m.indexes {
		if attr := p.index(m, ix); attr != "" {
			attrs = append(attrs, attr)
		}
	}
	if name != m.Name {
		attrs = append(attrs, fmt.Sprintf("@@map(%s)", jsString(m.Name)))
	}
	if p.ignored[m] {
		attrs = append(attrs, "@@ignore")
	}
	if multi {
		attrs = append(attrs, fmt.Sprintf("@@schema(%s)", jsString(m.Schema)))
	}
	if len(attrs) > 0 {
		b.WriteString("\n")
		for _, a := range attrs {
			b.WriteString("  " + a + "\n")
		}
	}
	b.WriteString("}\n")
}

// index renders a plain index. The access methods other than b-tree and hash
// take operator classes Prisma checks against the field type, so only the one
// combination that needs none — GIN over JSON or a list — is written; the rest
// are reported instead of being declared as the b-tree they are not.
func (p *prismaGen) index(m *ormTable, ix ORMIndex) string {
	method := strings.ToLower(ix.Method)
	typ := ""
	switch method {
	case "", "btree":
	case "hash":
		if p.provider != "postgresql" || len(ix.Columns) != 1 {
			method = ""
			break
		}
		typ = "Hash"
	case "gin":
		typ = "Gin"
		for _, name := range ix.Columns {
			c := m.byCol[name]
			if p.provider != "postgresql" || (c.t.Kind != ormJSON || c.t.Name != "jsonb") && !c.t.Array {
				typ = ""
			}
		}
		if typ == "" {
			p.warn("Index %s on %s uses the gin access method with an operator class Prisma has to be told about; it was left out.", ix.Name, p.label(m))
			return ""
		}
	default:
		p.warn("Index %s on %s uses the %s access method, which this target does not describe; it was left out.", ix.Name, p.label(m), method)
		return ""
	}
	cols := make([]string, len(ix.Columns))
	for i, name := range ix.Columns {
		cols[i] = p.names.field[m.byCol[name]]
		if i < len(ix.Desc) && ix.Desc[i] && typ == "" {
			cols[i] += "(sort: Desc)"
		}
	}
	attr := fmt.Sprintf("@@index([%s]", strings.Join(cols, ", "))
	if ix.Name != "" && ix.Name != m.Name+"_"+strings.Join(ix.Columns, "_")+"_idx" {
		attr += ", map: " + jsString(ix.Name)
	}
	if typ != "" {
		attr += ", type: " + typ
	}
	return attr + ")"
}

// action maps a referential action onto Prisma's word for it. SQL Server has
// no RESTRICT and Prisma rejects the word for that provider; NO ACTION is what
// the engine does in its place.
func (p *prismaGen) action(rule string) string {
	switch strings.ToUpper(strings.ReplaceAll(strings.TrimSpace(rule), "_", " ")) {
	case "NO ACTION":
		return "NoAction"
	case "RESTRICT":
		if p.provider == "sqlserver" {
			return "NoAction"
		}
		return "Restrict"
	case "CASCADE":
		return "Cascade"
	case "SET NULL":
		return "SetNull"
	case "SET DEFAULT":
		return "SetDefault"
	}
	return ""
}

func (p *prismaGen) enum(b *strings.Builder, e *ormEnum, multi bool) {
	name := p.names.enum[e]
	fmt.Fprintf(b, "\nenum %s {\n", name)
	for _, entry := range prismaEnumValues(e.Values) {
		if entry.ident != entry.value {
			fmt.Fprintf(b, "  %s @map(%s)\n", entry.ident, jsString(entry.value))
		} else {
			fmt.Fprintf(b, "  %s\n", entry.ident)
		}
	}
	var attrs []string
	// An enum read out of a column type has no object in the database to map to.
	if !e.inline && name != e.Name {
		attrs = append(attrs, fmt.Sprintf("@@map(%s)", jsString(e.Name)))
	}
	if multi {
		attrs = append(attrs, fmt.Sprintf("@@schema(%s)", jsString(e.Schema)))
	}
	if len(attrs) > 0 {
		b.WriteString("\n")
		for _, a := range attrs {
			b.WriteString("  " + a + "\n")
		}
	}
	b.WriteString("}\n")
}

type prismaEnumValue struct{ ident, value string }

// prismaEnumValues gives each enum label an identifier Prisma accepts. A label
// like "in-progress" or "" keeps its real value through @map.
func prismaEnumValues(values []string) []prismaEnumValue {
	used := newORMNamer(false)
	out := make([]prismaEnumValue, 0, len(values))
	for _, v := range values {
		ident := v
		if v == "" {
			ident = "EMPTY_ENUM_VALUE"
		} else if prismaIdent(v) != v {
			ident = prismaIdent(v)
		}
		out = append(out, prismaEnumValue{ident: used.take(ident), value: v})
	}
	return out
}

// enumIdent is the identifier a label was given, for a default that names it.
func prismaEnumIdent(values []string, value string) (string, bool) {
	for _, entry := range prismaEnumValues(values) {
		if entry.value == value {
			return entry.ident, true
		}
	}
	return "", false
}

// defaultAttr renders @default(...) for a column, or "" when it has none that
// Prisma can state.
func (p *prismaGen) defaultAttr(c *ormCol, scalar string, supported bool) string {
	generated := func(expr string) string {
		if p.provider == "sqlite" && !supported {
			return ""
		}
		return fmt.Sprintf("@default(dbgenerated(%s))", jsString(expr))
	}
	if c.Generated {
		return ""
	}
	d := c.def
	raw := d.sql(p.driver)
	if !supported {
		if d.Kind == ormDefNone || d.Kind == ormDefAssumedAuto || raw == "" {
			return ""
		}
		return generated(raw)
	}
	switch d.Kind {
	case ormDefAuto:
		if scalar != "Int" && scalar != "BigInt" {
			return ""
		}
		// CockroachDB's autoincrement() is unique_rowid(), which only fits a
		// BigInt; anything numbered from a real sequence is sequence().
		if p.provider == "cockroachdb" &&
			(scalar == "Int" || strings.HasPrefix(strings.ToLower(d.Raw), "nextval(")) {
			return "@default(sequence())"
		}
		return "@default(autoincrement())"
	case ormDefNow:
		if scalar == "DateTime" && !c.t.Array {
			return "@default(now())"
		}
		return generated(raw)
	case ormDefUUID:
		// The database generates it, which is what dbgenerated says; uuid()
		// would have Prisma Client make one up instead.
		return generated(d.Text)
	case ormDefString:
		if c.t.Array {
			return generated(raw)
		}
		if c.t.Enum != nil {
			if ident, ok := prismaEnumIdent(c.t.Enum.Values, d.Text); ok {
				return "@default(" + ident + ")"
			}
			return ""
		}
		if scalar == "String" {
			return "@default(" + jsString(d.Text) + ")"
		}
		return generated(raw)
	case ormDefNumber:
		switch scalar {
		case "Int", "BigInt":
			if strings.ContainsAny(d.Text, ".eE") {
				return generated(raw)
			}
			return "@default(" + d.Text + ")"
		case "Float", "Decimal":
			return "@default(" + d.Text + ")"
		}
		return generated(raw)
	case ormDefBool:
		if scalar == "Boolean" {
			return fmt.Sprintf("@default(%t)", d.Bool)
		}
		return generated(raw)
	case ormDefJSON:
		if scalar == "Json" {
			return "@default(" + jsString(d.Text) + ")"
		}
		return generated(raw)
	case ormDefEmptyArray:
		return "@default([])"
	case ormDefExpr:
		return generated(d.Text)
	}
	return ""
}

// scalar maps a column onto a Prisma scalar and, where the column's type is
// not the one that scalar defaults to on this provider, the @db.* attribute
// that says so. supported is false for a type Prisma has no scalar for; the
// scalar is then the Unsupported("…") form.
func (p *prismaGen) scalar(c *ormCol) (scalar, native string, supported bool) {
	t := c.t
	if t.Enum != nil {
		return p.names.enum[t.Enum], "", true
	}
	var ok bool
	switch p.provider {
	case "mysql":
		scalar, native, ok = prismaMySQLType(t)
	case "sqlite":
		scalar, ok = prismaSQLiteType(t)
	case "sqlserver":
		scalar, native, ok = prismaMSSQLType(t)
	case "cockroachdb":
		scalar, native, ok = prismaCockroachType(t)
	default:
		scalar, native, ok = prismaPostgresType(t)
	}
	if !ok {
		return fmt.Sprintf("Unsupported(%s)", jsString(strings.TrimSpace(c.Type))), "", false
	}
	return scalar, native, true
}

func ormPrecisionOr(t ormType, def int) int {
	if t.HasPrecision {
		return t.Precision
	}
	return def
}

func prismaSized(name string, n int) string {
	if n > 0 {
		return fmt.Sprintf("%s(%d)", name, n)
	}
	return name
}

func prismaPostgresType(t ormType) (scalar, native string, ok bool) {
	switch t.Kind {
	case ormBool:
		return "Boolean", "", true
	case ormInt16:
		return "Int", "SmallInt", true
	case ormInt32:
		return "Int", "", true
	case ormInt64:
		if t.Name == "oid" {
			return "Int", "Oid", true
		}
		return "BigInt", "", true
	case ormFloat32:
		return "Float", "Real", true
	case ormFloat64:
		return "Float", "", true
	case ormDecimal:
		if t.HasPrecision {
			return "Decimal", fmt.Sprintf("Decimal(%d, %d)", t.Precision, t.Scale), true
		}
		return "Decimal", "Decimal", true
	case ormMoney:
		return "Decimal", "Money", true
	case ormChar:
		return "String", prismaSized("Char", t.Length), true
	case ormVarchar:
		return "String", prismaSized("VarChar", t.Length), true
	case ormText:
		switch t.Name {
		case "text":
			return "String", "", true
		case "citext":
			return "String", "Citext", true
		}
	case ormUUID:
		return "String", "Uuid", true
	case ormJSON:
		if t.Name == "json" {
			return "Json", "Json", true
		}
		return "Json", "", true
	case ormXML:
		return "String", "Xml", true
	case ormBytes:
		return "Bytes", "", true
	case ormDate:
		return "DateTime", "Date", true
	case ormTime:
		if t.TZ {
			return "DateTime", fmt.Sprintf("Timetz(%d)", ormPrecisionOr(t, 6)), true
		}
		return "DateTime", fmt.Sprintf("Time(%d)", ormPrecisionOr(t, 6)), true
	case ormDateTime:
		return "DateTime", fmt.Sprintf("Timestamp(%d)", ormPrecisionOr(t, 6)), true
	case ormDateTimeTZ:
		return "DateTime", fmt.Sprintf("Timestamptz(%d)", ormPrecisionOr(t, 6)), true
	case ormNet:
		if t.Name == "inet" {
			return "String", "Inet", true
		}
	case ormBit:
		if t.Name == "varbit" {
			return "String", prismaSized("VarBit", t.Length), true
		}
		return "String", prismaSized("Bit", max(t.Length, 1)), true
	}
	return "", "", false
}

// prismaCockroachType is the cockroachdb provider's own native-type set, which
// shares PostgreSQL's wire protocol and not its type names.
func prismaCockroachType(t ormType) (scalar, native string, ok bool) {
	switch t.Kind {
	case ormBool:
		return "Boolean", "", true
	case ormInt16:
		return "Int", "Int2", true
	case ormInt32:
		return "Int", "", true
	case ormInt64:
		if t.Name == "oid" {
			return "Int", "Oid", true
		}
		return "BigInt", "", true
	case ormFloat32:
		return "Float", "Float4", true
	case ormFloat64:
		return "Float", "", true
	case ormDecimal:
		if t.HasPrecision {
			return "Decimal", fmt.Sprintf("Decimal(%d, %d)", t.Precision, t.Scale), true
		}
		return "Decimal", "Decimal", true
	case ormChar:
		return "String", prismaSized("Char", t.Length), true
	case ormVarchar:
		return "String", prismaSized("String", t.Length), true
	case ormText:
		if t.Name == "text" {
			return "String", "", true
		}
	case ormUUID:
		return "String", "Uuid", true
	case ormJSON:
		return "Json", "", true
	case ormBytes:
		return "Bytes", "", true
	case ormDate:
		return "DateTime", "Date", true
	case ormTime:
		if t.TZ {
			return "DateTime", fmt.Sprintf("Timetz(%d)", ormPrecisionOr(t, 6)), true
		}
		return "DateTime", fmt.Sprintf("Time(%d)", ormPrecisionOr(t, 6)), true
	case ormDateTime:
		return "DateTime", fmt.Sprintf("Timestamp(%d)", ormPrecisionOr(t, 6)), true
	case ormDateTimeTZ:
		return "DateTime", fmt.Sprintf("Timestamptz(%d)", ormPrecisionOr(t, 6)), true
	case ormNet:
		if t.Name == "inet" {
			return "String", "Inet", true
		}
	case ormBit:
		if t.Name == "varbit" {
			return "String", prismaSized("VarBit", t.Length), true
		}
		return "String", prismaSized("Bit", max(t.Length, 1)), true
	}
	return "", "", false
}

func prismaMySQLType(t ormType) (scalar, native string, ok bool) {
	unsigned := func(signed, uns string) string {
		if t.Unsigned {
			return uns
		}
		return signed
	}
	switch t.Kind {
	case ormBool:
		if t.Name == "bit" {
			return "Boolean", "Bit(1)", true
		}
		return "Boolean", "", true
	case ormInt8:
		return "Int", unsigned("TinyInt", "UnsignedTinyInt"), true
	case ormInt16:
		return "Int", unsigned("SmallInt", "UnsignedSmallInt"), true
	case ormInt32:
		if t.Name == "mediumint" {
			return "Int", unsigned("MediumInt", "UnsignedMediumInt"), true
		}
		return "Int", unsigned("", "UnsignedInt"), true
	case ormInt64:
		return "BigInt", unsigned("", "UnsignedBigInt"), true
	case ormFloat32:
		return "Float", "Float", true
	case ormFloat64:
		return "Float", "", true
	case ormDecimal:
		if t.HasPrecision {
			return "Decimal", fmt.Sprintf("Decimal(%d, %d)", t.Precision, t.Scale), true
		}
		return "Decimal", "Decimal(10, 0)", true
	case ormChar:
		return "String", fmt.Sprintf("Char(%d)", max(t.Length, 1)), true
	case ormVarchar:
		return "String", fmt.Sprintf("VarChar(%d)", max(t.Length, 1)), true
	case ormText:
		switch t.Name {
		case "tinytext":
			return "String", "TinyText", true
		case "text":
			return "String", "Text", true
		case "mediumtext":
			return "String", "MediumText", true
		case "longtext":
			return "String", "LongText", true
		}
	case ormJSON:
		return "Json", "", true
	case ormBytes:
		switch t.Name {
		case "binary":
			return "Bytes", fmt.Sprintf("Binary(%d)", max(t.Length, 1)), true
		case "varbinary":
			return "Bytes", fmt.Sprintf("VarBinary(%d)", max(t.Length, 1)), true
		case "tinyblob":
			return "Bytes", "TinyBlob", true
		case "blob":
			return "Bytes", "Blob", true
		case "mediumblob":
			return "Bytes", "MediumBlob", true
		case "longblob":
			return "Bytes", "", true
		}
	case ormBit:
		return "Bytes", fmt.Sprintf("Bit(%d)", max(t.Length, 1)), true
	case ormDate:
		return "DateTime", "Date", true
	case ormTime:
		return "DateTime", fmt.Sprintf("Time(%d)", ormPrecisionOr(t, 0)), true
	case ormDateTime:
		return "DateTime", fmt.Sprintf("DateTime(%d)", ormPrecisionOr(t, 0)), true
	case ormDateTimeTZ:
		return "DateTime", fmt.Sprintf("Timestamp(%d)", ormPrecisionOr(t, 0)), true
	case ormYear:
		return "Int", "Year", true
	}
	return "", "", false
}

// prismaSQLiteType has no native types to annotate: SQLite has storage
// classes, and Prisma's sqlite provider has only the scalars.
func prismaSQLiteType(t ormType) (scalar string, ok bool) {
	switch t.Kind {
	case ormBool:
		return "Boolean", true
	case ormInt8, ormInt16, ormInt32, ormYear:
		return "Int", true
	case ormInt64:
		return "BigInt", true
	case ormFloat32, ormFloat64:
		return "Float", true
	case ormDecimal, ormMoney:
		return "Decimal", true
	case ormChar, ormVarchar, ormText, ormUUID, ormTime:
		return "String", true
	case ormJSON:
		return "Json", true
	case ormBytes:
		return "Bytes", true
	case ormDate, ormDateTime, ormDateTimeTZ:
		return "DateTime", true
	}
	return "", false
}

func prismaMSSQLType(t ormType) (scalar, native string, ok bool) {
	sized := func(name string) string {
		switch {
		case t.Length < 0:
			return name + "(Max)"
		case t.Length > 0:
			return fmt.Sprintf("%s(%d)", name, t.Length)
		}
		return name
	}
	switch t.Kind {
	case ormBool:
		return "Boolean", "", true
	case ormInt8:
		return "Int", "TinyInt", true
	case ormInt16:
		return "Int", "SmallInt", true
	case ormInt32:
		return "Int", "", true
	case ormInt64:
		return "BigInt", "", true
	case ormFloat32:
		return "Float", "Real", true
	case ormFloat64:
		return "Float", "", true
	case ormDecimal:
		if t.HasPrecision {
			return "Decimal", fmt.Sprintf("Decimal(%d, %d)", t.Precision, t.Scale), true
		}
		return "Decimal", "Decimal(18, 0)", true
	case ormMoney:
		if t.Name == "smallmoney" {
			return "Float", "SmallMoney", true
		}
		return "Float", "Money", true
	case ormChar:
		if t.Name == "nchar" {
			return "String", sized("NChar"), true
		}
		return "String", sized("Char"), true
	case ormVarchar:
		if t.Name == "nvarchar" {
			return "String", sized("NVarChar"), true
		}
		return "String", sized("VarChar"), true
	case ormText:
		if t.Name == "ntext" {
			return "String", "NText", true
		}
		return "String", "Text", true
	case ormUUID:
		return "String", "UniqueIdentifier", true
	case ormXML:
		return "String", "Xml", true
	case ormBytes:
		switch t.Name {
		case "binary":
			return "Bytes", sized("Binary"), true
		case "varbinary":
			return "Bytes", sized("VarBinary"), true
		case "image":
			return "Bytes", "Image", true
		}
	case ormDate:
		return "DateTime", "Date", true
	case ormTime:
		return "DateTime", "Time", true
	case ormDateTime:
		switch t.Name {
		case "datetime":
			return "DateTime", "DateTime", true
		case "smalldatetime":
			return "DateTime", "SmallDateTime", true
		}
		return "DateTime", "", true
	case ormDateTimeTZ:
		return "DateTime", "DateTimeOffset", true
	}
	return "", "", false
}
