package dbx

import (
	"fmt"
	"strings"
)

// TypeORM.
//
// Entities in the shape typeorm-model-generator made familiar: the column's
// database type stated on every @Column so `synchronize` has nothing to guess,
// indexes and unique constraints as class decorators under their real names,
// and each foreign key as a relation on both entities, with the scalar key
// column kept beside it. Relation properties are typed Relation<T>, which is
// what lets the entities import each other as ES modules.

var typeormImports = strings.Fields(`Column Entity Index JoinColumn ManyToOne OneToMany OneToOne
	PrimaryColumn PrimaryGeneratedColumn Relation Unique ViewColumn ViewEntity`)

type typeormGen struct {
	*ormGen
	names *ormNaming
}

func generateTypeORM(g *ormGen) []ORMFile {
	t := &typeormGen{ormGen: g}
	rules := tsClassRules(g, typeormImports...)
	rules.modelSuffix = "Entity"
	t.names = g.names(rules)

	var units []*tsUnit
	if u := tsEnumUnit(g, t.names); u != nil {
		units = append(units, u)
	}
	for _, m := range g.models {
		units = append(units, t.entity(m))
	}
	header := "// Generated by Just Dashboard from live database introspection.\n" +
		"// A reviewed starting point: verify types, defaults and relations. Keep\n" +
		"// `synchronize` off when pointing a DataSource at a database that already exists.\n"
	return tsLayout(header, units, g.opts.Split, "entities.ts")
}

// enumName is the enum type's name as TypeORM has to be given it. TypeORM
// writes an entity's schema in front of the name, and failing that takes a
// dotted name as schema and type; so an enum that lives outside its entity's
// schema can be named when the entity states no schema, and not otherwise.
func (t *typeormGen) enumName(m *ormTable, c *ormCol, e *ormEnum) string {
	switch {
	case e.Schema == "" || e.Schema == m.Schema:
	case !t.qualified(m) && !strings.Contains(e.Schema+e.Name, "."):
		return e.Schema + "." + e.Name
	default:
		t.warn("%s.%s uses enum type %s.%s, and TypeORM looks for an entity's enum types in the entity's own schema; leave synchronize off, or it creates a second %s there.",
			t.label(m), c.Name, e.Schema, e.Name, e.Name)
	}
	return e.Name
}

// typeormColumn maps a column onto the type name TypeORM's driver for the
// engine accepts, the options that go with it, and the property's TypeScript
// type. known is false for a type the driver has no name for.
func (t *typeormGen) column(m *ormTable, c *ormCol) (typ string, opts []string, ts string, known bool) {
	ct := c.t
	precision := func() {
		if ct.HasPrecision {
			opts = append(opts, fmt.Sprintf("precision: %d", ct.Precision))
		}
	}
	decimal := func() {
		if ct.HasPrecision {
			opts = append(opts, fmt.Sprintf("precision: %d", ct.Precision), fmt.Sprintf("scale: %d", ct.Scale))
		}
	}
	length := func() {
		switch {
		case ct.Length < 0:
			opts = append(opts, `length: "max"`)
		case ct.Length > 0:
			opts = append(opts, fmt.Sprintf("length: %d", ct.Length))
		}
	}
	if ct.Kind == ormEnumKind && ct.Enum != nil {
		name := t.names.enum[ct.Enum]
		opts = append(opts, "enum: "+name)
		if !ct.Enum.inline {
			opts = append(opts, "enumName: "+jsString(t.enumName(m, c, ct.Enum)))
		}
		return "enum", opts, name, true
	}

	switch t.driver {
	case DriverPostgres:
		switch ct.Kind {
		case ormBool:
			return "boolean", nil, "boolean", true
		case ormInt16:
			return "smallint", nil, "number", true
		case ormInt32:
			return "integer", nil, "number", true
		case ormInt64:
			if ct.Name == "oid" {
				return "", nil, "", false
			}
			return "bigint", nil, "string", true
		case ormFloat32:
			return "real", nil, "number", true
		case ormFloat64:
			return "double precision", nil, "number", true
		case ormDecimal:
			decimal()
			return "numeric", opts, "string", true
		case ormMoney:
			return "money", nil, "string", true
		case ormChar:
			length()
			return "char", opts, "string", true
		case ormVarchar:
			length()
			return "varchar", opts, "string", true
		case ormText:
			if ct.Name == "name" {
				return "", nil, "", false
			}
			return ct.Name, nil, "string", true
		case ormUUID:
			return "uuid", nil, "string", true
		case ormJSON:
			return ct.Name, nil, "unknown", true
		case ormXML:
			return "xml", nil, "string", true
		case ormBytes:
			return "bytea", nil, "Buffer", true
		case ormDate:
			return "date", nil, "string", true
		case ormTime:
			precision()
			if ct.TZ {
				return "time with time zone", opts, "string", true
			}
			return "time", opts, "string", true
		case ormDateTime:
			precision()
			return "timestamp", opts, "Date", true
		case ormDateTimeTZ:
			precision()
			return "timestamp with time zone", opts, "Date", true
		case ormInterval:
			// The driver hands back its own interval object, not a string.
			return "interval", nil, "unknown", true
		case ormNet:
			return ct.Name, nil, "string", true
		case ormBit:
			length()
			if ct.Name == "varbit" {
				return "bit varying", opts, "string", true
			}
			return "bit", opts, "string", true
		case ormGeo:
			switch ct.Name {
			case "point", "line", "lseg", "box", "circle", "path", "polygon":
				return ct.Name, nil, "unknown", true
			}
		case ormUnknown:
			if strings.EqualFold(strings.TrimSpace(c.Type), "tsvector") {
				return "tsvector", nil, "string", true
			}
		}

	case DriverMySQL:
		unsigned := func() {
			if ct.Unsigned {
				opts = append(opts, "unsigned: true")
			}
		}
		switch ct.Kind {
		case ormBool:
			if ct.Name == "bit" {
				return "bit", nil, "Buffer", true
			}
			return "boolean", nil, "boolean", true
		case ormInt8, ormInt16:
			unsigned()
			return ct.Name, opts, "number", true
		case ormInt32:
			unsigned()
			return ct.Name, opts, "number", true
		case ormInt64:
			unsigned()
			return "bigint", opts, "string", true
		case ormFloat32:
			return "float", nil, "number", true
		case ormFloat64:
			return "double", nil, "number", true
		case ormDecimal:
			decimal()
			return "decimal", opts, "string", true
		case ormChar, ormVarchar:
			length()
			return ct.Name, opts, "string", true
		case ormText:
			return ct.Name, nil, "string", true
		case ormJSON:
			return "json", nil, "unknown", true
		case ormBytes:
			if ct.Name == "binary" || ct.Name == "varbinary" {
				length()
			}
			return ct.Name, opts, "Buffer", true
		case ormBit:
			return "bit", nil, "Buffer", true
		case ormDate:
			return "date", nil, "string", true
		case ormTime:
			precision()
			return "time", opts, "string", true
		case ormDateTime:
			precision()
			return "datetime", opts, "Date", true
		case ormDateTimeTZ:
			precision()
			return "timestamp", opts, "Date", true
		case ormYear:
			return "year", nil, "number", true
		case ormSet:
			opts = append(opts, "enum: ["+strings.Join(jsStrings(ct.Values), ", ")+"]")
			return "set", opts, "string[]", true
		case ormGeo:
			return ct.Name, nil, "unknown", true
		}

	case DriverSQLite:
		switch ct.Kind {
		case ormBool:
			return "boolean", nil, "boolean", true
		case ormInt8, ormInt16, ormInt32, ormYear:
			return "integer", nil, "number", true
		case ormInt64:
			return "bigint", nil, "number", true
		case ormFloat32, ormFloat64:
			return "real", nil, "number", true
		case ormDecimal, ormMoney:
			return "numeric", nil, "number", true
		case ormChar, ormVarchar:
			length()
			return "varchar", opts, "string", true
		case ormText, ormUUID:
			return "text", nil, "string", true
		case ormJSON:
			return "simple-json", nil, "unknown", true
		case ormBytes:
			return "blob", nil, "Buffer", true
		case ormDate:
			return "date", nil, "string", true
		case ormTime:
			return "time", nil, "string", true
		case ormDateTime, ormDateTimeTZ:
			return "datetime", nil, "Date", true
		}

	case DriverMSSQL:
		switch ct.Kind {
		case ormBool:
			return "bit", nil, "boolean", true
		case ormInt8, ormInt16, ormInt32:
			return ct.Name, nil, "number", true
		case ormInt64:
			return "bigint", nil, "string", true
		case ormFloat32:
			return "real", nil, "number", true
		case ormFloat64:
			return "float", nil, "number", true
		case ormDecimal:
			decimal()
			return ct.Name, opts, "number", true
		case ormMoney:
			return ct.Name, nil, "number", true
		case ormChar, ormVarchar:
			length()
			return ct.Name, opts, "string", true
		case ormText:
			return ct.Name, nil, "string", true
		case ormUUID:
			return "uniqueidentifier", nil, "string", true
		case ormXML:
			return "xml", nil, "string", true
		case ormBytes:
			if ct.Name == "binary" || ct.Name == "varbinary" {
				length()
			}
			return ct.Name, opts, "Buffer", true
		case ormDate, ormTime, ormDateTime, ormDateTimeTZ:
			return ct.Name, nil, "Date", true
		case ormGeo:
			return ct.Name, nil, "unknown", true
		}

	case DriverOracle:
		switch ct.Kind {
		case ormBool:
			return "number", []string{"precision: 1", "scale: 0"}, "boolean", true
		case ormInt32, ormInt64, ormDecimal:
			decimal()
			return "number", opts, "number", true
		case ormFloat32, ormFloat64:
			return "float", nil, "number", true
		case ormChar, ormVarchar:
			length()
			return ct.Name, opts, "string", true
		case ormText:
			return ct.Name, nil, "string", true
		case ormBytes:
			if ct.Name == "raw" {
				length()
				return "raw", opts, "Buffer", true
			}
			if ct.Name == "bfile" || ct.Name == "long raw" || ct.Name == "blob" {
				return ct.Name, nil, "Buffer", true
			}
		case ormDateTime:
			if ct.Name == "date" {
				return "date", nil, "Date", true
			}
			precision()
			return "timestamp", opts, "Date", true
		case ormDateTimeTZ:
			precision()
			return ct.Name, opts, "Date", true
		case ormInterval:
			return ct.Name, nil, "string", true
		}
	}
	return "", nil, "", false
}

func (t *typeormGen) entity(m *ormTable) *tsUnit {
	class := t.names.model[m]
	u := newTSUnit(class, class)
	prop := func(cols []string) string {
		out := make([]string, len(cols))
		for i, c := range cols {
			out[i] = jsString(t.names.field[m.byCol[c]])
		}
		return "[" + strings.Join(out, ", ") + "]"
	}

	var b strings.Builder
	b.WriteString(tsDocComment("", m.Comment))
	if len(m.PrimaryKey) == 0 && !m.view {
		t.warn("%s has no primary key. TypeORM needs one to load an entity: mark the columns that identify a row with @PrimaryColumn.", t.label(m))
		b.WriteString("// No primary key in the database. TypeORM needs one: mark the identifying columns with @PrimaryColumn.\n")
	}

	var where []string
	if t.qualified(m) {
		if t.driver == DriverMySQL {
			where = append(where, "database: "+jsString(m.Schema))
		} else {
			where = append(where, "schema: "+jsString(m.Schema))
		}
	}
	if m.view {
		u.use("typeorm", "ViewEntity", "ViewColumn")
		parts := append([]string{"name: " + jsString(m.Name)}, where...)
		if m.Kind == ORMKindMatView {
			parts = append(parts, "materialized: true")
		}
		// The view exists; TypeORM is told not to create or replace it.
		parts = append(parts, "synchronize: false")
		fmt.Fprintf(&b, "@ViewEntity(%s)\n", jsObject(parts))
	} else {
		for _, ix := range m.uniques {
			u.use("typeorm", "Index")
			fmt.Fprintf(&b, "@Index(%s, %s, { unique: true })\n", jsString(ix.Name), prop(ix.Columns))
		}
		for _, ix := range t.plainIndexes(m) {
			u.use("typeorm", "Index")
			fmt.Fprintf(&b, "@Index(%s, %s)\n", jsString(ix.Name), prop(ix.Columns))
		}
		u.use("typeorm", "Entity")
		if len(where) > 0 {
			fmt.Fprintf(&b, "@Entity(%s, %s)\n", jsString(m.Name), jsObject(where))
		} else {
			fmt.Fprintf(&b, "@Entity(%s)\n", jsString(m.Name))
		}
	}
	fmt.Fprintf(&b, "export class %s {\n", class)

	first := true
	member := func(lines ...string) {
		if !first {
			b.WriteString("\n")
		}
		first = false
		for _, l := range lines {
			b.WriteString("  " + l + "\n")
		}
	}

	for _, c := range m.cols {
		name := t.names.field[c]
		typ, opts, ts, known := t.column(m, c)
		if !known {
			t.warn("%s.%s has type %s, which TypeORM has no column type for; it is declared as text.", t.label(m), c.Name, c.Type)
			typ, opts, ts = "text", nil, "string"
		}
		if c.t.Array {
			ts += "[]"
			opts = append(opts, "array: true")
		}
		if e := c.t.Enum; e != nil {
			u.ref(t.names.enum[e])
		}
		declared := ts
		if c.Nullable && ts != "unknown" {
			declared += " | null"
		}
		var lines []string
		if c.Comment != "" {
			lines = append(lines, strings.TrimSuffix(tsDocComment("", c.Comment), "\n"))
		}
		if m.view {
			if name != c.Name {
				lines = append(lines, fmt.Sprintf("@ViewColumn({ name: %s })", jsString(c.Name)))
			} else {
				lines = append(lines, "@ViewColumn()")
			}
			member(append(lines, fmt.Sprintf("%s!: %s", name, declared))...)
			continue
		}

		parts := []string{"type: " + jsString(typ)}
		if name != c.Name {
			parts = append(parts, "name: "+jsString(c.Name))
		}
		pk := m.pk[c.Name]
		single := pk && len(m.PrimaryKey) == 1
		switch {
		case single && t.opts.Defaults && c.def.Kind == ormDefAuto && c.t.isInteger():
			u.use("typeorm", "PrimaryGeneratedColumn")
			if c.t.Unsigned {
				parts = append(parts, "unsigned: true")
			}
			if c.Identity == "always" || c.Identity == "by default" {
				parts = append(parts, "generatedIdentity: "+jsString(strings.ToUpper(c.Identity)))
				lines = append(lines, fmt.Sprintf("@PrimaryGeneratedColumn(\"identity\", %s)", jsObject(parts)))
			} else {
				lines = append(lines, fmt.Sprintf("@PrimaryGeneratedColumn(%s)", jsObject(parts)))
			}
		case single && t.opts.Defaults && c.def.Kind == ormDefUUID && c.t.Kind == ormUUID:
			u.use("typeorm", "PrimaryGeneratedColumn")
			if len(parts) > 1 {
				lines = append(lines, fmt.Sprintf("@PrimaryGeneratedColumn(\"uuid\", %s)", jsObject(parts[1:])))
			} else {
				lines = append(lines, `@PrimaryGeneratedColumn("uuid")`)
			}
		default:
			parts = append(parts, opts...)
			if c.Nullable {
				parts = append(parts, "nullable: true")
			}
			if t.opts.Defaults {
				parts = append(parts, t.defaults(c, ts)...)
			}
			decorator := "Column"
			if pk {
				decorator = "PrimaryColumn"
			}
			u.use("typeorm", decorator)
			lines = append(lines, fmt.Sprintf("@%s(%s)", decorator, jsObject(parts)))
		}
		member(append(lines, fmt.Sprintf("%s!: %s", name, declared))...)
	}

	for _, r := range m.rels {
		other := t.names.model[r.to]
		u.ref(other)
		u.use("typeorm", "JoinColumn", "type Relation")
		decorator := "ManyToOne"
		if r.unique {
			decorator = "OneToOne"
		}
		u.use("typeorm", decorator)
		var options []string
		if a := typeormAction(r.fk.OnDelete); a != "" {
			options = append(options, "onDelete: "+jsString(a))
		}
		if a := typeormAction(r.fk.OnUpdate); a != "" {
			options = append(options, "onUpdate: "+jsString(a))
		}
		head := fmt.Sprintf("@%s(() => %s, (other) => other.%s", decorator, other, t.names.back[r])
		if len(options) > 0 {
			head += ", " + jsObject(options)
		}
		var joins []string
		for i, col := range r.fk.Columns {
			parts := []string{
				"name: " + jsString(col),
				"referencedColumnName: " + jsString(t.names.field[r.to.byCol[r.fk.RefColumns[i]]]),
			}
			if i == 0 && r.fk.Name != "" {
				parts = append(parts, "foreignKeyConstraintName: "+jsString(r.fk.Name))
			}
			joins = append(joins, jsObject(parts))
		}
		join := "@JoinColumn(" + joins[0] + ")"
		if len(joins) > 1 {
			join = "@JoinColumn([" + strings.Join(joins, ", ") + "])"
		}
		declared := "Relation<" + other + ">"
		if r.optional {
			declared += " | null"
		}
		member(head+")", join, fmt.Sprintf("%s!: %s", t.names.fwd[r], declared))
	}
	for _, r := range m.back {
		other := t.names.model[r.from]
		u.ref(other)
		u.use("typeorm", "type Relation")
		if r.unique {
			u.use("typeorm", "OneToOne")
			member(fmt.Sprintf("@OneToOne(() => %s, (other) => other.%s)", other, t.names.fwd[r]),
				fmt.Sprintf("%s!: Relation<%s> | null", t.names.back[r], other))
			continue
		}
		u.use("typeorm", "OneToMany")
		member(fmt.Sprintf("@OneToMany(() => %s, (other) => other.%s)", other, t.names.fwd[r]),
			fmt.Sprintf("%s!: Relation<%s>[]", t.names.back[r], other))
	}
	b.WriteString("}\n")
	u.body = b.String()
	return u
}

// typeormAction is a referential action in TypeORM's words, or "" for the
// engine's default. TypeORM calls SET DEFAULT plain "DEFAULT".
func typeormAction(rule string) string {
	switch a := ormAction(rule); a {
	case "", "NO ACTION":
		return ""
	case "SET DEFAULT":
		return "DEFAULT"
	default:
		return a
	}
}

// defaults renders a column's default (and MySQL's ON UPDATE) as @Column
// options. A literal is passed as one; anything the database computes is
// passed as a function returning its SQL, which is how TypeORM tells the two
// apart.
func (t *typeormGen) defaults(c *ormCol, ts string) []string {
	if c.Generated {
		if c.GeneratedExpr == "" {
			return []string{"insert: false", "update: false"}
		}
		return []string{`generatedType: "STORED"`, "asExpression: " + jsString(c.GeneratedExpr)}
	}
	raw := func(expr string) string { return "default: () => " + jsString(expr) }
	var out []string
	d := c.def
	switch d.Kind {
	case ormDefAuto:
		// A numbered column that is not the primary key: the sequence stays
		// the database's business.
		out = append(out, "insert: false")
	case ormDefNow, ormDefExpr, ormDefJSON:
		out = append(out, raw(d.sql(t.driver)))
	case ormDefUUID:
		out = append(out, raw(d.Text))
	case ormDefEmptyArray:
		out = append(out, raw(d.sql(t.driver)))
	case ormDefString:
		switch {
		case c.t.Array:
			out = append(out, raw(d.sql(t.driver)))
		case c.t.Enum != nil:
			if member, ok := tsEnumMember(c.t.Enum.Values, d.Text); ok {
				out = append(out, "default: "+t.names.enum[c.t.Enum]+"."+member)
			}
		default:
			out = append(out, "default: "+jsString(d.Text))
		}
	case ormDefNumber:
		if ts == "number" {
			out = append(out, "default: "+d.Text)
		} else {
			out = append(out, "default: "+jsString(d.Text))
		}
	case ormDefBool:
		if ts == "boolean" {
			out = append(out, fmt.Sprintf("default: %t", d.Bool))
		} else {
			out = append(out, raw(d.sql(t.driver)))
		}
	}
	if c.OnUpdateNow && t.driver == DriverMySQL {
		out = append(out, `onUpdate: "CURRENT_TIMESTAMP"`)
	}
	return out
}
