package dbx

import (
	"fmt"
	"strings"
)

// Eloquent.
//
// Laravel models that say what Eloquent would otherwise assume: the table's
// real name, a primary key that is not an auto-incrementing "id", whether the
// table has both timestamp columns, which columns may be mass-assigned and how
// each is cast. Relations are methods, one per foreign key on each side, with
// the key columns spelt out so nothing depends on Laravel's naming guesses.
//
// Eloquent has no composite keys, primary or foreign. A table with a composite
// primary key still gets a model to read through; a composite foreign key gets
// no relation. Both are reported.

// eloquentReserved are members every model already has. A relation method of
// the same name would replace Eloquent's own.
var eloquentReserved = strings.Fields(`save delete update fill push touch refresh fresh replicate load
	is query all with create destroy forceDelete restore increment decrement on table connection exists
	attributes relations casts fillable guarded hidden visible timestamps incrementing keyType
	primaryKey wasRecentlyCreated toArray toJson getTable getKey newQuery newInstance getAttribute
	setAttribute only except append`)

type eloquentGen struct {
	*ormGen
	names *ormNaming
}

// phpUnit is one declaration and the classes it has to import.
type phpUnit struct {
	name string
	body string
	uses map[string]bool
}

func generateEloquent(g *ormGen) []ORMFile {
	e := &eloquentGen{ormGen: g}
	e.names = g.names(ormNameRules{
		model: func(t string) string { return pascal(singular(t)) },
		field: func(c string) string { return c },
		rel:   ormCamel,
		enum:  pascal,
		top:   []string{"Model", "BelongsTo", "HasMany", "HasOne", "Carbon", "Collection"},
		escapeTop: func(s string) string {
			if phpReserved[strings.ToLower(s)] {
				return s + "Model"
			}
			return s
		},
		modelSuffix: "Model",
		member:      eloquentReserved,
		fold:        true,
	})

	var units []phpUnit
	for _, en := range g.enums {
		units = append(units, e.enum(en))
	}
	for _, m := range g.models {
		units = append(units, e.model(m))
	}

	const header = "<?php\n\n" +
		"// Generated by Just Dashboard from live database introspection.\n" +
		"// A reviewed starting point: verify casts, fillable columns and relations.\n\n" +
		"namespace App\\Models;\n"
	render := func(uses map[string]bool, bodies []string) string {
		var b strings.Builder
		b.WriteString(header)
		if len(uses) > 0 {
			b.WriteString("\n")
			for _, u := range ormSortedKeys(uses) {
				b.WriteString("use " + u + ";\n")
			}
		}
		for _, body := range bodies {
			b.WriteString("\n" + body)
		}
		return b.String()
	}

	if g.opts.Split {
		files := make([]ORMFile, 0, len(units))
		for _, u := range units {
			files = append(files, ORMFile{Filename: u.name + ".php", Content: render(u.uses, []string{u.body})})
		}
		return files
	}
	uses := map[string]bool{}
	var bodies []string
	for _, u := range units {
		for k := range u.uses {
			uses[k] = true
		}
		bodies = append(bodies, u.body)
	}
	return []ORMFile{{Filename: "Models.php", Content: render(uses, bodies)}}
}

// phpEnumCases gives each enum label a case name.
func phpEnumCases(values []string) [][2]string {
	used := newORMNamer(true)
	out := make([][2]string, 0, len(values))
	for _, v := range values {
		name := pascal(v)
		if len(ormIdentWords(v)) == 0 {
			name = "Empty"
		}
		if strings.EqualFold(name, "class") {
			// The one word PHP will not take as a constant's name.
			name = "Class_"
		}
		out = append(out, [2]string{used.take(name), v})
	}
	return out
}

func (e *eloquentGen) enum(en *ormEnum) phpUnit {
	name := e.names.enum[en]
	var b strings.Builder
	fmt.Fprintf(&b, "enum %s: string\n{\n", name)
	for _, c := range phpEnumCases(en.Values) {
		fmt.Fprintf(&b, "    case %s = %s;\n", c[0], phpString(c[1]))
	}
	b.WriteString("}\n")
	return phpUnit{name: name, body: b.String()}
}

// cast returns the Eloquent cast for a column, or "" where the value is best
// left as the string the driver returns, and the PHPDoc type that goes with it.
func (e *eloquentGen) cast(c *ormCol) (cast, doc string) {
	t := c.t
	if t.Array {
		return "", "string"
	}
	switch t.Kind {
	case ormBool:
		return phpString("boolean"), "bool"
	case ormInt8, ormInt16, ormInt32, ormInt64, ormYear:
		return phpString("integer"), "int"
	case ormFloat32, ormFloat64:
		return phpString("float"), "float"
	case ormDecimal:
		if t.HasPrecision {
			return phpString(fmt.Sprintf("decimal:%d", t.Scale)), "string"
		}
		return "", "string"
	case ormJSON:
		return phpString("array"), "array"
	case ormDate:
		return phpString("date"), `\Illuminate\Support\Carbon`
	case ormDateTime, ormDateTimeTZ:
		return phpString("datetime"), `\Illuminate\Support\Carbon`
	case ormEnumKind:
		if t.Enum != nil {
			return e.names.enum[t.Enum] + "::class", e.names.enum[t.Enum]
		}
	}
	return "", "string"
}

func (e *eloquentGen) model(m *ormTable) phpUnit {
	class := e.names.model[m]
	uses := map[string]bool{`Illuminate\Database\Eloquent\Model`: true}

	var doc, casts, fillable []string
	hasCol := func(name string) bool {
		c := m.byCol[name]
		return c != nil && (c.t.Kind == ormDateTime || c.t.Kind == ormDateTimeTZ)
	}
	timestamps := hasCol("created_at") && hasCol("updated_at") && !m.view
	pk := m.singlePK()

	for _, c := range m.cols {
		cast, docType := e.cast(c)
		if c.Nullable {
			docType += "|null"
		}
		doc = append(doc, fmt.Sprintf(" * @property %s $%s", docType, ormBlockComment(c.Name)))
		managed := timestamps && (c.Name == "created_at" || c.Name == "updated_at")
		if cast != "" && !managed {
			casts = append(casts, fmt.Sprintf("        %s => %s,", phpString(c.Name), cast))
		}
		auto := c.def.Kind == ormDefAuto || c.def.Kind == ormDefAssumedAuto
		if !c.Generated && !managed && !(pk == c && auto) && !m.view {
			fillable = append(fillable, "        "+phpString(c.Name)+",")
		}
	}

	var methods []string
	for _, r := range m.rels {
		if len(r.fk.Columns) != 1 {
			e.warn("%s.%s is a composite foreign key, which Eloquent relations cannot express; the relation was left out.",
				e.label(m), strings.Join(r.fk.Columns, ", "))
			continue
		}
		other := e.names.model[r.to]
		uses[`Illuminate\Database\Eloquent\Relations\BelongsTo`] = true
		doc = append(doc, fmt.Sprintf(" * @property-read %s%s $%s", other, map[bool]string{true: "|null"}[r.optional], e.names.fwd[r]))
		methods = append(methods, fmt.Sprintf("    public function %s(): BelongsTo\n    {\n        return $this->belongsTo(%s::class, %s, %s);\n    }\n",
			e.names.fwd[r], other, phpString(r.fk.Columns[0]), phpString(r.fk.RefColumns[0])))
	}
	for _, r := range m.back {
		if len(r.fk.Columns) != 1 {
			continue
		}
		other := e.names.model[r.from]
		kind, call := "HasMany", "hasMany"
		docType := fmt.Sprintf(`\Illuminate\Database\Eloquent\Collection<int, %s>`, other)
		if r.unique {
			kind, call = "HasOne", "hasOne"
			docType = other + "|null"
		}
		uses[`Illuminate\Database\Eloquent\Relations\`+kind] = true
		doc = append(doc, fmt.Sprintf(" * @property-read %s $%s", docType, e.names.back[r]))
		methods = append(methods, fmt.Sprintf("    public function %s(): %s\n    {\n        return $this->%s(%s::class, %s, %s);\n    }\n",
			e.names.back[r], kind, call, other, phpString(r.fk.Columns[0]), phpString(r.fk.RefColumns[0])))
	}

	var b strings.Builder
	b.WriteString("/**\n")
	if m.Comment != "" {
		fmt.Fprintf(&b, " * %s\n *\n", ormBlockComment(m.Comment))
	}
	if m.view {
		fmt.Fprintf(&b, " * Reads the %s %s; it cannot be written through.\n *\n", m.Kind, ormBlockComment(m.Name))
	}
	b.WriteString(strings.Join(doc, "\n") + "\n */\n")
	fmt.Fprintf(&b, "class %s extends Model\n{\n", class)

	table := m.Name
	if e.qualified(m) {
		table = m.Schema + "." + m.Name
	}
	fmt.Fprintf(&b, "    protected $table = %s;\n", phpString(table))

	switch {
	case pk == nil:
		if len(m.PrimaryKey) > 1 {
			e.warn("%s has a composite primary key, which Eloquent does not support: the model reads rows, but find(), save() on an existing row and delete() will not work.", e.label(m))
		} else if !m.view {
			e.warn("%s has no primary key: the model reads rows, but find(), save() on an existing row and delete() will not work.", e.label(m))
		}
		b.WriteString("\n    protected $primaryKey = null;\n\n    public $incrementing = false;\n")
	default:
		if pk.Name != "id" {
			fmt.Fprintf(&b, "\n    protected $primaryKey = %s;\n", phpString(pk.Name))
		}
		if pk.def.Kind != ormDefAuto && pk.def.Kind != ormDefAssumedAuto {
			b.WriteString("\n    public $incrementing = false;\n")
		}
		if !pk.t.isInteger() {
			b.WriteString("\n    protected $keyType = 'string';\n")
		}
	}
	if !timestamps {
		b.WriteString("\n    public $timestamps = false;\n")
	}
	if len(fillable) > 0 {
		b.WriteString("\n    protected $fillable = [\n" + strings.Join(fillable, "\n") + "\n    ];\n")
	}
	if len(casts) > 0 {
		b.WriteString("\n    protected $casts = [\n" + strings.Join(casts, "\n") + "\n    ];\n")
	}
	for _, method := range methods {
		b.WriteString("\n" + method)
	}
	b.WriteString("}\n")
	return phpUnit{name: class, body: b.String(), uses: uses}
}
