package dbx

import (
	"fmt"
	"sort"
	"strings"
)

// Drizzle.
//
// One schema.ts in the shape `drizzle-kit pull` writes: a table per export,
// the column's real name kept in the builder's first argument, constraints
// that span columns in the table's third argument, and a relations() block
// per table so the relational query API has both ends of every foreign key.
// A type Drizzle ships no builder for becomes a customType that names the
// database type exactly, because the alternative — text() — would let
// drizzle-kit rewrite the column on the next push.

// drizzleImport is the column-builder module for the driver.
func drizzleImport(driver Driver) (module, table string) {
	switch driver {
	case DriverMySQL:
		return "drizzle-orm/mysql-core", "mysqlTable"
	case DriverSQLite:
		return "drizzle-orm/sqlite-core", "sqliteTable"
	default:
		return "drizzle-orm/pg-core", "pgTable"
	}
}

// drizzleBuilders are the names each dialect module exports that a generated
// declaration could collide with: a table called "date" or "index" must not be
// declared over the builder of the same name.
var drizzleBuilders = strings.Fields(`relations sql customType
	pgTable pgSchema pgEnum pgView pgMaterializedView mysqlTable mysqlSchema mysqlEnum mysqlView
	sqliteTable sqliteView primaryKey foreignKey unique uniqueIndex index
	bigint bigserial boolean char cidr date doublePrecision inet integer interval json jsonb line
	macaddr macaddr8 numeric point real serial smallint smallserial text time timestamp uuid varchar
	binary datetime decimal double float int mediumint tinyint varbinary year
	tinytext mediumtext longtext blob`)

type drizzleGen struct {
	*ormGen
	names   *ormNaming
	module  string
	tableFn string
	used    map[string]bool // dialect-module imports
	core    map[string]bool // "drizzle-orm" imports
	// custom maps a database type to the customType declared for it.
	custom      map[string]string
	customOrder []string
	customData  map[string]string
	top         *ormNamer
	schemaVar   map[string]string
	schemaOrder []string
}

func generateDrizzle(g *ormGen) []ORMFile {
	module, tableFn := drizzleImport(g.driver)
	d := &drizzleGen{
		ormGen: g, module: module, tableFn: tableFn,
		used: map[string]bool{}, core: map[string]bool{},
		custom: map[string]string{}, customData: map[string]string{}, schemaVar: map[string]string{},
	}
	rules := ormNameRules{
		model: sanitizeIdent, field: sanitizeIdent, enum: sanitizeIdent,
		top: drizzleBuilders, escapeTop: jsIdent, modelSuffix: "Table",
	}
	if g.opts.Naming == ORMNamingCamel {
		rules.model, rules.field, rules.enum = ormCamel, ormCamel, ormCamel
	}
	d.names = g.names(rules)
	d.top = d.names.top

	var enums, tables, views, rels []string
	for _, e := range g.enums {
		if g.driver == DriverPostgres && !e.inline {
			enums = append(enums, d.enum(e))
		}
	}
	for _, m := range g.models {
		if m.view {
			views = append(views, d.table(m))
		} else {
			tables = append(tables, d.table(m))
		}
	}
	for _, m := range g.models {
		if block := d.relations(m); block != "" {
			rels = append(rels, block)
		}
	}

	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// A reviewed starting point: verify types, defaults and relations.\n\n")
	if len(d.core) > 0 {
		b.WriteString(tsImport(tsSortedImports(d.core), "drizzle-orm"))
	}
	b.WriteString(tsImport(tsSortedImports(d.used), module))

	section := func(blocks []string) {
		if len(blocks) > 0 {
			b.WriteString("\n" + strings.Join(blocks, "\n"))
		}
	}
	var customs, schemas []string
	for _, typ := range d.customOrder {
		customs = append(customs, fmt.Sprintf("const %s = customType<{ data: %s }>({\n  dataType() {\n    return %s\n  },\n})\n",
			d.custom[typ], d.customData[typ], jsString(typ)))
	}
	for _, s := range d.schemaOrder {
		fn := "pgSchema"
		if g.driver == DriverMySQL {
			fn = "mysqlSchema"
		}
		schemas = append(schemas, fmt.Sprintf("export const %s = %s(%s)\n", d.schemaVar[s], fn, jsString(s)))
	}
	section(customs)
	if len(schemas) > 0 {
		b.WriteString("\n" + strings.Join(schemas, ""))
	}
	if len(enums) > 0 {
		b.WriteString("\n" + strings.Join(enums, ""))
	}
	section(tables)
	section(views)
	section(rels)
	return []ORMFile{{Filename: "schema.ts", Content: b.String()}}
}

// tsImport renders a named import, broken one name to a line once it would
// run past a hundred columns, which is where Prettier breaks it.
func tsImport(names []string, module string) string {
	line := fmt.Sprintf("import { %s } from %s\n", strings.Join(names, ", "), jsString(module))
	if len(line) <= 101 {
		return line
	}
	return fmt.Sprintf("import {\n  %s,\n} from %s\n", strings.Join(names, ",\n  "), jsString(module))
}

// tsSortedImports orders import names alphabetically, a type-only import sorting
// by its name rather than by the word "type".
func tsSortedImports(set map[string]bool) []string {
	names := make([]string, 0, len(set))
	for n := range set {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool {
		return strings.TrimPrefix(names[i], "type ") < strings.TrimPrefix(names[j], "type ")
	})
	return names
}

// schemaRef returns the variable holding a schema, declaring it on first use,
// or "" when what lives there needs no qualifying. PostgreSQL's default schema
// never does: pgSchema("public") is an error in Drizzle, and pgTable is how a
// table there is declared. MySQL has no default, so once the tables span
// databases every one of them names its own.
func (d *drizzleGen) schemaRef(schema string) string {
	switch {
	case schema == "" || d.driver == DriverSQLite:
		return ""
	case d.driver == DriverPostgres && schema == d.defaultSchema:
		return ""
	case d.driver == DriverMySQL && !d.multiSchema:
		return ""
	}
	if v, ok := d.schemaVar[schema]; ok {
		return v
	}
	name := sanitizeIdent(schema)
	if d.opts.Naming == ORMNamingCamel {
		name = ormCamel(schema)
	}
	v := d.top.take(jsIdent(name), jsIdent(name)+"Schema")
	d.schemaVar[schema] = v
	d.schemaOrder = append(d.schemaOrder, schema)
	if d.driver == DriverMySQL {
		d.used["mysqlSchema"] = true
	} else {
		d.used["pgSchema"] = true
	}
	return v
}

func (d *drizzleGen) enum(e *ormEnum) string {
	values := "[" + strings.Join(jsStrings(e.Values), ", ") + "]"
	if ref := d.schemaRef(e.Schema); ref != "" {
		return fmt.Sprintf("export const %s = %s.enum(%s, %s)\n", d.names.enum[e], ref, jsString(e.Name), values)
	}
	d.used["pgEnum"] = true
	return fmt.Sprintf("export const %s = pgEnum(%s, %s)\n", d.names.enum[e], jsString(e.Name), values)
}

// customType declares, once per database type, a builder for a type Drizzle
// has none for.
func (d *drizzleGen) customType(dbType, data string) string {
	if v, ok := d.custom[dbType]; ok {
		return v
	}
	base := ormCamel(dbType)
	if base == "field" {
		base = "custom"
	}
	v := d.top.take(jsIdent(base), jsIdent(base)+"Type")
	d.custom[dbType] = v
	d.customData[dbType] = data
	d.customOrder = append(d.customOrder, dbType)
	d.used["customType"] = true
	return v
}

func (d *drizzleGen) table(m *ormTable) string {
	name := d.names.model[m]
	ref := d.schemaRef(m.Schema)

	var cols []string
	for _, c := range m.cols {
		cols = append(cols, fmt.Sprintf("%s: %s,", jsKey(d.names.field[c]), d.column(m, c)))
	}
	extras := d.extras(m)

	opener := d.tableFn
	suffix := ""
	switch {
	case m.Kind == ORMKindMatView && d.driver == DriverPostgres:
		opener, suffix = "pgMaterializedView", ".existing()"
	case m.view:
		opener = map[Driver]string{DriverMySQL: "mysqlView", DriverSQLite: "sqliteView"}[d.driver]
		if opener == "" {
			opener = "pgView"
		}
		suffix = ".existing()"
	}
	if ref != "" {
		switch {
		case m.Kind == ORMKindMatView && d.driver == DriverPostgres:
			opener = ref + ".materializedView"
		case m.view:
			opener = ref + ".view"
		default:
			opener = ref + ".table"
		}
	} else {
		d.used[opener] = true
	}

	var b strings.Builder
	if m.Comment != "" {
		fmt.Fprintf(&b, "/** %s */\n", ormBlockComment(m.Comment))
	}
	if len(extras) == 0 {
		fmt.Fprintf(&b, "export const %s = %s(%s, {\n", name, opener, jsString(m.Name))
		for _, c := range cols {
			b.WriteString("  " + c + "\n")
		}
		b.WriteString("})" + suffix + "\n")
		return b.String()
	}
	fmt.Fprintf(&b, "export const %s = %s(\n  %s,\n  {\n", name, opener, jsString(m.Name))
	for _, c := range cols {
		b.WriteString("    " + c + "\n")
	}
	b.WriteString("  },\n  (table) => [\n")
	for _, e := range extras {
		b.WriteString("    " + e + ",\n")
	}
	b.WriteString("  ],\n)\n")
	return b.String()
}

// extras are the constraints that belong to the table rather than to one
// column: a composite key, a composite unique, an index, a composite foreign
// key.
func (d *drizzleGen) extras(m *ormTable) []string {
	if m.view {
		return nil
	}
	ref := func(cols []string) string {
		out := make([]string, len(cols))
		for i, c := range cols {
			out[i] = "table." + d.names.field[m.byCol[c]]
		}
		return strings.Join(out, ", ")
	}
	var out []string
	if len(m.PrimaryKey) > 1 {
		d.used["primaryKey"] = true
		out = append(out, fmt.Sprintf("primaryKey({ columns: [%s] })", ref(m.PrimaryKey)))
	}
	for _, ix := range m.compositeUniques() {
		d.used["unique"] = true
		out = append(out, fmt.Sprintf("unique(%s).on(%s)", jsString(ix.Name), ref(ix.Columns)))
	}
	for _, ix := range m.indexes {
		d.used["index"] = true
		method := strings.ToLower(ix.Method)
		if d.driver == DriverPostgres && method != "" && method != "btree" {
			out = append(out, fmt.Sprintf("index(%s).using(%s, %s)", jsString(ix.Name), jsString(method), ref(ix.Columns)))
			continue
		}
		cols := make([]string, len(ix.Columns))
		for i, c := range ix.Columns {
			cols[i] = "table." + d.names.field[m.byCol[c]]
			if d.driver == DriverPostgres && i < len(ix.Desc) && ix.Desc[i] {
				cols[i] += ".desc()"
			}
		}
		out = append(out, fmt.Sprintf("index(%s).on(%s)", jsString(ix.Name), strings.Join(cols, ", ")))
	}
	for _, r := range m.rels {
		if len(r.fk.Columns) < 2 {
			continue
		}
		d.used["foreignKey"] = true
		foreign := make([]string, len(r.fk.RefColumns))
		for i, c := range r.fk.RefColumns {
			foreign[i] = d.names.model[r.to] + "." + d.names.field[r.to.byCol[c]]
		}
		fk := fmt.Sprintf("foreignKey({ columns: [%s], foreignColumns: [%s]", ref(r.fk.Columns), strings.Join(foreign, ", "))
		if r.fk.Name != "" {
			fk += ", name: " + jsString(r.fk.Name)
		}
		fk += " })"
		if a := drizzleAction(r.fk.OnDelete); a != "" {
			fk += ".onDelete(" + jsString(a) + ")"
		}
		if a := drizzleAction(r.fk.OnUpdate); a != "" {
			fk += ".onUpdate(" + jsString(a) + ")"
		}
		out = append(out, fk)
	}
	return out
}

// drizzleAction is a referential action in Drizzle's words, or "" for the
// engine's default, which needs no saying.
func drizzleAction(rule string) string {
	switch strings.ToUpper(strings.ReplaceAll(strings.TrimSpace(rule), "_", " ")) {
	case "CASCADE":
		return "cascade"
	case "RESTRICT":
		return "restrict"
	case "SET NULL":
		return "set null"
	case "SET DEFAULT":
		return "set default"
	}
	return ""
}

// column renders one column's builder chain.
func (d *drizzleGen) column(m *ormTable, c *ormCol) string {
	call := d.builder(m, c)
	if c.t.Array && d.driver == DriverPostgres {
		call += ".array()"
	}
	pk := len(m.PrimaryKey) == 1 && m.pk[c.Name] && !m.view
	if pk {
		if d.driver == DriverSQLite && c.Identity == "autoincrement" && d.opts.Defaults {
			call += ".primaryKey({ autoIncrement: true })"
		} else {
			call += ".primaryKey()"
		}
	}
	if !c.Nullable {
		call += ".notNull()"
	}
	if m.view {
		return call
	}
	if d.opts.Defaults {
		call += d.defaultCall(c)
	}
	if ix, ok := m.uniqueOn(c.Name); ok {
		// The engine's own name for a column-level unique and Drizzle's are
		// both left implicit; any other name is one somebody chose.
		if ix.Name == "" || ix.Name == m.Name+"_"+c.Name+"_key" || ix.Name == m.Name+"_"+c.Name+"_unique" ||
			strings.HasPrefix(ix.Name, "sqlite_autoindex_") {
			call += ".unique()"
		} else {
			call += ".unique(" + jsString(ix.Name) + ")"
		}
	}
	for _, r := range m.rels {
		if len(r.fk.Columns) != 1 || r.fk.Columns[0] != c.Name {
			continue
		}
		target := d.names.model[r.to] + "." + d.names.field[r.to.byCol[r.fk.RefColumns[0]]]
		arrow := "() => " + target
		if r.self {
			// A table that references itself cannot infer its own type while
			// it is still being declared.
			anyCol := map[Driver]string{DriverMySQL: "AnyMySqlColumn", DriverSQLite: "AnySQLiteColumn"}[d.driver]
			if anyCol == "" {
				anyCol = "AnyPgColumn"
			}
			d.used["type "+anyCol] = true
			arrow = "(): " + anyCol + " => " + target
		}
		var actions []string
		if a := drizzleAction(r.fk.OnDelete); a != "" {
			actions = append(actions, "onDelete: "+jsString(a))
		}
		if a := drizzleAction(r.fk.OnUpdate); a != "" {
			actions = append(actions, "onUpdate: "+jsString(a))
		}
		if len(actions) > 0 {
			call += fmt.Sprintf(".references(%s, { %s })", arrow, strings.Join(actions, ", "))
		} else {
			call += fmt.Sprintf(".references(%s)", arrow)
		}
		break
	}
	return call
}

// sqlTemplate renders a tagged sql`…` literal around a database expression.
func (d *drizzleGen) sqlTemplate(expr string) string {
	d.core["sql"] = true
	expr = strings.ReplaceAll(expr, `\`, `\\`)
	expr = strings.ReplaceAll(expr, "`", "\\`")
	expr = strings.ReplaceAll(expr, "${", "\\${")
	// A template literal may span lines; an escape reads the same and keeps
	// the column on one.
	expr = strings.ReplaceAll(expr, "\r", `\r`)
	expr = strings.ReplaceAll(expr, "\n", `\n`)
	return "sql`" + expr + "`"
}

func (d *drizzleGen) defaultCall(c *ormCol) string {
	if c.Generated {
		if c.GeneratedExpr == "" {
			return ""
		}
		return ".generatedAlwaysAs(" + d.sqlTemplate(c.GeneratedExpr) + ")"
	}
	// Drizzle's MySQL timestamp builder has defaultNow and onUpdateNow; its
	// datetime builder has neither, so a datetime says the same in SQL.
	mysqlTimestamp := d.driver == DriverMySQL && c.t.Name == "timestamp"
	onUpdate := ""
	if c.OnUpdateNow && mysqlTimestamp {
		onUpdate = ".onUpdateNow()"
	}
	def := c.def
	switch def.Kind {
	case ormDefAuto:
		switch {
		case d.driver == DriverMySQL && c.t.isInteger():
			return ".autoincrement()"
		case d.driver == DriverPostgres && c.Identity == "always":
			return ".generatedAlwaysAsIdentity()"
		case d.driver == DriverPostgres && c.Identity != "":
			return ".generatedByDefaultAsIdentity()"
		}
		// A PostgreSQL serial is the builder itself, and SQLite's rowid needs
		// nothing said.
		return ""
	case ormDefNow:
		switch {
		case d.driver == DriverSQLite, c.t.Array:
			return ".default(" + d.sqlTemplate(def.sql(d.driver)) + ")"
		case mysqlTimestamp, d.driver == DriverPostgres && (c.t.Kind == ormDateTime || c.t.Kind == ormDateTimeTZ):
			return ".defaultNow()" + onUpdate
		}
		return ".default(" + d.sqlTemplate(def.sql(d.driver)) + ")"
	case ormDefUUID:
		if d.driver == DriverPostgres && c.t.Kind == ormUUID && !c.t.Array && strings.EqualFold(def.Text, "gen_random_uuid()") {
			return ".defaultRandom()"
		}
		return ".default(" + d.sqlTemplate(def.Text) + ")"
	case ormDefString:
		if c.t.Array || !(c.t.isString() || c.t.Kind == ormUnknown) {
			return ".default(" + d.sqlTemplate(def.sql(d.driver)) + ")"
		}
		return ".default(" + jsString(def.Text) + ")"
	case ormDefNumber:
		switch {
		case c.t.Array:
			return ".default(" + d.sqlTemplate(def.sql(d.driver)) + ")"
		case c.t.isInteger() || c.t.Kind == ormFloat32 || c.t.Kind == ormFloat64 || c.t.Kind == ormYear:
			return ".default(" + def.Text + ")"
		case d.driver == DriverSQLite:
			return ".default(" + d.sqlTemplate(def.sql(d.driver)) + ")"
		}
		// numeric and decimal are strings on the JavaScript side.
		return ".default(" + jsString(def.Text) + ")"
	case ormDefBool:
		if c.t.Kind == ormBool && c.t.Name != "bit" {
			return fmt.Sprintf(".default(%t)", def.Bool)
		}
		return ".default(" + d.sqlTemplate(def.sql(d.driver)) + ")"
	case ormDefJSON:
		return ".default(" + def.Text + ")"
	case ormDefEmptyArray:
		return ".default([])"
	case ormDefExpr:
		return ".default(" + d.sqlTemplate(def.Text) + ")" + onUpdate
	}
	return ""
}

// builder renders the column builder call for the driver and type.
func (d *drizzleGen) builder(m *ormTable, c *ormCol) string {
	q := jsString(c.Name)
	t := c.t
	use := func(name, args string) string {
		d.used[name] = true
		if args == "" {
			return name + "(" + q + ")"
		}
		return name + "(" + q + ", " + args + ")"
	}
	custom := func(data string) string {
		dbType := strings.TrimSuffix(strings.TrimSpace(c.Type), "[]")
		if d.driver == DriverClickHouse || dbType == "" {
			dbType = t.Name
		}
		d.warn("%s.%s has type %s, which Drizzle ships no builder for; it is declared as a custom type.", d.label(m), c.Name, c.Type)
		return d.customType(dbType, data) + "(" + q + ")"
	}
	switch d.driver {
	case DriverSQLite:
		switch t.Kind {
		case ormBool:
			return use("integer", `{ mode: "boolean" }`)
		case ormInt8, ormInt16, ormInt32, ormInt64, ormYear:
			return use("integer", "")
		case ormFloat32, ormFloat64:
			return use("real", "")
		case ormDecimal, ormMoney:
			return use("numeric", "")
		case ormJSON:
			return use("text", `{ mode: "json" }`)
		case ormBytes:
			return use("blob", "")
		}
		// Text, and the dates SQLite keeps as text: CURRENT_TIMESTAMP writes a
		// string, and a string is what comes back.
		return use("text", "")

	case DriverMySQL:
		unsigned := func(extra string) string {
			switch {
			case t.Unsigned && extra != "":
				return "{ " + extra + ", unsigned: true }"
			case t.Unsigned:
				return "{ unsigned: true }"
			case extra != "":
				return "{ " + extra + " }"
			}
			return ""
		}
		fsp := ""
		if t.HasPrecision && t.Precision > 0 {
			fsp = fmt.Sprintf("{ fsp: %d }", t.Precision)
		}
		switch t.Kind {
		case ormBool:
			if t.Name == "bit" {
				return custom("Buffer")
			}
			return use("boolean", "")
		case ormInt8:
			return use("tinyint", unsigned(""))
		case ormInt16:
			return use("smallint", unsigned(""))
		case ormInt32:
			if t.Name == "mediumint" {
				return use("mediumint", unsigned(""))
			}
			return use("int", unsigned(""))
		case ormInt64:
			return use("bigint", unsigned(`mode: "number"`))
		case ormFloat32:
			return use("float", "")
		case ormFloat64:
			return use("double", "")
		case ormDecimal:
			if t.HasPrecision {
				return use("decimal", fmt.Sprintf("{ precision: %d, scale: %d }", t.Precision, t.Scale))
			}
			return use("decimal", "")
		case ormChar:
			return use("char", fmt.Sprintf("{ length: %d }", max(t.Length, 1)))
		case ormVarchar:
			return use("varchar", fmt.Sprintf("{ length: %d }", max(t.Length, 1)))
		case ormText:
			return use(t.Name, "")
		case ormJSON:
			return use("json", "")
		case ormBytes:
			switch t.Name {
			case "binary":
				return use("binary", fmt.Sprintf("{ length: %d }", max(t.Length, 1)))
			case "varbinary":
				return use("varbinary", fmt.Sprintf("{ length: %d }", max(t.Length, 1)))
			}
			return custom("Buffer")
		case ormDate:
			return use("date", "")
		case ormTime:
			return use("time", fsp)
		case ormDateTime:
			return use("datetime", fsp)
		case ormDateTimeTZ:
			return use("timestamp", fsp)
		case ormYear:
			return use("year", "")
		case ormEnumKind:
			if t.Enum != nil {
				return use("mysqlEnum", "["+strings.Join(jsStrings(t.Enum.Values), ", ")+"]")
			}
		}
		return custom("string")
	}

	// PostgreSQL.
	serial := d.opts.Defaults && c.def.Kind == ormDefAuto && c.Identity == "" && !c.t.Array
	precision := func(extra string) string {
		var parts []string
		if t.HasPrecision {
			parts = append(parts, fmt.Sprintf("precision: %d", t.Precision))
		}
		if extra != "" {
			parts = append(parts, extra)
		}
		if len(parts) == 0 {
			return ""
		}
		return "{ " + strings.Join(parts, ", ") + " }"
	}
	length := ""
	if t.Length > 0 {
		length = fmt.Sprintf("{ length: %d }", t.Length)
	}
	switch t.Kind {
	case ormBool:
		return use("boolean", "")
	case ormInt16:
		if serial {
			return use("smallserial", "")
		}
		return use("smallint", "")
	case ormInt32:
		if serial {
			return use("serial", "")
		}
		return use("integer", "")
	case ormInt64:
		if t.Name == "oid" {
			return custom("number")
		}
		if serial {
			return use("bigserial", `{ mode: "number" }`)
		}
		return use("bigint", `{ mode: "number" }`)
	case ormFloat32:
		return use("real", "")
	case ormFloat64:
		return use("doublePrecision", "")
	case ormDecimal:
		if t.HasPrecision {
			return use("numeric", fmt.Sprintf("{ precision: %d, scale: %d }", t.Precision, t.Scale))
		}
		return use("numeric", "")
	case ormChar:
		return use("char", length)
	case ormVarchar:
		return use("varchar", length)
	case ormText:
		if t.Name == "text" {
			return use("text", "")
		}
	case ormUUID:
		return use("uuid", "")
	case ormJSON:
		return use(t.Name, "")
	case ormBytes:
		return custom("Buffer")
	case ormDate:
		return use("date", "")
	case ormTime:
		if t.TZ {
			return use("time", precision("withTimezone: true"))
		}
		return use("time", precision(""))
	case ormDateTime:
		return use("timestamp", precision(""))
	case ormDateTimeTZ:
		return use("timestamp", precision("withTimezone: true"))
	case ormInterval:
		return use("interval", "")
	case ormNet:
		return use(t.Name, "")
	case ormGeo:
		if t.Name == "point" || t.Name == "line" {
			return use(t.Name, "")
		}
	case ormEnumKind:
		if t.Enum != nil {
			return d.names.enum[t.Enum] + "(" + q + ")"
		}
	}
	return custom("string")
}

// relations renders a table's relations() block: one() for each foreign key it
// holds, many() — or one(), for a key that is itself unique — for each that
// points at it.
func (d *drizzleGen) relations(m *ormTable) string {
	if len(m.rels) == 0 && len(m.back) == 0 {
		return ""
	}
	cols := func(t *ormTable, names []string) string {
		out := make([]string, len(names))
		for i, n := range names {
			out[i] = d.names.model[t] + "." + d.names.field[t.byCol[n]]
		}
		return strings.Join(out, ", ")
	}
	var lines []string
	one, many := false, false
	for _, r := range m.rels {
		one = true
		lines = append(lines, fmt.Sprintf("  %s: one(%s, {\n    fields: [%s],\n    references: [%s],\n    relationName: %s,\n  }),",
			jsKey(d.names.fwd[r]), d.names.model[r.to], cols(m, r.fk.Columns), cols(r.to, r.fk.RefColumns), jsString(r.name)))
	}
	for _, r := range m.back {
		if r.unique {
			one = true
			lines = append(lines, fmt.Sprintf("  %s: one(%s, {\n    fields: [%s],\n    references: [%s],\n    relationName: %s,\n  }),",
				jsKey(d.names.back[r]), d.names.model[r.from], cols(m, r.fk.RefColumns), cols(r.from, r.fk.Columns), jsString(r.name)))
			continue
		}
		many = true
		lines = append(lines, fmt.Sprintf("  %s: many(%s, { relationName: %s }),",
			jsKey(d.names.back[r]), d.names.model[r.from], jsString(r.name)))
	}
	var helpers []string
	if one {
		helpers = append(helpers, "one")
	}
	if many {
		helpers = append(helpers, "many")
	}
	d.core["relations"] = true
	table := d.names.model[m]
	return fmt.Sprintf("export const %s = relations(%s, ({ %s }) => ({\n%s\n}))\n",
		d.top.take(table+"Relations"), table, strings.Join(helpers, ", "), strings.Join(lines, "\n"))
}
