import { duration } from "@/lib/format"

/**
 * An expiry, as a person types one and as a key reports one.
 *
 * The old browser sent `Number(text) || -1`, and a negative expiry means
 * "never expire": typing `60s`, or clearing the box, removed the expiry and
 * said so cheerfully. Here a text is either a span the reader meant or
 * nothing at all — it is never read as "no expiry", which is a control of
 * its own.
 */

const UNITS: Record<string, number> = { s: 1, m: 60, h: 3600, d: 86_400, w: 604_800 }

/** The latest moment an expiry may name: the largest integer of milliseconds a browser states exactly. */
export const LATEST_EXPIRY_MS = Number.MAX_SAFE_INTEGER

export type TtlInput = { ok: true; seconds: number } | { ok: false; why: string }

/**
 * A span as typed: whole seconds (`90`), or parts with a unit (`5m`, `2h`,
 * `7d`, `1h 30m`). Anything else — zero, a negative, a fraction, a word — is
 * refused with the reason, and so is a span that ends past what the server
 * will set.
 */
export function parseTtl(text: string, now = Date.now()): TtlInput {
  const typed = text.trim().toLowerCase()
  if (!typed) return { ok: false, why: "Type how long the key should live." }
  let seconds = 0
  if (/^\d+$/.test(typed)) {
    seconds = Number(typed)
  } else if (/^(\d+\s*[smhdw]\s*)+$/.test(typed)) {
    for (const [, amount, unit] of typed.matchAll(/(\d+)\s*([smhdw])/g)) {
      seconds += Number(amount) * UNITS[unit]
    }
  } else {
    return { ok: false, why: "Seconds, or a span such as 30s, 5m, 2h or 7d." }
  }
  if (!Number.isSafeInteger(seconds) || seconds < 1) {
    return { ok: false, why: "An expiry is at least one second." }
  }
  if (now + seconds * 1000 > LATEST_EXPIRY_MS) {
    return { ok: false, why: "That is too far off to set. Remove the expiry instead." }
  }
  return { ok: true, seconds }
}

export type MomentInput = { ok: true; at: number } | { ok: false; why: string }

/** A moment from a date-and-time field, as Unix milliseconds — a future one. */
export function parseMoment(value: string, now = Date.now()): MomentInput {
  if (!value) return { ok: false, why: "Pick the date and time the key expires." }
  const at = new Date(value).getTime()
  if (Number.isNaN(at)) return { ok: false, why: "That is not a date and time." }
  if (at <= now) return { ok: false, why: "That moment has passed; the key would be deleted." }
  return { ok: true, at }
}

/** How long is left, in the two largest units: "2d 1h". */
export function ttlWord(seconds: number): string {
  if (seconds < 0) return "No expiry"
  // Past a few years the units stop meaning anything and the year does.
  if (seconds >= 86_400 * 730) return `${Math.floor(seconds / (86_400 * 365)).toLocaleString()}y`
  return duration(seconds)
}

/** How long is left in one unit, for a row with no room for two: "12h". */
export function ttlShort(seconds: number): string {
  if (seconds < 0) return ""
  if (seconds < 60) return `${seconds}s`
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`
  if (seconds < 86_400) return `${Math.floor(seconds / 3600)}h`
  if (seconds < 86_400 * 730) return `${Math.floor(seconds / 86_400).toLocaleString()}d`
  return `${Math.floor(seconds / (86_400 * 365)).toLocaleString()}y`
}

/** What is left of an expiry read `readAt` ago, in milliseconds. `-1` stays "none". */
export function remainingMs(pttl: number, readAt: number, now = Date.now()): number {
  if (pttl < 0) return -1
  return Math.max(pttl - (now - readAt), 0)
}

/** A stream entry's id as the moment it was added, where the id is a timestamp. */
export function entryMoment(id: string): Date | null {
  const ms = Number(id.split("-")[0])
  // Ids chosen by hand ("1-0") are not times; one generated by the server is.
  if (!Number.isSafeInteger(ms) || ms < 946_684_800_000 || ms > 32_503_680_000_000) return null
  return new Date(ms)
}

/** A date as the value a `datetime-local` field holds, in the reader's own zone. */
export function localMoment(at: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0")
  return `${at.getFullYear()}-${pad(at.getMonth() + 1)}-${pad(at.getDate())}T${pad(at.getHours())}:${pad(at.getMinutes())}`
}
