// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Exact
// numerics are strings, so nothing is rounded on the way through.

package models

import (
	"time"

	"github.com/lib/pq"
	"gorm.io/datatypes"
)

// EventKind is the event_kind enum.
type EventKind string

const (
	EventKindPageView  EventKind = "page_view"
	EventKindClick     EventKind = "click"
	EventKindAddToCart EventKind = "add-to-cart"
)

// CustomerTier is the customer_tier enum.
type CustomerTier string

const (
	CustomerTierFree CustomerTier = "free"
	CustomerTierPlus CustomerTier = "plus"
	CustomerTierPro  CustomerTier = "pro"
)

// OrderStatus is the order_status enum.
type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusShipped   OrderStatus = "shipped"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusRefunded  OrderStatus = "refunded"
)

// DailyRevenue maps the daily_revenue table.
type DailyRevenue struct {
	Day          time.Time `gorm:"column:day;type:date;primaryKey" json:"day"`
	Orders       int32     `gorm:"column:orders;type:integer;not null" json:"orders"`
	RevenueCents int64     `gorm:"column:revenue_cents;type:bigint;not null" json:"revenue_cents"`
}

// TableName is the table GORM reads and writes for DailyRevenue.
func (DailyRevenue) TableName() string { return "analytics.daily_revenue" }

// AnalyticsEvent maps the events table.
type AnalyticsEvent struct {
	ID         int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	CustomerID *int64         `gorm:"column:customer_id;type:bigint" json:"customer_id"`
	Kind       EventKind      `gorm:"column:kind;type:analytics.event_kind;not null" json:"kind"`
	Path       *string        `gorm:"column:path;type:text" json:"path"`
	DurationMs *int32         `gorm:"column:duration_ms;type:integer" json:"duration_ms"`
	Props      datatypes.JSON `gorm:"column:props;type:jsonb" json:"props"`
	OccurredAt time.Time      `gorm:"column:occurred_at;type:timestamp with time zone;not null;index:events_occurred_idx" json:"occurred_at"`

	Customer *Customer `gorm:"foreignKey:CustomerID;references:ID;constraint:OnDelete:SET NULL" json:"customer,omitempty"`
}

// TableName is the table GORM reads and writes for AnalyticsEvent.
func (AnalyticsEvent) TableName() string { return "analytics.events" }

// MixedCaseTable maps the Mixed Case Table table.
type MixedCaseTable struct {
	ID          int32   `gorm:"column:Id;type:integer;primaryKey;autoIncrement:false" json:"Id"`
	Select      *string `gorm:"column:select;type:text" json:"select"`
	WeirdColumn *string `gorm:"column:weird column;type:text" json:"weird column"`
	X2fa        bool    `gorm:"column:2fa;type:boolean;not null;default:false" json:"2fa"`
}

// TableName is the table GORM reads and writes for MixedCaseTable.
func (MixedCaseTable) TableName() string { return "public.Mixed Case Table" }

// AuditLog maps the audit_log table.
type AuditLog struct {
	At      time.Time      `gorm:"column:at;type:timestamp with time zone;not null;default:now()" json:"at"`
	Actor   *string        `gorm:"column:actor;type:text" json:"actor"`
	Action  string         `gorm:"column:action;type:text;not null" json:"action"`
	Payload datatypes.JSON `gorm:"column:payload;type:jsonb" json:"payload"`
}

// TableName is the table GORM reads and writes for AuditLog.
func (AuditLog) TableName() string { return "public.audit_log" }

// Category maps the categories table.
type Category struct {
	ID       int32  `gorm:"column:id;type:integer;primaryKey;autoIncrement" json:"id"`
	Slug     string `gorm:"column:slug;type:text;not null;uniqueIndex:categories_slug_key" json:"slug"`
	Name     string `gorm:"column:name;type:text;not null" json:"name"`
	ParentID *int32 `gorm:"column:parent_id;type:integer" json:"parent_id"`

	Parent     *Category  `gorm:"foreignKey:ParentID;references:ID" json:"parent,omitempty"`
	Categories []Category `gorm:"foreignKey:ParentID;references:ID" json:"categories,omitempty"`
	Products   []Product  `gorm:"foreignKey:CategoryID;references:ID" json:"products,omitempty"`
	Shipments  []Shipment `gorm:"foreignKey:CategorySlug;references:Slug" json:"shipments,omitempty"`
}

// TableName is the table GORM reads and writes for Category.
func (Category) TableName() string { return "public.categories" }

// CustomerProfile maps the customer_profiles table.
type CustomerProfile struct {
	CustomerID int64   `gorm:"column:customer_id;type:bigint;primaryKey;autoIncrement:false" json:"customer_id"`
	Bio        *string `gorm:"column:bio;type:text" json:"bio"`
	Website    *string `gorm:"column:website;type:character varying(255)" json:"website"`

	Customer *Customer `gorm:"foreignKey:CustomerID;references:ID;constraint:OnDelete:CASCADE" json:"customer,omitempty"`
}

// TableName is the table GORM reads and writes for CustomerProfile.
func (CustomerProfile) TableName() string { return "public.customer_profiles" }

// Customer maps customers: People who have an account in the shop
type Customer struct {
	ID             int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	Email          string         `gorm:"column:email;type:text;not null;uniqueIndex:customers_email_key" json:"email"`
	FullName       string         `gorm:"column:full_name;type:text;not null" json:"full_name"`
	Tier           CustomerTier   `gorm:"column:tier;type:customer_tier;not null;default:free" json:"tier"`
	Country        *string        `gorm:"column:country;type:character(2)" json:"country"`
	MarketingOptIn bool           `gorm:"column:marketing_opt_in;type:boolean;not null;default:false" json:"marketing_opt_in"`
	Tags           pq.StringArray `gorm:"column:tags;type:text[];not null;default:'{}'::text[]" json:"tags"`
	// Free-form preferences captured at sign-up
	Profile       datatypes.JSON `gorm:"column:profile;type:jsonb;not null;default:'{}'::jsonb" json:"profile"`
	Avatar        []byte         `gorm:"column:avatar;type:bytea" json:"avatar"`
	ExternalID    string         `gorm:"column:external_id;type:uuid;not null;default:gen_random_uuid()" json:"external_id"`
	LifetimeValue string         `gorm:"column:lifetime_value;type:numeric(12,2);not null;default:0" json:"lifetime_value"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	LastSeenAt    *time.Time     `gorm:"column:last_seen_at;type:timestamp with time zone" json:"last_seen_at"`

	Events              []AnalyticsEvent `gorm:"foreignKey:CustomerID;references:ID" json:"events,omitempty"`
	CustomerProfile     *CustomerProfile `gorm:"foreignKey:CustomerID;references:ID" json:"customer_profile,omitempty"`
	MessagesRecipientID []Message        `gorm:"foreignKey:RecipientID;references:ID" json:"messages_recipient_id,omitempty"`
	MessagesSenderID    []Message        `gorm:"foreignKey:SenderID;references:ID" json:"messages_sender_id,omitempty"`
	Orders              []Order          `gorm:"foreignKey:CustomerID;references:ID" json:"orders,omitempty"`
}

// TableName is the table GORM reads and writes for Customer.
func (Customer) TableName() string { return "public.customers" }

// Event maps the events table.
type Event struct {
	ID       int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	Name     string    `gorm:"column:name;type:character varying(120);not null" json:"name"`
	StartsAt time.Time `gorm:"column:starts_at;type:timestamp without time zone;not null" json:"starts_at"`
}

// TableName is the table GORM reads and writes for Event.
func (Event) TableName() string { return "public.events" }

// Measurement maps the measurements table.
type Measurement struct {
	SensorID int32     `gorm:"column:sensor_id;type:integer;primaryKey" json:"sensor_id"`
	TakenAt  time.Time `gorm:"column:taken_at;type:timestamp with time zone;primaryKey" json:"taken_at"`
	Reading  *float64  `gorm:"column:reading;type:double precision" json:"reading"`
}

// TableName is the table GORM reads and writes for Measurement.
func (Measurement) TableName() string { return "public.measurements" }

// Message maps the messages table.
type Message struct {
	ID          string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	SenderID    int64     `gorm:"column:sender_id;type:bigint;not null" json:"sender_id"`
	RecipientID *int64    `gorm:"column:recipient_id;type:bigint" json:"recipient_id"`
	Body        string    `gorm:"column:body;type:text;not null" json:"body"`
	SentAt      time.Time `gorm:"column:sent_at;type:timestamp(3) with time zone;not null;default:now()" json:"sent_at"`

	Recipient *Customer `gorm:"foreignKey:RecipientID;references:ID;constraint:OnDelete:SET NULL" json:"recipient,omitempty"`
	Sender    *Customer `gorm:"foreignKey:SenderID;references:ID;constraint:OnDelete:CASCADE" json:"sender,omitempty"`
}

// TableName is the table GORM reads and writes for Message.
func (Message) TableName() string { return "public.messages" }

// OrderItem maps the order_items table.
type OrderItem struct {
	OrderID        int64 `gorm:"column:order_id;type:bigint;primaryKey;uniqueIndex:order_items_order_product_key,priority:1" json:"order_id"`
	LineNo         int16 `gorm:"column:line_no;type:smallint;primaryKey" json:"line_no"`
	ProductID      int64 `gorm:"column:product_id;type:bigint;not null;uniqueIndex:order_items_order_product_key,priority:2" json:"product_id"`
	Quantity       int32 `gorm:"column:quantity;type:integer;not null;default:1" json:"quantity"`
	UnitPriceCents int32 `gorm:"column:unit_price_cents;type:integer;not null" json:"unit_price_cents"`

	Order     *Order     `gorm:"foreignKey:OrderID;references:ID;constraint:OnDelete:CASCADE" json:"order,omitempty"`
	Product   *Product   `gorm:"foreignKey:ProductID;references:ID" json:"product,omitempty"`
	Shipments []Shipment `gorm:"foreignKey:OrderID,LineNo;references:OrderID,LineNo" json:"shipments,omitempty"`
}

// TableName is the table GORM reads and writes for OrderItem.
func (OrderItem) TableName() string { return "public.order_items" }

// Order maps the orders table.
type Order struct {
	ID              int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	CustomerID      int64          `gorm:"column:customer_id;type:bigint;not null" json:"customer_id"`
	Status          OrderStatus    `gorm:"column:status;type:order_status;not null;default:pending;index:orders_status_placed_idx,priority:1" json:"status"`
	TotalCents      int64          `gorm:"column:total_cents;type:bigint;not null;default:0" json:"total_cents"`
	Currency        string         `gorm:"column:currency;type:character(3);not null;default:EUR" json:"currency"`
	ShippingAddress datatypes.JSON `gorm:"column:shipping_address;type:jsonb" json:"shipping_address"`
	Note            *string        `gorm:"column:note;type:text" json:"note"`
	PlacedAt        time.Time      `gorm:"column:placed_at;type:timestamp with time zone;not null;default:now();index:orders_status_placed_idx,priority:2" json:"placed_at"`
	ShippedAt       *time.Time     `gorm:"column:shipped_at;type:timestamp with time zone" json:"shipped_at"`

	Customer   *Customer   `gorm:"foreignKey:CustomerID;references:ID;constraint:OnDelete:CASCADE" json:"customer,omitempty"`
	OrderItems []OrderItem `gorm:"foreignKey:OrderID;references:ID" json:"order_items,omitempty"`
}

// TableName is the table GORM reads and writes for Order.
func (Order) TableName() string { return "public.orders" }

// Product maps the products table.
type Product struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement" json:"id"`
	Sku          string         `gorm:"column:sku;type:character varying(32);not null;uniqueIndex:products_sku_key" json:"sku"`
	Name         string         `gorm:"column:name;type:character varying(200);not null" json:"name"`
	Description  *string        `gorm:"column:description;type:text" json:"description"`
	CategoryID   *int32         `gorm:"column:category_id;type:integer;index:products_category_idx" json:"category_id"`
	PriceCents   int32          `gorm:"column:price_cents;type:integer;not null" json:"price_cents"`
	Stock        int32          `gorm:"column:stock;type:integer;not null;default:0" json:"stock"`
	Attributes   datatypes.JSON `gorm:"column:attributes;type:jsonb;not null;default:'{}'::jsonb" json:"attributes"`
	WeightKg     *float64       `gorm:"column:weight_kg;type:double precision" json:"weight_kg"`
	Discontinued bool           `gorm:"column:discontinued;type:boolean;not null;default:false" json:"discontinued"`
	ReleasedOn   *time.Time     `gorm:"column:released_on;type:date" json:"released_on"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp without time zone;not null;default:now()" json:"updated_at"`

	Category   *Category   `gorm:"foreignKey:CategoryID;references:ID" json:"category,omitempty"`
	OrderItems []OrderItem `gorm:"foreignKey:ProductID;references:ID" json:"order_items,omitempty"`
}

// TableName is the table GORM reads and writes for Product.
func (Product) TableName() string { return "public.products" }

// Shipment maps the shipments table.
type Shipment struct {
	ID           int32   `gorm:"column:id;type:integer;primaryKey;autoIncrement" json:"id"`
	OrderID      int64   `gorm:"column:order_id;type:bigint;not null" json:"order_id"`
	LineNo       int16   `gorm:"column:line_no;type:smallint;not null" json:"line_no"`
	CategorySlug *string `gorm:"column:category_slug;type:text" json:"category_slug"`
	TrackingCode string  `gorm:"column:tracking_code;type:character varying(40);not null;uniqueIndex:shipments_tracking_code_key" json:"tracking_code"`

	Category  *Category  `gorm:"foreignKey:CategorySlug;references:Slug" json:"category,omitempty"`
	OrderItem *OrderItem `gorm:"foreignKey:OrderID,LineNo;references:OrderID,LineNo;constraint:OnDelete:CASCADE" json:"order_item,omitempty"`
}

// TableName is the table GORM reads and writes for Shipment.
func (Shipment) TableName() string { return "public.shipments" }

// TypeSample maps the type_samples table.
type TypeSample struct {
	ID       int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement" json:"id"`
	Small    int16          `gorm:"column:small;type:smallint;not null;default:0" json:"small"`
	Ratio    *float32       `gorm:"column:ratio;type:real" json:"ratio"`
	Price    *string        `gorm:"column:price;type:money" json:"price"`
	Amount   *string        `gorm:"column:amount;type:numeric" json:"amount"`
	Code     string         `gorm:"column:code;type:character varying(16);not null;default:N/A" json:"code"`
	Fixed    *string        `gorm:"column:fixed;type:character(4)" json:"fixed"`
	Starts   *string        `gorm:"column:starts;type:time without time zone" json:"starts"`
	StartsTz *string        `gorm:"column:starts_tz;type:time with time zone" json:"starts_tz"`
	Span     *string        `gorm:"column:span;type:interval" json:"span"`
	Addr     *string        `gorm:"column:addr;type:inet" json:"addr"`
	Doc      *string        `gorm:"column:doc;type:xml" json:"doc"`
	Flags    []byte         `gorm:"column:flags;type:bit(8)" json:"flags"`
	Search   *string        `gorm:"column:search;type:tsvector" json:"search"`
	Scores   pq.Int32Array  `gorm:"column:scores;type:integer[]" json:"scores"`
	Day      time.Time      `gorm:"column:day;type:date;not null;default:CURRENT_DATE" json:"day"`
	Meta     datatypes.JSON `gorm:"column:meta;type:json" json:"meta"`
	Label    string         `gorm:"column:label;type:text;not null;default:it's" json:"label"`
	Total    *string        `gorm:"column:total;type:numeric(10,2);->" json:"total"`
	Stamp    time.Time      `gorm:"column:stamp;type:timestamp(3) without time zone;not null;default:timezone('utc'::text, now())" json:"stamp"`
}

// TableName is the table GORM reads and writes for TypeSample.
func (TypeSample) TableName() string { return "public.type_samples" }
