package deploy

import (
	"crypto/rand"
	"errors"
	"os"
	"path"
	"strings"
)

// A generated Dockerfile builds from the repository's whole checkout, and
// BuildKit reads `.just-dashboard/Dockerfile.dockerignore` in place of the
// repository's own .dockerignore once it exists. Writing one therefore
// decides both halves of what reaches the image: the dashboard's own
// exclusions always apply, and the repository's rules apply too — except a
// rule written for the repository's own prebuilt Dockerfile that would
// leave out a file the recipe reads (an allowlist `*` drops package.json).

type dockerignoreDrop struct {
	Rule  string
	Input string
}

// recipeInputNames are the root files the automatic recipes read by name.
var recipeInputNames = map[string]bool{
	"package.json": true, "package-lock.json": true, "npm-shrinkwrap.json": true, "bun.lock": true,
	"bun.lockb": true, "pnpm-lock.yaml": true, "pnpm-workspace.yaml": true, "yarn.lock": true,
	".yarnrc.yml": true, ".npmrc": true, ".nvmrc": true, ".node-version": true, "tsconfig.json": true,
	"angular.json": true, "Procfile": true,
	"go.mod": true, "go.sum": true, "go.work": true, ".go-version": true,
	"requirements.txt": true, "pyproject.toml": true, "uv.lock": true, "poetry.lock": true,
	".python-version": true, "runtime.txt": true, "manage.py": true,
	"Cargo.toml": true, "Cargo.lock": true, "rust-toolchain": true, "rust-toolchain.toml": true,
	"pom.xml": true, "build.gradle": true, "build.gradle.kts": true, "settings.gradle": true,
	"settings.gradle.kts": true, "gradlew": true, "gradle": true, "mvnw": true, ".mvn": true, ".java-version": true,
	"deno.json": true, "deno.jsonc": true, "deno.lock": true,
	"composer.json": true, "composer.lock": true, "artisan": true, "index.php": true, "index.html": true,
	"prisma": true, "drizzle.config.ts": true, "drizzle.config.js": true,
}

// recipeInputPrefixes are framework configuration files, named per tool.
var recipeInputPrefixes = []string{
	"next.config.", "vite.config.", "nuxt.config.", "svelte.config.", "astro.config.", "remix.config.",
	"react-router.config.", "gatsby-config.", "docusaurus.config.", "eleventy.config.", ".eleventy.",
	"tailwind.config.", "postcss.config.", "webpack.config.", "prisma.config.",
}

func recipeInput(name string) bool {
	if recipeInputNames[name] {
		return true
	}
	for _, prefix := range recipeInputPrefixes {
		if strings.HasPrefix(name, prefix) {
			return true
		}
	}
	return strings.HasSuffix(name, ".csproj") || strings.HasSuffix(name, ".fsproj") || strings.HasSuffix(name, ".sln")
}

// recipeDockerignore renders the ignore file for a generated Dockerfile of
// the given recipe kind ("static" for a plain static site) from the
// repository's own rules and the names at the build root.
func recipeDockerignore(repository []byte, rootNames []string, kind string) (string, []dockerignoreDrop) {
	rules := parseDockerignore(repository)
	inputs := []string{}
	for _, name := range rootNames {
		if recipeInput(name) {
			inputs = append(inputs, name)
		}
	}
	dropped := []dockerignoreDrop{}
	// Setting one rule aside can expose an input a broader earlier rule
	// also covered, so this repeats until no input is left out.
	for round := 0; round < len(rules)+1; round++ {
		removed := false
		for _, input := range inputs {
			excluded, decidedBy := dockerignoreExcludes(rules, input)
			if !excluded {
				continue
			}
			kept := rules[:0:0]
			for _, rule := range rules {
				if rule.Line == decidedBy && !rule.Negate && !removed {
					removed = true
					continue
				}
				kept = append(kept, rule)
			}
			rules = kept
			dropped = append(dropped, dockerignoreDrop{Rule: decidedBy, Input: input})
			break
		}
		if !removed {
			break
		}
	}
	lines := []string{"# Generated by Just Dashboard for the automatic build; the repository's own rules follow."}
	for _, rule := range rules {
		lines = append(lines, rule.Line)
	}
	// These come last so that no repository rule can bring them back.
	lines = append(lines, "**/node_modules", ".dockerignore", ".just-dashboard", ".just-dashboard-build-metadata-*")
	switch kind {
	case "static", "php", "node", "deno":
		// Served or copied whole into the runtime image; the history and
		// remote a checkout carries are nobody's business there. Toolchains
		// that stamp or version builds from Git (Go, Python's setuptools-scm,
		// Maven's git-commit-id, SourceLink) keep it.
		lines = append(lines, ".git")
	}
	if kind == "static" {
		// A static site serves every file in its context, and a committed
		// .env is configuration, not content.
		lines = append(lines, ".env", ".env.*")
	}
	return strings.Join(lines, "\n") + "\n", dropped
}

// writeGeneratedDockerignore places the ignore file beside the generated
// Dockerfile with the same discipline: root-relative, exclusive, renamed
// into place, so a checkout symlink cannot redirect it.
func writeGeneratedDockerignore(root, content string) error {
	directory, err := os.OpenRoot(root)
	if err != nil {
		return err
	}
	defer directory.Close()
	if err := directory.MkdirAll(".just-dashboard", 0o700); err != nil {
		return err
	}
	temporary := ".just-dashboard/.Dockerfile.dockerignore-" + rand.Text()
	file, err := directory.OpenFile(temporary, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer directory.Remove(temporary)
	_, writeErr := file.WriteString(content)
	closeErr := file.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		return err
	}
	return directory.Rename(temporary, ".just-dashboard/Dockerfile.dockerignore")
}

// buildRootNames lists the names at a build root for recipeDockerignore.
func buildRootNames(root string) []string {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil
	}
	names := make([]string, 0, len(entries))
	for index, entry := range entries {
		if index >= 4096 {
			break
		}
		names = append(names, path.Base(entry.Name()))
	}
	return names
}

// writeRecipeDockerignore renders and writes the ignore file for a generated
// Dockerfile at root.
func writeRecipeDockerignore(root, kind string) error {
	repository, _ := readContainedRegular(root, ".dockerignore", 256<<10)
	content, _ := recipeDockerignore(repository, buildRootNames(root), kind)
	return writeGeneratedDockerignore(root, content)
}
