package deploy

import (
	"strings"
	"testing"
)

// The PHP recipe's asset stage is the JavaScript install planner's plan run
// on the PHP recipe's vendor stage: the manager, its pinned release and the
// Node major come from the same reading as a Node recipe's, and the stage
// has PHP and vendor/ for the scripts that need them. These cases follow a
// Laravel application from detection through preflight to the Dockerfile.

const laravelPNPMLock = "lockfileVersion: '9.0'\n\nimporters:\n\n  .:\n    devDependencies:\n" +
	"      laravel-vite-plugin:\n        specifier: ^2.0.0\n        version: 2.0.1\n" +
	"      vite:\n        specifier: ^7.0.0\n        version: 7.1.0\n\n" +
	"packages:\n\n  laravel-vite-plugin@2.0.1: {}\n\n  vite@7.1.0: {}\n"

func laravelAssetTree() map[string]string {
	return laravelTree(map[string]string{
		"composer.json": `{"require":{"php":"^8.2","laravel/framework":"^12.0","tightenco/ziggy":"^2.0"}}`,
		// Ziggy's routes are generated by artisan before Vite bundles them.
		"package.json":   `{"private":true,"packageManager":"pnpm@10.18.3","scripts":{"build":"php artisan ziggy:generate && vite build"},"devDependencies":{"laravel-vite-plugin":"^2.0.0","vite":"^7.0.0"}}`,
		"pnpm-lock.yaml": laravelPNPMLock,
		"vite.config.ts": "export default defineConfig({\n  // build: { outDir: 'dist' },\n  plugins: [laravel({ input: ['resources/js/app.ts'] })],\n})\n",
		".nvmrc":         "20\n",
	})
}

func TestLaravelAssetStageInstallsWithTheNodePlanOnTheVendorStage(t *testing.T) {
	t.Parallel()
	candidate, prepared, findings := phpPlan(t, laravelAssetTree())
	if candidate.Recipe != "php" || candidate.Framework != "laravel" || candidate.RecipeIssue != "" || candidate.PackageManager != "pnpm" ||
		candidate.PHP == nil || candidate.PHP.AssetOutput != "public/build" {
		t.Fatalf("candidate = %+v / %+v", candidate, candidate.PHP)
	}
	assertDockerfile(t, prepared.DockerfilePreview, []string{
		// The Node major is the repository's, read as the Node recipe reads it.
		"FROM node:20-alpine@sha256:",
		// pnpm is the release package.json declares, installed once into the
		// toolchain the asset stage copies.
		"RUN corepack enable pnpm && corepack install -g pnpm@10.18.3\n",
		" AS assets-toolchain\n",
		"FROM vendor AS assets\nCOPY --from=assets-toolchain /usr/local /opt/node\n",
		"RUN pnpm install --frozen-lockfile",
		nodeBuildRun("pnpm run build\n"),
		// A commented-out outDir is not the output; laravel()'s is.
		"COPY --from=assets /app/public/build /app/public/build\n",
	}, []string{"/app/dist", "FROM node:22-alpine"})
	// The build script runs php, which the vendor stage has.
	for _, code := range []string{"command_runner_missing", "recipe_unsupported"} {
		if item := findingByCode(findings, code); item != nil {
			t.Fatalf("%s = %+v", code, item)
		}
	}
	if selected := findingByCode(findings, "node_version_selected"); selected == nil || selected.Measured != "20 (.nvmrc)" {
		t.Fatalf("node_version_selected = %+v", selected)
	}

	// The Node version in Build settings reaches the asset stage, as the
	// package manager does.
	chosen := func(build *BuildPlanConfig) { build.NodeVersion = "24" }
	_, prepared, findings = phpPlan(t, laravelAssetTree(), chosen)
	assertDockerfile(t, prepared.DockerfilePreview, []string{"FROM node:24-alpine@sha256:"}, []string{"node:20-alpine"})
	if selected := findingByCode(findings, "node_version_selected"); selected == nil || selected.Measured != "24 (Build settings)" {
		t.Fatalf("node_version_selected = %+v", selected)
	}
	configuration := nodeTestConfiguration(BuildPlanConfig{Method: BuildRecipe, Recipe: "php", NodeVersion: "24",
		StartCommand: candidate.StartCommand})
	if err := configuration.Validate(); err != nil {
		t.Fatalf("a PHP plan with a Node version = %v", err)
	}
	configuration.Build.Recipe = "go"
	if err := configuration.Validate(); err == nil || !strings.Contains(err.Error(), "Node version") {
		t.Fatalf("a Go plan with a Node version = %v", err)
	}
}

// A Node recipe's image has no PHP, so the same script is refused there
// before the build, on the field that runs it.
func TestANodeRecipeStillRefusesAScriptThatRunsPHP(t *testing.T) {
	t.Parallel()
	result, candidate := detectNodeTree(t, map[string]string{
		"package.json":   `{"private":true,"packageManager":"pnpm@10.18.3","scripts":{"build":"php artisan ziggy:generate && vite build"},"devDependencies":{"laravel-vite-plugin":"^2.0.0","vite":"^7.0.0"}}`,
		"pnpm-lock.yaml": laravelPNPMLock,
	})
	if candidate.Recipe != "node" {
		t.Fatalf("candidate = %+v", candidate)
	}
	findings := preflightFindings(nodeDraft(result), nodeTestConfiguration(BuildPlanConfig{Method: BuildRecipe, Recipe: "node",
		BuildCommand: candidate.BuildCommand, OutputDirectory: candidate.OutputDirectory}), dockerHost, false)
	if runner := findingByCode(findings, "command_runner_missing"); runner == nil || runner.Measured != "php" ||
		runner.FieldID != "configuration.build.buildCommand" {
		t.Fatalf("command_runner_missing = %+v", runner)
	}
}

// Lume is a Deno build whose output nginx serves: it builds on the Deno
// release the repository declares, installs from its lock, caches no entry
// and starts nothing, and its site is served with the static server's own
// configuration.
func TestLumeBuildsOnTheDeclaredDenoReleaseAndIsServedAsASite(t *testing.T) {
	t.Parallel()
	prepared, candidate, err := prepareSite(t, map[string]string{
		"deno.json":  `{"imports":{"lume/":"https://deno.land/x/lume@v3.2.5/"},"tasks":{"build":"deno task lume","lume":"echo x"}}`,
		"deno.lock":  "{}",
		".dvmrc":     "2.4.5\n",
		"_config.ts": "const site = lume({ dest: \"./out\" })\nexport default site\n",
		"about.md":   "# about",
		"_redirects": "/old  /about  301\n",
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if candidate.Recipe != "deno" || candidate.Framework != "lume" || candidate.OutputDirectory != "out" || candidate.StartCommand != "" {
		t.Fatalf("candidate = %+v", candidate)
	}
	assertDockerfileLines(t, prepared.DockerfilePreview, []string{
		"FROM denoland/deno:alpine-2.4.5@sha256:", " AS build\n", "RUN deno install --frozen\n", "RUN deno task build\n",
		"COPY --from=build /app/out/ /usr/share/nginx/html/\n",
		"        try_files $uri $uri.html $uri/ =404;",
		"        return 301 /about$is_args$args;",
	}, []string{"CMD ", "--entrypoint", "deno cache"})
	if prepared.Toolchain != "deno 2.4.5 (.dvmrc)" {
		t.Fatalf("toolchain = %q", prepared.Toolchain)
	}
}
