// Generated by Just Dashboard from live database introspection.
// The shape `diesel print-schema` writes. A reviewed starting point: check it
// against your migrations before relying on it.

pub mod sql_types {
    #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "customer_tier"))]
    pub struct CustomerTier;

    #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "order_status"))]
    pub struct OrderStatus;

    #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "timetz"))]
    pub struct Timetz;

    #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "xml"))]
    pub struct Xml;

    #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "bit"))]
    pub struct Bit;

    #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "tsvector"))]
    pub struct Tsvector;
}

diesel::table! {
    use diesel::sql_types::*;

    #[sql_name = "Mixed Case Table"]
    mixed_case_table (id) {
        #[sql_name = "Id"]
        id -> Int4,
        select -> Nullable<Text>,
        #[sql_name = "weird column"]
        weird_column -> Nullable<Text>,
        #[sql_name = "2fa"]
        _2fa -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    categories (id) {
        id -> Int4,
        slug -> Text,
        name -> Text,
        parent_id -> Nullable<Int4>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    customer_profiles (customer_id) {
        customer_id -> Int8,
        bio -> Nullable<Text>,
        #[max_length = 255]
        website -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::CustomerTier;

    customers (id) {
        id -> Int8,
        email -> Text,
        full_name -> Text,
        tier -> CustomerTier,
        #[max_length = 2]
        country -> Nullable<Bpchar>,
        marketing_opt_in -> Bool,
        tags -> Array<Nullable<Text>>,
        profile -> Jsonb,
        avatar -> Nullable<Bytea>,
        external_id -> Uuid,
        lifetime_value -> Numeric,
        created_at -> Timestamptz,
        last_seen_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    events (id) {
        id -> Int8,
        #[max_length = 120]
        name -> Varchar,
        starts_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    measurements (sensor_id, taken_at) {
        sensor_id -> Int4,
        taken_at -> Timestamptz,
        reading -> Nullable<Float8>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    messages (id) {
        id -> Uuid,
        sender_id -> Int8,
        recipient_id -> Nullable<Int8>,
        body -> Text,
        sent_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    order_items (order_id, line_no) {
        order_id -> Int8,
        line_no -> Int2,
        product_id -> Int8,
        quantity -> Int4,
        unit_price_cents -> Int4,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::OrderStatus;

    orders (id) {
        id -> Int8,
        customer_id -> Int8,
        status -> OrderStatus,
        total_cents -> Int8,
        #[max_length = 3]
        currency -> Bpchar,
        shipping_address -> Nullable<Jsonb>,
        note -> Nullable<Text>,
        placed_at -> Timestamptz,
        shipped_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    products (id) {
        id -> Int8,
        #[max_length = 32]
        sku -> Varchar,
        #[max_length = 200]
        name -> Varchar,
        description -> Nullable<Text>,
        category_id -> Nullable<Int4>,
        price_cents -> Int4,
        stock -> Int4,
        attributes -> Jsonb,
        weight_kg -> Nullable<Float8>,
        discontinued -> Bool,
        released_on -> Nullable<Date>,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    shipments (id) {
        id -> Int4,
        order_id -> Int8,
        line_no -> Int2,
        category_slug -> Nullable<Text>,
        #[max_length = 40]
        tracking_code -> Varchar,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Timetz;
    use super::sql_types::Xml;
    use super::sql_types::Bit;
    use super::sql_types::Tsvector;

    type_samples (id) {
        id -> Int4,
        small -> Int2,
        ratio -> Nullable<Float4>,
        price -> Nullable<Money>,
        amount -> Nullable<Numeric>,
        #[max_length = 16]
        code -> Varchar,
        #[max_length = 4]
        fixed -> Nullable<Bpchar>,
        starts -> Nullable<Time>,
        starts_tz -> Nullable<Timetz>,
        span -> Nullable<Interval>,
        addr -> Nullable<Inet>,
        doc -> Nullable<Xml>,
        flags -> Nullable<Bit>,
        search -> Nullable<Tsvector>,
        scores -> Nullable<Array<Nullable<Int4>>>,
        day -> Date,
        meta -> Nullable<Json>,
        label -> Text,
        total -> Nullable<Numeric>,
        stamp -> Timestamp,
    }
}

diesel::joinable!(customer_profiles -> customers (customer_id));
diesel::joinable!(order_items -> orders (order_id));
diesel::joinable!(order_items -> products (product_id));
diesel::joinable!(orders -> customers (customer_id));
diesel::joinable!(products -> categories (category_id));

diesel::allow_tables_to_appear_in_same_query!(
    mixed_case_table,
    categories,
    customer_profiles,
    customers,
    events,
    measurements,
    messages,
    order_items,
    orders,
    products,
    shipments,
    type_samples,
);

pub mod analytics {
    pub mod sql_types {
        #[derive(diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
        #[diesel(postgres_type(name = "event_kind", schema = "analytics"))]
        pub struct EventKind;
    }

    diesel::table! {
        use diesel::sql_types::*;

        analytics.daily_revenue (day) {
            day -> Date,
            orders -> Int4,
            revenue_cents -> Int8,
        }
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::EventKind;

        analytics.events (id) {
            id -> Int8,
            customer_id -> Nullable<Int8>,
            kind -> EventKind,
            path -> Nullable<Text>,
            duration_ms -> Nullable<Int4>,
            props -> Nullable<Jsonb>,
            occurred_at -> Timestamptz,
        }
    }

    diesel::allow_tables_to_appear_in_same_query!(
        daily_revenue,
        events,
    );
}
