package netx

import (
	"context"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"syscall"
	"testing"
	"time"

	"github.com/Wayy01/Just-Dashboard/backend/internal/proxysvc"
)

// pointResolvConf makes /etc/resolv.conf a file the test owns. "stub" is the
// link Ubuntu ships, "uplink" the one to the uplink servers, "static" a plain
// file with a header NetworkManager would have written.
func pointResolvConf(t *testing.T, mode string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	switch mode {
	case "stub":
		if err := os.Symlink("../run/systemd/resolve/stub-resolv.conf", path); err != nil {
			t.Fatal(err)
		}
	case "uplink":
		if err := os.Symlink("../run/systemd/resolve/resolv.conf", path); err != nil {
			t.Fatal(err)
		}
	default:
		body := "# Generated by NetworkManager\nsearch example.internal\nnameserver 198.51.100.53\nnameserver 198.51.100.54\noptions timeout:2\n"
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	prev := resolvConfPath
	resolvConfPath = path
	t.Cleanup(func() { resolvConfPath = prev })
	return path
}

func TestParseResolvedStatusCurrentFormat(t *testing.T) {
	t.Parallel()
	g, links, total := parseResolvedStatus(fixture(t, "dns-resolvectl-status.txt"))
	if g.ResolvConfMode != "stub" || g.DNSOverTLS != "no" || g.DNSSEC != "no" || g.DNSSECSupported {
		t.Fatalf("global = %+v", g)
	}
	if !reflect.DeepEqual(g.Protocols, []string{"-LLMNR", "-mDNS", "-DNSOverTLS", "DNSSEC=no/unsupported"}) {
		t.Fatalf("global protocols = %v", g.Protocols)
	}
	if len(g.Servers) != 0 {
		t.Fatalf("a global section with no servers read %v", g.Servers)
	}
	// Docker's bridges and veths print a section each with nothing in it.
	if total != 6 || len(links) != 2 {
		t.Fatalf("%d of %d links kept: %+v", len(links), total, links)
	}
	eth := links[0]
	if eth.Name != "ens3" || eth.Index != 2 || !eth.DefaultRoute || eth.CurrentServer != "203.0.113.53" ||
		!reflect.DeepEqual(eth.Servers, []string{"203.0.113.53"}) ||
		!reflect.DeepEqual(eth.Domains, []string{"example.internal"}) ||
		!reflect.DeepEqual(eth.Scopes, []string{"DNS"}) {
		t.Fatalf("ens3 = %+v", eth)
	}
	ts := links[1]
	if ts.Name != "tailscale0" || ts.DefaultRoute || len(ts.Servers) != 2 || ts.Servers[1] != "fd7a:115c:a1e0::53" {
		t.Fatalf("tailscale0 = %+v", ts)
	}
	// The domain list wraps over continuation lines.
	if len(ts.Domains) != 6 || ts.Domains[0] != "tailnet-example.ts.net" || ts.Domains[5] != "~ts.net" {
		t.Fatalf("tailscale0 domains = %v", ts.Domains)
	}
}

// Servers carrying #names, and an IPv6 server on a continuation line whose
// colons must not read as a label.
func TestParseResolvedStatusDNSOverTLS(t *testing.T) {
	t.Parallel()
	g, links, _ := parseResolvedStatus(fixture(t, "dns-resolvectl-status-dot.txt"))
	if g.DNSOverTLS != "yes" || g.DNSSEC != "allow-downgrade" || !g.DNSSECSupported {
		t.Fatalf("global settings = %q %q %v", g.DNSOverTLS, g.DNSSEC, g.DNSSECSupported)
	}
	if g.CurrentServer != "1.1.1.1#cloudflare-dns.com" {
		t.Fatalf("current = %q", g.CurrentServer)
	}
	want := []string{"1.1.1.1#cloudflare-dns.com", "1.0.0.1#cloudflare-dns.com",
		"2606:4700:4700::1111#cloudflare-dns.com", "2606:4700:4700::1001#cloudflare-dns.com"}
	if !reflect.DeepEqual(g.Servers, want) {
		t.Fatalf("servers = %v", g.Servers)
	}
	if !reflect.DeepEqual(g.Fallback, []string{"9.9.9.9#dns.quad9.net"}) || !reflect.DeepEqual(g.Domains, []string{"~."}) {
		t.Fatalf("fallback %v domains %v", g.Fallback, g.Domains)
	}
	if len(links) != 1 || links[0].DNSOverTLS != "opportunistic" || !links[0].DefaultRoute {
		t.Fatalf("links = %+v", links)
	}
}

// Before systemd 248 the same facts are printed one "… setting:" line each.
func TestParseResolvedStatusOlderFormat(t *testing.T) {
	t.Parallel()
	g, links, total := parseResolvedStatus(fixture(t, "dns-resolvectl-status-old.txt"))
	if g.DNSOverTLS != "opportunistic" || g.DNSSEC != "allow-downgrade" || !g.DNSSECSupported {
		t.Fatalf("settings = %q %q %v", g.DNSOverTLS, g.DNSSEC, g.DNSSECSupported)
	}
	if g.CurrentServer != "9.9.9.9" || !reflect.DeepEqual(g.Servers, []string{"9.9.9.9", "149.112.112.112", "2620:fe::fe"}) {
		t.Fatalf("servers = %v (current %q)", g.Servers, g.CurrentServer)
	}
	if !reflect.DeepEqual(g.Fallback, []string{"1.1.1.1"}) || !reflect.DeepEqual(g.Domains, []string{"~."}) {
		t.Fatalf("fallback %v, domains %v: the NTA list must not leak into them", g.Fallback, g.Domains)
	}
	if total != 2 || len(links) != 1 {
		t.Fatalf("%d of %d links kept", len(links), total)
	}
	if l := links[0]; l.Name != "eth0" || !l.DefaultRoute || len(l.Servers) != 2 || l.DNSOverTLS != "no" || l.DNSSEC != "no" {
		t.Fatalf("eth0 = %+v", l)
	}
}

func TestParseResolvedStats(t *testing.T) {
	t.Parallel()
	st := parseResolvedStats(fixture(t, "dns-resolvectl-statistics.txt"))
	if st == nil {
		t.Fatal("nothing read")
	}
	if st.CacheSize != 55 || st.CacheHits != 44866630 || st.CacheMisses != 5555394 || st.Transactions != 50421344 ||
		st.Timeouts != 329 || st.Failures != 60 || st.DNSSECSecure != 0 {
		t.Fatalf("stats = %+v", st)
	}
	if st.HitPercent != 89 {
		t.Fatalf("hit percent = %v", st.HitPercent)
	}
	if parseResolvedStats("Failed to issue io.systemd.Resolve.Monitor.DumpStatistics() varlink call: nope\n") != nil {
		t.Fatal("an error message read as statistics")
	}
}

func TestReadResolvConf(t *testing.T) {
	stub := readResolvConf(pointResolvConf(t, "stub"))
	if stub.Mode != "stub" || stub.ManagedBy != "systemd-resolved" || !strings.HasSuffix(stub.Target, "stub-resolv.conf") {
		t.Fatalf("stub = %+v", stub)
	}
	if uplink := readResolvConf(pointResolvConf(t, "uplink")); uplink.Mode != "uplink" {
		t.Fatalf("uplink = %+v", uplink)
	}
	static := readResolvConf(pointResolvConf(t, "static"))
	if static.Mode != "static" || static.ManagedBy != "NetworkManager" ||
		!reflect.DeepEqual(static.Nameservers, []string{"198.51.100.53", "198.51.100.54"}) ||
		!reflect.DeepEqual(static.Search, []string{"example.internal"}) ||
		!reflect.DeepEqual(static.Options, []string{"timeout:2"}) {
		t.Fatalf("static = %+v", static)
	}
	if missing := readResolvConf(filepath.Join(t.TempDir(), "nope")); missing.Mode != "missing" || missing.Nameservers == nil {
		t.Fatalf("missing = %+v", missing)
	}
}

func TestDNSKindAndAdblockImages(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct{ process, addr, want string }{
		{"systemd-resolve", "127.0.0.53", "resolved-stub"},
		{"", "127.0.0.54", "resolved-stub"},
		{"dnsmasq", "0.0.0.0", "dnsmasq"},
		{"unbound", "127.0.0.1", "unbound"},
		{"named", "::", "named"},
		{"AdGuardHome", "0.0.0.0", "adguardhome"},
		{"pihole-FTL", "0.0.0.0", "pihole"},
		{"docker-proxy", "0.0.0.0", "docker-proxy"},
		{"coredns", "0.0.0.0", "other"},
	} {
		if got := dnsKind(tc.process, tc.addr); got != tc.want {
			t.Errorf("dnsKind(%q, %q) = %q, want %q", tc.process, tc.addr, got, tc.want)
		}
	}
	for image, want := range map[string]string{
		"adguard/adguardhome":               "adguardhome",
		"adguard/adguardhome:v0.107.50":     "adguardhome",
		"docker.io/adguard/adguardhome":     "adguardhome",
		"registry.local:5000/adguardhome:1": "adguardhome",
		"pihole/pihole:latest":              "pihole",
		"ghcr.io/pi-hole/pihole:2024.07.0":  "pihole",
		"pihole/pihole@sha256:abc":          "pihole",
		"nginx:1.27":                        "",
		"adguard/something":                 "",
	} {
		if got := adblockKind(image); got != want {
			t.Errorf("adblockKind(%q) = %q, want %q", image, got, want)
		}
	}
}

func TestDetectAdblockAsContainerAndProcess(t *testing.T) {
	t.Parallel()
	containers := []DNSContainer{
		{Name: "adguard", Image: "adguard/adguardhome:latest", State: "running", Ports: []DNSPort{
			{Private: 53, Public: 53, Type: "udp"}, {Private: 53, Public: 53, Type: "tcp"},
			{Private: 3000, Public: 3001, Type: "tcp"}, {Private: 853, Public: 853, Type: "tcp"},
		}},
		{Name: "old-pihole", Image: "pihole/pihole", State: "exited"},
		{Name: "web", Image: "nginx", State: "running"},
	}
	listeners := []proxysvc.Listener{
		{Protocol: "udp", Address: "0.0.0.0", Port: 53, PID: 900, Process: "docker-proxy", Scope: proxysvc.ScopeAll},
		{Protocol: "udp", Address: "127.0.0.1", Port: 53, PID: 410, Process: "pihole-FTL", Scope: proxysvc.ScopeLoopback},
		{Protocol: "tcp", Address: "127.0.0.1", Port: 8080, PID: 410, Process: "pihole-FTL", Scope: proxysvc.ScopeLoopback},
		{Protocol: "tcp", Address: "127.0.0.1", Port: 4711, PID: 410, Process: "pihole-FTL", Scope: proxysvc.ScopeLoopback},
		{Protocol: "tcp", Address: "0.0.0.0", Port: 22, PID: 1, Process: "sshd"},
	}
	dns := dnsListeners(listeners)
	if len(dns) != 2 || dns[0].Kind != "docker-proxy" || dns[1].Kind != "pihole" || !dns[1].Loopback || dns[0].Loopback {
		t.Fatalf("listeners = %+v", dns)
	}
	got := detectAdblock(containers, listeners, dns)
	if len(got) != 2 {
		t.Fatalf("adblock = %+v", got)
	}
	if a := got[0]; a.Kind != "adguardhome" || a.RunsAs != "container" || a.Container != "adguard" || !a.Answering || a.WebPort != 3001 {
		t.Fatalf("container = %+v", a)
	}
	if a := got[1]; a.Kind != "pihole" || a.RunsAs != "process" || !a.Answering || a.WebPort != 8080 {
		t.Fatalf("process = %+v (4711 is FTL's API, 8080 its web page)", a)
	}
}

func TestPickWebPort(t *testing.T) {
	t.Parallel()
	port := func(private, public uint16) DNSPort { return DNSPort{Private: private, Public: public, Type: "tcp"} }
	if got := pickWebPort([]DNSPort{port(4711, 4711), port(8080, 8080), port(80, 80)}); got != 80 {
		t.Fatalf("got %d", got)
	}
	// By what the container listens on, reported as what it is published as.
	if got := pickWebPort([]DNSPort{port(853, 853), port(3000, 3001)}); got != 3001 {
		t.Fatalf("got %d", got)
	}
	if got := pickWebPort([]DNSPort{port(9000, 9000), port(7000, 7000), port(853, 100)}); got != 7000 {
		t.Fatalf("got %d", got)
	}
	if got := pickWebPort(nil); got != 0 {
		t.Fatalf("got %d", got)
	}
}

func TestPresetsCarryTheirNames(t *testing.T) {
	t.Parallel()
	byID := map[string]DNSPreset{}
	for _, p := range DNSPresets() {
		byID[p.ID] = p
		if len(p.TLSServers) != len(p.Servers) || !strings.HasSuffix(p.TLSServers[0], "#"+p.TLSName) {
			t.Errorf("%s: TLSServers = %v", p.ID, p.TLSServers)
		}
	}
	if len(byID) != 6 {
		t.Fatalf("%d presets", len(byID))
	}
	if p := byID["quad9"]; p.Servers[1] != "149.112.112.112" || p.TLSName != "dns.quad9.net" || !p.BlocksMalware || p.BlocksAds {
		t.Fatalf("quad9 = %+v", p)
	}
	if p := byID["mullvad-adblock"]; len(p.Servers) != 2 || !p.BlocksAds || p.Product != "mullvad" {
		t.Fatalf("mullvad = %+v", p)
	}
	if p := byID["cloudflare-malware"]; p.Servers[0] != "1.1.1.2" || p.Product != "cloudflare" {
		t.Fatalf("cloudflare malware = %+v", p)
	}
	for _, p := range DNSPresets() {
		for _, sv := range p.TLSServers {
			if _, err := cleanDNSServers([]string{sv}, "upstream"); err != nil {
				t.Errorf("%s: %v", sv, err)
			}
		}
	}
}

func TestReadResolvConfAcceptsTabsAndMixedWhitespace(t *testing.T) {
	path := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(path, []byte("nameserver\t192.0.2.53\nsearch\t home.arpa\tlan.example\noptions\ttimeout:1 attempts:2\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	rc := readResolvConf(path)
	if !reflect.DeepEqual(rc.Nameservers, []string{"192.0.2.53"}) || len(rc.Search) != 2 || len(rc.Options) != 2 {
		t.Fatalf("tab-delimited resolver configuration = %+v", rc)
	}
}

func TestDNSServersKeepPortsScopesAndTLSNames(t *testing.T) {
	tests := []struct{ input, entry, dial string }{
		{"1.1.1.1:5353", "1.1.1.1:5353", "1.1.1.1:5353"},
		{"[2001:db8:0::53]:5353#DNS.Example.", "[2001:db8::53]:5353#dns.example", "[2001:db8::53]:5353"},
		{"[fe80::53]:5353%eth0#dns.example", "[fe80::53]:5353%eth0#dns.example", "[fe80::53%eth0]:5353"},
		{"[fe80::53%eth0]:5353", "[fe80::53]:5353%eth0", "[fe80::53%eth0]:5353"},
		{"fe80::53%eth0", "fe80::53%eth0", "fe80::53%eth0"},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			clean, err := cleanDNSServers([]string{tc.input}, "upstream")
			if err != nil || len(clean) != 1 || clean[0] != tc.entry {
				t.Fatalf("clean = %v, %v", clean, err)
			}
			sv, err := parseDNSServer(clean[0])
			if err != nil || sv.lookupServer() != tc.dial {
				t.Fatalf("dial = %q, %v", sv.lookupServer(), err)
			}
		})
	}
}

func TestRestoreResolvedSurvivesCanceledRequest(t *testing.T) {
	s := testService(t)
	record(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	called := false
	run = func(ctx context.Context, name string, args ...string) (string, error) {
		called = true
		if ctx.Err() != nil {
			t.Errorf("resolver rollback inherited request cancellation: %v", ctx.Err())
		}
		if _, ok := ctx.Deadline(); !ok {
			t.Error("resolver rollback has no bounded recovery deadline")
		}
		return "", nil
	}
	s.restoreResolved(ctx, []byte("[Resolve]\nDNS=192.0.2.53\n"), true)
	if !called {
		t.Fatal("restored resolver was not restarted")
	}
}

func TestSetDNSVerifiesAnIsolatedLANName(t *testing.T) {
	s, _ := resolvedHost(t, func(name string, qtype uint16) dnsBehavior {
		if name == "nas.home.arpa" {
			return answerA("192.168.1.7")(name, qtype)
		}
		return dnsBehavior{rcode: 3}
	})
	res, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"192.168.1.53"}, VerificationName: "nas.home.arpa."}, "alice")
	if err != nil || !res.Verified || res.Via != "nas.home.arpa" {
		t.Fatalf("isolated LAN verification = %+v, %v", res, err)
	}
}

func TestVerifyDNSWorksWithoutAStubListener(t *testing.T) {
	rec := record(t)
	rec.on("resolvectl query --type=A --legend=no nas.home.arpa.", "nas.home.arpa: 192.168.1.7\n")
	previousDial := dnsDial
	t.Cleanup(func() { dnsDial = previousDial })
	dnsDial = func(context.Context, string, string) (net.Conn, error) { return nil, syscall.ECONNREFUSED }
	name, _, err := verifyResolution(context.Background(), "nas.home.arpa")
	if err != nil || name != "nas.home.arpa" {
		t.Fatalf("resolved with stub disabled = %q, %v", name, err)
	}
}

func TestCleanDNSSettings(t *testing.T) {
	t.Parallel()
	cf := []string{"1.1.1.1#cloudflare-dns.com", "1.0.0.1#cloudflare-dns.com"}
	tests := []struct {
		name    string
		req     DNSSettings
		wantErr string
	}{
		{"plain upstreams", DNSSettings{Servers: []string{"1.1.1.1", "2606:4700:4700::1111"}}, ""},
		{"DoT with names", DNSSettings{Servers: cf, DNSOverTLS: "yes", DNSSEC: "allow-downgrade", Cache: "yes"}, ""},
		{"DoT strict needs names", DNSSettings{Servers: []string{"1.1.1.1#cloudflare-dns.com", "1.0.0.1"}, DNSOverTLS: "yes"}, "needs a server name for every server"},
		{"DoT strict needs names on fallback", DNSSettings{Servers: cf, Fallback: []string{"9.9.9.9"}, DNSOverTLS: "yes"}, "needs a server name for every server"},
		{"DoT strict needs upstreams", DNSSettings{DNSOverTLS: "yes", DNSSEC: "yes"}, "needs upstreams"},
		{"opportunistic DoT needs none", DNSSettings{Servers: []string{"1.1.1.1"}, DNSOverTLS: "opportunistic"}, ""},
		{"not an address", DNSSettings{Servers: []string{"one.one.one.one"}}, "not an IP address"},
		{"link-local upstream", DNSSettings{Servers: []string{"fe80::1%eth0"}}, ""},
		{"custom port", DNSSettings{Servers: []string{"1.1.1.1:5353"}}, ""},
		{"unscoped link-local", DNSSettings{Servers: []string{"fe80::1"}}, "give its interface"},
		{"bad interface", DNSSettings{Servers: []string{"fe80::1%eth0\nDNS=8.8.8.8"}}, "interface"},
		{"zero port", DNSSettings{Servers: []string{"1.1.1.1:0"}}, "port"},
		{"bad tls name", DNSSettings{Servers: []string{"1.1.1.1#bad name"}}, "server name"},
		{"tls name with newline", DNSSettings{Servers: []string{"1.1.1.1#a.com\nDNS=6.6.6.6"}}, "server name"},
		{"stub as upstream", DNSSettings{Servers: []string{"127.0.0.53"}}, "ask itself"},
		{"unspecified", DNSSettings{Servers: []string{"0.0.0.0"}}, "cannot be a DNS server"},
		{"nine servers", DNSSettings{Servers: []string{"1.1.1.1", "1.0.0.1", "8.8.8.8", "8.8.4.4", "9.9.9.9", "149.112.112.112", "94.140.14.14", "94.140.15.15", "194.242.2.3"}}, "at most 8"},
		{"routing domain", DNSSettings{Servers: []string{"1.1.1.1"}, Domains: []string{"~.", "~corp.example.com", "lan.example.com"}}, ""},
		{"bad domain", DNSSettings{Servers: []string{"1.1.1.1"}, Domains: []string{"~bad domain"}}, "domain"},
		{"bad dnssec", DNSSettings{Servers: []string{"1.1.1.1"}, DNSSEC: "maybe"}, "DNSSEC is"},
		{"bad cache", DNSSettings{Servers: []string{"1.1.1.1"}, Cache: "forever"}, "cache"},
		{"nothing", DNSSettings{}, "nothing to set"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			_, err := cleanDNSSettings(tc.req)
			switch {
			case tc.wantErr == "" && err != nil:
				t.Fatalf("refused: %v", err)
			case tc.wantErr != "" && (err == nil || !strings.Contains(err.Error(), tc.wantErr)):
				t.Fatalf("error = %v, want one containing %q", err, tc.wantErr)
			}
		})
	}
	got, err := cleanDNSSettings(DNSSettings{Servers: []string{" 1.1.1.1#Cloudflare-DNS.com. ", "1.1.1.1#cloudflare-dns.com", "2606:4700:4700:0:0:0:0:1111"}})
	if err != nil || !reflect.DeepEqual(got.Servers, []string{"1.1.1.1#cloudflare-dns.com", "2606:4700:4700::1111"}) {
		t.Fatalf("normalised = %v, %v", got.Servers, err)
	}
}

func TestRenderResolvedRoundTrips(t *testing.T) {
	prev := dnsNow
	dnsNow = func() time.Time { return time.Date(2026, 10, 7, 9, 30, 0, 0, time.UTC) }
	t.Cleanup(func() { dnsNow = prev })

	req := DNSSettings{
		Servers:    []string{"1.1.1.1#cloudflare-dns.com", "2606:4700:4700::1111#cloudflare-dns.com"},
		Fallback:   []string{"9.9.9.9#dns.quad9.net"},
		Domains:    []string{"~.", "lan.example.com"},
		DNSSEC:     "allow-downgrade",
		DNSOverTLS: "yes",
		Cache:      "no-negative",
	}
	text := renderResolved(req, "ion")
	want := `# Generated by Just Dashboard for ion on 2026-10-07 09:30 UTC.
# systemd-resolved reads this after resolved.conf. Change it on the dashboard's
# Network, DNS page; an edit here is overwritten by the next change there.
[Resolve]
DNS=
DNS=1.1.1.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com
FallbackDNS=
FallbackDNS=9.9.9.9#dns.quad9.net
Domains=
Domains=~. lan.example.com
DNSSEC=allow-downgrade
DNSOverTLS=yes
Cache=no-negative
`
	if text != want {
		t.Fatalf("rendered:\n%s", text)
	}
	path := filepath.Join(t.TempDir(), "90-just-dashboard.conf")
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		t.Fatal(err)
	}
	m := readManagedDNS(path)
	if !m.Exists || !reflect.DeepEqual(m.Servers, req.Servers) || !reflect.DeepEqual(m.Fallback, req.Fallback) ||
		!reflect.DeepEqual(m.Domains, req.Domains) || m.DNSSEC != "allow-downgrade" || m.DNSOverTLS != "yes" || m.Cache != "no-negative" {
		t.Fatalf("read back = %+v", m)
	}
	// Only what was chosen is written.
	if min := renderResolved(DNSSettings{Servers: []string{"9.9.9.9"}}, ""); strings.Contains(min, "DNSSEC") || strings.Contains(min, "for ") {
		t.Fatalf("minimal drop-in:\n%s", min)
	}
	if m := readManagedDNS(filepath.Join(t.TempDir(), "absent")); m.Exists || m.Servers == nil {
		t.Fatalf("absent = %+v", m)
	}
}

// resolvedHost stages a host where systemd-resolved runs and the stub
// answers as resolve says. The drop-in's directory is the test service's.
func resolvedHost(t *testing.T, stub func(string, uint16) dnsBehavior) (*Service, *recorder) {
	t.Helper()
	rec := record(t)
	rec.on("systemctl is-active systemd-resolved", "active\n")
	rec.on("systemctl restart systemd-resolved", "")
	pointResolvConf(t, "stub")
	routeDNS(t, map[string]string{"127.0.0.53": startFakeDNS(t, stub)})
	lookupTimeout = 400 * time.Millisecond
	return testService(t), rec
}

func countRestarts(rec *recorder) int {
	n := 0
	for _, c := range rec.commands() {
		if c == "systemctl restart systemd-resolved" {
			n++
		}
	}
	return n
}

func TestSetDNSWritesVerifiesAndReports(t *testing.T) {
	s, rec := resolvedHost(t, answerA("192.0.2.1"))
	got, err := s.SetDNS(context.Background(), DNSSettings{
		Servers: []string{"1.1.1.1#cloudflare-dns.com", "1.0.0.1#cloudflare-dns.com"}, DNSOverTLS: "yes",
	}, "ion")
	if err != nil {
		t.Fatal(err)
	}
	if !got.Verified || got.Via != "cloudflare.com" || got.Warning != "" || !got.Managed.Exists || got.Managed.DNSOverTLS != "yes" {
		t.Fatalf("result = %+v", got)
	}
	data, err := os.ReadFile(s.paths.Resolved)
	if err != nil || !strings.Contains(string(data), "DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com\n") ||
		!strings.Contains(string(data), "for ion") {
		t.Fatalf("drop-in = %q, %v", data, err)
	}
	if st, _ := os.Stat(s.paths.Resolved); st.Mode().Perm() != 0o644 {
		t.Fatalf("mode = %v", st.Mode())
	}
	if countRestarts(rec) != 1 {
		t.Fatalf("restarts = %d: %v", countRestarts(rec), rec.commands())
	}
}

// A restart that fails leaves a resolver nobody can say the state of, so the
// previous file goes back and resolved is restarted onto it.
func TestSetDNSRestoresThePreviousFileWhenTheRestartFails(t *testing.T) {
	s, rec := resolvedHost(t, answerA("192.0.2.1"))
	rec.replies = append([]reply{{prefix: "systemctl restart", err: errors.New("Job failed"), out: "Job failed"}}, rec.replies...)
	previous := "[Resolve]\nDNS=9.9.9.9\n"
	if err := writeFileAtomic(s.paths.Resolved, []byte(previous), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"1.1.1.1"}}, "ion")
	if err == nil || !strings.Contains(err.Error(), "recovery also failed") {
		t.Fatalf("error = %v", err)
	}
	data, _ := os.ReadFile(s.paths.Resolved)
	if string(data) != previous {
		t.Fatalf("drop-in after failure = %q", data)
	}
	if countRestarts(rec) != 2 {
		t.Fatalf("resolved must be restarted onto the restored file: %v", rec.commands())
	}
}

func TestSetDNSRemovesTheNewFileWhenThereWasNone(t *testing.T) {
	s, rec := resolvedHost(t, answerA("192.0.2.1"))
	rec.replies = append([]reply{{prefix: "systemctl restart", err: errors.New("Job failed"), out: "Job failed"}}, rec.replies...)
	if _, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"1.1.1.1"}}, ""); err == nil {
		t.Fatal("a failed restart reported success")
	}
	if _, err := os.Stat(s.paths.Resolved); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("the drop-in was left behind: %v", err)
	}
}

// Upstreams that do not answer are a host that cannot resolve anything. The
// restart succeeds; the check is what notices.
func TestSetDNSRollsBackWhenTheNewUpstreamsDoNotAnswer(t *testing.T) {
	s, rec := resolvedHost(t, func(string, uint16) dnsBehavior { return dnsBehavior{rcode: 2} })
	previous := "[Resolve]\nDNS=9.9.9.9\n"
	if err := writeFileAtomic(s.paths.Resolved, []byte(previous), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"203.0.113.250"}}, "ion")
	var up *UpstreamError
	if !errors.As(err, &up) || !strings.Contains(up.Reason, "did not answer") || !strings.Contains(up.Reason, "previous settings were put back") {
		t.Fatalf("error = %v", err)
	}
	data, _ := os.ReadFile(s.paths.Resolved)
	if string(data) != previous {
		t.Fatalf("drop-in after rollback = %q", data)
	}
	if countRestarts(rec) != 2 {
		t.Fatalf("restarts = %d", countRestarts(rec))
	}
}

func TestSetDNSRefusesWithoutResolved(t *testing.T) {
	rec := record(t)
	rec.on("systemctl is-active systemd-resolved", "inactive\n")
	pointResolvConf(t, "static")
	s := testService(t)
	_, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"1.1.1.1"}}, "")
	var ro *ReadOnlyError
	if !errors.As(err, &ro) || !strings.Contains(ro.Reason, "systemd-resolved is not running here") || !strings.Contains(ro.Reason, "NetworkManager") {
		t.Fatalf("error = %v", err)
	}
	if _, err := os.Stat(s.paths.Resolved); err == nil {
		t.Fatal("wrote a drop-in for a service that is not running")
	}
	if rec.ran("systemctl restart") {
		t.Fatal("restarted a service that is not running")
	}
}

func TestSetDNSValidatesBeforeTouchingAnything(t *testing.T) {
	rec := record(t)
	s := testService(t)
	if _, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"1.1.1.1"}, DNSOverTLS: "yes"}, ""); err == nil {
		t.Fatal("DNS over TLS without server names was accepted")
	}
	if len(rec.commands()) != 0 {
		t.Fatalf("ran %v for a request that is invalid", rec.commands())
	}
}

func TestSetDNSWarnsWhenProgramsDoNotUseResolved(t *testing.T) {
	s, _ := resolvedHost(t, answerA("192.0.2.1"))
	pointResolvConf(t, "static")
	got, err := s.SetDNS(context.Background(), DNSSettings{Servers: []string{"1.1.1.1"}}, "")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got.Warning, "198.51.100.53") {
		t.Fatalf("warning = %q", got.Warning)
	}
}

func TestResetDNS(t *testing.T) {
	s, rec := resolvedHost(t, answerA("192.0.2.1"))
	got, err := s.ResetDNS(context.Background())
	if err != nil || got.Managed.Exists || countRestarts(rec) != 0 {
		t.Fatalf("resetting nothing: %+v, %v, %d restarts", got, err, countRestarts(rec))
	}
	if err := writeFileAtomic(s.paths.Resolved, []byte("[Resolve]\nDNS=9.9.9.9\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err = s.ResetDNS(context.Background())
	if err != nil || !got.Verified || got.Managed.Exists {
		t.Fatalf("reset = %+v, %v", got, err)
	}
	if _, err := os.Stat(s.paths.Resolved); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("drop-in still there: %v", err)
	}
	if countRestarts(rec) != 1 {
		t.Fatalf("restarts = %d", countRestarts(rec))
	}
}

func TestResetDNSPutsTheFileBackWhenTheRestartFails(t *testing.T) {
	s, rec := resolvedHost(t, answerA("192.0.2.1"))
	rec.replies = append([]reply{{prefix: "systemctl restart", err: errors.New("Job failed"), out: "Job failed"}}, rec.replies...)
	previous := "[Resolve]\nDNS=9.9.9.9\n"
	if err := writeFileAtomic(s.paths.Resolved, []byte(previous), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := s.ResetDNS(context.Background()); err == nil {
		t.Fatal("a failed restart reported success")
	}
	if data, _ := os.ReadFile(s.paths.Resolved); string(data) != previous {
		t.Fatalf("drop-in = %q", data)
	}
}

func TestDNSReadsTheWholeChain(t *testing.T) {
	rec := record(t)
	rec.on("systemctl is-active systemd-resolved", "active\n").
		on("resolvectl status --no-pager", fixture(t, "dns-resolvectl-status-dot.txt")).
		on("resolvectl statistics", fixture(t, "dns-resolvectl-statistics.txt"))
	pointResolvConf(t, "stub")
	prev := listListeners
	listListeners = func(context.Context) ([]proxysvc.Listener, error) {
		return []proxysvc.Listener{
			{Protocol: "udp", Address: "127.0.0.53", Port: 53, PID: 700, Process: "systemd-resolve", Scope: proxysvc.ScopeLoopback},
			{Protocol: "tcp", Address: "127.0.0.53", Port: 53, PID: 700, Process: "systemd-resolve", Scope: proxysvc.ScopeLoopback},
			{Protocol: "tcp", Address: "0.0.0.0", Port: 443, PID: 9, Process: "caddy"},
		}, nil
	}
	t.Cleanup(func() { listListeners = prev })
	s := testService(t)
	if err := writeFileAtomic(s.paths.Resolved, []byte("[Resolve]\nDNS=1.1.1.1#cloudflare-dns.com\nDNSOverTLS=yes\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	v, err := s.DNS(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	if v.ResolvConf.Mode != "stub" || !v.Resolved.Active || v.Resolved.Global.DNSOverTLS != "yes" ||
		v.Resolved.Statistics == nil || v.Resolved.Statistics.HitPercent != 89 {
		t.Fatalf("resolved = %+v", v.Resolved)
	}
	if len(v.Listeners) != 2 || v.Listeners[0].Kind != "resolved-stub" {
		t.Fatalf("listeners = %+v", v.Listeners)
	}
	if !v.Managed.Exists || v.Managed.DNSOverTLS != "yes" || len(v.Presets) != 6 || v.Adblock == nil {
		t.Fatalf("managed = %+v", v.Managed)
	}

	sum := s.DNSSummary(context.Background(), []DNSContainer{{Name: "pihole", Image: "pihole/pihole", State: "running"}})
	if sum.Resolver != "systemd-resolved" || sum.DNSOverTLS != "yes" || sum.DNSSEC != "allow-downgrade" || !sum.Adblock || !sum.Custom ||
		len(sum.Upstreams) != 4 {
		t.Fatalf("summary = %+v", sum)
	}
}

func TestDNSOnAHostWithoutResolved(t *testing.T) {
	record(t, "resolvectl")
	pointResolvConf(t, "static")
	prev := listListeners
	listListeners = func(context.Context) ([]proxysvc.Listener, error) {
		return []proxysvc.Listener{{Protocol: "udp", Address: "127.0.0.1", Port: 53, PID: 5, Process: "dnsmasq", Scope: proxysvc.ScopeLoopback}}, nil
	}
	t.Cleanup(func() { listListeners = prev })
	s := testService(t)
	v, err := s.DNS(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	if v.Resolved.Installed || v.Resolved.Active || v.Resolved.Links == nil {
		t.Fatalf("resolved = %+v", v.Resolved)
	}
	sum := s.DNSSummary(context.Background(), nil)
	if sum.Resolver != "dnsmasq" || sum.Mode != "static" || len(sum.Upstreams) != 2 || sum.DNSOverTLS != "no" {
		t.Fatalf("summary = %+v", sum)
	}
}

func TestServerIP(t *testing.T) {
	t.Parallel()
	for in, want := range map[string]string{
		"1.1.1.1":                    "1.1.1.1",
		"1.1.1.1#cloudflare-dns.com": "1.1.1.1",
		"1.1.1.1:5353":               "1.1.1.1",
		"[::1]:5353":                 "::1",
		"fe80::1%eth0":               "fe80::1",
		"2606:4700:4700::1111#cloudflare-dns.com": "2606:4700:4700::1111",
	} {
		got, ok := serverIP(in)
		if !ok || got.String() != want {
			t.Errorf("serverIP(%q) = %v, %v; want %s", in, got, ok, want)
		}
	}
	if _, ok := serverIP("not-an-address"); ok {
		t.Error("a name read as an address")
	}
}

func TestSetDNSVerifiesAnIPv6OnlyLANName(t *testing.T) {
	s, _ := resolvedHost(t, func(name string, qtype uint16) dnsBehavior {
		if name == "nas.home.arpa" && qtype == 28 {
			return dnsBehavior{rdatas: [][]byte{net.ParseIP("fd00::7").To16()}}
		}
		return dnsBehavior{}
	})
	res, err := s.SetDNS(t.Context(), DNSSettings{Servers: []string{"fd00::53"}, VerificationName: "nas.home.arpa"}, "alice")
	if err != nil || !res.Verified || res.Via != "nas.home.arpa" {
		t.Fatalf("IPv6-only LAN verification = %+v, %v", res, err)
	}
}

func TestVerifyIPv6DNSWorksWithoutAStubListener(t *testing.T) {
	rec := record(t)
	rec.on("resolvectl query --type=A --legend=no nas.home.arpa.", "nas.home.arpa: no A records\n")
	rec.on("resolvectl query --type=AAAA --legend=no nas.home.arpa.", "nas.home.arpa: fd00::7\n")
	previousDial := dnsDial
	t.Cleanup(func() { dnsDial = previousDial })
	dnsDial = func(context.Context, string, string) (net.Conn, error) { return nil, syscall.ECONNREFUSED }
	name, _, err := verifyResolution(t.Context(), "nas.home.arpa")
	if err != nil || name != "nas.home.arpa" {
		t.Fatalf("IPv6 resolved with stub disabled = %q, %v", name, err)
	}
}

func TestDNSRefusesUnreadableBackupBeforeMutation(t *testing.T) {
	for _, reset := range []bool{false, true} {
		t.Run(fmt.Sprint(reset), func(t *testing.T) {
			s, rec := resolvedHost(t, answerA("192.0.2.7"))
			if err := os.MkdirAll(s.paths.Resolved, 0o700); err != nil {
				t.Fatal(err)
			}
			var err error
			if reset {
				_, err = s.ResetDNS(t.Context())
			} else {
				_, err = s.SetDNS(t.Context(), DNSSettings{Servers: []string{"192.0.2.53"}}, "alice")
			}
			if err == nil || !strings.Contains(err.Error(), "reading the resolver drop-in") {
				t.Fatalf("unreadable backup = %v", err)
			}
			if rec.ran("systemctl restart systemd-resolved") {
				t.Fatal("resolver changed without a readable rollback backup")
			}
			if st, statErr := os.Stat(s.paths.Resolved); statErr != nil || !st.IsDir() {
				t.Fatalf("prior entry changed: %v", statErr)
			}
		})
	}
}

func TestDNSReportsRecoveryFailure(t *testing.T) {
	s, _ := resolvedHost(t, answerA("192.0.2.7"))
	previousRun := run
	run = func(ctx context.Context, name string, args ...string) (string, error) {
		if name == "systemctl" && len(args) > 0 && args[0] == "restart" {
			return "", errors.New("systemd manager unreachable")
		}
		return previousRun(ctx, name, args...)
	}
	_, err := s.SetDNS(t.Context(), DNSSettings{Servers: []string{"192.0.2.53"}}, "alice")
	if err == nil || !strings.Contains(err.Error(), "recovery also failed") || !strings.Contains(err.Error(), "restarting the previous resolver") {
		t.Fatalf("recovery failure hidden: %v", err)
	}
}
