package netx

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Wayy01/Just-Dashboard/backend/internal/proxysvc"
)

// stagedHost is a host root the owner adapter reads instead of this machine:
// files are written under it, links are made inside it, and /etc/resolv.conf
// is read through it the way the dashboard's container reads /host.
type stagedHost struct {
	files map[string]string
	links map[string]string
	dirs  []string
}

func stageHost(t *testing.T, h stagedHost) {
	t.Helper()
	root := t.TempDir()
	for _, dir := range h.dirs {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	for path, body := range h.files {
		full := filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	for path, target := range h.links {
		full := filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(target, full); err != nil {
			t.Fatal(err)
		}
	}
	prevHost, prevOwner, prevPath := dnsHostRoot, dnsOwnerRoot, resolvConfPath
	dnsHostRoot, dnsOwnerRoot, resolvConfPath = root, root, "/etc/resolv.conf"
	t.Cleanup(func() { dnsHostRoot, dnsOwnerRoot, resolvConfPath = prevHost, prevOwner, prevPath })
}

func resolverOwnerOf(t *testing.T, resolved bool, mode string, listeners ...DNSListener) ResolverOwner {
	t.Helper()
	rc := readResolvConf(resolvConfPath)
	return resolverOwner(context.Background(), rc, ResolvedView{Active: resolved, Global: ResolvedGlobal{ResolvConfMode: mode}}, listeners)
}

const stubBody = "# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).\n# Do not edit.\nnameserver 127.0.0.53\noptions edns0 trust-ad\nsearch staged.example\n"

func TestResolverOwnerAcrossDistributions(t *testing.T) {
	loopbackUnbound := DNSListener{Address: "127.0.0.1", Protocol: "udp", Process: "unbound", Kind: "unbound", Loopback: true}
	loopbackDnsmasq := DNSListener{Address: "127.0.0.1", Protocol: "udp", Process: "dnsmasq", Kind: "dnsmasq", Loopback: true}
	for _, tc := range []struct {
		name                     string
		host                     stagedHost
		resolved                 bool
		mode                     string
		nm                       string
		listeners                []DNSListener
		id, chain, confidence    string
		writes                   bool
		href                     string
		handoff, conflict, notes string
	}{
		{
			name:     "Ubuntu stub link",
			host:     stagedHost{files: map[string]string{"/run/systemd/resolve/stub-resolv.conf": stubBody}, links: map[string]string{"/etc/resolv.conf": "../run/systemd/resolve/stub-resolv.conf"}},
			resolved: true, mode: "stub",
			id: "systemd-resolved", chain: "stub", confidence: "confirmed", writes: true, href: "#dns-links", handoff: "drop-in",
		},
		{
			name:     "absolute stub link is read inside the host root",
			host:     stagedHost{files: map[string]string{"/run/systemd/resolve/stub-resolv.conf": stubBody}, links: map[string]string{"/etc/resolv.conf": "/run/systemd/resolve/stub-resolv.conf"}},
			resolved: true, mode: "stub",
			id: "systemd-resolved", chain: "stub", confidence: "confirmed", writes: true, notes: "staged.example",
		},
		{
			name: "Fedora NetworkManager delegating to resolved",
			host: stagedHost{
				files: map[string]string{"/run/systemd/resolve/stub-resolv.conf": stubBody, "/etc/NetworkManager/NetworkManager.conf": "[main]\nplugins=keyfile\n", "/usr/lib/NetworkManager/conf.d/20-resolved.conf": "[main]\ndns=systemd-resolved\n"},
				links: map[string]string{"/etc/resolv.conf": "../run/systemd/resolve/stub-resolv.conf"},
			},
			resolved: true, mode: "stub", nm: "active",
			id: "systemd-resolved", chain: "stub", confidence: "confirmed", writes: true, notes: "dns=systemd-resolved",
		},
		{
			name: "RHEL NetworkManager writing the file itself",
			host: stagedHost{files: map[string]string{
				"/etc/resolv.conf":                        "# Generated by NetworkManager\nsearch corp.example\nnameserver 10.0.0.53\n",
				"/etc/NetworkManager/NetworkManager.conf": "[main]\n#dns=dnsmasq\n",
			}},
			nm: "active",
			id: "networkmanager", chain: "direct", confidence: "confirmed", href: "/network/interfaces", handoff: "nmcli",
		},
		{
			name: "NetworkManager rc-manager=symlink through a /var/run link",
			host: stagedHost{
				files: map[string]string{"/run/NetworkManager/resolv.conf": "# Generated by NetworkManager\nnameserver 192.0.2.53\n", "/etc/NetworkManager/conf.d/rc.conf": "[main]\nrc-manager=symlink\n"},
				links: map[string]string{"/var/run": "../run", "/etc/resolv.conf": "/var/run/NetworkManager/resolv.conf"},
			},
			nm: "active",
			id: "networkmanager", chain: "direct", confidence: "confirmed", notes: "rc-manager=symlink",
		},
		{
			name: "NetworkManager's dnsmasq plugin",
			host: stagedHost{files: map[string]string{
				"/etc/resolv.conf":                      "# Generated by NetworkManager\nnameserver 127.0.0.1\n",
				"/etc/NetworkManager/conf.d/dns.conf":   "[main]\ndns=dnsmasq\n",
				"/usr/lib/NetworkManager/conf.d/a.conf": "[main]\ndns=default\n",
			}},
			nm: "active", listeners: []DNSListener{loopbackDnsmasq},
			id: "networkmanager", chain: "local-cache", confidence: "confirmed", handoff: "dnsmasq plugin",
		},
		{
			name: "resolved running while NetworkManager bypasses it",
			host: stagedHost{files: map[string]string{
				"/etc/resolv.conf":                        "# Generated by NetworkManager\nnameserver 10.0.0.53\n",
				"/etc/NetworkManager/NetworkManager.conf": "[main]\ndns=systemd-resolved\nrc-manager=file\n",
			}},
			resolved: true, mode: "foreign", nm: "inactive",
			id: "networkmanager", chain: "direct", confidence: "declared", conflict: "does not reach them",
		},
		{
			name: "Debian resolvconf",
			host: stagedHost{
				files: map[string]string{"/run/resolvconf/resolv.conf": "# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)\n#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN\nnameserver 192.0.2.1\n"},
				links: map[string]string{"/etc/resolv.conf": "../run/resolvconf/resolv.conf"},
				dirs:  []string{"/etc/resolvconf/resolv.conf.d"},
			},
			id: "resolvconf", chain: "direct", confidence: "confirmed", handoff: "resolvconf -u",
		},
		{
			name: "openresolv on Alpine or Arch",
			host: stagedHost{files: map[string]string{"/etc/resolv.conf": "# Generated by resolvconf\nnameserver 192.0.2.1\n", "/etc/resolvconf.conf": "name_servers=192.0.2.1\n"}},
			id:   "openresolv", chain: "direct", confidence: "confirmed", handoff: "/etc/resolvconf.conf",
		},
		{
			name: "SUSE netconfig",
			host: stagedHost{
				files: map[string]string{"/run/netconfig/resolv.conf": "### /etc/resolv.conf is a symlink to /run/netconfig/resolv.conf\n### autogenerated by netconfig!\nnameserver 192.0.2.1\n", "/etc/sysconfig/network/config": "NETCONFIG_DNS_POLICY=\"auto\"\n"},
				links: map[string]string{"/etc/resolv.conf": "/run/netconfig/resolv.conf"},
			},
			id: "netconfig", chain: "direct", confidence: "confirmed", handoff: "netconfig update -f",
		},
		{
			name: "dhcpcd on Raspberry Pi OS",
			host: stagedHost{files: map[string]string{"/etc/resolv.conf": "# Generated by dhcpcd from eth0.dhcp\n# /etc/resolv.conf.head can replace this line\nnameserver 192.168.1.1\n"}},
			id:   "dhcpcd", chain: "direct", confidence: "declared", handoff: "dhcpcd.conf",
		},
		{
			name: "Tailscale writing the file",
			host: stagedHost{files: map[string]string{"/etc/resolv.conf": "# resolv.conf(5) file generated by tailscale\n# For more info, see https://tailscale.com/s/resolvconf-overwrite\n# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN\n\nnameserver 100.100.100.100\n"}},
			id:   "tailscale", chain: "direct", confidence: "declared", conflict: "tailscaled rewrites",
		},
		{
			name: "WSL",
			host: stagedHost{files: map[string]string{"/etc/resolv.conf": "# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:\nnameserver 172.20.0.1\n"}},
			id:   "wsl", chain: "direct", confidence: "declared", handoff: "wsl.conf",
		},
		{
			name:      "Unbound answering on loopback",
			host:      stagedHost{files: map[string]string{"/etc/resolv.conf": "nameserver 127.0.0.1\n"}},
			listeners: []DNSListener{loopbackUnbound},
			id:        "local-cache", chain: "local-cache", confidence: "inferred", handoff: "Unbound",
		},
		{
			name: "plain file",
			host: stagedHost{files: map[string]string{"/etc/resolv.conf": "nameserver 192.0.2.53\n"}},
			id:   "static", chain: "direct", confidence: "inferred", handoff: "edit it directly",
		},
		{
			name: "missing file",
			host: stagedHost{dirs: []string{"/etc"}},
			id:   "missing", chain: "missing", confidence: "unknown", handoff: "does not exist",
		},
		{
			name:     "uplink link",
			host:     stagedHost{files: map[string]string{"/run/systemd/resolve/resolv.conf": "nameserver 192.0.2.53\n"}, links: map[string]string{"/etc/resolv.conf": "../run/systemd/resolve/resolv.conf"}},
			resolved: true, mode: "uplink",
			id: "systemd-resolved", chain: "uplink", confidence: "confirmed", writes: true, conflict: "routing domains, DNS over TLS",
		},
		{
			name: "stub link without resolved",
			host: stagedHost{files: map[string]string{"/run/systemd/resolve/stub-resolv.conf": stubBody}, links: map[string]string{"/etc/resolv.conf": "../run/systemd/resolve/stub-resolv.conf"}},
			id:   "systemd-resolved", chain: "stub", confidence: "declared", conflict: "not running", handoff: "Start systemd-resolved",
		},
		{
			name: "unrecognised link",
			host: stagedHost{files: map[string]string{"/opt/vpn/resolv.conf": "nameserver 198.51.100.7\n"}, links: map[string]string{"/etc/resolv.conf": "/opt/vpn/resolv.conf"}},
			id:   "unknown", chain: "direct", confidence: "unknown", handoff: "/opt/vpn/resolv.conf",
		},
		{
			name: "link loop",
			host: stagedHost{links: map[string]string{"/etc/resolv.conf": "/etc/loop", "/etc/loop": "/etc/resolv.conf"}},
			id:   "unknown", chain: "direct", confidence: "unknown", notes: "cannot be read",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rec := record(t)
			stageHost(t, tc.host)
			if tc.nm != "" {
				rec.on("systemctl is-active NetworkManager", tc.nm+"\n")
			}
			o := resolverOwnerOf(t, tc.resolved, tc.mode, tc.listeners...)
			if o.ID != tc.id || o.Chain != tc.chain || o.Confidence != tc.confidence || o.DashboardWrites != tc.writes || o.Name == "" {
				t.Fatalf("owner = %+v", o)
			}
			if tc.href != "" && o.HandoffHref != tc.href {
				t.Fatalf("handoff href = %q", o.HandoffHref)
			}
			if !strings.Contains(o.Handoff, tc.handoff) {
				t.Fatalf("handoff = %q, want %q", o.Handoff, tc.handoff)
			}
			joined := strings.Join(o.Conflicts, "\n")
			if tc.conflict != "" && !strings.Contains(joined, tc.conflict) {
				t.Fatalf("conflicts = %q, want %q", joined, tc.conflict)
			}
			if tc.conflict == "" && tc.id != "tailscale" && tc.id != "networkmanager" && len(o.Conflicts) > 0 && tc.chain != "uplink" {
				t.Fatalf("unexpected conflicts: %q", joined)
			}
			var evidence strings.Builder
			for _, e := range o.Evidence {
				evidence.WriteString(e.Source + ": " + e.Detail + "\n")
			}
			if tc.notes != "" && !strings.Contains(evidence.String(), tc.notes) {
				t.Fatalf("evidence = %s, want %q", evidence.String(), tc.notes)
			}
			if o.Evidence == nil || o.Conflicts == nil {
				t.Fatalf("lists must be arrays: %+v", o)
			}
			if tc.nm == "" && rec.ran("systemctl is-active NetworkManager") {
				t.Fatal("asked about NetworkManager on a host with no sign of it")
			}
		})
	}
}

// A conf.d snippet in /etc shadows the one with its name in /usr/lib, and the
// snippets are read in name order after NetworkManager.conf.
func TestNetworkManagerDNSConfigurationPrecedence(t *testing.T) {
	record(t)
	stageHost(t, stagedHost{files: map[string]string{
		"/etc/NetworkManager/NetworkManager.conf":      "[main]\ndns=default\nrc-manager=file\n",
		"/usr/lib/NetworkManager/conf.d/10-dns.conf":   "[main]\ndns=dnsmasq\n",
		"/etc/NetworkManager/conf.d/10-dns.conf":       "[main]\ndns=systemd-resolved\n",
		"/run/NetworkManager/conf.d/20-unrelated.conf": "[logging]\ndns=none\n",
		"/etc/resolv.conf":                             "nameserver 192.0.2.1\n",
	}})
	cfg := readNetworkManagerDNS()
	if !cfg.present || cfg.dns != "systemd-resolved" || cfg.dnsFrom != "/etc/NetworkManager/conf.d/10-dns.conf" || cfg.rcManager != "file" {
		t.Fatalf("nm = %+v", cfg)
	}
}

// The view carries the owner, and a refusal on a host without resolved names
// the owner's own place to change DNS.
func TestDNSViewAndRefusalNameTheOwner(t *testing.T) {
	rec := record(t, "resolvectl")
	rec.on("systemctl is-active systemd-resolved", "inactive\n").on("systemctl is-active NetworkManager", "active\n")
	stageHost(t, stagedHost{files: map[string]string{
		"/run/NetworkManager/resolv.conf":         "# Generated by NetworkManager\nnameserver 192.0.2.53\n",
		"/etc/NetworkManager/NetworkManager.conf": "[main]\nrc-manager=symlink\n",
	}, links: map[string]string{"/etc/resolv.conf": "/run/NetworkManager/resolv.conf"}})
	prev := listListeners
	listListeners = func(context.Context) ([]proxysvc.Listener, error) { return nil, nil }
	t.Cleanup(func() { listListeners = prev })
	s := testService(t)
	v, err := s.DNS(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	if v.ResolvConf.Mode != "link" || v.ResolvConf.ManagedBy != "NetworkManager" || len(v.ResolvConf.Nameservers) != 1 || v.Owner.ID != "networkmanager" || v.Owner.HandoffHref != "/network/interfaces" {
		t.Fatalf("view = %+v / %+v", v.ResolvConf, v.Owner)
	}
	_, err = s.SetDNS(context.Background(), DNSSettings{Servers: []string{"192.0.2.9"}}, "")
	if err == nil || !strings.Contains(err.Error(), "NetworkManager decides /etc/resolv.conf") || !strings.Contains(err.Error(), "nmcli") {
		t.Fatalf("refusal = %v", err)
	}
}

// Read-only evidence on the machine running the test: the owner verdict for
// its own resolver chain. It reads files and asks resolvectl and systemctl for
// state; it writes nothing. Set JD_DNS_OWNER_LIVE=1 to run it.
func TestResolverOwnerReadsThisHost(t *testing.T) {
	if os.Getenv("JD_DNS_OWNER_LIVE") != "1" {
		t.Skip("set JD_DNS_OWNER_LIVE=1 to read this host's resolver owner")
	}
	s := testService(t)
	rc := readResolvConf(resolvConfPath)
	rv := s.readResolved(context.Background(), false)
	o := resolverOwner(context.Background(), rc, rv, nil)
	if o.ID == "" || o.Name == "" || o.Handoff == "" || o.Evidence == nil {
		t.Fatalf("owner = %+v", o)
	}
	t.Logf("owner=%s chain=%s confidence=%s dashboardWrites=%t handoff=%q", o.ID, o.Chain, o.Confidence, o.DashboardWrites, o.Handoff)
	for _, e := range o.Evidence {
		t.Logf("evidence %s: %s", e.Source, e.Detail)
	}
	for _, c := range o.Conflicts {
		t.Logf("conflict: %s", c)
	}
}
