package netx

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// UnitName is the oneshot unit that restores the dashboard's network at boot.
const UnitName = "just-dashboard-network.service"

// The files rendered from the spec, under Paths.Dir.
const (
	linksFile   = "links.batch"
	rules6File  = "rules6.batch"
	shapingFile = "shaping.batch"
	gatewayFile = "gateway.nft"
)

// rendered is every file the spec becomes, by path.
type rendered map[string][]byte

// renderAll turns a spec into its files. Pure: the same spec renders the same
// bytes, which is what the golden tests pin and what lets commit write only
// the files a change actually touched.
func (s *Service) renderAll(sp *Spec) (rendered, error) {
	return s.renderAllWithGateway(sp, nil)
}

func (s *Service) renderAllWithGateway(sp *Spec, candidate *string) (rendered, error) {
	var gateway string
	if candidate != nil {
		gateway = *candidate
	} else {
		var err error
		gateway, err = renderGateway(sp, s.trustedFor(sp))
		if err != nil {
			return nil, err
		}
	}
	out := rendered{
		filepath.Join(s.paths.Dir, linksFile):   []byte(renderLinks(sp)),
		filepath.Join(s.paths.Dir, rules6File):  []byte(renderIPv6Rules(sp)),
		filepath.Join(s.paths.Dir, shapingFile): []byte(renderShaping(sp)),
		filepath.Join(s.paths.Dir, gatewayFile): []byte(gateway),
		s.paths.Sysctl:                          []byte(renderSysctl(sp)),
		s.paths.Unit:                            []byte(s.unitFor(sp)),
	}
	return out, nil
}

// unitFor is the boot unit a spec needs on this host.
func (s *Service) unitFor(sp *Spec) string {
	return renderUnitWith(s.paths, needsAdmission(sp), shapingCleanup(sp), bridgeUnitCommands(sp), s.independentRecovery, hasSQM(sp))
}

const generatedHeader = "# Generated by Just Dashboard from spec.json. Edits here are overwritten;\n# change the network on the dashboard's Network pages instead.\n"

// renderUnit restores ordinary resources with failure-tolerant commands so one part
// failing — a device whose parent is gone, a Docker that is not installed, a
// host without nftables — does not stop the rest being restored, the same
// reason the batch files run with -force; each failure is still in the
// unit's journal.
//
// Ordered after the network managers, Docker and the firewalls rather than
// before them: a VLAN needs its parent configured, the forward admission goes
// in front of the rules ufw and Docker write, and Docker's DOCKER-USER chain
// exists only once Docker has started.
func renderUnit(paths Paths, admission bool, recovery ...bool) string {
	return renderUnitWith(paths, admission, nil, nil, recovery...)
}

// renderUnitWith is renderUnit with the shaping deletes that clear a device
// before its queues are replaced, and the bridge commands a spec needs after
// its devices exist: port VLAN memberships and VXLAN flood destinations, which
// `ip -batch` cannot carry. Each is a separate failure-tolerant line, and a
// spec without them renders exactly the unit it always did.
//
// Deletes that only clear the way (an admission rule, a queue or policer that
// is about to be replaced) are ExecStartPre lines. On a fresh boot there is
// nothing to delete and they fail by design; kept apart, the ExecStart lines
// are the restoration itself, so their measured exits are a boot's result.
func renderUnitWith(paths Paths, admission bool, cleanup, bridge [][]string, recovery ...bool) string {
	dir := paths.Dir
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(`[Unit]
Description=Just Dashboard network: the devices, routes, gateway and shaping it made
Documentation=https://github.com/JustDashboard/Just-Dashboard
Wants=network-online.target
After=network-online.target systemd-networkd.service NetworkManager.service networking.service docker.service ufw.service firewalld.service
# systemd-networkd removes routes and rules it did not make when it restarts
# (netplan apply, an upgrade), so this unit restarts with it and puts them back.
PartOf=systemd-networkd.service

[Service]
Type=oneshot
		RemainAfterExit=yes
`)
	if len(recovery) > 0 && recovery[0] {
		fmt.Fprintf(&b, "ExecStartPre=%s --network-recover-boot %s pending\n", filepath.Join(dir, recoveryBinary), dir)
	}
	for _, cmd := range admissionCommands(false) {
		fmt.Fprintf(&b, "ExecStartPre=-%s\n", strings.Join(cmd, " "))
	}
	for _, cmd := range cleanup {
		fmt.Fprintf(&b, "ExecStartPre=-tc %s\n", strings.Join(cmd, " "))
	}
	fmt.Fprintf(&b, "ExecStart=-ip -force -batch %s\n", filepath.Join(dir, linksFile))
	for _, cmd := range bridge {
		fmt.Fprintf(&b, "ExecStart=-bridge %s\n", strings.Join(cmd, " "))
	}
	fmt.Fprintf(&b, "ExecStart=-ip -6 -force -batch %s\n", filepath.Join(dir, rules6File))
	fmt.Fprintf(&b, "ExecStart=-tc -force -batch %s\n", filepath.Join(dir, shapingFile))
	fmt.Fprintf(&b, "ExecStart=-nft -f %s\n", filepath.Join(dir, gatewayFile))
	for _, cmd := range admissionCommands(admission) {
		if cmd[1] == "-I" {
			fmt.Fprintf(&b, "ExecStart=-%s\n", strings.Join(cmd, " "))
		}
	}
	// The kernel settings again, now that loading the gateway table has
	// loaded conntrack: systemd-sysctl ran before the module existed, so
	// nf_conntrack_max was not there to set, and a later sysctl.d file may
	// have overridden the rest.
	fmt.Fprintf(&b, "ExecStart=-sysctl -q -p %s\n", paths.Sysctl)
	if len(recovery) > 1 && recovery[1] {
		// Other network resources restore first; a failed optional SQM helper
		// is visible as a failed unit without blocking their restoration.
		fmt.Fprintf(&b, "ExecStart=%s --network-sqm-restore %s\n", filepath.Join(dir, recoveryBinary), dir)
	}
	b.WriteString("ExecStop=-nft delete table inet " + gatewayTable + "\n")
	for _, cmd := range admissionCommands(false) {
		fmt.Fprintf(&b, "ExecStop=-%s\n", strings.Join(cmd, " "))
	}
	b.WriteString(`
[Install]
WantedBy=multi-user.target systemd-networkd.service
`)
	return b.String()
}

// step is the runtime half of a change: what to run on the host now, how to
// take it back, and what to check once it ran.
type step struct {
	apply             func(ctx context.Context) error
	undo              func(ctx context.Context)
	verify            func(ctx context.Context) error
	verifyPersistence func(ctx context.Context) error
	// recovery carries observed state that cannot be reconstructed from the
	// previous managed spec, such as an interface's original default MTU.
	recovery []recoveryCommand
	// Fetched cache replacements are staged until the journal is durable.
	recoveryFiles []recoverySnapshot
	gatewayRules  *string
}

// commit makes a change the proxy editor's way: render the new spec and check
// what can be checked, apply the one runtime change, verify it, and only then
// write the boot files and the spec. Anything failing before the files are
// written puts the runtime change back, so the files never describe a network
// that did not work. The caller holds s.mu.
func (s *Service) commit(ctx context.Context, sp *Spec, st step) error {
	lock, err := lockChange(s.paths.Dir)
	if err != nil {
		return err
	}
	defer unlockChange(lock)
	files, err := s.renderAllWithGateway(sp, st.gatewayRules)
	if err != nil {
		return err
	}
	// The ruleset is checked only when the gateway holds something: a host
	// without nftables can still have its bridges, routes and kernel settings
	// made, and an empty table has nothing to get wrong. The gateway's own
	// changes load the table, which says plainly when nft is missing.
	gatewayPath := filepath.Join(s.paths.Dir, gatewayFile)
	if gatewayHolds(sp) && changed(gatewayPath, files[gatewayPath]) {
		if err := checkRuleset(ctx, s.paths.Dir, files[gatewayPath]); err != nil {
			return err
		}
	}
	b, err := json.MarshalIndent(sp, "", "  ")
	if err != nil {
		return err
	}
	files[s.specPath()] = append(b, '\n')
	// Capture every previous file before touching the kernel. A directory or
	// unreadable target is an error, not a file that can safely be replaced.
	var paths []string
	previous := map[string]savedNetworkFile{}
	for path, data := range files {
		if !changed(path, data) {
			continue
		}
		before, err := saveNetworkFile(path)
		if err != nil {
			return fmt.Errorf("reading %s before changing the network: %w", path, err)
		}
		previous[path] = before
		if path != s.specPath() {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	if _, changed := previous[s.specPath()]; changed {
		paths = append(paths, s.specPath())
	}
	journal, err := s.prepareChange(ctx, sp, paths, previous, files[s.specPath()], st.recovery, st.recoveryFiles)
	if err != nil {
		return err
	}
	var runtimeFailures []string
	recoveryCtx := context.WithValue(ctx, recoveryErrorsKey{}, &runtimeFailures)
	finishRecovery := func(cause error, written []string, undo bool) error {
		journal.Phase = "recovering"
		if err := journal.save(); err != nil {
			journal.RecoveryErrors = append(journal.RecoveryErrors, "record recovery: "+err.Error())
		}
		for i := len(written) - 1; i >= 0; i-- {
			p := written[i]
			if err := previous[p].restore(p); err != nil {
				journal.RecoveryErrors = append(journal.RecoveryErrors, "restore "+p+": "+err.Error())
			}
		}
		if undo {
			rollback(recoveryCtx, st.undo)
		}
		if st.verifyPersistence != nil && has("systemctl") {
			for _, path := range written {
				if path == s.paths.Unit {
					_, err := run(recoveryCtx, "systemctl", "daemon-reload")
					recordRecoveryError(recoveryCtx, err)
					break
				}
			}
		}
		journal.RecoveryErrors = append(journal.RecoveryErrors, runtimeFailures...)
		journal.Phase, journal.Persistence, journal.Runtime = "recovered", "restored", "undo_attempted"
		if len(journal.RecoveryErrors) > 0 {
			journal.Phase, journal.Persistence, journal.Runtime = "degraded", "unknown", "unknown"
		}
		if err := journal.save(); err != nil {
			return errors.Join(cause, fmt.Errorf("recording recovery: %w", err))
		}
		return cause
	}
	if st.apply != nil {
		if err := st.apply(recoveryCtx); err != nil {
			return finishRecovery(err, nil, false)
		}
	}
	journal.Phase, journal.Runtime = "runtime_applied", "applied"
	journal.AppliedAt = time.Now().UTC()
	if err := journal.save(); err != nil {
		return finishRecovery(err, nil, true)
	}
	if st.verify != nil {
		if err := st.verify(recoveryCtx); err != nil {
			return finishRecovery(err, nil, true)
		}
	}
	unitChanged := changed(s.paths.Unit, files[s.paths.Unit])
	var written []string
	for _, path := range paths {
		perm := os.FileMode(0o644)
		if path == s.specPath() {
			perm = 0o600
		}
		// A rename can reach the filesystem before a later fsync reports
		// failure. Include the attempted path even when the writer fails.
		written = append(written, path)
		if err := writeNetworkFile(path, files[path], perm); err != nil {
			// Restoring only the kernel would leave the next boot applying the
			// failed candidate. Restore the complete file set before undoing it.
			return finishRecovery(fmt.Errorf("writing %s: %w", path, err), written, true)
		}
	}
	journal.Phase, journal.Persistence = "persisted", "written"
	if err := journal.save(); err != nil {
		return finishRecovery(err, written, true)
	}
	if err := s.ensureUnit(ctx, unitChanged); err != nil {
		if journal.OwnerUserID > 0 {
			return finishRecovery(err, written, true)
		}

		journal.Phase, journal.Boot = "boot_degraded", "failed"
		if journal.Watchdog == "armed" {
			journal.Watchdog = "completed"
		}
		if saveErr := journal.save(); saveErr != nil {
			return &persistenceError{errors.Join(err, saveErr)}
		}
		return &persistenceError{err}
	}
	if st.verifyPersistence != nil {
		if err := st.verifyPersistence(ctx); err != nil {
			return finishRecovery(err, written, true)
		}
	}
	journal.Phase, journal.Boot = "saved", "enabled"
	if journal.Watchdog == "armed" {
		journal.Watchdog = "completed"
	}
	if !has("systemctl") {
		journal.Boot = "unsupported"
	}
	if err := finishPendingConfirmation(journal); err != nil {
		return finishRecovery(err, written, true)
	}

	if err := journal.save(); err != nil {
		return finishRecovery(err, written, true)
	}
	return nil
}

// The kernel and spec are already committed when enabling the boot unit
// fails. Callers must retain ancillary state that the saved spec references.
type persistenceError struct{ error }

func (e *persistenceError) Unwrap() error { return e.error }

var writeNetworkFile = writeFileAtomic

var syncNetworkDirectory = func(path string) error {
	dir, err := os.Open(path)
	if err != nil {
		return err
	}
	defer dir.Close()
	return dir.Sync()
}

type savedNetworkFile struct {
	data   []byte
	perm   os.FileMode
	exists bool
}

func saveNetworkFile(path string) (savedNetworkFile, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return savedNetworkFile{}, nil
	}
	if err != nil {
		return savedNetworkFile{}, err
	}
	info, err := os.Stat(path)
	if err != nil {
		return savedNetworkFile{}, err
	}
	return savedNetworkFile{data: data, perm: info.Mode().Perm(), exists: true}, nil
}

func (f savedNetworkFile) restore(path string) error {
	if f.exists {
		return writeFileAtomic(path, f.data, f.perm)
	}
	err := os.Remove(path)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	// A terminal journal must not outlive an unlink lost at power failure.
	// Retry the sync even when an earlier attempt already removed the entry.
	parent := filepath.Dir(path)
	if err := syncNetworkDirectory(parent); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			if _, statErr := os.Lstat(parent); errors.Is(statErr, fs.ErrNotExist) {
				return nil
			}
		}
		return fmt.Errorf("syncing restored absence of %s: %w", path, err)
	}
	return nil
}

// A dropped browser or an expired request must not cancel the work that puts
// its network back. Keep request values for logging and a separate deadline.
func rollback(ctx context.Context, undo func(context.Context)) {
	if undo == nil {
		return
	}
	recovery, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
	defer cancel()
	undo(recovery)
}

// changed reports whether a file's contents differ from data. A file that
// cannot be read is treated as changed, so it is written.
func changed(path string, data []byte) bool {
	cur, err := os.ReadFile(path)
	return err != nil || !bytes.Equal(cur, data)
}

// checkRuleset asks nft to parse and type-check a ruleset without loading it.
// `nft -c` reads a file, so the candidate is written beside the real one
// first; it is removed whatever the answer.
func checkRuleset(ctx context.Context, dir string, ruleset []byte) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp := filepath.Join(dir, "."+gatewayFile+".check")
	if err := os.WriteFile(tmp, ruleset, 0o600); err != nil {
		return err
	}
	defer os.Remove(tmp)
	if _, err := run(ctx, "nft", "-c", "-f", tmp); err != nil {
		var missing *UnavailableError
		if errors.As(err, &missing) {
			return &UnavailableError{Tool: "nft", Package: "nftables"}
		}
		return fmt.Errorf("the gateway ruleset was refused by nft: %w", err)
	}
	return nil
}

// ensureUnit installs and enables the boot unit. It is enabled rather than
// started: everything it would restore was just applied, and running the
// batch files again over a live network would only report what already
// exists. systemd reads a changed unit after daemon-reload, so that runs only
// when the file changed.
func (s *Service) ensureUnit(ctx context.Context, unitChanged bool) error {
	if !has("systemctl") {
		// A host without systemd keeps the files; the Overview says nothing
		// will read them at boot.
		return nil
	}
	if unitChanged {
		if _, err := run(ctx, "systemctl", "daemon-reload"); err != nil {
			return fmt.Errorf("the network was changed, but systemd could not reload the boot unit: %w", err)
		}
	}
	if out, _ := run(ctx, "systemctl", "is-enabled", UnitName); strings.TrimSpace(out) == "enabled" {
		return nil
	}
	if _, err := run(ctx, "systemctl", "enable", UnitName); err != nil {
		return fmt.Errorf("the network was changed, but the unit that restores it at boot could not be enabled: %w", err)
	}
	return nil
}

// Persistence says how what the dashboard made survives a reboot, for the
// Overview's identity line.
type Persistence struct {
	// Unit is enabled, disabled, missing (nothing was made yet) or
	// unsupported (no systemd).
	Unit string `json:"unit"`
	// Made counts the entries the spec holds.
	Made   int           `json:"made"`
	Dir    string        `json:"dir"`
	Change *ChangeStatus `json:"change,omitempty"`
}

// PersistenceStatus reads the boot unit's state.
func (s *Service) PersistenceStatus(ctx context.Context) Persistence {
	p := Persistence{Dir: s.paths.Dir, Unit: "missing"}
	if journal, err := readChange(s.paths.Dir); err == nil {
		status := journal.ChangeStatus
		p.Change = &status
	} else if !errors.Is(err, fs.ErrNotExist) {
		p.Change = &ChangeStatus{Phase: "unreadable", Runtime: "unknown", Persistence: "unknown", Boot: "unknown"}
	}
	sp, err := s.loadSpec()
	if err == nil {
		p.Made = len(sp.Links) + len(sp.Addresses) + len(sp.Routes) + len(sp.Rules) +
			len(sp.Namespaces) + len(sp.Shaping) + len(sp.Forwards) + len(sp.NAT) +
			len(sp.Limits) + len(sp.Blocklists) + len(sp.Sysctls)
	}
	if !has("systemctl") {
		p.Unit = "unsupported"
		return p
	}
	if _, err := os.Stat(s.paths.Unit); errors.Is(err, fs.ErrNotExist) {
		return p
	}
	out, _ := run(ctx, "systemctl", "is-enabled", UnitName)
	if strings.TrimSpace(out) == "enabled" {
		p.Unit = "enabled"
	} else {
		p.Unit = "disabled"
	}
	return p
}

// gatewayHolds reports whether the spec puts anything into the gateway
// table, enabled or not: a disabled entry is still rendered, as a comment
// nft has to parse.
func gatewayHolds(sp *Spec) bool {
	return len(sp.Forwards)+len(sp.NAT)+len(sp.Limits)+len(sp.Blocklists) > 0
}
