package netx

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// UnitName is the oneshot unit that restores the dashboard's network at boot.
const UnitName = "just-dashboard-network.service"

// The files rendered from the spec, under Paths.Dir.
const (
	linksFile   = "links.batch"
	shapingFile = "shaping.batch"
	gatewayFile = "gateway.nft"
)

// rendered is every file the spec becomes, by path.
type rendered map[string][]byte

// renderAll turns a spec into its files. Pure: the same spec renders the same
// bytes, which is what the golden tests pin and what lets commit write only
// the files a change actually touched.
func (s *Service) renderAll(sp *Spec) (rendered, error) {
	gateway, err := renderGateway(sp, s.trustedFor(sp))
	if err != nil {
		return nil, err
	}
	out := rendered{
		filepath.Join(s.paths.Dir, linksFile):   []byte(renderLinks(sp)),
		filepath.Join(s.paths.Dir, shapingFile): []byte(renderShaping(sp)),
		filepath.Join(s.paths.Dir, gatewayFile): []byte(gateway),
		s.paths.Sysctl:                          []byte(renderSysctl(sp)),
		s.paths.Unit:                            []byte(renderUnit(s.paths, needsAdmission(sp))),
	}
	return out, nil
}

const generatedHeader = "# Generated by Just Dashboard from spec.json. Edits here are overwritten;\n# change the network on the dashboard's Network pages instead.\n"

// renderUnit is the boot unit. Every line is prefixed with "-" so one part
// failing — a device whose parent is gone, a Docker that is not installed, a
// host without nftables — does not stop the rest being restored, the same
// reason the batch files run with -force; each failure is still in the
// unit's journal.
//
// Ordered after the network managers, Docker and the firewalls rather than
// before them: a VLAN needs its parent configured, the forward admission goes
// in front of the rules ufw and Docker write, and Docker's DOCKER-USER chain
// exists only once Docker has started.
func renderUnit(paths Paths, admission bool) string {
	dir := paths.Dir
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(`[Unit]
Description=Just Dashboard network: the devices, routes, gateway and shaping it made
Documentation=https://github.com/JustDashboard/Just-Dashboard
Wants=network-online.target
After=network-online.target systemd-networkd.service NetworkManager.service networking.service docker.service ufw.service firewalld.service

[Service]
Type=oneshot
RemainAfterExit=yes
`)
	fmt.Fprintf(&b, "ExecStart=-ip -force -batch %s\n", filepath.Join(dir, linksFile))
	fmt.Fprintf(&b, "ExecStart=-tc -force -batch %s\n", filepath.Join(dir, shapingFile))
	fmt.Fprintf(&b, "ExecStart=-nft -f %s\n", filepath.Join(dir, gatewayFile))
	for _, cmd := range admissionCommands(admission) {
		fmt.Fprintf(&b, "ExecStart=-%s\n", strings.Join(cmd, " "))
	}
	b.WriteString("ExecStop=-nft delete table inet " + gatewayTable + "\n")
	for _, cmd := range admissionCommands(false) {
		fmt.Fprintf(&b, "ExecStop=-%s\n", strings.Join(cmd, " "))
	}
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return b.String()
}

// step is the runtime half of a change: what to run on the host now, how to
// take it back, and what to check once it ran.
type step struct {
	apply  func(ctx context.Context) error
	undo   func(ctx context.Context)
	verify func(ctx context.Context) error
}

// commit makes a change the proxy editor's way: render the new spec and check
// what can be checked, apply the one runtime change, verify it, and only then
// write the boot files and the spec. Anything failing before the files are
// written puts the runtime change back, so the files never describe a network
// that did not work. The caller holds s.mu.
func (s *Service) commit(ctx context.Context, sp *Spec, st step) error {
	files, err := s.renderAll(sp)
	if err != nil {
		return err
	}
	// The ruleset is checked only when the gateway holds something: a host
	// without nftables can still have its bridges, routes and kernel settings
	// made, and an empty table has nothing to get wrong. The gateway's own
	// changes load the table, which says plainly when nft is missing.
	gatewayPath := filepath.Join(s.paths.Dir, gatewayFile)
	if gatewayHolds(sp) && changed(gatewayPath, files[gatewayPath]) {
		if err := checkRuleset(ctx, s.paths.Dir, files[gatewayPath]); err != nil {
			return err
		}
	}
	if st.apply != nil {
		if err := st.apply(ctx); err != nil {
			return err
		}
	}
	if st.verify != nil {
		if err := st.verify(ctx); err != nil {
			if st.undo != nil {
				st.undo(ctx)
			}
			return err
		}
	}
	unitChanged := changed(s.paths.Unit, files[s.paths.Unit])
	for path, data := range files {
		if !changed(path, data) {
			continue
		}
		if err := writeFileAtomic(path, data, 0o644); err != nil {
			if st.undo != nil {
				st.undo(ctx)
			}
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	b, err := json.MarshalIndent(sp, "", "  ")
	if err != nil {
		return err
	}
	if err := writeFileAtomic(s.specPath(), append(b, '\n'), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", s.specPath(), err)
	}
	return s.ensureUnit(ctx, unitChanged)
}

// changed reports whether a file's contents differ from data. A file that
// cannot be read is treated as changed, so it is written.
func changed(path string, data []byte) bool {
	cur, err := os.ReadFile(path)
	return err != nil || !bytes.Equal(cur, data)
}

// checkRuleset asks nft to parse and type-check a ruleset without loading it.
// `nft -c` reads a file, so the candidate is written beside the real one
// first; it is removed whatever the answer.
func checkRuleset(ctx context.Context, dir string, ruleset []byte) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp := filepath.Join(dir, "."+gatewayFile+".check")
	if err := os.WriteFile(tmp, ruleset, 0o600); err != nil {
		return err
	}
	defer os.Remove(tmp)
	if _, err := run(ctx, "nft", "-c", "-f", tmp); err != nil {
		var missing *UnavailableError
		if errors.As(err, &missing) {
			return &UnavailableError{Tool: "nft", Package: "nftables"}
		}
		return fmt.Errorf("the gateway ruleset was refused by nft: %w", err)
	}
	return nil
}

// ensureUnit installs and enables the boot unit. It is enabled rather than
// started: everything it would restore was just applied, and running the
// batch files again over a live network would only report what already
// exists. systemd reads a changed unit after daemon-reload, so that runs only
// when the file changed.
func (s *Service) ensureUnit(ctx context.Context, unitChanged bool) error {
	if !has("systemctl") {
		// A host without systemd keeps the files; the Overview says nothing
		// will read them at boot.
		return nil
	}
	if unitChanged {
		if _, err := run(ctx, "systemctl", "daemon-reload"); err != nil {
			return fmt.Errorf("the network was changed, but systemd could not reload the boot unit: %w", err)
		}
	}
	if out, _ := run(ctx, "systemctl", "is-enabled", UnitName); strings.TrimSpace(out) == "enabled" {
		return nil
	}
	if _, err := run(ctx, "systemctl", "enable", UnitName); err != nil {
		return fmt.Errorf("the network was changed, but the unit that restores it at boot could not be enabled: %w", err)
	}
	return nil
}

// Persistence says how what the dashboard made survives a reboot, for the
// Overview's identity line.
type Persistence struct {
	// Unit is enabled, disabled, missing (nothing was made yet) or
	// unsupported (no systemd).
	Unit string `json:"unit"`
	// Made counts the entries the spec holds.
	Made int    `json:"made"`
	Dir  string `json:"dir"`
}

// PersistenceStatus reads the boot unit's state.
func (s *Service) PersistenceStatus(ctx context.Context) Persistence {
	p := Persistence{Dir: s.paths.Dir, Unit: "missing"}
	sp, err := s.loadSpec()
	if err == nil {
		p.Made = len(sp.Links) + len(sp.Addresses) + len(sp.Routes) + len(sp.Rules) +
			len(sp.Namespaces) + len(sp.Shaping) + len(sp.Forwards) + len(sp.NAT) +
			len(sp.Limits) + len(sp.Blocklists) + len(sp.Sysctls)
	}
	if !has("systemctl") {
		p.Unit = "unsupported"
		return p
	}
	if _, err := os.Stat(s.paths.Unit); errors.Is(err, fs.ErrNotExist) {
		return p
	}
	out, _ := run(ctx, "systemctl", "is-enabled", UnitName)
	if strings.TrimSpace(out) == "enabled" {
		p.Unit = "enabled"
	} else {
		p.Unit = "disabled"
	}
	return p
}

// gatewayHolds reports whether the spec puts anything into the gateway
// table, enabled or not: a disabled entry is still rendered, as a comment
// nft has to parse.
func gatewayHolds(sp *Spec) bool {
	return len(sp.Forwards)+len(sp.NAT)+len(sp.Limits)+len(sp.Blocklists) > 0
}
