// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and associations. Call
// initModels(sequelize) once, before the first query.

import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model,
  type NonAttribute,
  type Sequelize,
} from "sequelize"

export class Customer extends Model<InferAttributes<Customer>, InferCreationAttributes<Customer>> {
  declare ID: CreationOptional<number>
  declare EMAIL: string
  declare FULL_NAME: CreationOptional<string | null>
  declare BALANCE: CreationOptional<string>
  declare POINTS: CreationOptional<string | null>
  declare BIG_ID: CreationOptional<number | null>
  declare RATIO: CreationOptional<number | null>
  declare NOTES: CreationOptional<string | null>
  declare TOKEN: CreationOptional<Buffer | null>
  declare STATE: CreationOptional<string>
  declare CREATED: CreationOptional<Date>
  declare UPDATED: CreationOptional<Date | null>
  declare KEPT_FOR: CreationOptional<string | null>

  declare ORDERS?: NonAttribute<Order[]>
}

export function initCustomer(sequelize: Sequelize): typeof Customer {
  Customer.init(
    {
      ID: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true, allowNull: false },
      EMAIL: { type: DataTypes.STRING(255), allowNull: false },
      FULL_NAME: { type: DataTypes.STRING(200), allowNull: true },
      BALANCE: { type: DataTypes.DECIMAL(18, 2), allowNull: false, defaultValue: "0" },
      POINTS: { type: DataTypes.DECIMAL, allowNull: true },
      BIG_ID: { type: DataTypes.BIGINT, allowNull: true },
      RATIO: { type: DataTypes.DOUBLE, allowNull: true },
      NOTES: { type: DataTypes.TEXT, allowNull: true },
      TOKEN: { type: "RAW(16)", allowNull: true },
      STATE: { type: DataTypes.CHAR(1), allowNull: false, defaultValue: "A" },
      CREATED: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
      UPDATED: { type: DataTypes.DATE(6), allowNull: true },
      KEPT_FOR: { type: "INTERVAL DAY(2) TO SECOND(6)", allowNull: true },
    },
    {
      sequelize,
      tableName: "CUSTOMERS",
      timestamps: false,
      indexes: [
        { name: "CUSTOMERS_EMAIL_UK", unique: true, fields: ["EMAIL"] },
      ],
    },
  )
  return Customer
}

export class Order extends Model<InferAttributes<Order>, InferCreationAttributes<Order>> {
  declare ID: number
  declare CUSTOMER_ID: number
  declare TOTAL: string
  declare PLACED: CreationOptional<Date>

  declare CUSTOMER?: NonAttribute<Customer>
}

export function initOrder(sequelize: Sequelize): typeof Order {
  Order.init(
    {
      ID: { type: DataTypes.BIGINT, primaryKey: true, allowNull: false },
      CUSTOMER_ID: { type: DataTypes.BIGINT, allowNull: false },
      TOTAL: { type: DataTypes.DECIMAL(12, 2), allowNull: false },
      PLACED: { type: DataTypes.DATE(6), allowNull: false, defaultValue: DataTypes.NOW },
    },
    {
      sequelize,
      tableName: "ORDERS",
      timestamps: false,
    },
  )
  return Order
}

export function initModels(sequelize: Sequelize) {
  initCustomer(sequelize)
  initOrder(sequelize)

  Order.belongsTo(Customer, { as: "CUSTOMER", foreignKey: "CUSTOMER_ID", targetKey: "ID", onDelete: "CASCADE", onUpdate: "NO ACTION" })
  Customer.hasMany(Order, { as: "ORDERS", foreignKey: "CUSTOMER_ID", sourceKey: "ID" })

  return { Customer, Order }
}
