/**
 * The words of SQL, as data: which ones the formatter writes in capitals,
 * and which ones and which functions the completion offers on each engine.
 *
 * `RESERVED` is deliberately the words that are never a column in practice.
 * `name`, `type`, `status`, `key`, `value`, `date`, `user`, `count` are all
 * words of some dialect and all columns of somebody's table; capitalising a
 * column because it spells a keyword would be the formatter rewriting the
 * reader's schema.
 */
const words = (text: string) => text.trim().split(/\s+/)

export const RESERVED: ReadonlySet<string> = new Set(
  words(`
  SELECT FROM WHERE GROUP BY HAVING ORDER LIMIT OFFSET FETCH FIRST NEXT ROWS ONLY
  DISTINCT ALL AS ON USING JOIN INNER LEFT RIGHT FULL OUTER CROSS NATURAL LATERAL
  UNION INTERSECT EXCEPT WITH RECURSIVE
  INSERT INTO VALUES UPDATE SET DELETE RETURNING MERGE MATCHED CONFLICT DO NOTHING
  CREATE ALTER DROP TRUNCATE TABLE VIEW MATERIALIZED INDEX UNIQUE SCHEMA DATABASE SEQUENCE
  TRIGGER FUNCTION PROCEDURE EXTENSION CONSTRAINT PRIMARY FOREIGN REFERENCES DEFAULT CHECK
  ADD COLUMN RENAME TO CASCADE RESTRICT TEMPORARY TEMP IF EXISTS REPLACE
  AND OR NOT IN IS NULL LIKE ILIKE BETWEEN SIMILAR ANY SOME
  CASE WHEN THEN ELSE END
  ASC DESC NULLS LAST
  OVER PARTITION WINDOW RANGE UNBOUNDED PRECEDING FOLLOWING CURRENT ROW FILTER WITHIN
  EXPLAIN ANALYZE VERBOSE SHOW DESCRIBE
  BEGIN START TRANSACTION COMMIT ROLLBACK SAVEPOINT RELEASE
  GRANT REVOKE
  TRUE FALSE
  CAST INTERVAL COLLATE ESCAPE
  FOR SHARE LOCK NOWAIT SKIP LOCKED
  VACUUM REINDEX OPTIMIZE PRAGMA
  FINAL SAMPLE PREWHERE ARRAY SETTINGS FORMAT QUALIFY ASOF GLOBAL
  `),
)

/** Offered as you type, on every engine. */
const COMMON_KEYWORDS = words(`
  SELECT FROM WHERE GROUP BY HAVING ORDER LIMIT OFFSET DISTINCT AS ON JOIN INNER LEFT RIGHT FULL
  OUTER CROSS UNION ALL INTERSECT EXCEPT WITH INSERT INTO VALUES UPDATE SET DELETE CREATE ALTER DROP
  TABLE VIEW INDEX AND OR NOT IN IS NULL LIKE BETWEEN EXISTS CASE WHEN THEN ELSE END ASC DESC
  OVER PARTITION EXPLAIN BEGIN COMMIT ROLLBACK TRUE FALSE CAST PRIMARY KEY FOREIGN REFERENCES
  DEFAULT UNIQUE CHECK CONSTRAINT COLUMN ADD RENAME TRUNCATE
`)

const COMMON_FUNCTIONS = words(`
  COUNT SUM AVG MIN MAX COALESCE NULLIF ABS ROUND FLOOR CEIL LOWER UPPER TRIM LENGTH SUBSTRING
  REPLACE CONCAT ROW_NUMBER RANK DENSE_RANK LAG LEAD FIRST_VALUE LAST_VALUE NTILE
`)

type Vocabulary = { keywords: string[]; functions: string[] }

const VOCABULARIES: Record<string, Vocabulary> = {
  postgres: {
    keywords: words(`
      RETURNING ILIKE LATERAL MATERIALIZED RECURSIVE CONFLICT NOTHING NULLS FIRST LAST FILTER
      WINDOW ANALYZE VERBOSE BUFFERS VACUUM REINDEX CONCURRENTLY EXTENSION SCHEMA SEQUENCE
      INTERVAL USING FETCH ONLY ROWS SHOW
    `),
    functions: words(`
      NOW CURRENT_TIMESTAMP CURRENT_DATE DATE_TRUNC DATE_PART EXTRACT AGE TO_CHAR TO_DATE
      TO_TIMESTAMP GENERATE_SERIES STRING_AGG ARRAY_AGG JSON_AGG JSONB_AGG JSONB_BUILD_OBJECT
      JSONB_EXTRACT_PATH_TEXT UNNEST GREATEST LEAST PG_SIZE_PRETTY PG_TOTAL_RELATION_SIZE
      PG_RELATION_SIZE PG_DATABASE_SIZE CURRENT_DATABASE CURRENT_SCHEMA CURRENT_USER VERSION
      GEN_RANDOM_UUID MD5 REGEXP_REPLACE SPLIT_PART POSITION LEFT RIGHT STRPOS BOOL_AND BOOL_OR
      PERCENTILE_CONT
    `),
  },
  mysql: {
    keywords: words(`
      SHOW DESCRIBE DATABASES TABLES COLUMNS PROCESSLIST STATUS VARIABLES ENGINE DUPLICATE KEY
      IGNORE STRAIGHT_JOIN USE REPLACE ANALYZE OPTIMIZE REGEXP UNSIGNED AUTO_INCREMENT
    `),
    functions: words(`
      NOW CURDATE CURTIME DATE_FORMAT DATE_ADD DATE_SUB DATEDIFF TIMESTAMPDIFF UNIX_TIMESTAMP
      FROM_UNIXTIME GROUP_CONCAT IFNULL IF JSON_EXTRACT JSON_UNQUOTE JSON_OBJECT JSON_ARRAYAGG
      CHAR_LENGTH LOCATE LEFT RIGHT LPAD RPAD GREATEST LEAST DATABASE VERSION UUID MD5 SHA2
      FOUND_ROWS LAST_INSERT_ID
    `),
  },
  sqlite: {
    keywords: words(`
      PRAGMA VACUUM REINDEX ATTACH DETACH GLOB AUTOINCREMENT WITHOUT ROWID STRICT REPLACE
      RETURNING ANALYZE INDEXED
    `),
    functions: words(`
      DATE TIME DATETIME JULIANDAY STRFTIME UNIXEPOCH IFNULL IIF GROUP_CONCAT INSTR SUBSTR
      TYPEOF TOTAL RANDOM HEX QUOTE PRINTF JSON_EXTRACT JSON_OBJECT JSON_GROUP_ARRAY
      JSON_EACH LAST_INSERT_ROWID CHANGES SQLITE_VERSION
    `),
  },
  sqlserver: {
    keywords: words(`
      TOP OUTPUT INSERTED DELETED NOLOCK MERGE MATCHED EXEC EXECUTE DECLARE GO USE OFFSET FETCH
      NEXT ROWS ONLY IDENTITY PIVOT UNPIVOT APPLY TRY CATCH
    `),
    functions: words(`
      GETDATE SYSDATETIME GETUTCDATE DATEADD DATEDIFF DATEPART DATENAME FORMAT CONVERT
      TRY_CONVERT TRY_CAST ISNULL IIF LEN CHARINDEX STUFF STRING_AGG STRING_SPLIT NEWID
      SCOPE_IDENTITY DB_NAME OBJECT_NAME SCHEMA_NAME JSON_VALUE JSON_QUERY OPENJSON ISJSON
    `),
  },
  clickhouse: {
    keywords: words(`
      FINAL SAMPLE PREWHERE ARRAY GLOBAL ANY ASOF SETTINGS FORMAT ENGINE OPTIMIZE SYSTEM SHOW
      DESCRIBE DATABASES TABLES TTL MATERIALIZED POPULATE TOTALS ROLLUP CUBE ILIKE
    `),
    functions: words(`
      now today yesterday toDate toDateTime toStartOfMinute toStartOfHour toStartOfDay
      toStartOfWeek toStartOfMonth toYYYYMM formatDateTime dateDiff toString toInt64 toUInt64
      toFloat64 uniq uniqExact quantile quantiles median any anyLast argMin argMax groupArray
      groupUniqArray sumIf countIf avgIf arrayJoin has length empty notEmpty splitByChar
      formatReadableSize formatReadableQuantity JSONExtractString JSONExtractInt currentDatabase
      version topK
    `),
  },
  oracle: {
    keywords: words(`
      DUAL ROWNUM CONNECT PRIOR START MINUS MERGE MATCHED FETCH FIRST NEXT ROWS ONLY NOCYCLE
      VARCHAR2 NUMBER SYSDATE SYSTIMESTAMP
    `),
    functions: words(`
      NVL NVL2 DECODE TO_CHAR TO_DATE TO_NUMBER TO_TIMESTAMP TRUNC ADD_MONTHS MONTHS_BETWEEN
      LISTAGG INSTR SUBSTR LPAD RPAD REGEXP_LIKE REGEXP_SUBSTR GREATEST LEAST SYS_GUID
      SYS_CONTEXT JSON_VALUE JSON_QUERY
    `),
  },
}

const unique = (list: string[]) => [...new Set(list)]

/** The keywords and functions the completion offers for a driver. */
export function vocabularyOf(driver: string): Vocabulary {
  const own = Object.hasOwn(VOCABULARIES, driver) ? VOCABULARIES[driver] : undefined
  return {
    keywords: unique([...COMMON_KEYWORDS, ...(own?.keywords ?? [])]),
    functions: unique([...COMMON_FUNCTIONS, ...(own?.functions ?? [])]),
  }
}
