// Generated by Just Dashboard from live database introspection.
// The shape `diesel print-schema` writes. A reviewed starting point: check it
// against your migrations before relying on it.

diesel::table! {
    use diesel::sql_types::*;

    notes (id) {
        id -> Integer,
        user_id -> Integer,
        title -> Text,
        body -> Nullable<Text>,
        pinned -> Bool,
        score -> Nullable<Double>,
        price -> Nullable<Double>,
        payload -> Nullable<Text>,
        attachment -> Nullable<Binary>,
        created_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    user_tags (user_id, tag) {
        user_id -> Integer,
        tag -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    users (id) {
        id -> Integer,
        email -> Text,
        name -> Nullable<Text>,
    }
}

diesel::joinable!(notes -> users (user_id));
diesel::joinable!(user_tags -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    notes,
    user_tags,
    users,
);
