# Generated by Just Dashboard from live database introspection.
# A reviewed starting point: verify types, defaults and relationships.

import datetime
import decimal
import uuid
from typing import Any, Optional

from sqlalchemy import (
    BigInteger,
    Boolean,
    CHAR,
    Column,
    Computed,
    Date,
    DateTime,
    Double,
    Enum,
    ForeignKey,
    ForeignKeyConstraint,
    Identity,
    Index,
    Integer,
    Interval,
    JSON,
    LargeBinary,
    Numeric,
    REAL,
    SmallInteger,
    String,
    Table,
    Text,
    Time,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import (
    ARRAY,
    BIT,
    INET,
    JSONB,
    MONEY,
    TIMESTAMP,
    TSVECTOR,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class DailyRevenue(Base):
    __tablename__ = "daily_revenue"
    __table_args__ = {"schema": "analytics"}

    day: Mapped[datetime.date] = mapped_column(Date, primary_key=True)
    orders: Mapped[int] = mapped_column(Integer)
    revenue_cents: Mapped[int] = mapped_column(BigInteger)


class AnalyticsEvent(Base):
    __tablename__ = "events"
    __table_args__ = (
        Index("events_occurred_idx", "occurred_at"),
        {"schema": "analytics"},
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    customer_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("public.customers.id", ondelete="SET NULL", name="events_customer_id_fkey"))
    kind: Mapped[str] = mapped_column(Enum("page_view", "click", "add-to-cart", name="event_kind", schema="analytics"))
    path: Mapped[Optional[str]] = mapped_column(Text)
    duration_ms: Mapped[Optional[int]] = mapped_column(Integer)
    props: Mapped[Optional[Any]] = mapped_column(JSONB)
    occurred_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True))

    customer: Mapped[Optional["Customer"]] = relationship(back_populates="events", foreign_keys=[customer_id])


# top_products is a materialized view: declared as a Table to select from, never to create.
t_top_products = Table(
    "top_products",
    Base.metadata,
    Column("product_id", BigInteger),
    Column("units", BigInteger),
    schema="analytics",
)


class MixedCaseTable(Base):
    __tablename__ = "Mixed Case Table"
    __table_args__ = {"schema": "public"}

    Id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    select: Mapped[Optional[str]] = mapped_column(Text)
    weird_column: Mapped[Optional[str]] = mapped_column("weird column", Text)
    _2fa: Mapped[bool] = mapped_column("2fa", Boolean, server_default=text("false"))


# audit_log has no primary key, which the ORM needs to map a class; it is a Table instead.
t_audit_log = Table(
    "audit_log",
    Base.metadata,
    Column("at", DateTime(timezone=True), server_default=text("now()"), nullable=False),
    Column("actor", Text),
    Column("action", Text, nullable=False),
    Column("payload", JSONB),
    schema="public",
)


class Category(Base):
    __tablename__ = "categories"
    __table_args__ = (
        UniqueConstraint("slug", name="categories_slug_key"),
        {"schema": "public"},
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    slug: Mapped[str] = mapped_column(Text)
    name: Mapped[str] = mapped_column(Text)
    parent_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("public.categories.id", name="categories_parent_id_fkey"))

    parent: Mapped[Optional["Category"]] = relationship(back_populates="categories", foreign_keys=[parent_id], remote_side=[id])
    categories: Mapped[list["Category"]] = relationship(back_populates="parent", foreign_keys="Category.parent_id")
    products: Mapped[list["Product"]] = relationship(back_populates="category", foreign_keys="Product.category_id")
    shipments: Mapped[list["Shipment"]] = relationship(back_populates="category", foreign_keys="Shipment.category_slug")


class CustomerProfile(Base):
    __tablename__ = "customer_profiles"
    __table_args__ = {"schema": "public"}

    customer_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("public.customers.id", ondelete="CASCADE", name="customer_profiles_customer_id_fkey"), primary_key=True, autoincrement=False)
    bio: Mapped[Optional[str]] = mapped_column(Text)
    website: Mapped[Optional[str]] = mapped_column(String(255))

    customer: Mapped["Customer"] = relationship(back_populates="customer_profile", foreign_keys=[customer_id])


class Customer(Base):
    __tablename__ = "customers"
    __table_args__ = (
        UniqueConstraint("email", name="customers_email_key"),
        {"schema": "public", "comment": "People who have an account in the shop"},
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    email: Mapped[str] = mapped_column(Text)
    full_name: Mapped[str] = mapped_column(Text)
    tier: Mapped[str] = mapped_column(Enum("free", "plus", "pro", name="customer_tier", schema="public"), server_default=text("'free'::customer_tier"))
    country: Mapped[Optional[str]] = mapped_column(CHAR(2))
    marketing_opt_in: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    tags: Mapped[list[str]] = mapped_column(ARRAY(Text), server_default=text("'{}'::text[]"))
    profile: Mapped[Any] = mapped_column(JSONB, server_default=text("'{}'::jsonb"), comment="Free-form preferences captured at sign-up")
    avatar: Mapped[Optional[bytes]] = mapped_column(LargeBinary)
    external_id: Mapped[uuid.UUID] = mapped_column(Uuid, server_default=text("gen_random_uuid()"))
    lifetime_value: Mapped[decimal.Decimal] = mapped_column(Numeric(12, 2), server_default=text("0"))
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))
    last_seen_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(timezone=True))

    events: Mapped[list["AnalyticsEvent"]] = relationship(back_populates="customer", foreign_keys="AnalyticsEvent.customer_id")
    customer_profile: Mapped[Optional["CustomerProfile"]] = relationship(back_populates="customer", foreign_keys="CustomerProfile.customer_id", uselist=False)
    messages_recipient_id: Mapped[list["Message"]] = relationship(back_populates="recipient", foreign_keys="Message.recipient_id")
    messages_sender_id: Mapped[list["Message"]] = relationship(back_populates="sender", foreign_keys="Message.sender_id")
    orders: Mapped[list["Order"]] = relationship(back_populates="customer", foreign_keys="Order.customer_id")


class Event(Base):
    __tablename__ = "events"
    __table_args__ = {"schema": "public"}

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)
    name: Mapped[str] = mapped_column(String(120))
    starts_at: Mapped[datetime.datetime] = mapped_column(DateTime)


class Measurement(Base):
    __tablename__ = "measurements"
    __table_args__ = {"schema": "public"}

    sensor_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    taken_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), primary_key=True)
    reading: Mapped[Optional[float]] = mapped_column(Double)


class Message(Base):
    __tablename__ = "messages"
    __table_args__ = {"schema": "public"}

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))
    sender_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("public.customers.id", ondelete="CASCADE", name="messages_sender_id_fkey"))
    recipient_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("public.customers.id", ondelete="SET NULL", name="messages_recipient_id_fkey"))
    body: Mapped[str] = mapped_column(Text)
    sent_at: Mapped[datetime.datetime] = mapped_column(TIMESTAMP(timezone=True, precision=3), server_default=text("now()"))

    recipient: Mapped[Optional["Customer"]] = relationship(back_populates="messages_recipient_id", foreign_keys=[recipient_id])
    sender: Mapped["Customer"] = relationship(back_populates="messages_sender_id", foreign_keys=[sender_id])


class OrderItem(Base):
    __tablename__ = "order_items"
    __table_args__ = (
        UniqueConstraint("order_id", "product_id", name="order_items_order_product_key"),
        {"schema": "public"},
    )

    order_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("public.orders.id", ondelete="CASCADE", name="order_items_order_id_fkey"), primary_key=True)
    line_no: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    product_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("public.products.id", name="order_items_product_id_fkey"))
    quantity: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    unit_price_cents: Mapped[int] = mapped_column(Integer)

    order: Mapped["Order"] = relationship(back_populates="order_items", foreign_keys=[order_id])
    product: Mapped["Product"] = relationship(back_populates="order_items", foreign_keys=[product_id])
    shipments: Mapped[list["Shipment"]] = relationship(back_populates="order_item", foreign_keys="[Shipment.order_id, Shipment.line_no]")


# order_summary is a view: declared as a Table to select from, never to create.
t_order_summary = Table(
    "order_summary",
    Base.metadata,
    Column("id", BigInteger),
    Column("email", Text),
    Column("status", Enum("pending", "paid", "shipped", "delivered", "cancelled", "refunded", name="order_status", schema="public")),
    Column("total_cents", BigInteger),
    schema="public",
)


class Order(Base):
    __tablename__ = "orders"
    __table_args__ = (
        Index("orders_status_placed_idx", "status", "placed_at"),
        {"schema": "public"},
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    customer_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("public.customers.id", ondelete="CASCADE", name="orders_customer_id_fkey"))
    status: Mapped[str] = mapped_column(Enum("pending", "paid", "shipped", "delivered", "cancelled", "refunded", name="order_status", schema="public"), server_default=text("'pending'::order_status"))
    total_cents: Mapped[int] = mapped_column(BigInteger, server_default=text("0"))
    currency: Mapped[str] = mapped_column(CHAR(3), server_default=text("'EUR'::bpchar"))
    shipping_address: Mapped[Optional[Any]] = mapped_column(JSONB)
    note: Mapped[Optional[str]] = mapped_column(Text)
    placed_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))
    shipped_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(timezone=True))

    customer: Mapped["Customer"] = relationship(back_populates="orders", foreign_keys=[customer_id])
    order_items: Mapped[list["OrderItem"]] = relationship(back_populates="order", foreign_keys="OrderItem.order_id")


class Product(Base):
    __tablename__ = "products"
    __table_args__ = (
        UniqueConstraint("sku", name="products_sku_key"),
        Index("products_category_idx", "category_id"),
        Index("products_attributes_gin", "attributes", postgresql_using="gin"),
        {"schema": "public"},
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    sku: Mapped[str] = mapped_column(String(32))
    name: Mapped[str] = mapped_column(String(200))
    description: Mapped[Optional[str]] = mapped_column(Text)
    category_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("public.categories.id", name="products_category_id_fkey"))
    price_cents: Mapped[int] = mapped_column(Integer)
    stock: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    attributes: Mapped[Any] = mapped_column(JSONB, server_default=text("'{}'::jsonb"))
    weight_kg: Mapped[Optional[float]] = mapped_column(Double)
    discontinued: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    released_on: Mapped[Optional[datetime.date]] = mapped_column(Date)
    updated_at: Mapped[datetime.datetime] = mapped_column(DateTime, server_default=text("now()"))

    category: Mapped[Optional["Category"]] = relationship(back_populates="products", foreign_keys=[category_id])
    order_items: Mapped[list["OrderItem"]] = relationship(back_populates="product", foreign_keys="OrderItem.product_id")


class Shipment(Base):
    __tablename__ = "shipments"
    __table_args__ = (
        ForeignKeyConstraint(["order_id", "line_no"], ["public.order_items.order_id", "public.order_items.line_no"], ondelete="CASCADE", name="shipments_item_fkey"),
        UniqueConstraint("tracking_code", name="shipments_tracking_code_key"),
        {"schema": "public"},
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(BigInteger)
    line_no: Mapped[int] = mapped_column(SmallInteger)
    category_slug: Mapped[Optional[str]] = mapped_column(Text, ForeignKey("public.categories.slug", name="shipments_category_slug_fkey"))
    tracking_code: Mapped[str] = mapped_column(String(40))

    category: Mapped[Optional["Category"]] = relationship(back_populates="shipments", foreign_keys=[category_slug])
    order_item: Mapped["OrderItem"] = relationship(back_populates="shipments", foreign_keys=[order_id, line_no])


class TypeSample(Base):
    __tablename__ = "type_samples"
    __table_args__ = {"schema": "public"}

    id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    small: Mapped[int] = mapped_column(SmallInteger, server_default=text("0"))
    ratio: Mapped[Optional[float]] = mapped_column(REAL)
    price: Mapped[Optional[str]] = mapped_column(MONEY)
    amount: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric)
    code: Mapped[str] = mapped_column(String(16), server_default=text("'N/A'::character varying"))
    fixed: Mapped[Optional[str]] = mapped_column(CHAR(4))
    starts: Mapped[Optional[datetime.time]] = mapped_column(Time)
    starts_tz: Mapped[Optional[datetime.time]] = mapped_column(Time(timezone=True))
    span: Mapped[Optional[datetime.timedelta]] = mapped_column(Interval)
    addr: Mapped[Optional[str]] = mapped_column(INET)
    doc: Mapped[Optional[str]] = mapped_column(Text)
    flags: Mapped[Optional[str]] = mapped_column(BIT(8))
    search: Mapped[Optional[str]] = mapped_column(TSVECTOR)
    scores: Mapped[Optional[list[int]]] = mapped_column(ARRAY(Integer))
    day: Mapped[datetime.date] = mapped_column(Date, server_default=text("CURRENT_DATE"))
    meta: Mapped[Optional[Any]] = mapped_column(JSON)
    label: Mapped[str] = mapped_column(Text, server_default=text("'it''s'::text"))
    total: Mapped[Optional[decimal.Decimal]] = mapped_column(Numeric(10, 2), Computed("((small)::numeric * 1.5)", persisted=True))
    stamp: Mapped[datetime.datetime] = mapped_column(TIMESTAMP(precision=3), server_default=text("timezone('utc'::text, now())"))
