<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property string $guid
 * @property string $name
 * @property string|null $notes
 * @property string|null $code
 * @property bool $active
 * @property int $level
 * @property string|null $balance
 * @property string $credit
 * @property string|null $photo
 * @property \Illuminate\Support\Carbon|null $opened_on
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon|null $seen_at
 * @property string $version
 * @property-read \Illuminate\Database\Eloquent\Collection<int, Transfer> $transfersFromAccount
 * @property-read \Illuminate\Database\Eloquent\Collection<int, Transfer> $transfersToAccount
 */
class Account extends Model
{
    protected $table = 'dbo.accounts';

    public $timestamps = false;

    protected $fillable = [
        'guid',
        'name',
        'notes',
        'code',
        'active',
        'level',
        'balance',
        'credit',
        'photo',
        'opened_on',
        'created_at',
        'seen_at',
        'version',
    ];

    protected $casts = [
        'id' => 'integer',
        'active' => 'boolean',
        'level' => 'integer',
        'credit' => 'decimal:2',
        'opened_on' => 'date',
        'created_at' => 'datetime',
        'seen_at' => 'datetime',
    ];

    public function transfersFromAccount(): HasMany
    {
        return $this->hasMany(Transfer::class, 'from_account', 'id');
    }

    public function transfersToAccount(): HasMany
    {
        return $this->hasMany(Transfer::class, 'to_account', 'id');
    }
}

/**
 * @property int $id
 * @property int $from_account
 * @property int|null $to_account
 * @property string $amount
 * @property string $memo
 * @property-read Account $fromAccountRef
 * @property-read Account|null $toAccountRef
 */
class Transfer extends Model
{
    protected $table = 'dbo.transfers';

    public $timestamps = false;

    protected $fillable = [
        'from_account',
        'to_account',
        'amount',
        'memo',
    ];

    protected $casts = [
        'id' => 'integer',
        'from_account' => 'integer',
        'to_account' => 'integer',
        'amount' => 'decimal:2',
    ];

    public function fromAccountRef(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'from_account', 'id');
    }

    public function toAccountRef(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'to_account', 'id');
    }
}

/**
 * @property int $id
 * @property string $region
 * @property string|null $payload
 */
class SalesAccount extends Model
{
    protected $table = 'sales.accounts';

    public $incrementing = false;

    public $timestamps = false;

    protected $fillable = [
        'id',
        'region',
        'payload',
    ];

    protected $casts = [
        'id' => 'integer',
    ];
}
