// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Exact
// numerics are strings, so nothing is rounded on the way through.

package models

import (
	"time"

	"gorm.io/datatypes"
)

// Note maps the notes table.
type Note struct {
	ID         int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement" json:"id"`
	UserID     int32          `gorm:"column:user_id;type:integer;not null;index:idx_notes_user" json:"user_id"`
	Title      string         `gorm:"column:title;type:varchar(120);not null" json:"title"`
	Body       *string        `gorm:"column:body;type:text" json:"body"`
	Pinned     bool           `gorm:"column:pinned;type:boolean;not null;default:false" json:"pinned"`
	Score      *float64       `gorm:"column:score;type:real" json:"score"`
	Price      *string        `gorm:"column:price;type:decimal(10,2)" json:"price"`
	Payload    datatypes.JSON `gorm:"column:payload;type:json" json:"payload"`
	Attachment []byte         `gorm:"column:attachment;type:blob" json:"attachment"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`

	User *User `gorm:"foreignKey:UserID;references:ID;constraint:OnDelete:CASCADE" json:"user,omitempty"`
}

// TableName is the table GORM reads and writes for Note.
func (Note) TableName() string { return "notes" }

// UserTag maps the user_tags table.
type UserTag struct {
	UserID int32  `gorm:"column:user_id;type:integer;primaryKey" json:"user_id"`
	Tag    string `gorm:"column:tag;type:text;primaryKey" json:"tag"`

	User *User `gorm:"foreignKey:UserID;references:ID" json:"user,omitempty"`
}

// TableName is the table GORM reads and writes for UserTag.
func (UserTag) TableName() string { return "user_tags" }

// User maps the users table.
type User struct {
	ID    int32   `gorm:"column:id;type:integer;primaryKey;autoIncrement" json:"id"`
	Email string  `gorm:"column:email;type:text;not null;uniqueIndex:sqlite_autoindex_users_1" json:"email"`
	Name  *string `gorm:"column:name;type:text" json:"name"`

	Notes    []Note    `gorm:"foreignKey:UserID;references:ID" json:"notes,omitempty"`
	UserTags []UserTag `gorm:"foreignKey:UserID;references:ID" json:"user_tags,omitempty"`
}

// TableName is the table GORM reads and writes for User.
func (User) TableName() string { return "users" }
