// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
  OneToOne,
  PrimaryColumn,
  PrimaryGeneratedColumn,
  type Relation,
} from "typeorm"

export enum EventKind {
  PageView = "page_view",
  Click = "click",
  AddToCart = "add-to-cart",
}

export enum CustomerTier {
  Free = "free",
  Plus = "plus",
  Pro = "pro",
}

export enum OrderStatus {
  Pending = "pending",
  Paid = "paid",
  Shipped = "shipped",
  Delivered = "delivered",
  Cancelled = "cancelled",
  Refunded = "refunded",
}

@Entity("daily_revenue", { schema: "analytics" })
export class DailyRevenue {
  @PrimaryColumn({ type: "date" })
  day!: string

  @Column({ type: "integer" })
  orders!: number

  @Column({ type: "bigint" })
  revenue_cents!: string
}

@Index("events_occurred_idx", ["occurred_at"])
@Entity("events", { schema: "analytics" })
export class AnalyticsEvent {
  @PrimaryGeneratedColumn("identity", { type: "bigint", generatedIdentity: "ALWAYS" })
  id!: string

  @Column({ type: "bigint", nullable: true })
  customer_id!: string | null

  @Column({ type: "enum", enum: EventKind, enumName: "event_kind" })
  kind!: EventKind

  @Column({ type: "text", nullable: true })
  path!: string | null

  @Column({ type: "integer", nullable: true })
  duration_ms!: number | null

  @Column({ type: "jsonb", nullable: true })
  props!: unknown

  @Column({ type: "timestamp with time zone" })
  occurred_at!: Date

  @ManyToOne(() => Customer, (other) => other.events, { onDelete: "SET NULL" })
  @JoinColumn({ name: "customer_id", referencedColumnName: "id", foreignKeyConstraintName: "events_customer_id_fkey" })
  customer!: Relation<Customer> | null
}

@Entity("Mixed Case Table", { schema: "public" })
export class MixedCaseTable {
  @PrimaryColumn({ type: "integer" })
  Id!: number

  @Column({ type: "text", nullable: true })
  select!: string | null

  @Column({ type: "text", name: "weird column", nullable: true })
  weird_column!: string | null

  @Column({ type: "boolean", name: "2fa", default: false })
  _2fa!: boolean
}

// No primary key in the database. TypeORM needs one: mark the identifying columns with @PrimaryColumn.
@Entity("audit_log", { schema: "public" })
export class AuditLog {
  @Column({ type: "timestamp with time zone", default: () => "now()" })
  at!: Date

  @Column({ type: "text", nullable: true })
  actor!: string | null

  @Column({ type: "text" })
  action!: string

  @Column({ type: "jsonb", nullable: true })
  payload!: unknown
}

@Index("categories_slug_key", ["slug"], { unique: true })
@Entity("categories", { schema: "public" })
export class Category {
  @PrimaryGeneratedColumn({ type: "integer" })
  id!: number

  @Column({ type: "text" })
  slug!: string

  @Column({ type: "text" })
  name!: string

  @Column({ type: "integer", nullable: true })
  parent_id!: number | null

  @ManyToOne(() => Category, (other) => other.categories)
  @JoinColumn({ name: "parent_id", referencedColumnName: "id", foreignKeyConstraintName: "categories_parent_id_fkey" })
  parent!: Relation<Category> | null

  @OneToMany(() => Category, (other) => other.parent)
  categories!: Relation<Category>[]

  @OneToMany(() => Product, (other) => other.category)
  products!: Relation<Product>[]

  @OneToMany(() => Shipment, (other) => other.category)
  shipments!: Relation<Shipment>[]
}

@Entity("customer_profiles", { schema: "public" })
export class CustomerProfile {
  @PrimaryColumn({ type: "bigint" })
  customer_id!: string

  @Column({ type: "text", nullable: true })
  bio!: string | null

  @Column({ type: "varchar", length: 255, nullable: true })
  website!: string | null

  @OneToOne(() => Customer, (other) => other.customer_profile, { onDelete: "CASCADE" })
  @JoinColumn({ name: "customer_id", referencedColumnName: "id", foreignKeyConstraintName: "customer_profiles_customer_id_fkey" })
  customer!: Relation<Customer>
}

/** People who have an account in the shop */
@Index("customers_email_key", ["email"], { unique: true })
@Entity("customers", { schema: "public" })
export class Customer {
  @PrimaryGeneratedColumn({ type: "bigint" })
  id!: string

  @Column({ type: "text" })
  email!: string

  @Column({ type: "text" })
  full_name!: string

  @Column({ type: "enum", enum: CustomerTier, enumName: "customer_tier", default: CustomerTier.Free })
  tier!: CustomerTier

  @Column({ type: "char", length: 2, nullable: true })
  country!: string | null

  @Column({ type: "boolean", default: false })
  marketing_opt_in!: boolean

  @Column({ type: "text", array: true, default: () => "'{}'::text[]" })
  tags!: string[]

  /** Free-form preferences captured at sign-up */
  @Column({ type: "jsonb", default: () => "'{}'::jsonb" })
  profile!: unknown

  @Column({ type: "bytea", nullable: true })
  avatar!: Buffer | null

  @Column({ type: "uuid", default: () => "gen_random_uuid()" })
  external_id!: string

  @Column({ type: "numeric", precision: 12, scale: 2, default: "0" })
  lifetime_value!: string

  @Column({ type: "timestamp with time zone", default: () => "now()" })
  created_at!: Date

  @Column({ type: "timestamp with time zone", nullable: true })
  last_seen_at!: Date | null

  @OneToMany(() => AnalyticsEvent, (other) => other.customer)
  events!: Relation<AnalyticsEvent>[]

  @OneToOne(() => CustomerProfile, (other) => other.customer)
  customer_profile!: Relation<CustomerProfile> | null

  @OneToMany(() => Message, (other) => other.recipient)
  messages_recipient_id!: Relation<Message>[]

  @OneToMany(() => Message, (other) => other.sender)
  messages_sender_id!: Relation<Message>[]

  @OneToMany(() => Order, (other) => other.customer)
  orders!: Relation<Order>[]
}

@Entity("events", { schema: "public" })
export class Event {
  @PrimaryGeneratedColumn("identity", { type: "bigint", generatedIdentity: "BY DEFAULT" })
  id!: string

  @Column({ type: "varchar", length: 120 })
  name!: string

  @Column({ type: "timestamp" })
  starts_at!: Date
}

@Entity("measurements", { schema: "public" })
export class Measurement {
  @PrimaryColumn({ type: "integer" })
  sensor_id!: number

  @PrimaryColumn({ type: "timestamp with time zone" })
  taken_at!: Date

  @Column({ type: "double precision", nullable: true })
  reading!: number | null
}

@Entity("messages", { schema: "public" })
export class Message {
  @PrimaryGeneratedColumn("uuid")
  id!: string

  @Column({ type: "bigint" })
  sender_id!: string

  @Column({ type: "bigint", nullable: true })
  recipient_id!: string | null

  @Column({ type: "text" })
  body!: string

  @Column({ type: "timestamp with time zone", precision: 3, default: () => "now()" })
  sent_at!: Date

  @ManyToOne(() => Customer, (other) => other.messages_recipient_id, { onDelete: "SET NULL" })
  @JoinColumn({ name: "recipient_id", referencedColumnName: "id", foreignKeyConstraintName: "messages_recipient_id_fkey" })
  recipient!: Relation<Customer> | null

  @ManyToOne(() => Customer, (other) => other.messages_sender_id, { onDelete: "CASCADE" })
  @JoinColumn({ name: "sender_id", referencedColumnName: "id", foreignKeyConstraintName: "messages_sender_id_fkey" })
  sender!: Relation<Customer>
}

@Index("order_items_order_product_key", ["order_id", "product_id"], { unique: true })
@Entity("order_items", { schema: "public" })
export class OrderItem {
  @PrimaryColumn({ type: "bigint" })
  order_id!: string

  @PrimaryColumn({ type: "smallint" })
  line_no!: number

  @Column({ type: "bigint" })
  product_id!: string

  @Column({ type: "integer", default: 1 })
  quantity!: number

  @Column({ type: "integer" })
  unit_price_cents!: number

  @ManyToOne(() => Order, (other) => other.order_items, { onDelete: "CASCADE" })
  @JoinColumn({ name: "order_id", referencedColumnName: "id", foreignKeyConstraintName: "order_items_order_id_fkey" })
  order!: Relation<Order>

  @ManyToOne(() => Product, (other) => other.order_items)
  @JoinColumn({ name: "product_id", referencedColumnName: "id", foreignKeyConstraintName: "order_items_product_id_fkey" })
  product!: Relation<Product>

  @OneToMany(() => Shipment, (other) => other.order_item)
  shipments!: Relation<Shipment>[]
}

@Index("orders_status_placed_idx", ["status", "placed_at"])
@Entity("orders", { schema: "public" })
export class Order {
  @PrimaryGeneratedColumn({ type: "bigint" })
  id!: string

  @Column({ type: "bigint" })
  customer_id!: string

  @Column({ type: "enum", enum: OrderStatus, enumName: "order_status", default: OrderStatus.Pending })
  status!: OrderStatus

  @Column({ type: "bigint", default: "0" })
  total_cents!: string

  @Column({ type: "char", length: 3, default: "EUR" })
  currency!: string

  @Column({ type: "jsonb", nullable: true })
  shipping_address!: unknown

  @Column({ type: "text", nullable: true })
  note!: string | null

  @Column({ type: "timestamp with time zone", default: () => "now()" })
  placed_at!: Date

  @Column({ type: "timestamp with time zone", nullable: true })
  shipped_at!: Date | null

  @ManyToOne(() => Customer, (other) => other.orders, { onDelete: "CASCADE" })
  @JoinColumn({ name: "customer_id", referencedColumnName: "id", foreignKeyConstraintName: "orders_customer_id_fkey" })
  customer!: Relation<Customer>

  @OneToMany(() => OrderItem, (other) => other.order)
  order_items!: Relation<OrderItem>[]
}

@Index("products_sku_key", ["sku"], { unique: true })
@Index("products_category_idx", ["category_id"])
@Entity("products", { schema: "public" })
export class Product {
  @PrimaryGeneratedColumn({ type: "bigint" })
  id!: string

  @Column({ type: "varchar", length: 32 })
  sku!: string

  @Column({ type: "varchar", length: 200 })
  name!: string

  @Column({ type: "text", nullable: true })
  description!: string | null

  @Column({ type: "integer", nullable: true })
  category_id!: number | null

  @Column({ type: "integer" })
  price_cents!: number

  @Column({ type: "integer", default: 0 })
  stock!: number

  @Column({ type: "jsonb", default: () => "'{}'::jsonb" })
  attributes!: unknown

  @Column({ type: "double precision", nullable: true })
  weight_kg!: number | null

  @Column({ type: "boolean", default: false })
  discontinued!: boolean

  @Column({ type: "date", nullable: true })
  released_on!: string | null

  @Column({ type: "timestamp", default: () => "now()" })
  updated_at!: Date

  @ManyToOne(() => Category, (other) => other.products)
  @JoinColumn({ name: "category_id", referencedColumnName: "id", foreignKeyConstraintName: "products_category_id_fkey" })
  category!: Relation<Category> | null

  @OneToMany(() => OrderItem, (other) => other.product)
  order_items!: Relation<OrderItem>[]
}

@Index("shipments_tracking_code_key", ["tracking_code"], { unique: true })
@Entity("shipments", { schema: "public" })
export class Shipment {
  @PrimaryGeneratedColumn({ type: "integer" })
  id!: number

  @Column({ type: "bigint" })
  order_id!: string

  @Column({ type: "smallint" })
  line_no!: number

  @Column({ type: "text", nullable: true })
  category_slug!: string | null

  @Column({ type: "varchar", length: 40 })
  tracking_code!: string

  @ManyToOne(() => Category, (other) => other.shipments)
  @JoinColumn({ name: "category_slug", referencedColumnName: "slug", foreignKeyConstraintName: "shipments_category_slug_fkey" })
  category!: Relation<Category> | null

  @ManyToOne(() => OrderItem, (other) => other.shipments, { onDelete: "CASCADE" })
  @JoinColumn([{ name: "order_id", referencedColumnName: "order_id", foreignKeyConstraintName: "shipments_item_fkey" }, { name: "line_no", referencedColumnName: "line_no" }])
  order_item!: Relation<OrderItem>
}

@Entity("type_samples", { schema: "public" })
export class TypeSample {
  @PrimaryGeneratedColumn("identity", { type: "integer", generatedIdentity: "BY DEFAULT" })
  id!: number

  @Column({ type: "smallint", default: 0 })
  small!: number

  @Column({ type: "real", nullable: true })
  ratio!: number | null

  @Column({ type: "money", nullable: true })
  price!: string | null

  @Column({ type: "numeric", nullable: true })
  amount!: string | null

  @Column({ type: "varchar", length: 16, default: "N/A" })
  code!: string

  @Column({ type: "char", length: 4, nullable: true })
  fixed!: string | null

  @Column({ type: "time", nullable: true })
  starts!: string | null

  @Column({ type: "time with time zone", nullable: true })
  starts_tz!: string | null

  @Column({ type: "interval", nullable: true })
  span!: unknown

  @Column({ type: "inet", nullable: true })
  addr!: string | null

  @Column({ type: "xml", nullable: true })
  doc!: string | null

  @Column({ type: "bit", length: 8, nullable: true })
  flags!: string | null

  @Column({ type: "tsvector", nullable: true })
  search!: string | null

  @Column({ type: "integer", array: true, nullable: true })
  scores!: number[] | null

  @Column({ type: "date", default: () => "CURRENT_DATE" })
  day!: string

  @Column({ type: "json", nullable: true })
  meta!: unknown

  @Column({ type: "text", default: "it's" })
  label!: string

  @Column({ type: "numeric", precision: 10, scale: 2, nullable: true, generatedType: "STORED", asExpression: "((small)::numeric * 1.5)" })
  total!: string | null

  @Column({ type: "timestamp", precision: 3, default: () => "timezone('utc'::text, now())" })
  stamp!: Date
}
