// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations. Keep
// `synchronize` off when pointing a DataSource at a database that already exists.

import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryColumn,
  PrimaryGeneratedColumn,
  type Relation,
} from "typeorm"

@Index("UQ_accounts_guid", ["guid"], { unique: true })
@Entity("accounts", { schema: "dbo" })
export class Account {
  @PrimaryGeneratedColumn({ type: "int" })
  id!: number

  @Column({ type: "uniqueidentifier", default: () => "newid()" })
  guid!: string

  @Column({ type: "nvarchar", length: 200 })
  name!: string

  @Column({ type: "nvarchar", length: "max", nullable: true })
  notes!: string | null

  @Column({ type: "char", length: 8, nullable: true })
  code!: string | null

  @Column({ type: "bit", default: true })
  active!: boolean

  @Column({ type: "tinyint", default: 0 })
  level!: number

  @Column({ type: "money", nullable: true })
  balance!: number | null

  @Column({ type: "decimal", precision: 18, scale: 2, default: 0 })
  credit!: number

  @Column({ type: "varbinary", length: "max", nullable: true })
  photo!: Buffer | null

  @Column({ type: "date", nullable: true })
  opened_on!: Date | null

  @Column({ type: "datetime2", default: () => "(sysdatetime())" })
  created_at!: Date

  @Column({ type: "datetimeoffset", nullable: true })
  seen_at!: Date | null

  @Column({ type: "rowversion" })
  version!: Buffer

  @OneToMany(() => Transfer, (other) => other.from_account_ref)
  transfers_from_account!: Relation<Transfer>[]

  @OneToMany(() => Transfer, (other) => other.to_account_ref)
  transfers_to_account!: Relation<Transfer>[]
}

@Index("IX_transfers_from", ["from_account"])
@Entity("transfers", { schema: "dbo" })
export class Transfer {
  @PrimaryGeneratedColumn({ type: "bigint" })
  id!: string

  @Column({ type: "int" })
  from_account!: number

  @Column({ type: "int", nullable: true })
  to_account!: number | null

  @Column({ type: "decimal", precision: 18, scale: 2 })
  amount!: number

  @Column({ type: "varchar", length: 255, default: "" })
  memo!: string

  @ManyToOne(() => Account, (other) => other.transfers_from_account, { onDelete: "CASCADE" })
  @JoinColumn({ name: "from_account", referencedColumnName: "id", foreignKeyConstraintName: "FK_transfers_from" })
  from_account_ref!: Relation<Account>

  @ManyToOne(() => Account, (other) => other.transfers_to_account)
  @JoinColumn({ name: "to_account", referencedColumnName: "id", foreignKeyConstraintName: "FK_transfers_to" })
  to_account_ref!: Relation<Account> | null
}

@Entity("accounts", { schema: "sales" })
export class SalesAccount {
  @PrimaryColumn({ type: "int" })
  id!: number

  @Column({ type: "nchar", length: 2 })
  region!: string

  @Column({ type: "xml", nullable: true })
  payload!: string | null
}
