package gameserver

import (
	"archive/zip"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

var (
	ErrInvalidArchive = errors.New("server archive is invalid")
	ErrNoServerFound  = errors.New("no Minecraft server was found")
)

const (
	maxArchiveEntries = 20000
	maxArchiveBytes   = 8 << 30
	maxScanEntries    = 50000
	maxScanDepth      = 8
)

// ImportEvidence is one observed fact that led to a conclusion. An import
// preview shows its reasoning; the operator confirms or corrects it.
type ImportEvidence struct {
	Path   string `json:"path"`
	Reason string `json:"reason"`
}

// ImportPreview is what an import found. Nothing is copied, started or changed
// to produce it.
type ImportPreview struct {
	Root         string            `json:"root"`
	Edition      string            `json:"edition"`
	Software     string            `json:"software"`
	Version      string            `json:"version,omitempty"`
	Evidence     []ImportEvidence  `json:"evidence"`
	WorldPaths   []string          `json:"worldPaths"`
	ModPaths     []string          `json:"modPaths"`
	ConfigPaths  []string          `json:"configPaths"`
	LogPaths     []string          `json:"logPaths"`
	IgnoredPaths []string          `json:"ignoredPaths"`
	Properties   map[string]string `json:"properties,omitempty"`
	Port         int               `json:"port,omitempty"`
	TotalBytes   int64             `json:"totalBytes"`
	EULAAccepted bool              `json:"eulaAccepted"`
	Warnings     []string          `json:"warnings"`
}

// runtimeOutput names directories that are regenerated on start. Copying them
// wastes space and can carry a crashed server's state into a fresh one.
var runtimeOutput = map[string]string{
	"logs":          "regenerated by the server on every start",
	"crash-reports": "diagnostic output from the previous host",
	"cache":         "rebuilt on demand",
	"libraries":     "re-downloaded by the server launcher",
	"versions":      "re-downloaded by the server launcher",
	".fabric":       "extracted by the mod loader on start",
	"debug":         "diagnostic output from the previous host",
}

// worldMarker files identify a Minecraft world directory rather than an
// arbitrary folder that happens to sit beside the server jar.
var worldMarkers = []string{"level.dat", "level.dat_old", "session.lock"}

// PreviewDirectory inspects a server directory in place. It reads names and a
// bounded amount of server.properties; it never follows a symlink out of the
// root and never writes anything.
func PreviewDirectory(root string) (*ImportPreview, error) {
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return nil, fmt.Errorf("%w: %s is not a directory", ErrNoServerFound, root)
	}
	resolved, err := filepath.EvalSymlinks(root)
	if err != nil {
		return nil, fmt.Errorf("%w: %s could not be resolved", ErrNoServerFound, root)
	}
	preview := &ImportPreview{
		Root: resolved, Edition: "unknown", Software: "unknown",
		Evidence: []ImportEvidence{}, WorldPaths: []string{}, ModPaths: []string{},
		ConfigPaths: []string{}, LogPaths: []string{}, IgnoredPaths: []string{}, Warnings: []string{},
	}
	entries := 0
	walkErr := filepath.WalkDir(resolved, func(current string, entry fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		entries++
		if entries > maxScanEntries {
			return fs.SkipAll
		}
		relative, relErr := filepath.Rel(resolved, current)
		if relErr != nil || relative == "." {
			return nil
		}
		if strings.Count(relative, string(os.PathSeparator)) >= maxScanDepth {
			return fs.SkipDir
		}
		// A symlink pointing outside the chosen root would import somebody
		// else's files under this deployment's name.
		if entry.Type()&fs.ModeSymlink != 0 {
			target, linkErr := filepath.EvalSymlinks(current)
			if linkErr != nil || !contained(resolved, target) {
				preview.Warnings = append(preview.Warnings,
					relative+" is a link pointing outside the chosen directory and will not be imported")
				return nil
			}
			return nil
		}
		if entry.IsDir() {
			if reason, ignored := runtimeOutput[entry.Name()]; ignored {
				preview.IgnoredPaths = append(preview.IgnoredPaths, relative+" — "+reason)
				return fs.SkipDir
			}
			return nil
		}
		if stat, statErr := entry.Info(); statErr == nil {
			preview.TotalBytes += stat.Size()
		}
		classifyImportFile(preview, resolved, relative)
		return nil
	})
	if walkErr != nil {
		return nil, walkErr
	}
	finishPreview(preview)
	if preview.Software == "unknown" && len(preview.WorldPaths) == 0 {
		return nil, fmt.Errorf("%w: %s holds no server jar, server.properties or world", ErrNoServerFound, root)
	}
	return preview, nil
}

func contained(root, candidate string) bool {
	relative, err := filepath.Rel(root, candidate)
	return err == nil && relative != ".." && !strings.HasPrefix(relative, ".."+string(os.PathSeparator))
}

func classifyImportFile(preview *ImportPreview, root, relative string) {
	base := filepath.Base(relative)
	directory := filepath.Dir(relative)
	switch {
	case base == "server.properties":
		preview.ConfigPaths = append(preview.ConfigPaths, relative)
		if content, err := readBounded(filepath.Join(root, relative), 256<<10); err == nil {
			preview.Properties = ParseProperties(content).Values()
		}
		preview.Evidence = append(preview.Evidence, ImportEvidence{
			Path: relative, Reason: "a Minecraft server writes this file on first start",
		})
	case base == "eula.txt":
		preview.ConfigPaths = append(preview.ConfigPaths, relative)
		if content, err := readBounded(filepath.Join(root, relative), 4<<10); err == nil {
			preview.EULAAccepted = strings.Contains(strings.ToLower(content), "eula=true")
		}
	case base == "bedrock_server" || base == "bedrock_server.exe":
		preview.Edition, preview.Software = "bedrock", "bedrock"
		preview.Evidence = append(preview.Evidence, ImportEvidence{
			Path: relative, Reason: "the Bedrock dedicated server executable",
		})
	// A jar inside mods/ or plugins/ is content, not the server. Classifying by
	// directory first keeps a plugin from being read as the server software.
	case directory == "mods" || strings.HasPrefix(directory, "mods"+string(os.PathSeparator)):
		preview.ModPaths = appendUnique(preview.ModPaths, "mods")
	case directory == "plugins" || strings.HasPrefix(directory, "plugins"+string(os.PathSeparator)):
		preview.ModPaths = appendUnique(preview.ModPaths, "plugins")
	case strings.HasSuffix(base, ".jar"):
		recordJarEvidence(preview, relative, base)
	case base == "level.dat" || base == "level.dat_old":
		world := directory
		if world == "." {
			world = "."
		}
		preview.WorldPaths = appendUnique(preview.WorldPaths, world)
		preview.Evidence = append(preview.Evidence, ImportEvidence{
			Path: world, Reason: "holds level.dat, so it is a world",
		})
	case strings.HasSuffix(base, ".log") || strings.HasSuffix(base, ".log.gz"):
		preview.LogPaths = appendUnique(preview.LogPaths, directory)
	case base == "bukkit.yml" || base == "spigot.yml" || base == "paper.yml" ||
		base == "purpur.yml" || base == "server.json" || base == "ops.json" ||
		base == "whitelist.json" || base == "allowlist.json" || base == "banned-players.json":
		preview.ConfigPaths = appendUnique(preview.ConfigPaths, relative)
		if base == "paper.yml" || base == "purpur.yml" || base == "spigot.yml" {
			software := strings.TrimSuffix(base, ".yml")
			if preview.Software == "unknown" || preview.Software == "vanilla" {
				preview.Software = software
				preview.Evidence = append(preview.Evidence, ImportEvidence{
					Path: relative, Reason: "only a " + software + " server writes this file",
				})
			}
		}
	}
}

func recordJarEvidence(preview *ImportPreview, relative, base string) {
	lower := strings.ToLower(base)
	if preview.Edition == "unknown" {
		preview.Edition = "java"
	}
	for software, marker := range map[string]string{
		"paper": "paper", "purpur": "purpur", "fabric": "fabric",
		"forge": "forge", "neoforge": "neoforge", "spigot": "spigot",
	} {
		if strings.Contains(lower, marker) {
			preview.Software = software
			preview.Evidence = append(preview.Evidence, ImportEvidence{
				Path: relative, Reason: "the jar name identifies a " + software + " server",
			})
			preview.Version = versionFromJarName(lower)
			return
		}
	}
	if strings.Contains(lower, "server") || strings.Contains(lower, "minecraft") {
		if preview.Software == "unknown" {
			preview.Software = "vanilla"
			preview.Evidence = append(preview.Evidence, ImportEvidence{
				Path: relative, Reason: "a server jar with no loader marker",
			})
			preview.Version = versionFromJarName(lower)
		}
	}
}

// versionFromJarName reads the version out of a conventional jar name. A name
// that does not carry one produces nothing rather than a guess.
func versionFromJarName(name string) string {
	for _, part := range strings.FieldsFunc(strings.TrimSuffix(name, ".jar"), func(r rune) bool {
		return r == '-' || r == '_'
	}) {
		if len(part) < 3 || part[0] < '1' || part[0] > '9' {
			continue
		}
		dots := strings.Count(part, ".")
		if dots >= 1 && dots <= 2 {
			valid := true
			for _, r := range part {
				if (r < '0' || r > '9') && r != '.' {
					valid = false
					break
				}
			}
			if valid {
				return part
			}
		}
	}
	return ""
}

func finishPreview(preview *ImportPreview) {
	sort.Strings(preview.WorldPaths)
	sort.Strings(preview.ModPaths)
	sort.Strings(preview.ConfigPaths)
	sort.Strings(preview.LogPaths)
	sort.Strings(preview.IgnoredPaths)
	if preview.Properties != nil {
		if port, found := preview.Properties["server-port"]; found {
			if parsed := atoiSafe(port); parsed > 0 && parsed < 65536 {
				preview.Port = parsed
			}
		}
		if preview.Port == 0 {
			if port, found := preview.Properties["server-portv6"]; found {
				if parsed := atoiSafe(port); parsed > 0 && parsed < 65536 {
					preview.Port = parsed
				}
			}
		}
	}
	if preview.Port == 0 {
		if preview.Edition == "bedrock" {
			preview.Port = 19132
		} else {
			preview.Port = 25565
		}
	}
	if len(preview.WorldPaths) == 0 {
		preview.Warnings = append(preview.Warnings,
			"No world was found. The server will generate a new one on first start.")
	}
	if len(preview.WorldPaths) > 1 {
		preview.Warnings = append(preview.Warnings,
			"More than one world directory was found. All of them are imported; the server loads the one named in server.properties.")
	}
	if !preview.EULAAccepted {
		preview.Warnings = append(preview.Warnings,
			"This server has not accepted the Minecraft EULA. You will be asked to accept it before it starts.")
	}
	if preview.Software == "unknown" && preview.Edition == "java" {
		preview.Warnings = append(preview.Warnings,
			"The server software could not be identified from the files. Choose it yourself on the next step.")
	}
}

func atoiSafe(value string) int {
	result := 0
	for _, r := range strings.TrimSpace(value) {
		if r < '0' || r > '9' {
			return 0
		}
		result = result*10 + int(r-'0')
		if result > 1<<20 {
			return 0
		}
	}
	return result
}

func appendUnique(list []string, value string) []string {
	for _, existing := range list {
		if existing == value {
			return list
		}
	}
	return append(list, value)
}

func readBounded(path string, limit int64) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	content, err := io.ReadAll(io.LimitReader(file, limit))
	return string(content), err
}

// ArchiveEntry is one file inside an uploaded server archive, after its name
// has been checked.
type ArchiveEntry struct {
	Path  string
	Bytes int64
}

// InspectArchive validates an uploaded zip before anything is extracted. Every
// rejection here is a path that would otherwise write outside the destination.
func InspectArchive(reader io.ReaderAt, size int64) ([]ArchiveEntry, string, error) {
	if size <= 0 || size > maxArchiveBytes {
		return nil, "", fmt.Errorf("%w: the archive is empty or larger than 8 GiB", ErrInvalidArchive)
	}
	archive, err := zip.NewReader(reader, size)
	if err != nil {
		return nil, "", fmt.Errorf("%w: it is not a readable zip file", ErrInvalidArchive)
	}
	if len(archive.File) > maxArchiveEntries {
		return nil, "", fmt.Errorf("%w: it holds more than %d entries", ErrInvalidArchive, maxArchiveEntries)
	}
	entries := make([]ArchiveEntry, 0, len(archive.File))
	var total int64
	for _, file := range archive.File {
		name := file.Name
		if strings.ContainsRune(name, '\x00') || strings.ContainsRune(name, '\\') {
			return nil, "", fmt.Errorf("%w: entry %q uses an unsupported path separator", ErrInvalidArchive, name)
		}
		if path.IsAbs(name) || strings.HasPrefix(name, "/") {
			return nil, "", fmt.Errorf("%w: entry %q is an absolute path", ErrInvalidArchive, name)
		}
		clean := path.Clean(name)
		if clean == ".." || strings.HasPrefix(clean, "../") {
			return nil, "", fmt.Errorf("%w: entry %q escapes the archive root", ErrInvalidArchive, name)
		}
		mode := file.Mode()
		if mode&os.ModeSymlink != 0 {
			return nil, "", fmt.Errorf("%w: entry %q is a symbolic link", ErrInvalidArchive, name)
		}
		if mode&(os.ModeDevice|os.ModeNamedPipe|os.ModeSocket) != 0 {
			return nil, "", fmt.Errorf("%w: entry %q is not a regular file", ErrInvalidArchive, name)
		}
		if strings.HasSuffix(name, "/") {
			continue
		}
		total += int64(file.UncompressedSize64)
		if total > maxArchiveBytes {
			return nil, "", fmt.Errorf("%w: its contents expand beyond 8 GiB", ErrInvalidArchive)
		}
		entries = append(entries, ArchiveEntry{Path: clean, Bytes: int64(file.UncompressedSize64)})
	}
	if len(entries) == 0 {
		return nil, "", fmt.Errorf("%w: it contains no files", ErrInvalidArchive)
	}
	root, err := archiveRoot(entries)
	if err != nil {
		return nil, "", err
	}
	return entries, root, nil
}

// archiveRoot finds the directory the server actually lives in. An archive of a
// folder has one top-level directory; an archive of a folder's contents has
// none, and an archive of several servers is ambiguous and refused.
func archiveRoot(entries []ArchiveEntry) (string, error) {
	markers := map[string]bool{"server.properties": true, "eula.txt": true, "bedrock_server": true}
	candidates := map[string]bool{}
	for _, entry := range entries {
		// InspectArchive rejects these already. Repeating the check keeps this
		// function safe to call on its own rather than safe only in context.
		if entry.Path == "" || path.IsAbs(entry.Path) || strings.Contains(entry.Path, "..") ||
			strings.Contains(entry.Path, "\\") {
			continue
		}
		base := path.Base(entry.Path)
		if markers[base] || strings.HasSuffix(base, ".jar") {
			candidates[path.Dir(entry.Path)] = true
		}
		for _, marker := range worldMarkers {
			if base == marker {
				candidates[path.Dir(path.Dir(entry.Path))] = true
			}
		}
	}
	delete(candidates, "")
	if len(candidates) == 0 {
		return "", fmt.Errorf("%w: no server.properties, server jar or world was found inside it", ErrNoServerFound)
	}
	roots := make([]string, 0, len(candidates))
	for candidate := range candidates {
		roots = append(roots, candidate)
	}
	sort.Strings(roots)
	// A shallower candidate that is a parent of all the others is the root.
	shortest := roots[0]
	for _, candidate := range roots {
		if candidate != shortest && !strings.HasPrefix(candidate+"/", shortest+"/") && shortest != "." {
			return "", fmt.Errorf("%w: it holds more than one server (%s and %s). Extract the one you want and try again",
				ErrInvalidArchive, shortest, candidate)
		}
	}
	return shortest, nil
}
