# Generated by Just Dashboard from live database introspection.
# A reviewed starting point, in the shape inspectdb writes: verify field
# types and on_delete rules. These models are managed: run makemigrations
# --dry-run first and read what Django thinks it has to change.

from decimal import Decimal
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.functions import RandomUUID
from django.contrib.postgres.indexes import GinIndex
from django.db import models
from django.db.models.functions import Now


class EventKind(models.TextChoices):
    PAGE_VIEW = "page_view", "Page view"
    CLICK = "click", "Click"
    ADD_TO_CART = "add-to-cart", "Add to cart"


class CustomerTier(models.TextChoices):
    FREE = "free", "Free"
    PLUS = "plus", "Plus"
    PRO = "pro", "Pro"


class OrderStatus(models.TextChoices):
    PENDING = "pending", "Pending"
    PAID = "paid", "Paid"
    SHIPPED = "shipped", "Shipped"
    DELIVERED = "delivered", "Delivered"
    CANCELLED = "cancelled", "Cancelled"
    REFUNDED = "refunded", "Refunded"


class DailyRevenue(models.Model):
    day = models.DateField(primary_key=True)
    orders = models.IntegerField()
    revenue_cents = models.BigIntegerField()

    class Meta:
        managed = True
        db_table = "analytics\".\"daily_revenue"


class AnalyticsEvent(models.Model):
    id = models.BigAutoField(primary_key=True)
    customer = models.ForeignKey("Customer", models.SET_NULL, related_name="events", blank=True, null=True)
    kind = models.CharField(max_length=11, choices=EventKind.choices)
    path = models.TextField(blank=True, null=True)
    duration_ms = models.IntegerField(blank=True, null=True)
    props = models.JSONField(blank=True, null=True)
    occurred_at = models.DateTimeField()

    class Meta:
        managed = True
        db_table = "analytics\".\"events"
        indexes = [
            models.Index(fields=["occurred_at"], name="events_occurred_idx"),
        ]


class MixedCaseTable(models.Model):
    id = models.IntegerField(primary_key=True, db_column="Id")
    select = models.TextField(blank=True, null=True)
    weird_column = models.TextField(db_column="weird column", blank=True, null=True)
    field_2fa = models.BooleanField(db_column="2fa", db_default=False)

    class Meta:
        managed = True
        db_table = "public\".\"Mixed Case Table"


class AuditLog(models.Model):
    # No primary key in the database: Django will assume an "id" column that does not exist.
    at = models.DateTimeField(db_default=Now())
    actor = models.TextField(blank=True, null=True)
    action = models.TextField()
    payload = models.JSONField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "public\".\"audit_log"


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    slug = models.TextField(unique=True)
    name = models.TextField()
    parent = models.ForeignKey("self", models.DO_NOTHING, related_name="categories", blank=True, null=True)

    class Meta:
        managed = True
        db_table = "public\".\"categories"


class CustomerProfile(models.Model):
    customer = models.OneToOneField("Customer", models.CASCADE, related_name="customer_profile", primary_key=True)
    bio = models.TextField(blank=True, null=True)
    website = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = "public\".\"customer_profiles"


class Customer(models.Model):
    id = models.BigAutoField(primary_key=True)
    email = models.TextField(unique=True)
    full_name = models.TextField()
    tier = models.CharField(max_length=4, choices=CustomerTier.choices, db_default="free")
    country = models.CharField(max_length=2, blank=True, null=True)
    marketing_opt_in = models.BooleanField(db_default=False)
    tags = ArrayField(models.TextField())
    profile = models.JSONField(db_comment="Free-form preferences captured at sign-up")
    avatar = models.BinaryField(blank=True, null=True)
    external_id = models.UUIDField(db_default=RandomUUID())
    lifetime_value = models.DecimalField(max_digits=12, decimal_places=2, db_default=Decimal("0"))
    created_at = models.DateTimeField(db_default=Now())
    last_seen_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "public\".\"customers"
        db_table_comment = "People who have an account in the shop"


class Event(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=120)
    starts_at = models.DateTimeField()

    class Meta:
        managed = True
        db_table = "public\".\"events"


class Measurement(models.Model):
    pk = models.CompositePrimaryKey("sensor_id", "taken_at")
    sensor_id = models.IntegerField()
    taken_at = models.DateTimeField()
    reading = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "public\".\"measurements"


class Message(models.Model):
    id = models.UUIDField(primary_key=True, db_default=RandomUUID())
    sender = models.ForeignKey("Customer", models.CASCADE, related_name="messages_sender_id")
    recipient = models.ForeignKey("Customer", models.SET_NULL, related_name="messages_recipient_id", blank=True, null=True)
    body = models.TextField()
    sent_at = models.DateTimeField(db_default=Now())

    class Meta:
        managed = True
        db_table = "public\".\"messages"


class OrderItem(models.Model):
    pk = models.CompositePrimaryKey("order_id", "line_no")
    order = models.ForeignKey("Order", models.CASCADE, related_name="order_items")
    line_no = models.SmallIntegerField()
    product = models.ForeignKey("Product", models.DO_NOTHING, related_name="order_items")
    quantity = models.IntegerField(db_default=1)
    unit_price_cents = models.IntegerField()

    class Meta:
        managed = True
        db_table = "public\".\"order_items"
        constraints = [
            models.UniqueConstraint(fields=["order", "product"], name="order_items_order_product_key"),
        ]


class Order(models.Model):
    id = models.BigAutoField(primary_key=True)
    customer = models.ForeignKey("Customer", models.CASCADE, related_name="orders")
    status = models.CharField(max_length=9, choices=OrderStatus.choices, db_default="pending")
    total_cents = models.BigIntegerField(db_default=0)
    currency = models.CharField(max_length=3, db_default="EUR")
    shipping_address = models.JSONField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    placed_at = models.DateTimeField(db_default=Now())
    shipped_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "public\".\"orders"
        indexes = [
            models.Index(fields=["status", "-placed_at"], name="orders_status_placed_idx"),
        ]


class Product(models.Model):
    id = models.BigAutoField(primary_key=True)
    sku = models.CharField(max_length=32, unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey("Category", models.DO_NOTHING, related_name="products", blank=True, null=True)
    price_cents = models.IntegerField()
    stock = models.IntegerField(db_default=0)
    attributes = models.JSONField()
    weight_kg = models.FloatField(blank=True, null=True)
    discontinued = models.BooleanField(db_default=False)
    released_on = models.DateField(blank=True, null=True)
    updated_at = models.DateTimeField(db_default=Now())

    class Meta:
        managed = True
        db_table = "public\".\"products"
        indexes = [
            models.Index(fields=["category"], name="products_category_idx"),
            GinIndex(fields=["attributes"], name="products_attributes_gin"),
        ]


class Shipment(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.BigIntegerField()
    line_no = models.SmallIntegerField()
    category = models.ForeignKey("Category", models.DO_NOTHING, db_column="category_slug", to_field="slug", related_name="shipments", blank=True, null=True)
    tracking_code = models.CharField(max_length=40, unique=True)

    class Meta:
        managed = True
        db_table = "public\".\"shipments"


class TypeSample(models.Model):
    id = models.AutoField(primary_key=True)
    small = models.SmallIntegerField(db_default=0)
    ratio = models.FloatField(blank=True, null=True)
    price = models.TextField(blank=True, null=True)  # This field type is a guess.
    amount = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    code = models.CharField(max_length=16, db_default="N/A")
    fixed = models.CharField(max_length=4, blank=True, null=True)
    starts = models.TimeField(blank=True, null=True)
    starts_tz = models.TimeField(blank=True, null=True)
    span = models.DurationField(blank=True, null=True)
    addr = models.GenericIPAddressField(blank=True, null=True)
    doc = models.TextField(blank=True, null=True)
    flags = models.TextField(blank=True, null=True)  # This field type is a guess.
    search = models.TextField(blank=True, null=True)  # This field type is a guess.
    scores = ArrayField(models.IntegerField(), blank=True, null=True)
    day = models.DateField()
    meta = models.JSONField(blank=True, null=True)
    label = models.TextField(db_default="it's")
    total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, editable=False)
    stamp = models.DateTimeField()

    class Meta:
        managed = True
        db_table = "public\".\"type_samples"
