<?php

// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify casts, fillable columns and relations.

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property int $user_id
 * @property string $title
 * @property string|null $body
 * @property bool $pinned
 * @property float|null $score
 * @property string|null $price
 * @property array|null $payload
 * @property string|null $attachment
 * @property \Illuminate\Support\Carbon $created_at
 * @property-read User $user
 */
class Note extends Model
{
    protected $table = 'notes';

    public $timestamps = false;

    protected $fillable = [
        'user_id',
        'title',
        'body',
        'pinned',
        'score',
        'price',
        'payload',
        'attachment',
        'created_at',
    ];

    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'pinned' => 'boolean',
        'score' => 'float',
        'price' => 'decimal:2',
        'payload' => 'array',
        'created_at' => 'datetime',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

/**
 * @property int $user_id
 * @property string $tag
 * @property-read User $user
 */
class UserTag extends Model
{
    protected $table = 'user_tags';

    protected $primaryKey = null;

    public $incrementing = false;

    public $timestamps = false;

    protected $fillable = [
        'user_id',
        'tag',
    ];

    protected $casts = [
        'user_id' => 'integer',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

/**
 * @property int $id
 * @property string $email
 * @property string|null $name
 * @property-read \Illuminate\Database\Eloquent\Collection<int, Note> $notes
 * @property-read \Illuminate\Database\Eloquent\Collection<int, UserTag> $userTags
 */
class User extends Model
{
    protected $table = 'users';

    public $timestamps = false;

    protected $fillable = [
        'email',
        'name',
    ];

    protected $casts = [
        'id' => 'integer',
    ];

    public function notes(): HasMany
    {
        return $this->hasMany(Note::class, 'user_id', 'id');
    }

    public function userTags(): HasMany
    {
        return $this->hasMany(UserTag::class, 'user_id', 'id');
    }
}
