// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations.

import { relations, sql } from "drizzle-orm"
import {
  type AnyPgColumn,
  bigint,
  bigserial,
  boolean,
  char,
  customType,
  date,
  doublePrecision,
  foreignKey,
  index,
  inet,
  integer,
  interval,
  json,
  jsonb,
  numeric,
  pgEnum,
  pgSchema,
  pgTable,
  pgView,
  primaryKey,
  real,
  serial,
  smallint,
  text,
  time,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core"

const bytea = customType<{ data: Buffer }>({
  dataType() {
    return "bytea"
  },
})

const money = customType<{ data: string }>({
  dataType() {
    return "money"
  },
})

const xml = customType<{ data: string }>({
  dataType() {
    return "xml"
  },
})

const bit8 = customType<{ data: string }>({
  dataType() {
    return "bit(8)"
  },
})

const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector"
  },
})

export const analytics = pgSchema("analytics")

export const event_kind = analytics.enum("event_kind", ["page_view", "click", "add-to-cart"])
export const customer_tier = pgEnum("customer_tier", ["free", "plus", "pro"])
export const order_status = pgEnum("order_status", ["pending", "paid", "shipped", "delivered", "cancelled", "refunded"])

export const daily_revenue = analytics.table("daily_revenue", {
  day: date("day").primaryKey().notNull(),
  orders: integer("orders").notNull(),
  revenue_cents: bigint("revenue_cents", { mode: "number" }).notNull(),
})

export const analytics_events = analytics.table(
  "events",
  {
    id: bigint("id", { mode: "number" }).primaryKey().notNull().generatedAlwaysAsIdentity(),
    customer_id: bigint("customer_id", { mode: "number" }).references(() => customers.id, { onDelete: "set null" }),
    kind: event_kind("kind").notNull(),
    path: text("path"),
    duration_ms: integer("duration_ms"),
    props: jsonb("props"),
    occurred_at: timestamp("occurred_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    index("events_occurred_idx").on(table.occurred_at),
  ],
)

export const Mixed_Case_Table = pgTable("Mixed Case Table", {
  Id: integer("Id").primaryKey().notNull(),
  select: text("select"),
  weird_column: text("weird column"),
  _2fa: boolean("2fa").notNull().default(false),
})

export const audit_log = pgTable("audit_log", {
  at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  actor: text("actor"),
  action: text("action").notNull(),
  payload: jsonb("payload"),
})

export const categories = pgTable("categories", {
  id: serial("id").primaryKey().notNull(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  parent_id: integer("parent_id").references((): AnyPgColumn => categories.id),
})

export const customer_profiles = pgTable("customer_profiles", {
  customer_id: bigint("customer_id", { mode: "number" }).primaryKey().notNull().references(() => customers.id, { onDelete: "cascade" }),
  bio: text("bio"),
  website: varchar("website", { length: 255 }),
})

/** People who have an account in the shop */
export const customers = pgTable("customers", {
  id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
  email: text("email").notNull().unique(),
  full_name: text("full_name").notNull(),
  tier: customer_tier("tier").notNull().default("free"),
  country: char("country", { length: 2 }),
  marketing_opt_in: boolean("marketing_opt_in").notNull().default(false),
  tags: text("tags").array().notNull().default([]),
  profile: jsonb("profile").notNull().default({}),
  avatar: bytea("avatar"),
  external_id: uuid("external_id").notNull().defaultRandom(),
  lifetime_value: numeric("lifetime_value", { precision: 12, scale: 2 }).notNull().default("0"),
  created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  last_seen_at: timestamp("last_seen_at", { withTimezone: true }),
})

export const events = pgTable("events", {
  id: bigint("id", { mode: "number" }).primaryKey().notNull().generatedByDefaultAsIdentity(),
  name: varchar("name", { length: 120 }).notNull(),
  starts_at: timestamp("starts_at").notNull(),
})

export const measurements = pgTable(
  "measurements",
  {
    sensor_id: integer("sensor_id").notNull(),
    taken_at: timestamp("taken_at", { withTimezone: true }).notNull(),
    reading: doublePrecision("reading"),
  },
  (table) => [
    primaryKey({ columns: [table.sensor_id, table.taken_at] }),
  ],
)

export const messages = pgTable("messages", {
  id: uuid("id").primaryKey().notNull().defaultRandom(),
  sender_id: bigint("sender_id", { mode: "number" }).notNull().references(() => customers.id, { onDelete: "cascade" }),
  recipient_id: bigint("recipient_id", { mode: "number" }).references(() => customers.id, { onDelete: "set null" }),
  body: text("body").notNull(),
  sent_at: timestamp("sent_at", { precision: 3, withTimezone: true }).notNull().defaultNow(),
})

export const order_items = pgTable(
  "order_items",
  {
    order_id: bigint("order_id", { mode: "number" }).notNull().references(() => orders.id, { onDelete: "cascade" }),
    line_no: smallint("line_no").notNull(),
    product_id: bigint("product_id", { mode: "number" }).notNull().references(() => products.id),
    quantity: integer("quantity").notNull().default(1),
    unit_price_cents: integer("unit_price_cents").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.order_id, table.line_no] }),
    unique("order_items_order_product_key").on(table.order_id, table.product_id),
  ],
)

export const orders = pgTable(
  "orders",
  {
    id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
    customer_id: bigint("customer_id", { mode: "number" }).notNull().references(() => customers.id, { onDelete: "cascade" }),
    status: order_status("status").notNull().default("pending"),
    total_cents: bigint("total_cents", { mode: "number" }).notNull().default(0),
    currency: char("currency", { length: 3 }).notNull().default("EUR"),
    shipping_address: jsonb("shipping_address"),
    note: text("note"),
    placed_at: timestamp("placed_at", { withTimezone: true }).notNull().defaultNow(),
    shipped_at: timestamp("shipped_at", { withTimezone: true }),
  },
  (table) => [
    index("orders_status_placed_idx").on(table.status, table.placed_at.desc()),
  ],
)

export const products = pgTable(
  "products",
  {
    id: bigserial("id", { mode: "number" }).primaryKey().notNull(),
    sku: varchar("sku", { length: 32 }).notNull().unique(),
    name: varchar("name", { length: 200 }).notNull(),
    description: text("description"),
    category_id: integer("category_id").references(() => categories.id),
    price_cents: integer("price_cents").notNull(),
    stock: integer("stock").notNull().default(0),
    attributes: jsonb("attributes").notNull().default({}),
    weight_kg: doublePrecision("weight_kg"),
    discontinued: boolean("discontinued").notNull().default(false),
    released_on: date("released_on"),
    updated_at: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [
    index("products_category_idx").on(table.category_id),
    index("products_attributes_gin").using("gin", table.attributes),
  ],
)

export const shipments = pgTable(
  "shipments",
  {
    id: serial("id").primaryKey().notNull(),
    order_id: bigint("order_id", { mode: "number" }).notNull(),
    line_no: smallint("line_no").notNull(),
    category_slug: text("category_slug").references(() => categories.slug),
    tracking_code: varchar("tracking_code", { length: 40 }).notNull().unique(),
  },
  (table) => [
    foreignKey({ columns: [table.order_id, table.line_no], foreignColumns: [order_items.order_id, order_items.line_no], name: "shipments_item_fkey" }).onDelete("cascade"),
  ],
)

export const type_samples = pgTable("type_samples", {
  id: integer("id").primaryKey().notNull().generatedByDefaultAsIdentity(),
  small: smallint("small").notNull().default(0),
  ratio: real("ratio"),
  price: money("price"),
  amount: numeric("amount"),
  code: varchar("code", { length: 16 }).notNull().default("N/A"),
  fixed: char("fixed", { length: 4 }),
  starts: time("starts"),
  starts_tz: time("starts_tz", { withTimezone: true }),
  span: interval("span"),
  addr: inet("addr"),
  doc: xml("doc"),
  flags: bit8("flags"),
  search: tsvector("search"),
  scores: integer("scores").array(),
  day: date("day").notNull().default(sql`CURRENT_DATE`),
  meta: json("meta"),
  label: text("label").notNull().default("it's"),
  total: numeric("total", { precision: 10, scale: 2 }).generatedAlwaysAs(sql`((small)::numeric * 1.5)`),
  stamp: timestamp("stamp", { precision: 3 }).notNull().default(sql`timezone('utc'::text, now())`),
})

export const top_products = analytics.materializedView("top_products", {
  product_id: bigint("product_id", { mode: "number" }),
  units: bigint("units", { mode: "number" }),
}).existing()

export const order_summary = pgView("order_summary", {
  id: bigint("id", { mode: "number" }),
  email: text("email"),
  status: order_status("status"),
  total_cents: bigint("total_cents", { mode: "number" }),
}).existing()

export const analytics_eventsRelations = relations(analytics_events, ({ one }) => ({
  customer: one(customers, {
    fields: [analytics_events.customer_id],
    references: [customers.id],
    relationName: "events_customer_id",
  }),
}))

export const categoriesRelations = relations(categories, ({ one, many }) => ({
  parent: one(categories, {
    fields: [categories.parent_id],
    references: [categories.id],
    relationName: "categories_parent_id",
  }),
  categories: many(categories, { relationName: "categories_parent_id" }),
  products: many(products, { relationName: "products_category_id" }),
  shipments: many(shipments, { relationName: "shipments_category_slug" }),
}))

export const customer_profilesRelations = relations(customer_profiles, ({ one }) => ({
  customer: one(customers, {
    fields: [customer_profiles.customer_id],
    references: [customers.id],
    relationName: "customer_profiles_customer_id",
  }),
}))

export const customersRelations = relations(customers, ({ one, many }) => ({
  events: many(analytics_events, { relationName: "events_customer_id" }),
  customer_profile: one(customer_profiles, {
    fields: [customers.id],
    references: [customer_profiles.customer_id],
    relationName: "customer_profiles_customer_id",
  }),
  messages_recipient_id: many(messages, { relationName: "messages_recipient_id" }),
  messages_sender_id: many(messages, { relationName: "messages_sender_id" }),
  orders: many(orders, { relationName: "orders_customer_id" }),
}))

export const messagesRelations = relations(messages, ({ one }) => ({
  recipient: one(customers, {
    fields: [messages.recipient_id],
    references: [customers.id],
    relationName: "messages_recipient_id",
  }),
  sender: one(customers, {
    fields: [messages.sender_id],
    references: [customers.id],
    relationName: "messages_sender_id",
  }),
}))

export const order_itemsRelations = relations(order_items, ({ one, many }) => ({
  order: one(orders, {
    fields: [order_items.order_id],
    references: [orders.id],
    relationName: "order_items_order_id",
  }),
  product: one(products, {
    fields: [order_items.product_id],
    references: [products.id],
    relationName: "order_items_product_id",
  }),
  shipments: many(shipments, { relationName: "shipments_order_id_line_no" }),
}))

export const ordersRelations = relations(orders, ({ one, many }) => ({
  customer: one(customers, {
    fields: [orders.customer_id],
    references: [customers.id],
    relationName: "orders_customer_id",
  }),
  order_items: many(order_items, { relationName: "order_items_order_id" }),
}))

export const productsRelations = relations(products, ({ one, many }) => ({
  category: one(categories, {
    fields: [products.category_id],
    references: [categories.id],
    relationName: "products_category_id",
  }),
  order_items: many(order_items, { relationName: "order_items_product_id" }),
}))

export const shipmentsRelations = relations(shipments, ({ one }) => ({
  category: one(categories, {
    fields: [shipments.category_slug],
    references: [categories.slug],
    relationName: "shipments_category_slug",
  }),
  order_item: one(order_items, {
    fields: [shipments.order_id, shipments.line_no],
    references: [order_items.order_id, order_items.line_no],
    relationName: "shipments_order_id_line_no",
  }),
}))
