// Generated by Just Dashboard from live database introspection.
// A reviewed starting point: verify types, defaults and relations.

import { relations, sql } from "drizzle-orm"
import {
  blob,
  index,
  integer,
  numeric,
  primaryKey,
  real,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core"

export const notes = sqliteTable(
  "notes",
  {
    id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
    user_id: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    body: text("body"),
    pinned: integer("pinned", { mode: "boolean" }).notNull().default(false),
    score: real("score"),
    price: numeric("price"),
    payload: text("payload", { mode: "json" }),
    attachment: blob("attachment"),
    created_at: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_notes_user").on(table.user_id),
  ],
)

export const user_tags = sqliteTable(
  "user_tags",
  {
    user_id: integer("user_id").notNull().references(() => users.id),
    tag: text("tag").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.user_id, table.tag] }),
  ],
)

export const users = sqliteTable("users", {
  id: integer("id").primaryKey().notNull(),
  email: text("email").notNull().unique(),
  name: text("name"),
})

export const notesRelations = relations(notes, ({ one }) => ({
  user: one(users, {
    fields: [notes.user_id],
    references: [users.id],
    relationName: "notes_user_id",
  }),
}))

export const user_tagsRelations = relations(user_tags, ({ one }) => ({
  user: one(users, {
    fields: [user_tags.user_id],
    references: [users.id],
    relationName: "user_tags_user_id",
  }),
}))

export const usersRelations = relations(users, ({ many }) => ({
  notes: many(notes, { relationName: "notes_user_id" }),
  user_tags: many(user_tags, { relationName: "user_tags_user_id" }),
}))
